// Package py emits Python 3.10+. Go value semantics are preserved with
// explicit copies, stable struct storage objects, cells for boxed scalars,
// integers normalized to their Go widths, and bytes for Go strings.
package py

import (
	"bytes"
	"fmt"
	"go/constant"
	"go/token"
	"sort"
	"strconv"
	"strings"

	"github.com/eugenioenko/goalchemy/internal/ir"
)

type Output struct {
	Source    []byte
	Contracts []string
	// Lines maps generated line numbers (1-based) to source positions.
	Lines map[int]token.Position
}

type emitter struct {
	p         *ir.Program
	symbols   map[string]string
	contracts map[string]bool
	classes   map[*ir.Type]string
	tds       map[*ir.Type]string
	helperQ   []*ir.Type
	helperOut bytes.Buffer
	seenHelp  map[*ir.Type]bool
}

func Emit(p *ir.Program, symbols map[string]string) (*Output, error) {
	e := &emitter{p: p, symbols: symbols, contracts: map[string]bool{}, classes: map[*ir.Type]string{},
		tds: map[*ir.Type]string{}, seenHelp: map[*ir.Type]bool{}}
	for _, t := range p.Types.All {
		if t.Boxed {
			e.tds[t] = fmt.Sprintf("TD_%d", t.ID)
		}
	}
	var fns bytes.Buffer
	for _, f := range p.Funcs {
		fns.WriteString(e.function(f))
	}
	var tds bytes.Buffer
	e.typeDescs(&tds)
	var globals bytes.Buffer
	for _, g := range p.Globals {
		z := e.zero(g.Type)
		if g.AddrTaken && !g.Type.IsAggregate() {
			fmt.Fprintf(&globals, "%s = rt.Cell(%s)\n", g.Sym, z)
		} else {
			fmt.Fprintf(&globals, "%s = %s\n", g.Sym, z)
		}
	}
	e.flushHelpers()
	var out bytes.Buffer
	out.WriteString("# Code generated by goalchemy. DO NOT EDIT.\n# flake8: noqa\nimport rt\n\n")
	out.Write(e.helperOut.Bytes())
	out.WriteString("\n")
	out.Write(globals.Bytes())
	out.WriteString("\n")
	out.Write(fns.Bytes())
	for _, f := range p.Funcs {
		fmt.Fprintf(&out, "%s._fid = %d\n", f.Sym, f.ID)
	}
	out.WriteString("\n")
	out.Write(tds.Bytes())
	if p.Cooperative {
		e.use("core.task.spawn")
		start := p.Entry.Sym + "()"
		if !p.Entry.MaySuspend {
			start = "rt.sync(lambda: (" + p.Entry.Sym + "(), [])[1])"
		}
		fmt.Fprintf(&out, "\nif __name__ == \"__main__\":\n    rt.run_main(%s)\n", start)
	} else {
		fmt.Fprintf(&out, "\n\ndef _entry():\n    %s()\n", p.Init.Sym)
		if p.Main != nil {
			fmt.Fprintf(&out, "    %s()\n", p.Main.Sym)
		}
		out.WriteString("\n\nif __name__ == \"__main__\":\n    rt.main(_entry)\n")
	}
	var cs []string
	for c := range e.contracts {
		cs = append(cs, c)
	}
	sort.Strings(cs)
	src, lines := e.resolveMarkers(out.String())
	return &Output{Source: []byte(src), Contracts: cs, Lines: lines}, nil
}

const marker = "\x00@"

// resolveMarkers strips position markers, recording the source line of
// each generated line.
func (e *emitter) resolveMarkers(src string) (string, map[int]token.Position) {
	m := map[int]token.Position{}
	lines := strings.Split(src, "\n")
	for i, ln := range lines {
		for {
			j := strings.Index(ln, marker)
			if j < 0 {
				break
			}
			k := strings.IndexByte(ln[j+len(marker):], 0)
			n, _ := strconv.Atoi(ln[j+len(marker) : j+len(marker)+k])
			ln = ln[:j] + ln[j+len(marker)+k+1:]
			if e.p.Fset != nil {
				if pos := e.p.Fset.Position(token.Pos(n)); pos.IsValid() {
					m[i+1] = pos
				}
			}
		}
		lines[i] = ln
	}
	return strings.Join(lines, "\n"), m
}

func (e *emitter) use(c string) {
	if c != "" {
		e.contracts[c] = true
	}
}

var opaqueContracts = map[string]string{
	"sync.Mutex":      "std.sync.mutex.lock",
	"sync.WaitGroup":  "std.sync.waitgroup.add",
	"context.Context": "std.context.err",
}

func intKind(t *ir.Type) string { return t.U().Int.String() }

func (e *emitter) susp(t *ir.Type) bool { return e.p.SuspTypes[t.U()] }

func (e *emitter) adapt(f string, n int) string {
	e.use("core.task.spawn")
	return fmt.Sprintf("rt.adapt(%s, %d)", f, n)
}

// ---- type helpers ----

func (e *emitter) class(t *ir.Type) string {
	u := t.U()
	if n, ok := e.classes[u]; ok {
		return n
	}
	n := fmt.Sprintf("S%d", u.ID)
	e.classes[u] = n
	e.needHelpers(u)
	return n
}

func fieldProp(t *ir.Type, i int) string {
	f := t.U().Fields[i]
	if f.Name == "_" {
		return fmt.Sprintf("f__%d", i)
	}
	return "f_" + f.Name
}

func (e *emitter) needHelpers(t *ir.Type) {
	u := t.U()
	if e.seenHelp[u] {
		return
	}
	e.seenHelp[u] = true
	e.helperQ = append(e.helperQ, u)
}

func (e *emitter) flushHelpers() {
	for len(e.helperQ) > 0 {
		t := e.helperQ[0]
		e.helperQ = e.helperQ[1:]
		switch t.Kind {
		case ir.KStruct:
			e.structClass(t)
		case ir.KArray:
			e.arrayHelpers(t)
		}
	}
}

func (e *emitter) structClass(t *ir.Type) {
	n := e.class(t)
	var b strings.Builder
	var props []string
	for i := range t.Fields {
		props = append(props, strconv.Quote(fieldProp(t, i)))
	}
	props = append(props, `"__weakref__"`)
	fmt.Fprintf(&b, "class %s:\n    __slots__ = (%s,)\n\n    def __init__(self):\n", n, strings.Join(props, ", "))
	if len(t.Fields) == 0 {
		b.WriteString("        pass\n")
	}
	for i, f := range t.Fields {
		fmt.Fprintf(&b, "        self.%s = %s\n", fieldProp(t, i), e.zero(f.Type))
	}
	fmt.Fprintf(&b, "\n    def _clone(self):\n        r = %s()\n        r._set(self)\n        return r\n", n)
	b.WriteString("\n    def _set(self, o):\n")
	if len(t.Fields) == 0 {
		b.WriteString("        pass\n")
	}
	for i, f := range t.Fields {
		p := fieldProp(t, i)
		if f.Type.IsAggregate() {
			fmt.Fprintf(&b, "        %s\n", e.setStmt(f.Type, "self."+p, "o."+p))
		} else {
			fmt.Fprintf(&b, "        self.%s = o.%s\n", p, p)
		}
	}
	b.WriteString("\n    def _eq(self, o):\n        return True")
	for i, f := range t.Fields {
		if f.Name == "_" {
			continue
		}
		p := fieldProp(t, i)
		fmt.Fprintf(&b, " and %s", e.eqExpr(f.Type, "self."+p, "o."+p))
	}
	b.WriteString("\n\n    def _key(self):\n        return (")
	for i, f := range t.Fields {
		if f.Name == "_" {
			continue
		}
		fmt.Fprintf(&b, "%s, ", e.keyExpr(f.Type, "self."+fieldProp(t, i)))
	}
	b.WriteString(")\n\n\n")
	e.helperOut.WriteString(b.String())
}

func (e *emitter) arrayHelpers(t *ir.Type) {
	id := t.ID
	el := t.Elem
	var b strings.Builder
	fmt.Fprintf(&b, "def zero_%d():\n    return [%s for _ in range(%d)]\n\n\n", id, e.zero(el), t.Len)
	fmt.Fprintf(&b, "def clone_%d(s):\n    return [%s for x in s]\n\n\n", id, e.cloneExpr(el, "x"))
	if el.IsAggregate() {
		fmt.Fprintf(&b, "def set_%d(d, s):\n    for i in range(%d):\n        %s\n\n\n", id, t.Len, e.setStmt(el, "d[i]", "s[i]"))
	} else {
		fmt.Fprintf(&b, "def set_%d(d, s):\n    d[:] = s\n\n\n", id)
	}
	fmt.Fprintf(&b, "def eq_%d(x, y):\n    return all(%s for a, b in zip(x, y))\n\n\n", id, e.eqExpr(el, "a", "b"))
	fmt.Fprintf(&b, "def key_%d(x):\n    return tuple(%s for a in x)\n\n\n", id, e.keyExpr(el, "a"))
	e.helperOut.WriteString(b.String())
}

func (e *emitter) zero(t *ir.Type) string {
	u := t.U()
	switch u.Kind {
	case ir.KBool:
		return "False"
	case ir.KInt:
		return "0"
	case ir.KString:
		return `b""`
	case ir.KSlice:
		return "rt.NIL"
	case ir.KStruct:
		return e.class(u) + "()"
	case ir.KArray:
		e.needHelpers(u)
		return fmt.Sprintf("zero_%d()", u.ID)
	case ir.KOpaque:
		if !u.OpaqueRef {
			e.use(opaqueContracts[u.Name])
			return "rt." + u.Obj + "()"
		}
	}
	return "None"
}

func (e *emitter) cloneExpr(t *ir.Type, x string) string {
	u := t.U()
	switch u.Kind {
	case ir.KStruct, ir.KOpaque:
		if u.Kind == ir.KStruct {
			e.class(u)
		} else if u.OpaqueRef {
			return x
		}
		return x + "._clone()"
	case ir.KArray:
		e.needHelpers(u)
		return fmt.Sprintf("clone_%d(%s)", u.ID, x)
	}
	return x
}

func (e *emitter) cloneFn(t *ir.Type) string {
	if !t.IsAggregate() {
		return ""
	}
	return "lambda v: " + e.cloneExpr(t, "v")
}

func (e *emitter) setStmt(t *ir.Type, dst, src string) string {
	u := t.U()
	switch u.Kind {
	case ir.KStruct, ir.KOpaque:
		if u.Kind == ir.KStruct {
			e.class(u)
		}
		return dst + "._set(" + src + ")"
	case ir.KArray:
		e.needHelpers(u)
		return fmt.Sprintf("set_%d(%s, %s)", u.ID, dst, src)
	}
	return dst + " = " + src
}

func (e *emitter) eqExpr(t *ir.Type, a, b string) string {
	u := t.U()
	switch u.Kind {
	case ir.KStruct:
		e.class(u)
		return a + "._eq(" + b + ")"
	case ir.KArray:
		e.needHelpers(u)
		return fmt.Sprintf("eq_%d(%s, %s)", u.ID, a, b)
	case ir.KInterface:
		return fmt.Sprintf("rt.iface_eq(%s, %s)", a, b)
	case ir.KSlice, ir.KMap, ir.KFunc:
		return fmt.Sprintf("rt.uncomparable_eq(%q)", ir.TypeString(t))
	case ir.KPointer, ir.KChan, ir.KOpaque:
		return a + " is " + b
	}
	return a + " == " + b
}

func (e *emitter) keyExpr(t *ir.Type, x string) string {
	u := t.U()
	switch u.Kind {
	case ir.KStruct:
		e.class(u)
		return x + "._key()"
	case ir.KArray:
		e.needHelpers(u)
		return fmt.Sprintf("key_%d(%s)", u.ID, x)
	case ir.KInterface:
		return fmt.Sprintf("rt.iface_key(%s)", x)
	case ir.KPointer, ir.KChan, ir.KOpaque:
		return fmt.Sprintf("id(%s)", x)
	case ir.KSlice, ir.KMap, ir.KFunc:
		return fmt.Sprintf("rt.unhashable_key(%q)", ir.TypeString(t))
	case ir.KBool:
		return fmt.Sprintf("(%s, 'b')", x)
	}
	return x
}

func (e *emitter) keyFn(t *ir.Type) string {
	switch t.U().Kind {
	case ir.KStruct, ir.KArray, ir.KInterface:
		return "lambda k: " + e.keyExpr(t, "k")
	}
	return "rt.identity_key"
}

func (e *emitter) td(t *ir.Type) string {
	if n, ok := e.tds[t]; ok {
		return n
	}
	t.Boxed = true
	n := fmt.Sprintf("TD_%d", t.ID)
	e.tds[t] = n
	return n
}

func (e *emitter) typeDescs(b *bytes.Buffer) {
	var ts []*ir.Type
	for t := range e.tds {
		ts = append(ts, t)
	}
	sort.Slice(ts, func(i, j int) bool { return ts[i].ID < ts[j].ID })
	for _, t := range ts {
		if t.Kind == ir.KString {
			fmt.Fprintf(b, "%s = rt.STRING_TYPE\n", e.tds[t])
			continue
		}
		name := ir.TypeString(t)
		u := t.U()
		basic := "None"
		switch u.Kind {
		case ir.KInt:
			basic = `"int"`
		case ir.KBool:
			basic = `"bool"`
		case ir.KString:
			basic = `"string"`
		}
		eq := "lambda a, b: " + e.eqExpr(t, "a", "b")
		key := "lambda a: " + e.keyExpr(t, "a")
		comparable := "True"
		if !t.Comparable() {
			eq = fmt.Sprintf("lambda a, b: rt.uncomparable_eq(%q)", name)
			key = fmt.Sprintf("lambda a: rt.unhashable_key(%q)", name)
			comparable = "False"
		}
		var ms []string
		for _, m := range t.MethodSet {
			fn := m.Func.Sym
			if t.IsAggregate() {
				fn = fmt.Sprintf("rt.closure(%d, lambda r, *a: %s(%s, *a))", m.Func.ID, m.Func.Sym, e.cloneExpr(t, "r"))
			}
			if e.p.SuspMethods[m.ID] && !m.Func.MaySuspend {
				fn = e.adapt(fn, len(m.Func.Results))
			}
			ms = append(ms, fmt.Sprintf("%q: %s", m.ID, fn))
		}
		fmt.Fprintf(b, "%s = rt.type_desc(name=%q, kind=%q, eq=%s, key=%s, methods={%s}, basic=%s, comparable=%s)\n",
			e.tds[t], name, u.Kind.String(), eq, key, strings.Join(ms, ", "), basic, comparable)
	}
	e.flushHelpers()
}

// ---- functions ----

type fnEmitter struct {
	e      *emitter
	f      *ir.Func
	b      strings.Builder
	order  map[*ir.Block]int
	defers bool
	frame  bool
	indent string
}

func localName(l *ir.Local) string {
	n := l.Name
	if n == "" || n == "_" {
		n = "t"
	}
	return fmt.Sprintf("_%d_%s", l.ID, n)
}

func (fe *fnEmitter) w(format string, args ...any) {
	fe.b.WriteString(fe.indent)
	fmt.Fprintf(&fe.b, format, args...)
	fe.b.WriteString("\n")
}

func (fe *fnEmitter) local(l *ir.Local) string {
	if fe.frame {
		return "fr." + localName(l)
	}
	return localName(l)
}

func cell(l *ir.Local) bool { return l.Boxed && !l.Type.IsAggregate() }

func (fe *fnEmitter) val(v ir.Value) string {
	switch v := v.(type) {
	case *ir.Local:
		if cell(v) {
			return fe.local(v) + ".v"
		}
		return fe.local(v)
	case *ir.Const:
		return fe.e.constant(v)
	case *ir.FuncRef:
		if fe.e.susp(v.Type) && !v.Func.MaySuspend {
			return fe.e.adapt(v.Func.Sym, len(v.Func.Results))
		}
		return v.Func.Sym
	}
	panic(fmt.Sprintf("py: operand %T", v))
}

func (e *emitter) constant(c *ir.Const) string {
	if c.Nil {
		if c.Type.U().Kind == ir.KSlice {
			return "rt.NIL"
		}
		return "None"
	}
	switch c.Val.Kind() {
	case constant.Bool:
		if constant.BoolVal(c.Val) {
			return "True"
		}
		return "False"
	case constant.String:
		return pyBytes(constant.StringVal(c.Val))
	case constant.Int:
		return c.Val.ExactString()
	}
	panic("py: constant " + c.Val.String())
}

func pyBytes(s string) string {
	var b strings.Builder
	b.WriteString(`b"`)
	for i := 0; i < len(s); i++ {
		c := s[i]
		switch {
		case c == '"' || c == '\\':
			b.WriteByte('\\')
			b.WriteByte(c)
		case c >= 0x20 && c < 0x7f:
			b.WriteByte(c)
		default:
			fmt.Fprintf(&b, "\\x%02x", c)
		}
	}
	b.WriteByte('"')
	return b.String()
}

func rootType(p *ir.Place) *ir.Type {
	switch r := p.Root.(type) {
	case ir.LocalRoot:
		return r.Local.Type
	case ir.GlobalRoot:
		return r.Global.Type
	case ir.DerefRoot:
		return r.Ptr.IRType().U().Elem
	case ir.SliceRoot:
		return r.Slice.IRType().U().Elem
	case ir.ValueRoot:
		return r.Value.IRType()
	}
	return nil
}

func (fe *fnEmitter) globalRef(g *ir.Global) string {
	if g.AddrTaken && !g.Type.IsAggregate() {
		return g.Sym + ".v"
	}
	return g.Sym
}

func (fe *fnEmitter) rootExpr(p *ir.Place) string {
	switch r := p.Root.(type) {
	case ir.LocalRoot:
		return fe.val(r.Local)
	case ir.GlobalRoot:
		return fe.globalRef(r.Global)
	case ir.DerefRoot:
		if r.Ptr.IRType().U().Elem.IsAggregate() {
			return "rt.nilchk(" + fe.val(r.Ptr) + ")"
		}
		return "rt.nilchk(" + fe.val(r.Ptr) + ").v"
	case ir.SliceRoot:
		fe.e.use("core.slice.index")
		return "rt.sget(" + fe.val(r.Slice) + ", " + fe.val(r.Index) + ")"
	case ir.ValueRoot:
		return fe.val(r.Value)
	}
	panic("py: place root")
}

func (fe *fnEmitter) proj(base string, cur *ir.Type, pr ir.Proj) string {
	if pr.Index != nil {
		return fmt.Sprintf("%s[rt.idx(%s, %d)]", base, fe.val(pr.Index), cur.U().Len)
	}
	return base + "." + fieldProp(cur, pr.Field)
}

func (fe *fnEmitter) placeExpr(p *ir.Place) string {
	s := fe.rootExpr(p)
	cur := rootType(p)
	for _, pr := range p.Path {
		s = fe.proj(s, cur, pr)
		cur = pr.Type
	}
	return s
}

func (fe *fnEmitter) store(p *ir.Place, v string) string {
	t := p.Type
	if sr, ok := p.Root.(ir.SliceRoot); ok && len(p.Path) == 0 && !t.IsAggregate() {
		fe.e.use("core.slice.store")
		return fmt.Sprintf("rt.sset(%s, %s, %s)", fe.val(sr.Slice), fe.val(sr.Index), v)
	}
	if lr, ok := p.Root.(ir.LocalRoot); ok && len(p.Path) == 0 && t.IsAggregate() && lr.Local.Kind == ir.LTemp {
		return fe.local(lr.Local) + " = " + v
	}
	if t.IsAggregate() {
		return fe.e.setStmt(t, fe.placeExpr(p), v)
	}
	return fe.placeExpr(p) + " = " + v
}

func (fe *fnEmitter) addrOf(p *ir.Place) string {
	t := p.Type
	if len(p.Path) == 0 {
		switch r := p.Root.(type) {
		case ir.DerefRoot:
			return fe.val(r.Ptr)
		case ir.LocalRoot:
			if t.IsAggregate() || r.Local.Boxed {
				return fe.local(r.Local)
			}
		case ir.GlobalRoot:
			return r.Global.Sym
		}
	}
	if t.IsAggregate() {
		return fe.placeExpr(p)
	}
	last := p.Path[len(p.Path)-1]
	base := &ir.Place{Root: p.Root, Path: p.Path[:len(p.Path)-1]}
	cur := rootType(p)
	if len(p.Path) > 1 {
		cur = p.Path[len(p.Path)-2].Type
	}
	return fmt.Sprintf("rt.field_ref(%s, %q)", fe.placeExpr(base), fieldProp(cur, last.Field))
}

func (e *emitter) function(f *ir.Func) string {
	if f.MaySuspend {
		return e.frameFunction(f)
	}
	fe := &fnEmitter{e: e, f: f, order: map[*ir.Block]int{}}
	for i, b := range f.Blocks {
		fe.order[b] = i
	}
	for _, b := range f.Blocks {
		for _, in := range b.Instrs {
			if _, ok := in.(*ir.Defer); ok {
				fe.defers = true
			}
		}
	}
	var params []string
	for _, l := range f.Env {
		params = append(params, localName(l))
	}
	for _, l := range f.Params {
		params = append(params, localName(l))
	}
	fe.w("def %s(%s):", f.Sym, strings.Join(params, ", "))
	fe.indent = "    "
	fe.globalDecl()
	for _, r := range f.Results {
		fe.w("%s = None", localName(r))
	}
	if fe.defers {
		fe.w("_d = []")
		fe.w("_p = None")
		fe.w("try:")
		fe.indent = "        "
		fe.loop(f)
		fe.indent = "    "
		fe.w("except rt.GoPanic as _e:")
		fe.w("    _p = _e")
		fe.w("rt.run_defers(_d, _p)")
		fe.w("return %s", fe.results())
	} else if len(f.Blocks) == 1 {
		fe.block(f.Blocks[0])
	} else {
		fe.loop(f)
	}
	fe.indent = ""
	fe.b.WriteString("\n\n")
	return fe.b.String()
}

// globalDecl declares the globals the function rebinds.
func (fe *fnEmitter) globalDecl() {
	seen := map[string]bool{}
	var gs []string
	for _, b := range fe.f.Blocks {
		for _, in := range b.Instrs {
			st, ok := in.(*ir.Store)
			if !ok {
				continue
			}
			gr, ok := st.Place.Root.(ir.GlobalRoot)
			if !ok || len(st.Place.Path) > 0 || st.Place.Type.IsAggregate() || gr.Global.AddrTaken {
				continue
			}
			if !seen[gr.Global.Sym] {
				seen[gr.Global.Sym] = true
				gs = append(gs, gr.Global.Sym)
			}
		}
	}
	if len(gs) > 0 {
		sort.Strings(gs)
		fe.w("global %s", strings.Join(gs, ", "))
	}
}

// loop writes the block dispatch loop.
func (fe *fnEmitter) loop(f *ir.Func) {
	pc := fe.pc()
	if !fe.frame {
		fe.w("%s = 0", pc)
	}
	fe.w("while True:")
	base := fe.indent
	for i, b := range f.Blocks {
		kw := "elif"
		if i == 0 {
			kw = "if"
		}
		fe.indent = base + "    "
		fe.w("%s %s == %d:", kw, pc, i)
		fe.indent = base + "        "
		if b.ResumeOf != nil {
			fe.resume(b.ResumeOf)
		}
		fe.block(b)
	}
	fe.indent = base + "    "
	fe.w("else:")
	fe.w("    raise rt.fault(\"bad block\")")
	fe.indent = base
}

func (fe *fnEmitter) pc() string {
	if fe.frame {
		return "fr.pc"
	}
	return "_pc"
}

func (fe *fnEmitter) results() string {
	var vs []string
	for _, r := range fe.f.Results {
		v := fe.val(r)
		if r.Boxed && r.Type.IsAggregate() {
			v = fe.e.cloneExpr(r.Type, v)
		}
		vs = append(vs, v)
	}
	switch len(vs) {
	case 0:
		return "None"
	case 1:
		return vs[0]
	}
	return "(" + strings.Join(vs, ", ") + ")"
}

func (fe *fnEmitter) mark(pos token.Pos) string {
	if !pos.IsValid() {
		return ""
	}
	return fmt.Sprintf("%s%d\x00", marker, int(pos))
}

func (fe *fnEmitter) block(b *ir.Block) {
	for _, in := range b.Instrs {
		fe.instr(in)
	}
	fe.term(b.Term)
}

func (fe *fnEmitter) goTo(target *ir.Block) {
	fe.w("%s = %d", fe.pc(), fe.order[target])
	fe.w("continue")
}

func (fe *fnEmitter) term(t ir.Terminator) {
	m := fe.mark(t.Position())
	switch t := t.(type) {
	case *ir.Jump:
		fe.w("%s%s = %d", m, fe.pc(), fe.order[t.Target])
		fe.w("continue")
	case *ir.If:
		fe.w("%s%s = %d if %s else %d", m, fe.pc(), fe.order[t.Then], fe.val(t.Cond), fe.order[t.Else])
		fe.w("continue")
	case *ir.Pause:
		fe.pause(t)
	case *ir.Return:
		switch {
		case fe.frame:
			fe.w("%srt.ret(t, fr)", m)
			fe.w("return")
		case fe.defers:
			fe.w("%sbreak", m)
		default:
			fe.w("%sreturn %s", m, fe.results())
		}
	case *ir.Panic:
		fe.w("%sraise rt.go_panic(%s)", m, fe.val(t.X))
	case *ir.PanicRuntime:
		fe.w("%sraise rt.plain_panic(%s)", m, pyBytes(t.Msg))
	case *ir.Unreachable:
		fe.w("%sraise rt.fault(\"unreachable\")", m)
	default:
		panic(fmt.Sprintf("py: terminator %T", t))
	}
}

// frameFunction emits a suspending function as a resumable frame class
// and a starter binding the arguments.
func (e *emitter) frameFunction(f *ir.Func) string {
	fe := &fnEmitter{e: e, f: f, order: map[*ir.Block]int{}, frame: true}
	for i, b := range f.Blocks {
		fe.order[b] = i
	}
	cls := "F_" + f.Sym
	fe.w("class %s(rt.Frame):", cls)
	fe.indent = "    "
	fe.w("def results(self):")
	fe.w("    fr = self")
	fe.w("    return [%s]", strings.TrimSuffix(strings.TrimPrefix(fe.resultsList(), "("), ")"))
	fe.w("")
	fe.w("def step(self, t):")
	fe.w("    fr = self")
	fe.indent = "        "
	fe.globalDecl()
	fe.indent = "        "
	fe.loop(f)
	fe.indent = ""
	fe.b.WriteString("\n\n")
	var params []string
	for _, l := range f.Env {
		params = append(params, localName(l))
	}
	for _, l := range f.Params {
		params = append(params, localName(l))
	}
	fe.w("def %s(%s):", f.Sym, strings.Join(params, ", "))
	fe.w("    fr = %s()", cls)
	fe.w("    rt.Frame.__init__(fr)")
	for _, l := range append(append([]*ir.Local(nil), f.Env...), f.Params...) {
		fe.w("    fr.%s = %s", localName(l), localName(l))
	}
	for _, r := range f.Results {
		fe.w("    fr.%s = None", localName(r))
	}
	fe.w("    return fr")
	fe.b.WriteString("\n\n")
	return fe.b.String()
}

func (fe *fnEmitter) resultsList() string {
	var vs []string
	for _, r := range fe.f.Results {
		v := fe.val(r)
		if r.Boxed && r.Type.IsAggregate() {
			v = fe.e.cloneExpr(r.Type, v)
		}
		vs = append(vs, v)
	}
	return strings.Join(vs, ", ")
}

func (fe *fnEmitter) resume(op ir.Instr) {
	switch i := op.(type) {
	case *ir.Call:
		for k, d := range i.Dsts {
			if d != nil {
				fe.w("%s = t.rv[%d]", fe.val(d), k)
			}
		}
	case *ir.Recv:
		if i.Dst != nil {
			fe.w("%s = t.rv[0]", fe.val(i.Dst))
		}
		if i.Ok != nil {
			fe.w("%s = t.rv[1]", fe.val(i.Ok))
		}
	case *ir.Select:
		fe.w("%s = t.rv[0]", fe.val(i.Index))
		for k, c := range i.Cases {
			if c.Send || c.Dst == nil && c.Ok == nil {
				continue
			}
			fe.w("if t.rv[0] == %d:", k)
			if c.Dst != nil {
				fe.w("    %s = t.rv[1]", fe.val(c.Dst))
			}
			if c.Ok != nil {
				fe.w("    %s = t.rv[2]", fe.val(c.Ok))
			}
		}
	}
}

func (fe *fnEmitter) pause(p *ir.Pause) {
	e := fe.e
	fe.w("%sfr.pc = %d", fe.mark(p.Position()), fe.order[p.Next])
	switch i := p.Op.(type) {
	case *ir.Call:
		fn, args, _ := fe.callee(i)
		switch i.Kind {
		case ir.CallExtern:
			fe.w("%s(%s)", fn, strings.Join(append([]string{"t"}, args...), ", "))
		case ir.CallValue:
			fe.w("rt.call(t, rt.fnchk(%s)(%s))", fn, strings.Join(args, ", "))
		default:
			fe.w("rt.call(t, %s(%s))", fn, strings.Join(args, ", "))
		}
	case *ir.Send:
		e.use("core.chan.send")
		fe.w("rt.chan_send(t, %s, %s)", fe.val(i.Ch), fe.val(i.V))
	case *ir.Recv:
		e.use("core.chan.recv")
		fe.w("rt.chan_recv(t, %s)", fe.val(i.Ch))
	case *ir.Select:
		e.use("core.select")
		var cs []string
		for _, c := range i.Cases {
			if c.Send {
				cs = append(cs, fmt.Sprintf("(%s, True, %s)", fe.val(c.Ch), fe.val(c.V)))
			} else {
				cs = append(cs, fmt.Sprintf("(%s, False, None)", fe.val(c.Ch)))
			}
		}
		fe.w("rt.select(t, [%s], %s)", strings.Join(cs, ", "), pyBool(i.Default))
	default:
		panic(fmt.Sprintf("py: pause on %T", p.Op))
	}
	fe.w("return")
}

func pyBool(b bool) string {
	if b {
		return "True"
	}
	return "False"
}

var binName = map[ir.BinOpKind]string{ir.Add: "add", ir.Sub: "sub", ir.Mul: "mul", ir.Div: "div", ir.Rem: "rem",
	ir.And: "and", ir.Or: "or", ir.Xor: "xor", ir.AndNot: "andnot", ir.Shl: "shl", ir.Shr: "shr"}

var binContract = map[ir.BinOpKind]string{ir.Add: "core.integer.add", ir.Sub: "core.integer.sub", ir.Mul: "core.integer.mul",
	ir.Div: "core.integer.div", ir.Rem: "core.integer.rem", ir.And: "core.integer.and", ir.Or: "core.integer.or",
	ir.Xor: "core.integer.xor", ir.AndNot: "core.integer.andnot", ir.Shl: "core.integer.shl", ir.Shr: "core.integer.shr"}

func (fe *fnEmitter) callee(c *ir.Call) (fn string, args []string, fid string) {
	for _, a := range c.Args {
		args = append(args, fe.val(a))
	}
	switch c.Kind {
	case ir.CallStatic:
		return c.Func.Sym, args, strconv.Itoa(c.Func.ID)
	case ir.CallValue:
		f := fe.val(c.Fn)
		return f, args, "rt.fid(" + f + ")"
	case ir.CallInterface:
		x := fe.val(c.Recv)
		return fmt.Sprintf("rt.ichk(%s).t.methods[%q]", x, c.Method), append([]string{x + ".v"}, args...), "None"
	case ir.CallExtern:
		fe.e.use(c.Extern.Contract)
		for k, a := range c.Args {
			if u := a.IRType().U(); u.Kind == ir.KSlice && u.Elem.U().Kind == ir.KFunc && !fe.e.susp(u.Elem) {
				fe.e.use("core.task.spawn")
				args[k] = fmt.Sprintf("rt.adapt_slice(%s, %d)", args[k], len(u.Elem.U().Results))
			}
		}
		sym := "rt." + externSymbol(c.Extern.Contract)
		if m, ok := fe.e.symbols[c.Extern.Contract]; ok {
			sym = m
		}
		return sym, args, "None"
	}
	panic("py: call kind")
}

func externSymbol(contract string) string {
	return strings.ReplaceAll(contract, ".", "_")
}

func (fe *fnEmitter) dsts(ds []*ir.Local) string {
	var s []string
	for _, d := range ds {
		s = append(s, fe.val(d))
	}
	return strings.Join(s, ", ")
}

func (fe *fnEmitter) instr(in ir.Instr) {
	e := fe.e
	m := fe.mark(in.Position())
	fe.b.WriteString(strings.Repeat("", 0))
	w := func(format string, args ...any) {
		fe.w(m+format, args...)
		m = ""
	}
	switch i := in.(type) {
	case *ir.DeclVar:
		init := e.zero(i.L.Type)
		if i.Init != nil {
			init = fe.val(i.Init)
		}
		if cell(i.L) {
			w("%s = rt.Cell(%s)", fe.local(i.L), init)
		} else {
			w("%s = %s", fe.local(i.L), init)
		}
	case *ir.Assign:
		w("%s = %s", fe.val(i.Dst), fe.val(i.Src))
	case *ir.Zero:
		w("%s = %s", fe.val(i.Dst), e.zero(i.Dst.Type))
	case *ir.Load:
		x := fe.placeExpr(i.Place)
		if i.Dst.Type.IsAggregate() {
			x = e.cloneExpr(i.Dst.Type, x)
		}
		w("%s = %s", fe.val(i.Dst), x)
	case *ir.Store:
		w("%s", fe.store(i.Place, fe.val(i.V)))
	case *ir.AddrOf:
		w("%s = %s", fe.val(i.Dst), fe.addrOf(i.Place))
	case *ir.New:
		el := i.Dst.Type.U().Elem
		if el.IsAggregate() {
			w("%s = %s", fe.val(i.Dst), e.zero(el))
		} else {
			w("%s = rt.Cell(%s)", fe.val(i.Dst), e.zero(el))
		}
	case *ir.UnOp:
		x := fe.val(i.X)
		switch i.Op {
		case ir.Not:
			w("%s = not %s", fe.val(i.Dst), x)
		case ir.Neg:
			e.use("core.integer.neg")
			w("%s = rt.neg_%s(%s)", fe.val(i.Dst), intKind(i.Dst.Type), x)
		case ir.BitNot:
			e.use("core.integer.not")
			w("%s = rt.not_%s(%s)", fe.val(i.Dst), intKind(i.Dst.Type), x)
		}
	case *ir.BinOp:
		w("%s", fe.binop(i))
	case *ir.Convert:
		w("%s", fe.convert(i))
	case *ir.MakeInterface:
		w("%s = rt.box(%s, %s)", fe.val(i.Dst), e.td(i.X.IRType()), fe.val(i.X))
	case *ir.TypeAssert:
		fe.typeAssert(i, w)
	case *ir.Call:
		fn, args, _ := fe.callee(i)
		as := strings.Join(args, ", ")
		call := fn + "(" + as + ")"
		if i.Kind == ir.CallValue {
			call = "rt.fnchk(" + fn + ")(" + as + ")"
		}
		if i.Kind == ir.CallExtern && fe.adaptsResults(i) {
			w("_r = %s", call)
			for k, d := range i.Dsts {
				v := fmt.Sprintf("_r[%d]", k)
				if len(i.Dsts) == 1 {
					v = "_r"
				}
				if d.Type.U().Kind == ir.KFunc && e.susp(d.Type) {
					v = e.adapt(v, len(d.Type.U().Results))
				}
				w("%s = %s", fe.val(d), v)
			}
			return
		}
		if len(i.Dsts) > 0 {
			w("%s = %s", fe.dsts(i.Dsts), call)
		} else {
			w("%s", call)
		}
	case *ir.MakeClosure:
		var ps, as []string
		for j, l := range i.Env {
			ps = append(ps, fmt.Sprintf("e%d", j))
			as = append(as, fe.local(l))
		}
		inner := append(append([]string(nil), ps...), "*a")
		v := fmt.Sprintf("rt.closure(%d, (lambda %s: (lambda *a: %s(%s)))(%s))", i.Func.ID, strings.Join(ps, ", "), i.Func.Sym, strings.Join(inner, ", "), strings.Join(as, ", "))
		if e.susp(i.Dst.Type) && !i.Func.MaySuspend {
			v = e.adapt(v, len(i.Func.Results))
		}
		w("%s = %s", fe.val(i.Dst), v)
	case *ir.MakeBound:
		v := fmt.Sprintf("rt.bound(%d, %s, %s)", i.Func.ID, i.Func.Sym, fe.val(i.Recv))
		if e.susp(i.Dst.Type) && !i.Func.MaySuspend {
			v = e.adapt(v, len(i.Func.Results))
		}
		w("%s = %s", fe.val(i.Dst), v)
	case *ir.MakeIfaceBound:
		v := fmt.Sprintf("rt.ibound(%s, %q)", fe.val(i.Recv), i.Method)
		if e.susp(i.Dst.Type) && !e.p.SuspMethods[i.Method] {
			v = e.adapt(v, len(i.Dst.Type.U().Results))
		}
		w("%s = %s", fe.val(i.Dst), v)
	case *ir.Len:
		w("%s = %s", fe.val(i.Dst), fe.lenExpr(i.X, false))
	case *ir.Cap:
		w("%s = %s", fe.val(i.Dst), fe.lenExpr(i.X, true))
	case *ir.MakeSlice:
		e.use("core.slice.make")
		w("%s = rt.make_slice(%s, %s, lambda: %s)", fe.val(i.Dst), fe.val(i.Len), fe.val(i.Cap), e.zero(i.Dst.Type.U().Elem))
	case *ir.MakeMap:
		e.use("core.map.make")
		w("%s = rt.make_map(%s)", fe.val(i.Dst), e.keyFn(i.Dst.Type.U().Key))
	case *ir.Append:
		e.use("core.slice.append")
		cl := e.cloneFn(i.Dst.Type.U().Elem)
		switch {
		case i.Spread != nil && i.Spread.IRType().U().Kind == ir.KString:
			w("%s = rt.append_string(%s, %s)", fe.val(i.Dst), fe.val(i.S), fe.val(i.Spread))
		case i.Spread != nil:
			w("%s = rt.append_slice(%s, %s%s)", fe.val(i.Dst), fe.val(i.S), fe.val(i.Spread), optArg(cl))
		default:
			var es []string
			for _, x := range i.Elems {
				es = append(es, fe.val(x))
			}
			w("%s = rt.append(%s, [%s]%s)", fe.val(i.Dst), fe.val(i.S), strings.Join(es, ", "), optArg(cl))
		}
	case *ir.Copy:
		e.use("core.slice.copy")
		if i.Src.IRType().U().Kind == ir.KString {
			w("%s = rt.copy_string(%s, %s)", fe.val(i.N), fe.val(i.Dst), fe.val(i.Src))
		} else {
			w("%s = rt.copy(%s, %s%s)", fe.val(i.N), fe.val(i.Dst), fe.val(i.Src), optArg(e.cloneFn(i.Dst.IRType().U().Elem)))
		}
	case *ir.IndexString:
		e.use("core.string.index")
		w("%s = rt.sindex(%s, %s)", fe.val(i.Dst), fe.val(i.S), fe.val(i.I))
	case *ir.SliceOp:
		w("%s", fe.sliceOp(i))
	case *ir.MapLookup:
		e.use("core.map.lookup")
		mt := i.M.IRType().U()
		ok := "_"
		if i.Ok != nil {
			ok = fe.val(i.Ok)
		}
		w("%s, %s = rt.map_get(%s, %s, %s, lambda: %s)", fe.val(i.Dst), ok, fe.val(i.M), fe.val(i.K), e.keyFn(mt.Key), e.zero(mt.Elem))
		if mt.Elem.IsAggregate() {
			w("%s = %s", fe.val(i.Dst), e.cloneExpr(mt.Elem, fe.val(i.Dst)))
		}
	case *ir.MapStore:
		e.use("core.map.store")
		w("rt.map_set(%s, %s, %s)", fe.val(i.M), fe.val(i.K), fe.val(i.V))
	case *ir.MapDelete:
		e.use("core.map.delete")
		w("rt.map_delete(%s, %s, %s)", fe.val(i.M), fe.val(i.K), e.keyFn(i.M.IRType().U().Key))
	case *ir.Clear:
		if i.X.IRType().U().Kind == ir.KMap {
			e.use("core.map.clear")
			w("rt.map_clear(%s)", fe.val(i.X))
		} else {
			e.use("core.slice.clear")
			w("rt.clear_slice(%s, lambda: %s)", fe.val(i.X), e.zero(i.X.IRType().U().Elem))
		}
	case *ir.DecodeRune:
		e.use("core.string.decode_rune")
		w("%s, %s = rt.decode_rune(%s, %s)", fe.val(i.Rune), fe.val(i.Width), fe.val(i.S), fe.val(i.I))
	case *ir.MapIterInit:
		e.use("core.map.iterate")
		w("%s = rt.map_iter(%s)", fe.val(i.Iter), fe.val(i.M))
	case *ir.MapIterNext:
		mt := i.Iter.Type.Elem.U()
		w("%s = rt.map_next(%s)", fe.val(i.Ok), fe.val(i.Iter))
		if i.Key != nil {
			w("%s = %s", fe.val(i.Key), e.cloneExpr(mt.Key, fe.val(i.Iter)+".k"))
		}
		if i.Val != nil {
			w("%s = %s", fe.val(i.Val), e.cloneExpr(mt.Elem, fe.val(i.Iter)+".v"))
		}
	case *ir.Print:
		e.use("core.print")
		var as []string
		for _, a := range i.Args {
			as = append(as, fe.val(a))
		}
		w("rt.go_print([%s], %s)", strings.Join(as, ", "), pyBool(i.Newline))
	case *ir.Defer:
		fn, args, fid := fe.callee(i.Call)
		if i.Call.Kind == ir.CallInterface {
			panic("py: defer of interface call")
		}
		if fe.frame {
			w("fr.defers.append(rt.Deferred(%s, [%s], %s, %s))", fn, strings.Join(args, ", "), fid, pyBool(i.Call.Suspends))
			return
		}
		w("_d.append(rt.Deferred(%s, [%s], %s))", fn, strings.Join(args, ", "), fid)
	case *ir.Recover:
		w("%s = rt.recover(%d)", fe.val(i.Dst), fe.f.ID)
	case *ir.Rebind:
		switch {
		case cell(i.L):
			w("%s = rt.Cell(%s.v)", fe.local(i.L), fe.local(i.L))
		case i.L.Type.IsAggregate():
			w("%s = %s", fe.local(i.L), e.cloneExpr(i.L.Type, fe.local(i.L)))
		default:
			w("pass")
		}
	case *ir.BoxParam:
		if cell(i.L) {
			w("%s = rt.Cell(%s)", fe.local(i.L), fe.local(i.L))
		}
	case *ir.MakeChan:
		e.use("core.chan.make")
		w("%s = rt.make_chan(%s, lambda: %s)", fe.val(i.Dst), fe.val(i.Size), e.zero(i.Dst.Type.U().Elem))
	case *ir.Close:
		e.use("core.chan.close")
		w("rt.chan_close(%s)", fe.val(i.Ch))
	case *ir.Go:
		e.use("core.task.spawn")
		fn, args, _ := fe.callee(i.Call)
		if i.Call.Kind == ir.CallInterface {
			panic("py: go statement with interface call")
		}
		if i.Call.Kind == ir.CallValue {
			fn = "rt.fnchk(" + fn + ")"
		}
		var ps []string
		for k := range args {
			ps = append(ps, fmt.Sprintf("a%d", k))
		}
		call := fmt.Sprintf("f(%s)", strings.Join(ps, ", "))
		if !i.Call.Suspends {
			call = fmt.Sprintf("rt.sync(lambda: (f(%s), [])[1])", strings.Join(ps, ", "))
		}
		w("rt.spawn((lambda %s: %s)(%s))", strings.Join(append([]string{"f"}, ps...), ", "), call, strings.Join(append([]string{fn}, args...), ", "))
	default:
		panic(fmt.Sprintf("py: unsupported instruction %T", in))
	}
}

func (fe *fnEmitter) adaptsResults(c *ir.Call) bool {
	for _, d := range c.Dsts {
		if d != nil && d.Type.U().Kind == ir.KFunc && fe.e.susp(d.Type) {
			return true
		}
	}
	return false
}

func optArg(s string) string {
	if s == "" {
		return ""
	}
	return ", " + s
}

func (fe *fnEmitter) lenExpr(x ir.Value, isCap bool) string {
	t := x.IRType().U()
	v := fe.val(x)
	switch t.Kind {
	case ir.KString:
		return "len(" + v + ")"
	case ir.KSlice:
		if isCap {
			return v + ".c"
		}
		return v + ".l"
	case ir.KArray:
		return strconv.FormatInt(t.Len, 10)
	case ir.KPointer:
		return strconv.FormatInt(t.Elem.U().Len, 10)
	case ir.KMap:
		fe.e.use("core.map.len")
		return "rt.map_len(" + v + ")"
	case ir.KChan:
		if isCap {
			fe.e.use("core.chan.cap")
			return "rt.chan_cap(" + v + ")"
		}
		fe.e.use("core.chan.len")
		return "rt.chan_len(" + v + ")"
	}
	panic("py: len of " + t.String())
}

func (fe *fnEmitter) binop(i *ir.BinOp) string {
	e := fe.e
	d := fe.val(i.Dst)
	x, y := fe.val(i.X), fe.val(i.Y)
	t := i.X.IRType()
	switch i.Op {
	case ir.Eq, ir.Ne:
		xc, xnil := i.X.(*ir.Const)
		yc, ynil := i.Y.(*ir.Const)
		xnil = xnil && xc.Nil
		ynil = ynil && yc.Nil
		var eq string
		switch {
		case t.U().Kind == ir.KSlice:
			if ynil {
				eq = x + ".a is None"
			} else {
				eq = y + ".a is None"
			}
		case (xnil || ynil) && t.U().Kind != ir.KInterface:
			eq = x + " is " + y
		default:
			eq = e.eqExpr(t, x, y)
		}
		if i.Op == ir.Ne {
			eq = "not (" + eq + ")"
		}
		return d + " = " + eq
	case ir.Lt, ir.Le, ir.Gt, ir.Ge:
		return fmt.Sprintf("%s = %s %s %s", d, x, i.Op, y)
	case ir.Min:
		return fmt.Sprintf("%s = %s if %s < %s else %s", d, y, y, x, x)
	case ir.Max:
		return fmt.Sprintf("%s = %s if %s > %s else %s", d, y, y, x, x)
	}
	if t.U().Kind == ir.KString {
		e.use("core.string.concat")
		return fmt.Sprintf("%s = %s + %s", d, x, y)
	}
	e.use(binContract[i.Op])
	return fmt.Sprintf("%s = rt.%s_%s(%s, %s)", d, binName[i.Op], intKind(i.Dst.Type), x, y)
}

func (fe *fnEmitter) convert(i *ir.Convert) string {
	e := fe.e
	d, x := fe.val(i.Dst), fe.val(i.X)
	switch i.Kind {
	case ir.ConvNop, ir.ConvIfaceToIface:
		return d + " = " + x
	case ir.ConvInt:
		e.use("core.integer.convert")
		return fmt.Sprintf("%s = rt.to_%s(%s)", d, intKind(i.Dst.Type), x)
	case ir.ConvIntToString:
		e.use("core.string.from_rune")
		return fmt.Sprintf("%s = rt.from_rune(%s)", d, x)
	case ir.ConvStringToBytes:
		e.use("core.string.to_bytes")
		return fmt.Sprintf("%s = rt.to_bytes(%s)", d, x)
	case ir.ConvBytesToString:
		e.use("core.string.from_bytes")
		return fmt.Sprintf("%s = rt.from_bytes(%s)", d, x)
	case ir.ConvStringToRunes:
		e.use("core.string.to_runes")
		return fmt.Sprintf("%s = rt.to_runes(%s)", d, x)
	case ir.ConvRunesToString:
		e.use("core.string.from_runes")
		return fmt.Sprintf("%s = rt.from_runes(%s)", d, x)
	case ir.ConvSliceToArray:
		e.use("core.slice.to_array")
		at := i.Dst.Type.U()
		return fmt.Sprintf("%s = rt.slice_to_array(%s, %d%s)", d, x, at.Len, optArg(e.cloneFn(at.Elem)))
	}
	panic(fmt.Sprintf("py: conversion %d", i.Kind))
}

func (fe *fnEmitter) sliceOp(i *ir.SliceOp) string {
	opt := func(v ir.Value) string {
		if v == nil {
			return "None"
		}
		return fe.val(v)
	}
	d, x := fe.val(i.Dst), fe.val(i.X)
	switch i.X.IRType().U().Kind {
	case ir.KString:
		fe.e.use("core.string.slice")
		return fmt.Sprintf("%s = rt.sslice(%s, %s, %s)", d, x, opt(i.Lo), opt(i.Hi))
	case ir.KPointer:
		fe.e.use("core.slice.slice")
		return fmt.Sprintf("%s = rt.slice_array(rt.nilchk(%s), %s, %s, %s)", d, x, opt(i.Lo), opt(i.Hi), opt(i.Max))
	}
	fe.e.use("core.slice.slice")
	return fmt.Sprintf("%s = rt.reslice(%s, %s, %s, %s)", d, x, opt(i.Lo), opt(i.Hi), opt(i.Max))
}

func (fe *fnEmitter) typeAssert(i *ir.TypeAssert, w func(string, ...any)) {
	e := fe.e
	x := fe.val(i.X)
	d := fe.val(i.Dst)
	if i.T.IsInterface() {
		var ids, names []string
		for _, m := range i.T.U().Methods {
			ids = append(ids, strconv.Quote(m.ID))
			names = append(names, strconv.Quote(m.ID)+": "+strconv.Quote(m.Name))
		}
		test := fmt.Sprintf("(%s is not None and rt.implements_all(%s.t, [%s]) is None)", x, x, strings.Join(ids, ", "))
		if i.Ok != nil {
			w("%s = %s", fe.val(i.Ok), test)
			w("%s = %s if %s else None", d, x, fe.val(i.Ok))
			return
		}
		w("if not %s:", test)
		w("    raise rt.assert_panic(%s, %q, %q, None if %s is None else {%s}[rt.implements_all(%s.t, [%s])])",
			x, ir.TypeString(i.X.IRType()), ir.TypeString(i.T), x, strings.Join(names, ", "), x, strings.Join(ids, ", "))
		w("%s = %s", d, x)
		return
	}
	td := e.td(i.T)
	test := fmt.Sprintf("(%s is not None and %s.t is %s)", x, x, td)
	val := e.cloneExpr(i.T, x+".v")
	if i.Ok != nil {
		w("%s = %s", fe.val(i.Ok), test)
		w("%s = %s if %s else %s", d, val, fe.val(i.Ok), e.zero(i.T))
		return
	}
	w("if not %s:", test)
	w("    raise rt.assert_panic(%s, %q, %q, None)", x, ir.TypeString(i.X.IRType()), ir.TypeString(i.T))
	w("%s = %s", d, val)
}
