# Code generated by goalchemy spec generate. DO NOT EDIT.
# flake8: noqa
from codec import *
from codec import rt


def case_0(h):
    v_ch = dec_chan(h.let("ch"), lambda r: dec_int(r, "i64"), lambda: 0)
    r0 = rt.chan_cap(v_ch)
    return [enc_int(r0)]


def case_1(h):
    v_ch = dec_chan(h.let("ch"), lambda r: dec_int(r, "i64"), lambda: 0)
    rt.chan_close(v_ch)
    return []


def case_2(h):
    v_ch = dec_chan(h.let("ch"), lambda r: dec_int(r, "i64"), lambda: 0)
    rt.chan_close(v_ch)
    h.after("ch", enc_chan(v_ch, lambda e: enc_int(e)))
    return []


def case_3(h):
    v_ch = dec_chan(h.let("ch"), lambda r: dec_int(r, "i64"), lambda: 0)
    rt.chan_close(v_ch)
    return []


def case_4(h):
    v_ch = dec_chan(h.let("ch"), lambda r: dec_int(r, "i64"), lambda: 0)
    r0 = rt.chan_len(v_ch)
    return [enc_int(r0)]


def case_5(h):
    v_ch = dec_chan(h.let("ch"), lambda r: dec_int(r, "i64"), lambda: 0)
    r0 = rt.chan_len(v_ch)
    return [enc_int(r0)]


def case_6(h):
    v_size = dec_int(h.let("size"), "i64")
    r0 = rt.make_chan(v_size, lambda: 0)
    return [enc_chan(r0, lambda e: enc_int(e))]


def case_7(h):
    v_size = dec_int(h.let("size"), "i64")
    r0 = rt.make_chan(v_size, lambda: 0)
    return [enc_chan(r0, lambda e: enc_int(e))]


def case_8(h):
    v_ch = dec_chan(h.let("ch"), lambda r: dec_int(r, "i64"), lambda: 0)
    rv = rt.run_isolated(lambda t: rt.chan_recv(t, v_ch))
    r0 = rv[0]
    r1 = rv[1]
    h.after("ch", enc_chan(v_ch, lambda e: enc_int(e)))
    return [enc_int(r0), enc_bool(r1)]


def case_9(h):
    v_ch = dec_chan(h.let("ch"), lambda r: dec_string(r), lambda: b"")
    rv = rt.run_isolated(lambda t: rt.chan_recv(t, v_ch))
    r0 = rv[0]
    r1 = rv[1]
    return [enc_string(r0), enc_bool(r1)]


def case_10(h):
    v_ch = dec_chan(h.let("ch"), lambda r: dec_int(r, "i64"), lambda: 0)
    rv = rt.run_isolated(lambda t: rt.chan_recv(t, v_ch))
    r0 = rv[0]
    r1 = rv[1]
    return [enc_int(r0), enc_bool(r1)]


def case_11(h):
    v_ch = dec_chan(h.let("ch"), lambda r: dec_int(r, "i64"), lambda: 0)
    rv = rt.run_isolated(lambda t: rt.chan_recv(t, v_ch))
    r0 = rv[0]
    r1 = rv[1]
    return [enc_int(r0), enc_bool(r1)]


def case_12(h):
    v_ch = dec_chan(h.let("ch"), lambda r: dec_int(r, "i64"), lambda: 0)
    rv = rt.run_isolated(lambda t: rt.chan_recv(t, v_ch))
    r0 = rv[0]
    r1 = rv[1]
    return [enc_int(r0), enc_bool(r1)]


def case_13(h):
    v_ch = dec_chan(h.let("ch"), lambda r: dec_int(r, "i64"), lambda: 0)
    v_v = dec_int(h.let("v"), "i64")
    rv = rt.run_isolated(lambda t: rt.chan_send(t, v_ch, v_v))
    h.after("ch", enc_chan(v_ch, lambda e: enc_int(e)))
    return []


def case_14(h):
    v_ch = dec_chan(h.let("ch"), lambda r: dec_int(r, "i64"), lambda: 0)
    v_v = dec_int(h.let("v"), "i64")
    rv = rt.run_isolated(lambda t: rt.chan_send(t, v_ch, v_v))
    return []


def case_15(h):
    v_ch = dec_chan(h.let("ch"), lambda r: dec_int(r, "i64"), lambda: 0)
    v_v = dec_int(h.let("v"), "i64")
    rv = rt.run_isolated(lambda t: rt.chan_send(t, v_ch, v_v))
    return []


def case_16(h):
    v_ch = dec_chan(h.let("ch"), lambda r: dec_int(r, "i64"), lambda: 0)
    v_v = dec_int(h.let("v"), "i64")
    rv = rt.run_isolated(lambda t: rt.chan_send(t, v_ch, v_v))
    return []


def case_17(h):
    v_ch = dec_chan(h.let("ch"), lambda r: dec_string(r), lambda: b"")
    v_v = dec_string(h.let("v"))
    rv = rt.run_isolated(lambda t: rt.chan_send(t, v_ch, v_v))
    return []


def case_18(h):
    v_a = dec_int(h.let("a"), "i32")
    v_b = dec_int(h.let("b"), "i32")
    r0 = rt.add_i32(v_a, v_b)
    return [enc_int(r0)]


def case_19(h):
    v_a = dec_int(h.let("a"), "i64")
    v_b = dec_int(h.let("b"), "i64")
    r0 = rt.add_i64(v_a, v_b)
    return [enc_int(r0)]


def case_20(h):
    v_a = dec_int(h.let("a"), "i8")
    v_b = dec_int(h.let("b"), "i8")
    r0 = rt.add_i8(v_a, v_b)
    return [enc_int(r0)]


def case_21(h):
    v_a = dec_int(h.let("a"), "i64")
    v_b = dec_int(h.let("b"), "i64")
    r0 = rt.add_i64(v_a, v_b)
    return [enc_int(r0)]


def case_22(h):
    v_a = dec_int(h.let("a"), "u32")
    v_b = dec_int(h.let("b"), "u32")
    r0 = rt.add_u32(v_a, v_b)
    return [enc_int(r0)]


def case_23(h):
    v_a = dec_int(h.let("a"), "u64")
    v_b = dec_int(h.let("b"), "u64")
    r0 = rt.add_u64(v_a, v_b)
    return [enc_int(r0)]


def case_24(h):
    v_a = dec_int(h.let("a"), "i64")
    v_b = dec_int(h.let("b"), "i64")
    r0 = rt.and_i64(v_a, v_b)
    return [enc_int(r0)]


def case_25(h):
    v_a = dec_int(h.let("a"), "u32")
    v_b = dec_int(h.let("b"), "u32")
    r0 = rt.and_u32(v_a, v_b)
    return [enc_int(r0)]


def case_26(h):
    v_a = dec_int(h.let("a"), "i64")
    v_b = dec_int(h.let("b"), "i64")
    r0 = rt.andnot_i64(v_a, v_b)
    return [enc_int(r0)]


def case_27(h):
    v_a = dec_int(h.let("a"), "u16")
    v_b = dec_int(h.let("b"), "u16")
    r0 = rt.andnot_u16(v_a, v_b)
    return [enc_int(r0)]


def case_28(h):
    v_a = dec_int(h.let("a"), "u32")
    v_b = dec_int(h.let("b"), "u32")
    r0 = rt.compare_int(v_a, v_b)
    return [enc_int(r0)]


def case_29(h):
    v_a = dec_int(h.let("a"), "i64")
    v_b = dec_int(h.let("b"), "i64")
    r0 = rt.compare_int(v_a, v_b)
    return [enc_int(r0)]


def case_30(h):
    v_a = dec_int(h.let("a"), "u32")
    v_b = dec_int(h.let("b"), "u32")
    r0 = rt.compare_int(v_a, v_b)
    return [enc_int(r0)]


def case_31(h):
    v_a = dec_int(h.let("a"), "u64")
    v_b = dec_int(h.let("b"), "u64")
    r0 = rt.compare_int(v_a, v_b)
    return [enc_int(r0)]


def case_32(h):
    v_a = dec_int(h.let("a"), "i32")
    r0 = rt.to_u16(v_a)
    return [enc_int(r0)]


def case_33(h):
    v_a = dec_int(h.let("a"), "i64")
    r0 = rt.to_i64(v_a)
    return [enc_int(r0)]


def case_34(h):
    v_a = dec_int(h.let("a"), "i8")
    r0 = rt.to_u64(v_a)
    return [enc_int(r0)]


def case_35(h):
    v_a = dec_int(h.let("a"), "i64")
    r0 = rt.to_i8(v_a)
    return [enc_int(r0)]


def case_36(h):
    v_a = dec_int(h.let("a"), "u32")
    r0 = rt.to_i32(v_a)
    return [enc_int(r0)]


def case_37(h):
    v_a = dec_int(h.let("a"), "u64")
    r0 = rt.to_i64(v_a)
    return [enc_int(r0)]


def case_38(h):
    v_a = dec_int(h.let("a"), "i32")
    v_b = dec_int(h.let("b"), "i32")
    r0 = rt.div_i32(v_a, v_b)
    return [enc_int(r0)]


def case_39(h):
    v_a = dec_int(h.let("a"), "i64")
    v_b = dec_int(h.let("b"), "i64")
    r0 = rt.div_i64(v_a, v_b)
    return [enc_int(r0)]


def case_40(h):
    v_a = dec_int(h.let("a"), "i8")
    v_b = dec_int(h.let("b"), "i8")
    r0 = rt.div_i8(v_a, v_b)
    return [enc_int(r0)]


def case_41(h):
    v_a = dec_int(h.let("a"), "i64")
    v_b = dec_int(h.let("b"), "i64")
    r0 = rt.div_i64(v_a, v_b)
    return [enc_int(r0)]


def case_42(h):
    v_a = dec_int(h.let("a"), "i64")
    v_b = dec_int(h.let("b"), "i64")
    r0 = rt.div_i64(v_a, v_b)
    return [enc_int(r0)]


def case_43(h):
    v_a = dec_int(h.let("a"), "u64")
    v_b = dec_int(h.let("b"), "u64")
    r0 = rt.div_u64(v_a, v_b)
    return [enc_int(r0)]


def case_44(h):
    v_a = dec_int(h.let("a"), "i32")
    v_b = dec_int(h.let("b"), "i32")
    r0 = rt.mul_i32(v_a, v_b)
    return [enc_int(r0)]


def case_45(h):
    v_a = dec_int(h.let("a"), "i32")
    v_b = dec_int(h.let("b"), "i32")
    r0 = rt.mul_i32(v_a, v_b)
    return [enc_int(r0)]


def case_46(h):
    v_a = dec_int(h.let("a"), "i64")
    v_b = dec_int(h.let("b"), "i64")
    r0 = rt.mul_i64(v_a, v_b)
    return [enc_int(r0)]


def case_47(h):
    v_a = dec_int(h.let("a"), "i8")
    v_b = dec_int(h.let("b"), "i8")
    r0 = rt.mul_i8(v_a, v_b)
    return [enc_int(r0)]


def case_48(h):
    v_a = dec_int(h.let("a"), "u32")
    v_b = dec_int(h.let("b"), "u32")
    r0 = rt.mul_u32(v_a, v_b)
    return [enc_int(r0)]


def case_49(h):
    v_a = dec_int(h.let("a"), "u64")
    v_b = dec_int(h.let("b"), "u64")
    r0 = rt.mul_u64(v_a, v_b)
    return [enc_int(r0)]


def case_50(h):
    v_a = dec_int(h.let("a"), "i32")
    r0 = rt.neg_i32(v_a)
    return [enc_int(r0)]


def case_51(h):
    v_a = dec_int(h.let("a"), "i64")
    r0 = rt.neg_i64(v_a)
    return [enc_int(r0)]


def case_52(h):
    v_a = dec_int(h.let("a"), "u64")
    r0 = rt.neg_u64(v_a)
    return [enc_int(r0)]


def case_53(h):
    v_a = dec_int(h.let("a"), "u8")
    r0 = rt.neg_u8(v_a)
    return [enc_int(r0)]


def case_54(h):
    v_a = dec_int(h.let("a"), "i64")
    r0 = rt.not_i64(v_a)
    return [enc_int(r0)]


def case_55(h):
    v_a = dec_int(h.let("a"), "u32")
    r0 = rt.not_u32(v_a)
    return [enc_int(r0)]


def case_56(h):
    v_a = dec_int(h.let("a"), "u8")
    r0 = rt.not_u8(v_a)
    return [enc_int(r0)]


def case_57(h):
    v_a = dec_int(h.let("a"), "i8")
    v_b = dec_int(h.let("b"), "i8")
    r0 = rt.or_i8(v_a, v_b)
    return [enc_int(r0)]


def case_58(h):
    v_a = dec_int(h.let("a"), "u32")
    v_b = dec_int(h.let("b"), "u32")
    r0 = rt.or_u32(v_a, v_b)
    return [enc_int(r0)]


def case_59(h):
    v_a = dec_int(h.let("a"), "u8")
    v_b = dec_int(h.let("b"), "u8")
    r0 = rt.rem_u8(v_a, v_b)
    return [enc_int(r0)]


def case_60(h):
    v_a = dec_int(h.let("a"), "i64")
    v_b = dec_int(h.let("b"), "i64")
    r0 = rt.rem_i64(v_a, v_b)
    return [enc_int(r0)]


def case_61(h):
    v_a = dec_int(h.let("a"), "i64")
    v_b = dec_int(h.let("b"), "i64")
    r0 = rt.rem_i64(v_a, v_b)
    return [enc_int(r0)]


def case_62(h):
    v_a = dec_int(h.let("a"), "i64")
    v_b = dec_int(h.let("b"), "i64")
    r0 = rt.rem_i64(v_a, v_b)
    return [enc_int(r0)]


def case_63(h):
    v_a = dec_int(h.let("a"), "u32")
    v_b = dec_int(h.let("b"), "u32")
    r0 = rt.rem_u32(v_a, v_b)
    return [enc_int(r0)]


def case_64(h):
    v_a = dec_int(h.let("a"), "i64")
    v_b = dec_int(h.let("b"), "u64")
    r0 = rt.shl_i64(v_a, v_b)
    return [enc_int(r0)]


def case_65(h):
    v_a = dec_int(h.let("a"), "u64")
    v_b = dec_int(h.let("b"), "u64")
    r0 = rt.shl_u64(v_a, v_b)
    return [enc_int(r0)]


def case_66(h):
    v_a = dec_int(h.let("a"), "i64")
    v_b = dec_int(h.let("b"), "i64")
    r0 = rt.shl_i64(v_a, v_b)
    return [enc_int(r0)]


def case_67(h):
    v_a = dec_int(h.let("a"), "i64")
    v_b = dec_int(h.let("b"), "i64")
    r0 = rt.shl_i64(v_a, v_b)
    return [enc_int(r0)]


def case_68(h):
    v_a = dec_int(h.let("a"), "i8")
    v_b = dec_int(h.let("b"), "i64")
    r0 = rt.shl_i8(v_a, v_b)
    return [enc_int(r0)]


def case_69(h):
    v_a = dec_int(h.let("a"), "i32")
    v_b = dec_int(h.let("b"), "u64")
    r0 = rt.shl_i32(v_a, v_b)
    return [enc_int(r0)]


def case_70(h):
    v_a = dec_int(h.let("a"), "i64")
    v_b = dec_int(h.let("b"), "u64")
    r0 = rt.shr_i64(v_a, v_b)
    return [enc_int(r0)]


def case_71(h):
    v_a = dec_int(h.let("a"), "i8")
    v_b = dec_int(h.let("b"), "i64")
    r0 = rt.shr_i8(v_a, v_b)
    return [enc_int(r0)]


def case_72(h):
    v_a = dec_int(h.let("a"), "u8")
    v_b = dec_int(h.let("b"), "i64")
    r0 = rt.shr_u8(v_a, v_b)
    return [enc_int(r0)]


def case_73(h):
    v_a = dec_int(h.let("a"), "u64")
    v_b = dec_int(h.let("b"), "u64")
    r0 = rt.shr_u64(v_a, v_b)
    return [enc_int(r0)]


def case_74(h):
    v_a = dec_int(h.let("a"), "i8")
    v_b = dec_int(h.let("b"), "i64")
    r0 = rt.shr_i8(v_a, v_b)
    return [enc_int(r0)]


def case_75(h):
    v_a = dec_int(h.let("a"), "i32")
    v_b = dec_int(h.let("b"), "i64")
    r0 = rt.shr_i32(v_a, v_b)
    return [enc_int(r0)]


def case_76(h):
    v_a = dec_int(h.let("a"), "i16")
    v_b = dec_int(h.let("b"), "i16")
    r0 = rt.sub_i16(v_a, v_b)
    return [enc_int(r0)]


def case_77(h):
    v_a = dec_int(h.let("a"), "i64")
    v_b = dec_int(h.let("b"), "i64")
    r0 = rt.sub_i64(v_a, v_b)
    return [enc_int(r0)]


def case_78(h):
    v_a = dec_int(h.let("a"), "u8")
    v_b = dec_int(h.let("b"), "u8")
    r0 = rt.sub_u8(v_a, v_b)
    return [enc_int(r0)]


def case_79(h):
    v_a = dec_int(h.let("a"), "u64")
    v_b = dec_int(h.let("b"), "u64")
    r0 = rt.sub_u64(v_a, v_b)
    return [enc_int(r0)]


def case_80(h):
    v_a = dec_int(h.let("a"), "i32")
    v_b = dec_int(h.let("b"), "i32")
    r0 = rt.xor_i32(v_a, v_b)
    return [enc_int(r0)]


def case_81(h):
    v_a = dec_int(h.let("a"), "u64")
    v_b = dec_int(h.let("b"), "u64")
    r0 = rt.xor_u64(v_a, v_b)
    return [enc_int(r0)]


def case_82(h):
    v_m = dec_map(h.let("m"), lambda r: dec_int(r, "i64"), lambda r: dec_int(r, "i64"))
    rt.map_clear(v_m)
    h.after("m", enc_map(v_m, lambda e: enc_int(e), lambda e: enc_int(e)))
    return []


def case_83(h):
    v_m = dec_map(h.let("m"), lambda r: dec_int(r, "i64"), lambda r: dec_int(r, "i64"))
    v_k = dec_int(h.let("k"), "i64")
    rt.map_delete(v_m, v_k, rt.identity_key)
    return []


def case_84(h):
    v_m = dec_map(h.let("m"), lambda r: dec_int(r, "i64"), lambda r: dec_int(r, "i64"))
    v_k = dec_int(h.let("k"), "i64")
    rt.map_delete(v_m, v_k, rt.identity_key)
    h.after("m", enc_map(v_m, lambda e: enc_int(e), lambda e: enc_int(e)))
    return []


def case_85(h):
    v_m = dec_map(h.let("m"), lambda r: dec_int(r, "i64"), lambda r: dec_int(r, "i64"))
    r0 = rt.map_keys(v_m)
    return [enc_slice(r0, lambda e: enc_int(e))]


def case_86(h):
    v_m = dec_map(h.let("m"), lambda r: dec_int(r, "i64"), lambda r: dec_int(r, "i64"))
    r0 = rt.map_len(v_m)
    return [enc_int(r0)]


def case_87(h):
    v_m = dec_map(h.let("m"), lambda r: dec_int(r, "i64"), lambda r: dec_int(r, "i64"))
    r0 = rt.map_len(v_m)
    return [enc_int(r0)]


def case_88(h):
    v_m = dec_map(h.let("m"), lambda r: dec_int(r, "i64"), lambda r: dec_string(r))
    v_k = dec_int(h.let("k"), "i64")
    r0, r1 = rt.map_get(v_m, v_k, rt.identity_key, lambda: b"")
    return [enc_string(r0), enc_bool(r1)]


def case_89(h):
    v_m = dec_map(h.let("m"), lambda r: dec_string(r), lambda r: dec_int(r, "i64"))
    v_k = dec_string(h.let("k"))
    r0, r1 = rt.map_get(v_m, v_k, rt.identity_key, lambda: 0)
    return [enc_int(r0), enc_bool(r1)]


def case_90(h):
    r0 = rt.make_map(rt.identity_key)
    return [enc_map(r0, lambda e: enc_string(e), lambda e: enc_int(e))]


def case_91(h):
    v_m = dec_map(h.let("m"), lambda r: dec_int(r, "i64"), lambda r: dec_int(r, "i64"))
    v_k = dec_int(h.let("k"), "i64")
    v_v = dec_int(h.let("v"), "i64")
    rt.map_set(v_m, v_k, v_v)
    return []


def case_92(h):
    v_m = dec_map(h.let("m"), lambda r: dec_int(r, "i64"), lambda r: dec_int(r, "i64"))
    v_k = dec_int(h.let("k"), "i64")
    v_v = dec_int(h.let("v"), "i64")
    rt.map_set(v_m, v_k, v_v)
    h.after("m", enc_map(v_m, lambda e: enc_int(e), lambda e: enc_int(e)))
    return []


def case_93(h):
    v_v = dec_bool(h.let("v"))
    r0 = rt.print_string(v_v)
    return [enc_string(r0)]


def case_94(h):
    v_v = dec_string(h.let("v"))
    r0 = rt.print_string(v_v)
    return [enc_string(r0)]


def case_95(h):
    v_v = dec_int(h.let("v"), "i64")
    r0 = rt.print_string(v_v)
    return [enc_string(r0)]


def case_96(h):
    v_v = dec_int(h.let("v"), "u64")
    r0 = rt.print_string(v_v)
    return [enc_string(r0)]


def case_97(h):
    v_a = dec_chan(h.let("a"), lambda r: dec_int(r, "i64"), lambda: 0)
    v_b = dec_chan(h.let("b"), lambda r: dec_int(r, "i64"), lambda: 0)
    v_dflt = dec_bool(h.let("dflt"))
    rv = rt.run_isolated(lambda t: harness_select2(t, v_a, v_b, v_dflt))
    r0 = rv[0]
    return [enc_int(r0)]


def case_98(h):
    v_a = dec_chan(h.let("a"), lambda r: dec_int(r, "i64"), lambda: 0)
    v_b = dec_chan(h.let("b"), lambda r: dec_int(r, "i64"), lambda: 0)
    v_dflt = dec_bool(h.let("dflt"))
    rv = rt.run_isolated(lambda t: harness_select2(t, v_a, v_b, v_dflt))
    r0 = rv[0]
    return [enc_int(r0)]


def case_99(h):
    v_a = dec_chan(h.let("a"), lambda r: dec_int(r, "i64"), lambda: 0)
    v_b = dec_chan(h.let("b"), lambda r: dec_int(r, "i64"), lambda: 0)
    v_dflt = dec_bool(h.let("dflt"))
    rv = rt.run_isolated(lambda t: harness_select2(t, v_a, v_b, v_dflt))
    r0 = rv[0]
    return [enc_int(r0)]


def case_100(h):
    v_a = dec_chan(h.let("a"), lambda r: dec_int(r, "i64"), lambda: 0)
    v_b = dec_chan(h.let("b"), lambda r: dec_int(r, "i64"), lambda: 0)
    v_dflt = dec_bool(h.let("dflt"))
    rv = rt.run_isolated(lambda t: harness_select2(t, v_a, v_b, v_dflt))
    r0 = rv[0]
    h.after("b", enc_chan(v_b, lambda e: enc_int(e)))
    return [enc_int(r0)]


def case_101(h):
    v_s = dec_slice(h.let("s"), lambda r: dec_string(r), lambda: b"", False)
    v_vs = dec_slice(h.let("vs"), lambda r: dec_string(r), lambda: b"", False)
    r0 = rt.zero_append_growth(rt.append_slice(v_s, v_vs), v_s, lambda: b"")
    return [enc_slice(r0, lambda e: enc_string(e))]


def case_102(h):
    v_s = dec_slice(h.let("s"), lambda r: dec_int(r, "i64"), lambda: 0, False)
    v_vs = dec_slice(h.let("vs"), lambda r: dec_int(r, "i64"), lambda: 0, False)
    r0 = rt.zero_append_growth(rt.append_slice(v_s, v_vs), v_s, lambda: 0)
    return [enc_slice(r0, lambda e: enc_int(e))]


def case_103(h):
    v_s = dec_slice(h.let("s"), lambda r: dec_int(r, "i64"), lambda: 0, False)
    v_vs = dec_slice(h.let("vs"), lambda r: dec_int(r, "i64"), lambda: 0, False)
    r0 = rt.zero_append_growth(rt.append_slice(v_s, v_vs), v_s, lambda: 0)
    return [enc_slice(r0, lambda e: enc_int(e))]


def case_104(h):
    v_s = dec_slice(h.let("s"), lambda r: dec_int(r, "i64"), lambda: 0, False)
    v_t = view(v_s, h.let("t"))
    v_vs = dec_slice(h.let("vs"), lambda r: dec_int(r, "i64"), lambda: 0, False)
    r0 = rt.zero_append_growth(rt.append_slice(v_s, v_vs), v_s, lambda: 0)
    h.after("t", enc_slice(v_t, lambda e: enc_int(e)))
    return [enc_slice(r0, lambda e: enc_int(e))]


def case_105(h):
    v_s = dec_slice(h.let("s"), lambda r: dec_int(r, "i64"), lambda: 0, False)
    v_vs = dec_slice(h.let("vs"), lambda r: dec_int(r, "i64"), lambda: 0, False)
    r0 = rt.zero_append_growth(rt.append_slice(v_s, v_vs), v_s, lambda: 0)
    return [enc_slice(r0, lambda e: enc_int(e))]


def case_106(h):
    v_s = dec_slice(h.let("s"), lambda r: dec_int(r, "i64"), lambda: 0, False)
    v_a = view(v_s, h.let("a"))
    v_vs = view(v_s, h.let("vs"))
    r0 = rt.zero_append_growth(rt.append_slice(v_a, v_vs), v_a, lambda: 0)
    h.after("s", enc_slice(v_s, lambda e: enc_int(e)))
    return [enc_slice(r0, lambda e: enc_int(e))]


def case_107(h):
    v_s = dec_slice(h.let("s"), lambda r: dec_int(r, "i64"), lambda: 0, False)
    v_t = view(v_s, h.let("t"))
    rt.clear_slice(v_t, lambda: 0)
    h.after("s", enc_slice(v_s, lambda e: enc_int(e)))
    return []


def case_108(h):
    v_s = dec_slice(h.let("s"), lambda r: dec_int(r, "i64"), lambda: 0, False)
    v_d = view(v_s, h.let("d"))
    v_src = view(v_s, h.let("src"))
    r0 = rt.copy(v_d, v_src)
    h.after("s", enc_slice(v_s, lambda e: enc_int(e)))
    return [enc_int(r0)]


def case_109(h):
    v_d = dec_slice(h.let("d"), lambda r: dec_int(r, "u8"), lambda: 0, True)
    v_src = dec_slice(h.let("src"), lambda r: dec_int(r, "u8"), lambda: 0, True)
    r0 = rt.copy(v_d, v_src)
    h.after("d", enc_slice(v_d, lambda e: enc_int(e)))
    return [enc_int(r0)]


def case_110(h):
    v_s = dec_slice(h.let("s"), lambda r: dec_int(r, "i64"), lambda: 0, False)
    v_i = dec_int(h.let("i"), "i64")
    r0 = rt.sget(v_s, v_i)
    return [enc_int(r0)]


def case_111(h):
    v_s = dec_slice(h.let("s"), lambda r: dec_int(r, "i64"), lambda: 0, False)
    v_i = dec_int(h.let("i"), "i64")
    r0 = rt.sget(v_s, v_i)
    return [enc_int(r0)]


def case_112(h):
    v_s = dec_slice(h.let("s"), lambda r: dec_string(r), lambda: b"", False)
    v_i = dec_int(h.let("i"), "i64")
    r0 = rt.sget(v_s, v_i)
    return [enc_string(r0)]


def case_113(h):
    v_len = dec_int(h.let("len"), "i64")
    v_cap = dec_int(h.let("cap"), "i64")
    r0 = rt.make_slice(v_len, v_cap, lambda: 0, False)
    return [enc_slice(r0, lambda e: enc_int(e))]


def case_114(h):
    v_len = dec_int(h.let("len"), "i64")
    v_cap = dec_int(h.let("cap"), "i64")
    r0 = rt.make_slice(v_len, v_cap, lambda: 0, True)
    return [enc_slice(r0, lambda e: enc_int(e))]


def case_115(h):
    v_len = dec_int(h.let("len"), "i64")
    v_cap = dec_int(h.let("cap"), "i64")
    r0 = rt.make_slice(v_len, v_cap, lambda: 0, False)
    return [enc_slice(r0, lambda e: enc_int(e))]


def case_116(h):
    v_s = dec_slice(h.let("s"), lambda r: dec_int(r, "i64"), lambda: 0, False)
    v_lo = dec_int(h.let("lo"), "i64")
    v_hi = dec_int(h.let("hi"), "i64")
    v_max = dec_int(h.let("max"), "i64")
    r0 = rt.reslice(v_s, v_lo, v_hi, v_max)
    return [enc_slice(r0, lambda e: enc_int(e))]


def case_117(h):
    v_s = dec_slice(h.let("s"), lambda r: dec_int(r, "i64"), lambda: 0, False)
    v_lo = dec_int(h.let("lo"), "i64")
    v_hi = dec_int(h.let("hi"), "i64")
    v_max = dec_int(h.let("max"), "i64")
    r0 = rt.reslice(v_s, v_lo, v_hi, v_max)
    return [enc_slice(r0, lambda e: enc_int(e))]


def case_118(h):
    v_s = dec_slice(h.let("s"), lambda r: dec_int(r, "i64"), lambda: 0, False)
    v_lo = dec_int(h.let("lo"), "i64")
    v_hi = dec_int(h.let("hi"), "i64")
    v_max = dec_int(h.let("max"), "i64")
    r0 = rt.reslice(v_s, v_lo, v_hi, v_max)
    return [enc_slice(r0, lambda e: enc_int(e))]


def case_119(h):
    v_s = dec_slice(h.let("s"), lambda r: dec_int(r, "i64"), lambda: 0, False)
    v_lo = dec_int(h.let("lo"), "i64")
    v_hi = dec_int(h.let("hi"), "i64")
    v_max = dec_int(h.let("max"), "i64")
    r0 = rt.reslice(v_s, v_lo, v_hi, v_max)
    return [enc_slice(r0, lambda e: enc_int(e))]


def case_120(h):
    v_s = dec_slice(h.let("s"), lambda r: dec_int(r, "i64"), lambda: 0, False)
    v_lo = dec_int(h.let("lo"), "i64")
    v_hi = dec_int(h.let("hi"), "i64")
    v_max = dec_int(h.let("max"), "i64")
    r0 = rt.reslice(v_s, v_lo, v_hi, v_max)
    return [enc_slice(r0, lambda e: enc_int(e))]


def case_121(h):
    v_s = dec_slice(h.let("s"), lambda r: dec_int(r, "i64"), lambda: 0, False)
    v_t = view(v_s, h.let("t"))
    v_i = dec_int(h.let("i"), "i64")
    v_v = dec_int(h.let("v"), "i64")
    rt.sset(v_t, v_i, v_v)
    h.after("s", enc_slice(v_s, lambda e: enc_int(e)))
    return []


def case_122(h):
    v_s = dec_slice(h.let("s"), lambda r: dec_int(r, "i64"), lambda: 0, False)
    v_i = dec_int(h.let("i"), "i64")
    v_v = dec_int(h.let("v"), "i64")
    rt.sset(v_s, v_i, v_v)
    return []


def case_123(h):
    v_s = dec_slice(h.let("s"), lambda r: dec_int(r, "i64"), lambda: 0, False)
    r0 = rt.slice_to_array(v_s, 2)
    return [enc_array(r0, lambda e: enc_int(e))]


def case_124(h):
    v_s = dec_slice(h.let("s"), lambda r: dec_int(r, "i64"), lambda: 0, False)
    r0 = rt.slice_to_array(v_s, 2)
    return [enc_array(r0, lambda e: enc_int(e))]


def case_125(h):
    v_a = dec_string(h.let("a"))
    v_b = dec_string(h.let("b"))
    r0 = rt.scompare(v_a, v_b)
    return [enc_int(r0)]


def case_126(h):
    v_a = dec_string(h.let("a"))
    v_b = dec_string(h.let("b"))
    r0 = rt.scompare(v_a, v_b)
    return [enc_int(r0)]


def case_127(h):
    v_a = dec_string(h.let("a"))
    v_b = dec_string(h.let("b"))
    r0 = rt.scompare(v_a, v_b)
    return [enc_int(r0)]


def case_128(h):
    v_a = dec_string(h.let("a"))
    v_b = dec_string(h.let("b"))
    r0 = rt.scompare(v_a, v_b)
    return [enc_int(r0)]


def case_129(h):
    v_a = dec_string(h.let("a"))
    v_b = dec_string(h.let("b"))
    r0 = rt.concat(v_a, v_b)
    return [enc_string(r0)]


def case_130(h):
    v_a = dec_string(h.let("a"))
    v_b = dec_string(h.let("b"))
    r0 = rt.concat(v_a, v_b)
    return [enc_string(r0)]


def case_131(h):
    v_s = dec_string(h.let("s"))
    v_i = dec_int(h.let("i"), "i64")
    r0, r1 = rt.decode_rune(v_s, v_i)
    return [enc_int(r0), enc_int(r1)]


def case_132(h):
    v_s = dec_string(h.let("s"))
    v_i = dec_int(h.let("i"), "i64")
    r0, r1 = rt.decode_rune(v_s, v_i)
    return [enc_int(r0), enc_int(r1)]


def case_133(h):
    v_s = dec_string(h.let("s"))
    v_i = dec_int(h.let("i"), "i64")
    r0, r1 = rt.decode_rune(v_s, v_i)
    return [enc_int(r0), enc_int(r1)]


def case_134(h):
    v_s = dec_string(h.let("s"))
    v_i = dec_int(h.let("i"), "i64")
    r0, r1 = rt.decode_rune(v_s, v_i)
    return [enc_int(r0), enc_int(r1)]


def case_135(h):
    v_s = dec_string(h.let("s"))
    v_i = dec_int(h.let("i"), "i64")
    r0, r1 = rt.decode_rune(v_s, v_i)
    return [enc_int(r0), enc_int(r1)]


def case_136(h):
    v_s = dec_string(h.let("s"))
    v_i = dec_int(h.let("i"), "i64")
    r0, r1 = rt.decode_rune(v_s, v_i)
    return [enc_int(r0), enc_int(r1)]


def case_137(h):
    v_s = dec_string(h.let("s"))
    v_i = dec_int(h.let("i"), "i64")
    r0, r1 = rt.decode_rune(v_s, v_i)
    return [enc_int(r0), enc_int(r1)]


def case_138(h):
    v_b = dec_slice(h.let("b"), lambda r: dec_int(r, "u8"), lambda: 0, True)
    r0 = rt.from_bytes(v_b)
    return [enc_string(r0)]


def case_139(h):
    v_b = dec_slice(h.let("b"), lambda r: dec_int(r, "u8"), lambda: 0, True)
    r0 = rt.from_bytes(v_b)
    return [enc_string(r0)]


def case_140(h):
    v_r = dec_int(h.let("r"), "i32")
    r0 = rt.from_rune(v_r)
    return [enc_string(r0)]


def case_141(h):
    v_r = dec_int(h.let("r"), "i64")
    r0 = rt.from_rune(v_r)
    return [enc_string(r0)]


def case_142(h):
    v_r = dec_int(h.let("r"), "i8")
    r0 = rt.from_rune(v_r)
    return [enc_string(r0)]


def case_143(h):
    v_r = dec_int(h.let("r"), "i64")
    r0 = rt.from_rune(v_r)
    return [enc_string(r0)]


def case_144(h):
    v_r = dec_slice(h.let("r"), lambda r: dec_int(r, "i32"), lambda: 0, False)
    r0 = rt.from_runes(v_r)
    return [enc_string(r0)]


def case_145(h):
    v_r = dec_slice(h.let("r"), lambda r: dec_int(r, "i32"), lambda: 0, False)
    r0 = rt.from_runes(v_r)
    return [enc_string(r0)]


def case_146(h):
    v_s = dec_string(h.let("s"))
    v_i = dec_int(h.let("i"), "i64")
    r0 = rt.sindex(v_s, v_i)
    return [enc_int(r0)]


def case_147(h):
    v_s = dec_string(h.let("s"))
    v_i = dec_int(h.let("i"), "i64")
    r0 = rt.sindex(v_s, v_i)
    return [enc_int(r0)]


def case_148(h):
    v_s = dec_string(h.let("s"))
    v_i = dec_int(h.let("i"), "i64")
    r0 = rt.sindex(v_s, v_i)
    return [enc_int(r0)]


def case_149(h):
    v_s = dec_string(h.let("s"))
    v_i = dec_int(h.let("i"), "u64")
    r0 = rt.sindex(v_s, v_i)
    return [enc_int(r0)]


def case_150(h):
    v_s = dec_string(h.let("s"))
    v_lo = dec_int(h.let("lo"), "i64")
    v_hi = dec_int(h.let("hi"), "i64")
    r0 = rt.sslice(v_s, v_lo, v_hi)
    return [enc_string(r0)]


def case_151(h):
    v_s = dec_string(h.let("s"))
    v_lo = dec_int(h.let("lo"), "i64")
    v_hi = dec_int(h.let("hi"), "i64")
    r0 = rt.sslice(v_s, v_lo, v_hi)
    return [enc_string(r0)]


def case_152(h):
    v_s = dec_string(h.let("s"))
    v_lo = dec_int(h.let("lo"), "i64")
    v_hi = dec_int(h.let("hi"), "i64")
    r0 = rt.sslice(v_s, v_lo, v_hi)
    return [enc_string(r0)]


def case_153(h):
    v_s = dec_string(h.let("s"))
    v_lo = dec_int(h.let("lo"), "i64")
    v_hi = dec_int(h.let("hi"), "i64")
    r0 = rt.sslice(v_s, v_lo, v_hi)
    return [enc_string(r0)]


def case_154(h):
    v_s = dec_string(h.let("s"))
    r0 = rt.to_bytes(v_s)
    return [enc_slice(r0, lambda e: enc_int(e))]


def case_155(h):
    v_s = dec_string(h.let("s"))
    r0 = rt.to_bytes(v_s)
    return [enc_slice(r0, lambda e: enc_int(e))]


def case_156(h):
    v_s = dec_string(h.let("s"))
    r0 = rt.to_runes(v_s)
    return [enc_slice(r0, lambda e: enc_int(e))]


def case_157(h):
    rv = rt.run_isolated(lambda t: rt.call(t, new_spawn_check()))
    r0 = rv[0]
    return [enc_bool(r0)]


def case_158(h):
    v_data = dec_slice(h.let("data"), lambda r: dec_int(r, "u8"), lambda: 0, True)
    r0 = rt.lib_checksum_crc32_ieee(v_data)
    return [enc_int(r0)]


def case_159(h):
    v_data = dec_slice(h.let("data"), lambda r: dec_int(r, "u8"), lambda: 0, True)
    r0 = rt.lib_checksum_crc32_ieee(v_data)
    return [enc_int(r0)]


def case_160(h):
    v_data = dec_slice(h.let("data"), lambda r: dec_int(r, "u8"), lambda: 0, True)
    r0 = rt.lib_checksum_crc32_ieee(v_data)
    return [enc_int(r0)]


def case_161(h):
    v_data = dec_slice(h.let("data"), lambda r: dec_int(r, "u8"), lambda: 0, True)
    r0 = rt.lib_checksum_crc32_ieee(v_data)
    return [enc_int(r0)]


def case_162(h):
    v_data = dec_slice(h.let("data"), lambda r: dec_int(r, "u8"), lambda: 0, True)
    r0 = rt.lib_checksum_crc32_ieee(v_data)
    return [enc_int(r0)]


def case_163(h):
    v_key = dec_slice(h.let("key"), lambda r: dec_int(r, "u8"), lambda: 0, True)
    v_nonce = dec_slice(h.let("nonce"), lambda r: dec_int(r, "u8"), lambda: 0, True)
    v_data = dec_slice(h.let("data"), lambda r: dec_int(r, "u8"), lambda: 0, True)
    v_aad = dec_slice(h.let("aad"), lambda r: dec_int(r, "u8"), lambda: 0, True)
    rv = harness_host(lambda t: rt.lib_crypto_aes256gcm_decrypt(t, v_key, v_nonce, v_data, v_aad))
    r0 = rv[0]
    r1 = rv[1]
    return [enc_slice(r0, lambda e: enc_int(e)), enc_error(r1)]


def case_164(h):
    v_key = dec_slice(h.let("key"), lambda r: dec_int(r, "u8"), lambda: 0, True)
    v_nonce = dec_slice(h.let("nonce"), lambda r: dec_int(r, "u8"), lambda: 0, True)
    v_data = dec_slice(h.let("data"), lambda r: dec_int(r, "u8"), lambda: 0, True)
    v_aad = dec_slice(h.let("aad"), lambda r: dec_int(r, "u8"), lambda: 0, True)
    rv = harness_host(lambda t: rt.lib_crypto_aes256gcm_encrypt(t, v_key, v_nonce, v_data, v_aad))
    r0 = rv[0]
    r1 = rv[1]
    return [enc_slice(r0, lambda e: enc_int(e)), enc_error(r1)]


def case_165(h):
    v_key = None
    rv = harness_host(lambda t: rt.lib_crypto_close(t,v_key))
    return []


def case_166(h):
    v_private_key = None
    v_public_key = None
    rv = harness_host(lambda t: rt.lib_crypto_ecdh(t, v_private_key, v_public_key))
    r0 = rv[0]
    r1 = rv[1]
    return [enc_slice(r0, lambda e: enc_int(e)), enc_error(r1)]


def case_167(h):
    v_key = None
    v_data = dec_slice(h.let("data"), lambda r: dec_int(r, "u8"), lambda: 0, True)
    rv = harness_host(lambda t: rt.lib_crypto_es256_sign(t, v_key, v_data))
    r0 = rv[0]
    r1 = rv[1]
    return [enc_slice(r0, lambda e: enc_int(e)), enc_error(r1)]


def case_168(h):
    v_key = None
    v_data = dec_slice(h.let("data"), lambda r: dec_int(r, "u8"), lambda: 0, True)
    v_signature = dec_slice(h.let("signature"), lambda r: dec_int(r, "u8"), lambda: 0, True)
    rv = harness_host(lambda t: rt.lib_crypto_es256_verify(t, v_key, v_data, v_signature))
    r0 = rv[0]
    r1 = rv[1]
    return [enc_bool(r0), enc_error(r1)]


def case_169(h):
    v_secret = dec_slice(h.let("secret"), lambda r: dec_int(r, "u8"), lambda: 0, True)
    v_salt = dec_slice(h.let("salt"), lambda r: dec_int(r, "u8"), lambda: 0, True)
    v_info = dec_slice(h.let("info"), lambda r: dec_int(r, "u8"), lambda: 0, True)
    v_n = dec_int(h.let("n"), "i64")
    rv = harness_host(lambda t: rt.lib_crypto_hkdf_sha256(t, v_secret, v_salt, v_info, v_n))
    r0 = rv[0]
    r1 = rv[1]
    return [enc_slice(r0, lambda e: enc_int(e)), enc_error(r1)]


def case_170(h):
    v_key = dec_slice(h.let("key"), lambda r: dec_int(r, "u8"), lambda: 0, True)
    v_data = dec_slice(h.let("data"), lambda r: dec_int(r, "u8"), lambda: 0, True)
    rv = harness_host(lambda t: rt.lib_crypto_hmac_sha256(t, v_key, v_data))
    r0 = rv[0]
    r1 = rv[1]
    return [enc_slice(r0, lambda e: enc_int(e)), enc_error(r1)]


def case_171(h):
    v_key = dec_slice(h.let("key"), lambda r: dec_int(r, "u8"), lambda: 0, True)
    v_data = dec_slice(h.let("data"), lambda r: dec_int(r, "u8"), lambda: 0, True)
    v_mac = dec_slice(h.let("mac"), lambda r: dec_int(r, "u8"), lambda: 0, True)
    rv = harness_host(lambda t: rt.lib_crypto_hmac_sha256_verify(t, v_key, v_data, v_mac))
    r0 = rv[0]
    r1 = rv[1]
    return [enc_bool(r0), enc_error(r1)]


def case_172(h):
    v_data = dec_string(h.let("data"))
    rv = harness_host(lambda t: rt.lib_crypto_import_pem(t, v_data))
    r0 = rv[0]
    r1 = rv[1]
    return [enc_key(r0), enc_error(r1)]


def case_173(h):
    v_key = None
    rv = harness_host(lambda t: rt.lib_crypto_private_pem(t, v_key))
    r0 = rv[0]
    r1 = rv[1]
    return [enc_string(r0), enc_error(r1)]


def case_174(h):
    v_key = None
    rv = harness_host(lambda t: rt.lib_crypto_public_jwk(t, v_key))
    r0 = rv[0]
    r1 = rv[1]
    return [enc_slice(r0, lambda e: enc_string(e)), enc_error(r1)]


def case_175(h):
    v_key = None
    rv = harness_host(lambda t: rt.lib_crypto_public_pem(t, v_key))
    r0 = rv[0]
    r1 = rv[1]
    return [enc_string(r0), enc_error(r1)]


def case_176(h):
    v_n = dec_int(h.let("n"), "i64")
    rv = harness_host(lambda t: rt.lib_crypto_random(t, v_n))
    r0 = rv[0]
    r1 = rv[1]
    return [enc_slice(r0, lambda e: enc_int(e)), enc_error(r1)]


def case_177(h):
    v_key = None
    v_data = dec_slice(h.let("data"), lambda r: dec_int(r, "u8"), lambda: 0, True)
    rv = harness_host(lambda t: rt.lib_crypto_rs256_sign(t, v_key, v_data))
    r0 = rv[0]
    r1 = rv[1]
    return [enc_slice(r0, lambda e: enc_int(e)), enc_error(r1)]


def case_178(h):
    v_key = None
    v_data = dec_slice(h.let("data"), lambda r: dec_int(r, "u8"), lambda: 0, True)
    v_signature = dec_slice(h.let("signature"), lambda r: dec_int(r, "u8"), lambda: 0, True)
    rv = harness_host(lambda t: rt.lib_crypto_rs256_verify(t, v_key, v_data, v_signature))
    r0 = rv[0]
    r1 = rv[1]
    return [enc_bool(r0), enc_error(r1)]


def case_179(h):
    v_key = None
    v_data = dec_slice(h.let("data"), lambda r: dec_int(r, "u8"), lambda: 0, True)
    rv = harness_host(lambda t: rt.lib_crypto_rsaoaep_decrypt(t, v_key, v_data))
    r0 = rv[0]
    r1 = rv[1]
    return [enc_slice(r0, lambda e: enc_int(e)), enc_error(r1)]


def case_180(h):
    v_key = None
    v_data = dec_slice(h.let("data"), lambda r: dec_int(r, "u8"), lambda: 0, True)
    rv = harness_host(lambda t: rt.lib_crypto_rsaoaep_encrypt(t, v_key, v_data))
    r0 = rv[0]
    r1 = rv[1]
    return [enc_slice(r0, lambda e: enc_int(e)), enc_error(r1)]


def case_181(h):
    v_data = dec_slice(h.let("data"), lambda r: dec_int(r, "u8"), lambda: 0, True)
    rv = harness_host(lambda t: rt.lib_crypto_sha256(t, v_data))
    r0 = rv[0]
    r1 = rv[1]
    return [enc_slice(r0, lambda e: enc_int(e)), enc_error(r1)]


def case_182(h):
    v_data = dec_string(h.let("data"))
    r0, r1 = rt.lib_encoding_base64_decode(v_data)
    return [enc_slice(r0, lambda e: enc_int(e)), enc_error(r1)]


def case_183(h):
    v_data = dec_slice(h.let("data"), lambda r: dec_int(r, "u8"), lambda: 0, True)
    r0, r1 = rt.lib_encoding_base64_encode(v_data)
    return [enc_string(r0), enc_error(r1)]


def case_184(h):
    v_data = dec_string(h.let("data"))
    r0, r1 = rt.lib_encoding_base64_url_decode(v_data)
    return [enc_slice(r0, lambda e: enc_int(e)), enc_error(r1)]


def case_185(h):
    v_data = dec_slice(h.let("data"), lambda r: dec_int(r, "u8"), lambda: 0, True)
    r0, r1 = rt.lib_encoding_base64_url_encode(v_data)
    return [enc_string(r0), enc_error(r1)]


def case_186(h):
    v_ctx = rt.std_context_background()
    v_method = dec_string(h.let("method"))
    v_url = dec_string(h.let("url"))
    v_headers = dec_slice(h.let("headers"), lambda r: dec_string(r), lambda: b"", False)
    v_body = dec_slice(h.let("body"), lambda r: dec_int(r, "u8"), lambda: 0, True)
    v_max_response_bytes = dec_int(h.let("max_response_bytes"), "i64")
    v_timeout_millis = dec_int(h.let("timeout_millis"), "i64")
    rv = harness_host(lambda t: rt.lib_http_do(t,v_ctx,v_method,v_url,v_headers,v_body,v_max_response_bytes,v_timeout_millis))
    r0 = rv[0]
    r1 = rv[1]
    r2 = rv[2]
    r3 = rv[3]
    return [enc_int(r0), enc_slice(r1, lambda e: enc_string(e)), enc_slice(r2, lambda e: enc_int(e)), enc_error(r3)]


def case_187(h):
    v_fns = dec_slice(h.let("fns"), lambda r: None, lambda: None, False)
    rv = rt.run_isolated(lambda t: rt.lib_task_all(t, v_fns))
    return []


def case_188(h):
    r0 = rt.std_context_background()
    return [enc_zero(r0)]


def case_189(h):
    r0 = rt.std_context_canceled()
    return [enc_error(r0)]


def case_190(h):
    r0 = rt.std_context_deadline_exceeded()
    return [enc_error(r0)]


def case_191(h):
    v_ctx = rt.std_context_background()
    r0 = rt.std_context_context_done(v_ctx)
    return [enc_chan(r0, lambda e: enc_zero(e))]


def case_192(h):
    v_ctx = rt.std_context_background()
    r0 = rt.std_context_context_err(v_ctx)
    return [enc_error(r0)]


def case_193(h):
    v_parent = rt.std_context_background()
    r0, r1 = rt.std_context_with_cancel(v_parent)
    return [enc_zero(r0), enc_zero(r1)]


def case_194(h):
    v_parent = rt.std_context_background()
    v_d = dec_int(h.let("d"), "i64")
    r0, r1 = rt.std_context_with_timeout(v_parent, v_d)
    return [enc_zero(r0), enc_zero(r1)]


def case_195(h):
    v_err = dec_error(h.let("err"))
    v_target = dec_error(h.let("target"))
    r0 = rt.std_errors_is(v_err, v_target)
    return [enc_bool(r0)]


def case_196(h):
    v_err = dec_error(h.let("err"))
    v_target = dec_error(h.let("target"))
    r0 = rt.std_errors_is(v_err, v_target)
    return [enc_bool(r0)]


def case_197(h):
    v_err = dec_error(h.let("err"))
    v_target = v_err
    r0 = rt.std_errors_is(v_err, v_target)
    return [enc_bool(r0)]


def case_198(h):
    v_text = dec_string(h.let("text"))
    r0 = rt.std_errors_new(v_text)
    return [enc_error(r0)]


def case_199(h):
    v_err = dec_error(h.let("err"))
    r0 = rt.std_errors_unwrap(v_err)
    return [enc_error(r0)]


def case_200(h):
    rv = rt.run_isolated(lambda t: rt.std_runtime_gosched(t))
    return []


def case_201(h):
    v_m = rt.Mutex()
    rv = rt.run_isolated(lambda t: rt.std_sync_mutex_lock(t, v_m))
    return []


def case_202(h):
    v_m = rt.Mutex()
    rv = rt.run_isolated(lambda t: (rt.std_sync_mutex_lock(t, v_m), rt.std_sync_mutex_unlock(v_m)))
    return []


def case_203(h):
    v_wg = rt.WaitGroup()
    v_delta = dec_int(h.let("delta"), "i64")
    rt.std_sync_waitgroup_add(v_wg, v_delta)
    return []


def case_204(h):
    v_wg = rt.WaitGroup()
    v_delta = dec_int(h.let("delta"), "i64")
    rt.std_sync_waitgroup_add(v_wg, v_delta)
    return []


def case_205(h):
    v_wg = rt.WaitGroup()
    rt.std_sync_waitgroup_done(v_wg)
    return []


def case_206(h):
    v_wg = rt.WaitGroup()
    rv = rt.run_isolated(lambda t: rt.std_sync_waitgroup_wait(t, v_wg))
    return []


def case_207(h):
    v_d = dec_int(h.let("d"), "i64")
    rv = rt.run_isolated(lambda t: rt.std_time_sleep(t, v_d))
    return []


CASES = {
    "core.chan.cap/three": case_0,
    "core.chan.close/nil": case_1,
    "core.chan.close/open": case_2,
    "core.chan.close/twice": case_3,
    "core.chan.len/nil": case_4,
    "core.chan.len/two": case_5,
    "core.chan.make/buffered": case_6,
    "core.chan.make/negative": case_7,
    "core.chan.recv/buffered": case_8,
    "core.chan.recv/closed": case_9,
    "core.chan.recv/drains_before_close": case_10,
    "core.chan.recv/empty_blocks": case_11,
    "core.chan.recv/nil_blocks": case_12,
    "core.chan.send/buffered": case_13,
    "core.chan.send/closed": case_14,
    "core.chan.send/full_blocks": case_15,
    "core.chan.send/nil_blocks": case_16,
    "core.chan.send/unbuffered_blocks": case_17,
    "core.integer.add/int32_plain": case_18,
    "core.integer.add/int64_min": case_19,
    "core.integer.add/int8_wrap": case_20,
    "core.integer.add/int_big": case_21,
    "core.integer.add/uint32_wrap": case_22,
    "core.integer.add/uint64_wrap": case_23,
    "core.integer.and/neg": case_24,
    "core.integer.and/u32": case_25,
    "core.integer.andnot/i64": case_26,
    "core.integer.andnot/u16": case_27,
    "core.integer.compare/equal": case_28,
    "core.integer.compare/signed": case_29,
    "core.integer.compare/u32_high": case_30,
    "core.integer.compare/unsigned_high": case_31,
    "core.integer.convert/narrow_unsigned": case_32,
    "core.integer.convert/same": case_33,
    "core.integer.convert/sign_extend": case_34,
    "core.integer.convert/truncate": case_35,
    "core.integer.convert/u32_to_i32": case_36,
    "core.integer.convert/unsigned_wrap": case_37,
    "core.integer.div/by_zero": case_38,
    "core.integer.div/int64_min_neg1": case_39,
    "core.integer.div/int8_min_neg1": case_40,
    "core.integer.div/trunc_neg": case_41,
    "core.integer.div/trunc_pos": case_42,
    "core.integer.div/uint64_big": case_43,
    "core.integer.mul/int32_neg": case_44,
    "core.integer.mul/int32_wrap": case_45,
    "core.integer.mul/int64_wrap": case_46,
    "core.integer.mul/int8_wrap": case_47,
    "core.integer.mul/uint32_exact": case_48,
    "core.integer.mul/uint64_big": case_49,
    "core.integer.neg/min": case_50,
    "core.integer.neg/plain": case_51,
    "core.integer.neg/u64": case_52,
    "core.integer.neg/unsigned": case_53,
    "core.integer.not/signed": case_54,
    "core.integer.not/u32": case_55,
    "core.integer.not/u8": case_56,
    "core.integer.or/i8": case_57,
    "core.integer.or/u32": case_58,
    "core.integer.rem/by_zero": case_59,
    "core.integer.rem/min_neg1": case_60,
    "core.integer.rem/neg_dividend": case_61,
    "core.integer.rem/neg_divisor": case_62,
    "core.integer.rem/uint": case_63,
    "core.integer.shl/basic": case_64,
    "core.integer.shl/huge": case_65,
    "core.integer.shl/int64_63": case_66,
    "core.integer.shl/negative": case_67,
    "core.integer.shl/overflow_int8": case_68,
    "core.integer.shl/wide": case_69,
    "core.integer.shr/arith": case_70,
    "core.integer.shr/arith_wide": case_71,
    "core.integer.shr/logical": case_72,
    "core.integer.shr/logical_wide": case_73,
    "core.integer.shr/negative": case_74,
    "core.integer.shr/pos_wide": case_75,
    "core.integer.sub/int16_wrap": case_76,
    "core.integer.sub/int_plain": case_77,
    "core.integer.sub/uint8_wrap": case_78,
    "core.integer.sub/uint_wrap": case_79,
    "core.integer.xor/i32": case_80,
    "core.integer.xor/u64": case_81,
    "core.map.clear/all": case_82,
    "core.map.delete/nil_map": case_83,
    "core.map.delete/reinsert_moves": case_84,
    "core.map.iterate/insertion_order": case_85,
    "core.map.len/nil": case_86,
    "core.map.len/two": case_87,
    "core.map.lookup/nil_map": case_88,
    "core.map.lookup/present": case_89,
    "core.map.make/empty": case_90,
    "core.map.store/nil_map": case_91,
    "core.map.store/update_keeps_order": case_92,
    "core.print/bool": case_93,
    "core.print/bytes": case_94,
    "core.print/int": case_95,
    "core.print/u64": case_96,
    "core.select/closed_ready": case_97,
    "core.select/default_when_idle": case_98,
    "core.select/nothing_blocks": case_99,
    "core.select/only_ready": case_100,
    "core.slice.append/from_nil": case_101,
    "core.slice.append/grow_doubles": case_102,
    "core.slice.append/grow_required": case_103,
    "core.slice.append/in_place": case_104,
    "core.slice.append/nil_empty": case_105,
    "core.slice.append/overlap": case_106,
    "core.slice.clear/shared": case_107,
    "core.slice.copy/overlap_forward": case_108,
    "core.slice.copy/short_dst": case_109,
    "core.slice.index/basic": case_110,
    "core.slice.index/beyond_len": case_111,
    "core.slice.index/nil": case_112,
    "core.slice.make/basic": case_113,
    "core.slice.make/cap_lt_len": case_114,
    "core.slice.make/neg_len": case_115,
    "core.slice.slice/hi_gt_max": case_116,
    "core.slice.slice/lo_gt_hi": case_117,
    "core.slice.slice/max_oob": case_118,
    "core.slice.slice/nil_empty": case_119,
    "core.slice.slice/share": case_120,
    "core.slice.store/alias_visible": case_121,
    "core.slice.store/oob": case_122,
    "core.slice.to_array/prefix": case_123,
    "core.slice.to_array/short": case_124,
    "core.string.compare/equal": case_125,
    "core.string.compare/high_byte": case_126,
    "core.string.compare/less": case_127,
    "core.string.compare/prefix": case_128,
    "core.string.concat/basic": case_129,
    "core.string.concat/raw_bytes": case_130,
    "core.string.decode_rune/ascii": case_131,
    "core.string.decode_rune/four": case_132,
    "core.string.decode_rune/invalid": case_133,
    "core.string.decode_rune/overlong": case_134,
    "core.string.decode_rune/surrogate": case_135,
    "core.string.decode_rune/truncated": case_136,
    "core.string.decode_rune/two": case_137,
    "core.string.from_bytes/basic": case_138,
    "core.string.from_bytes/nil": case_139,
    "core.string.from_rune/ascii": case_140,
    "core.string.from_rune/huge": case_141,
    "core.string.from_rune/negative": case_142,
    "core.string.from_rune/surrogate": case_143,
    "core.string.from_runes/basic": case_144,
    "core.string.from_runes/invalid": case_145,
    "core.string.index/first": case_146,
    "core.string.index/negative": case_147,
    "core.string.index/oob": case_148,
    "core.string.index/unsigned_huge": case_149,
    "core.string.slice/hi_oob": case_150,
    "core.string.slice/inverted": case_151,
    "core.string.slice/mid": case_152,
    "core.string.slice/split_rune": case_153,
    "core.string.to_bytes/basic": case_154,
    "core.string.to_bytes/empty": case_155,
    "core.string.to_runes/mixed": case_156,
    "core.task.spawn/parent_continues": case_157,
    "lib.checksum.crc32_ieee/all_bytes": case_158,
    "lib.checksum.crc32_ieee/binary": case_159,
    "lib.checksum.crc32_ieee/check": case_160,
    "lib.checksum.crc32_ieee/empty": case_161,
    "lib.checksum.crc32_ieee/nil": case_162,
    "lib.crypto.aes256_gcm_decrypt/boundary_example": case_163,
    "lib.crypto.aes256_gcm_encrypt/boundary_example": case_164,
    "lib.crypto.close/boundary_example": case_165,
    "lib.crypto.ecdh/boundary_example": case_166,
    "lib.crypto.es256_sign/boundary_example": case_167,
    "lib.crypto.es256_verify/boundary_example": case_168,
    "lib.crypto.hkdf_sha256/boundary_example": case_169,
    "lib.crypto.hmac_sha256/boundary_example": case_170,
    "lib.crypto.hmac_sha256_verify/boundary_example": case_171,
    "lib.crypto.import_pem/boundary_example": case_172,
    "lib.crypto.private_pem/boundary_example": case_173,
    "lib.crypto.public_jwk/boundary_example": case_174,
    "lib.crypto.public_pem/boundary_example": case_175,
    "lib.crypto.random/boundary_example": case_176,
    "lib.crypto.rs256_sign/boundary_example": case_177,
    "lib.crypto.rs256_verify/boundary_example": case_178,
    "lib.crypto.rsa_oaep_decrypt/boundary_example": case_179,
    "lib.crypto.rsa_oaep_encrypt/boundary_example": case_180,
    "lib.crypto.sha256/boundary_example": case_181,
    "lib.encoding.base64_decode/boundary_example": case_182,
    "lib.encoding.base64_encode/boundary_example": case_183,
    "lib.encoding.base64_url_decode/boundary_example": case_184,
    "lib.encoding.base64_url_encode/boundary_example": case_185,
    "lib.http.do/boundary_example": case_186,
    "lib.task.all/empty": case_187,
    "std.context.background/root": case_188,
    "std.context.canceled/message": case_189,
    "std.context.deadline_exceeded/message": case_190,
    "std.context.done/background": case_191,
    "std.context.err/background": case_192,
    "std.context.with_cancel/child": case_193,
    "std.context.with_timeout/child": case_194,
    "std.errors.is/distinct": case_195,
    "std.errors.is/nils": case_196,
    "std.errors.is/same": case_197,
    "std.errors.new/message": case_198,
    "std.errors.unwrap/plain": case_199,
    "std.runtime.gosched/alone": case_200,
    "std.sync.mutex.lock/unlocked": case_201,
    "std.sync.mutex.unlock/lock_then_unlock": case_202,
    "std.sync.waitgroup.add/negative": case_203,
    "std.sync.waitgroup.add/positive": case_204,
    "std.sync.waitgroup.done/underflow": case_205,
    "std.sync.waitgroup.wait/zero_returns": case_206,
    "std.time.sleep/zero": case_207,
}
