// Code generated by goalchemy spec generate. DO NOT EDIT.
import * as rt from "./runtime_index.ts";
import { decInt, decBool, decString, decSlice, decMap, decError, decChan, view, encInt, encBool, encString, encSlice, encArray, encMap, encError, encChan, encZero, harnessSpawn, harnessSelect2, harnessLockUnlock, type H } from "./codec.ts";

export const cases: Record<string, (h: H) => Generator<unknown, unknown[], unknown>> = {
  "core.chan.cap/three": function* (h: H) {
    const v_ch = decChan(h.let("ch"), (r: any) => (decInt(r, "i64") as bigint));
    const r0 = rt.chanCap(v_ch);
    return [encInt(r0)];
  },
  "core.chan.close/nil": function* (h: H) {
    const v_ch = decChan(h.let("ch"), (r: any) => (decInt(r, "i64") as bigint));
    rt.chanClose(v_ch);
    return [];
  },
  "core.chan.close/open": function* (h: H) {
    const v_ch = decChan(h.let("ch"), (r: any) => (decInt(r, "i64") as bigint));
    rt.chanClose(v_ch);
    h.after("ch", encChan(v_ch, (e: any) => encInt(e)));
    return [];
  },
  "core.chan.close/twice": function* (h: H) {
    const v_ch = decChan(h.let("ch"), (r: any) => (decInt(r, "i64") as bigint));
    rt.chanClose(v_ch);
    return [];
  },
  "core.chan.len/nil": function* (h: H) {
    const v_ch = decChan(h.let("ch"), (r: any) => (decInt(r, "i64") as bigint));
    const r0 = rt.chanLen(v_ch);
    return [encInt(r0)];
  },
  "core.chan.len/two": function* (h: H) {
    const v_ch = decChan(h.let("ch"), (r: any) => (decInt(r, "i64") as bigint));
    const r0 = rt.chanLen(v_ch);
    return [encInt(r0)];
  },
  "core.chan.make/buffered": function* (h: H) {
    const v_size = (decInt(h.let("size"), "i64") as bigint);
    const r0 = rt.makeChan(v_size);
    return [encChan(r0, (e: any) => encInt(e))];
  },
  "core.chan.make/negative": function* (h: H) {
    const v_size = (decInt(h.let("size"), "i64") as bigint);
    const r0 = rt.makeChan(v_size);
    return [encChan(r0, (e: any) => encInt(e))];
  },
  "core.chan.recv/buffered": function* (h: H) {
    const v_ch = decChan(h.let("ch"), (r: any) => (decInt(r, "i64") as bigint));
    const [r0, r1] = yield* rt.chanRecv(v_ch, () => 0n);
    h.after("ch", encChan(v_ch, (e: any) => encInt(e)));
    return [encInt(r0), encBool(r1)];
  },
  "core.chan.recv/closed": function* (h: H) {
    const v_ch = decChan(h.let("ch"), (r: any) => decString(r));
    const [r0, r1] = yield* rt.chanRecv(v_ch, () => "");
    return [encString(r0), encBool(r1)];
  },
  "core.chan.recv/drains_before_close": function* (h: H) {
    const v_ch = decChan(h.let("ch"), (r: any) => (decInt(r, "i64") as bigint));
    const [r0, r1] = yield* rt.chanRecv(v_ch, () => 0n);
    return [encInt(r0), encBool(r1)];
  },
  "core.chan.recv/empty_blocks": function* (h: H) {
    const v_ch = decChan(h.let("ch"), (r: any) => (decInt(r, "i64") as bigint));
    const [r0, r1] = yield* rt.chanRecv(v_ch, () => 0n);
    return [encInt(r0), encBool(r1)];
  },
  "core.chan.recv/nil_blocks": function* (h: H) {
    const v_ch = decChan(h.let("ch"), (r: any) => (decInt(r, "i64") as bigint));
    const [r0, r1] = yield* rt.chanRecv(v_ch, () => 0n);
    return [encInt(r0), encBool(r1)];
  },
  "core.chan.send/buffered": function* (h: H) {
    const v_ch = decChan(h.let("ch"), (r: any) => (decInt(r, "i64") as bigint));
    const v_v = (decInt(h.let("v"), "i64") as bigint);
    yield* rt.chanSend(v_ch, v_v);
    h.after("ch", encChan(v_ch, (e: any) => encInt(e)));
    return [];
  },
  "core.chan.send/closed": function* (h: H) {
    const v_ch = decChan(h.let("ch"), (r: any) => (decInt(r, "i64") as bigint));
    const v_v = (decInt(h.let("v"), "i64") as bigint);
    yield* rt.chanSend(v_ch, v_v);
    return [];
  },
  "core.chan.send/full_blocks": function* (h: H) {
    const v_ch = decChan(h.let("ch"), (r: any) => (decInt(r, "i64") as bigint));
    const v_v = (decInt(h.let("v"), "i64") as bigint);
    yield* rt.chanSend(v_ch, v_v);
    return [];
  },
  "core.chan.send/nil_blocks": function* (h: H) {
    const v_ch = decChan(h.let("ch"), (r: any) => (decInt(r, "i64") as bigint));
    const v_v = (decInt(h.let("v"), "i64") as bigint);
    yield* rt.chanSend(v_ch, v_v);
    return [];
  },
  "core.chan.send/unbuffered_blocks": function* (h: H) {
    const v_ch = decChan(h.let("ch"), (r: any) => decString(r));
    const v_v = decString(h.let("v"));
    yield* rt.chanSend(v_ch, v_v);
    return [];
  },
  "core.integer.add/int32_plain": function* (h: H) {
    const v_a = (decInt(h.let("a"), "i32") as number);
    const v_b = (decInt(h.let("b"), "i32") as number);
    const r0 = rt.add_i32(v_a, v_b);
    return [encInt(r0)];
  },
  "core.integer.add/int64_min": function* (h: H) {
    const v_a = (decInt(h.let("a"), "i64") as bigint);
    const v_b = (decInt(h.let("b"), "i64") as bigint);
    const r0 = rt.add_i64(v_a, v_b);
    return [encInt(r0)];
  },
  "core.integer.add/int8_wrap": function* (h: H) {
    const v_a = (decInt(h.let("a"), "i8") as number);
    const v_b = (decInt(h.let("b"), "i8") as number);
    const r0 = rt.add_i8(v_a, v_b);
    return [encInt(r0)];
  },
  "core.integer.add/int_big": function* (h: H) {
    const v_a = (decInt(h.let("a"), "i64") as bigint);
    const v_b = (decInt(h.let("b"), "i64") as bigint);
    const r0 = rt.add_i64(v_a, v_b);
    return [encInt(r0)];
  },
  "core.integer.add/uint32_wrap": function* (h: H) {
    const v_a = (decInt(h.let("a"), "u32") as number);
    const v_b = (decInt(h.let("b"), "u32") as number);
    const r0 = rt.add_u32(v_a, v_b);
    return [encInt(r0)];
  },
  "core.integer.add/uint64_wrap": function* (h: H) {
    const v_a = (decInt(h.let("a"), "u64") as bigint);
    const v_b = (decInt(h.let("b"), "u64") as bigint);
    const r0 = rt.add_u64(v_a, v_b);
    return [encInt(r0)];
  },
  "core.integer.and/neg": function* (h: H) {
    const v_a = (decInt(h.let("a"), "i64") as bigint);
    const v_b = (decInt(h.let("b"), "i64") as bigint);
    const r0 = rt.and_i64(v_a, v_b);
    return [encInt(r0)];
  },
  "core.integer.and/u32": function* (h: H) {
    const v_a = (decInt(h.let("a"), "u32") as number);
    const v_b = (decInt(h.let("b"), "u32") as number);
    const r0 = rt.and_u32(v_a, v_b);
    return [encInt(r0)];
  },
  "core.integer.andnot/i64": function* (h: H) {
    const v_a = (decInt(h.let("a"), "i64") as bigint);
    const v_b = (decInt(h.let("b"), "i64") as bigint);
    const r0 = rt.andnot_i64(v_a, v_b);
    return [encInt(r0)];
  },
  "core.integer.andnot/u16": function* (h: H) {
    const v_a = (decInt(h.let("a"), "u16") as number);
    const v_b = (decInt(h.let("b"), "u16") as number);
    const r0 = rt.andnot_u16(v_a, v_b);
    return [encInt(r0)];
  },
  "core.integer.compare/equal": function* (h: H) {
    const v_a = (decInt(h.let("a"), "u32") as number);
    const v_b = (decInt(h.let("b"), "u32") as number);
    const r0 = rt.compare_int(v_a, v_b);
    return [encInt(r0)];
  },
  "core.integer.compare/signed": function* (h: H) {
    const v_a = (decInt(h.let("a"), "i64") as bigint);
    const v_b = (decInt(h.let("b"), "i64") as bigint);
    const r0 = rt.compare_int(v_a, v_b);
    return [encInt(r0)];
  },
  "core.integer.compare/u32_high": function* (h: H) {
    const v_a = (decInt(h.let("a"), "u32") as number);
    const v_b = (decInt(h.let("b"), "u32") as number);
    const r0 = rt.compare_int(v_a, v_b);
    return [encInt(r0)];
  },
  "core.integer.compare/unsigned_high": function* (h: H) {
    const v_a = (decInt(h.let("a"), "u64") as bigint);
    const v_b = (decInt(h.let("b"), "u64") as bigint);
    const r0 = rt.compare_int(v_a, v_b);
    return [encInt(r0)];
  },
  "core.integer.convert/narrow_unsigned": function* (h: H) {
    const v_a = (decInt(h.let("a"), "i32") as number);
    const r0 = rt.to_u16(v_a);
    return [encInt(r0)];
  },
  "core.integer.convert/same": function* (h: H) {
    const v_a = (decInt(h.let("a"), "i64") as bigint);
    const r0 = rt.to_i64(v_a);
    return [encInt(r0)];
  },
  "core.integer.convert/sign_extend": function* (h: H) {
    const v_a = (decInt(h.let("a"), "i8") as number);
    const r0 = rt.to_u64(v_a);
    return [encInt(r0)];
  },
  "core.integer.convert/truncate": function* (h: H) {
    const v_a = (decInt(h.let("a"), "i64") as bigint);
    const r0 = rt.to_i8(v_a);
    return [encInt(r0)];
  },
  "core.integer.convert/u32_to_i32": function* (h: H) {
    const v_a = (decInt(h.let("a"), "u32") as number);
    const r0 = rt.to_i32(v_a);
    return [encInt(r0)];
  },
  "core.integer.convert/unsigned_wrap": function* (h: H) {
    const v_a = (decInt(h.let("a"), "u64") as bigint);
    const r0 = rt.to_i64(v_a);
    return [encInt(r0)];
  },
  "core.integer.div/by_zero": function* (h: H) {
    const v_a = (decInt(h.let("a"), "i32") as number);
    const v_b = (decInt(h.let("b"), "i32") as number);
    const r0 = rt.div_i32(v_a, v_b);
    return [encInt(r0)];
  },
  "core.integer.div/int64_min_neg1": function* (h: H) {
    const v_a = (decInt(h.let("a"), "i64") as bigint);
    const v_b = (decInt(h.let("b"), "i64") as bigint);
    const r0 = rt.div_i64(v_a, v_b);
    return [encInt(r0)];
  },
  "core.integer.div/int8_min_neg1": function* (h: H) {
    const v_a = (decInt(h.let("a"), "i8") as number);
    const v_b = (decInt(h.let("b"), "i8") as number);
    const r0 = rt.div_i8(v_a, v_b);
    return [encInt(r0)];
  },
  "core.integer.div/trunc_neg": function* (h: H) {
    const v_a = (decInt(h.let("a"), "i64") as bigint);
    const v_b = (decInt(h.let("b"), "i64") as bigint);
    const r0 = rt.div_i64(v_a, v_b);
    return [encInt(r0)];
  },
  "core.integer.div/trunc_pos": function* (h: H) {
    const v_a = (decInt(h.let("a"), "i64") as bigint);
    const v_b = (decInt(h.let("b"), "i64") as bigint);
    const r0 = rt.div_i64(v_a, v_b);
    return [encInt(r0)];
  },
  "core.integer.div/uint64_big": function* (h: H) {
    const v_a = (decInt(h.let("a"), "u64") as bigint);
    const v_b = (decInt(h.let("b"), "u64") as bigint);
    const r0 = rt.div_u64(v_a, v_b);
    return [encInt(r0)];
  },
  "core.integer.mul/int32_neg": function* (h: H) {
    const v_a = (decInt(h.let("a"), "i32") as number);
    const v_b = (decInt(h.let("b"), "i32") as number);
    const r0 = rt.mul_i32(v_a, v_b);
    return [encInt(r0)];
  },
  "core.integer.mul/int32_wrap": function* (h: H) {
    const v_a = (decInt(h.let("a"), "i32") as number);
    const v_b = (decInt(h.let("b"), "i32") as number);
    const r0 = rt.mul_i32(v_a, v_b);
    return [encInt(r0)];
  },
  "core.integer.mul/int64_wrap": function* (h: H) {
    const v_a = (decInt(h.let("a"), "i64") as bigint);
    const v_b = (decInt(h.let("b"), "i64") as bigint);
    const r0 = rt.mul_i64(v_a, v_b);
    return [encInt(r0)];
  },
  "core.integer.mul/int8_wrap": function* (h: H) {
    const v_a = (decInt(h.let("a"), "i8") as number);
    const v_b = (decInt(h.let("b"), "i8") as number);
    const r0 = rt.mul_i8(v_a, v_b);
    return [encInt(r0)];
  },
  "core.integer.mul/uint32_exact": function* (h: H) {
    const v_a = (decInt(h.let("a"), "u32") as number);
    const v_b = (decInt(h.let("b"), "u32") as number);
    const r0 = rt.mul_u32(v_a, v_b);
    return [encInt(r0)];
  },
  "core.integer.mul/uint64_big": function* (h: H) {
    const v_a = (decInt(h.let("a"), "u64") as bigint);
    const v_b = (decInt(h.let("b"), "u64") as bigint);
    const r0 = rt.mul_u64(v_a, v_b);
    return [encInt(r0)];
  },
  "core.integer.neg/min": function* (h: H) {
    const v_a = (decInt(h.let("a"), "i32") as number);
    const r0 = rt.neg_i32(v_a);
    return [encInt(r0)];
  },
  "core.integer.neg/plain": function* (h: H) {
    const v_a = (decInt(h.let("a"), "i64") as bigint);
    const r0 = rt.neg_i64(v_a);
    return [encInt(r0)];
  },
  "core.integer.neg/u64": function* (h: H) {
    const v_a = (decInt(h.let("a"), "u64") as bigint);
    const r0 = rt.neg_u64(v_a);
    return [encInt(r0)];
  },
  "core.integer.neg/unsigned": function* (h: H) {
    const v_a = (decInt(h.let("a"), "u8") as number);
    const r0 = rt.neg_u8(v_a);
    return [encInt(r0)];
  },
  "core.integer.not/signed": function* (h: H) {
    const v_a = (decInt(h.let("a"), "i64") as bigint);
    const r0 = rt.not_i64(v_a);
    return [encInt(r0)];
  },
  "core.integer.not/u32": function* (h: H) {
    const v_a = (decInt(h.let("a"), "u32") as number);
    const r0 = rt.not_u32(v_a);
    return [encInt(r0)];
  },
  "core.integer.not/u8": function* (h: H) {
    const v_a = (decInt(h.let("a"), "u8") as number);
    const r0 = rt.not_u8(v_a);
    return [encInt(r0)];
  },
  "core.integer.or/i8": function* (h: H) {
    const v_a = (decInt(h.let("a"), "i8") as number);
    const v_b = (decInt(h.let("b"), "i8") as number);
    const r0 = rt.or_i8(v_a, v_b);
    return [encInt(r0)];
  },
  "core.integer.or/u32": function* (h: H) {
    const v_a = (decInt(h.let("a"), "u32") as number);
    const v_b = (decInt(h.let("b"), "u32") as number);
    const r0 = rt.or_u32(v_a, v_b);
    return [encInt(r0)];
  },
  "core.integer.rem/by_zero": function* (h: H) {
    const v_a = (decInt(h.let("a"), "u8") as number);
    const v_b = (decInt(h.let("b"), "u8") as number);
    const r0 = rt.rem_u8(v_a, v_b);
    return [encInt(r0)];
  },
  "core.integer.rem/min_neg1": function* (h: H) {
    const v_a = (decInt(h.let("a"), "i64") as bigint);
    const v_b = (decInt(h.let("b"), "i64") as bigint);
    const r0 = rt.rem_i64(v_a, v_b);
    return [encInt(r0)];
  },
  "core.integer.rem/neg_dividend": function* (h: H) {
    const v_a = (decInt(h.let("a"), "i64") as bigint);
    const v_b = (decInt(h.let("b"), "i64") as bigint);
    const r0 = rt.rem_i64(v_a, v_b);
    return [encInt(r0)];
  },
  "core.integer.rem/neg_divisor": function* (h: H) {
    const v_a = (decInt(h.let("a"), "i64") as bigint);
    const v_b = (decInt(h.let("b"), "i64") as bigint);
    const r0 = rt.rem_i64(v_a, v_b);
    return [encInt(r0)];
  },
  "core.integer.rem/uint": function* (h: H) {
    const v_a = (decInt(h.let("a"), "u32") as number);
    const v_b = (decInt(h.let("b"), "u32") as number);
    const r0 = rt.rem_u32(v_a, v_b);
    return [encInt(r0)];
  },
  "core.integer.shl/basic": function* (h: H) {
    const v_a = (decInt(h.let("a"), "i64") as bigint);
    const v_b = (decInt(h.let("b"), "u64") as bigint);
    const r0 = rt.shl_i64(v_a, v_b);
    return [encInt(r0)];
  },
  "core.integer.shl/huge": function* (h: H) {
    const v_a = (decInt(h.let("a"), "u64") as bigint);
    const v_b = (decInt(h.let("b"), "u64") as bigint);
    const r0 = rt.shl_u64(v_a, v_b);
    return [encInt(r0)];
  },
  "core.integer.shl/int64_63": function* (h: H) {
    const v_a = (decInt(h.let("a"), "i64") as bigint);
    const v_b = (decInt(h.let("b"), "i64") as bigint);
    const r0 = rt.shl_i64(v_a, v_b);
    return [encInt(r0)];
  },
  "core.integer.shl/negative": function* (h: H) {
    const v_a = (decInt(h.let("a"), "i64") as bigint);
    const v_b = (decInt(h.let("b"), "i64") as bigint);
    const r0 = rt.shl_i64(v_a, v_b);
    return [encInt(r0)];
  },
  "core.integer.shl/overflow_int8": function* (h: H) {
    const v_a = (decInt(h.let("a"), "i8") as number);
    const v_b = (decInt(h.let("b"), "i64") as bigint);
    const r0 = rt.shl_i8(v_a, v_b);
    return [encInt(r0)];
  },
  "core.integer.shl/wide": function* (h: H) {
    const v_a = (decInt(h.let("a"), "i32") as number);
    const v_b = (decInt(h.let("b"), "u64") as bigint);
    const r0 = rt.shl_i32(v_a, v_b);
    return [encInt(r0)];
  },
  "core.integer.shr/arith": function* (h: H) {
    const v_a = (decInt(h.let("a"), "i64") as bigint);
    const v_b = (decInt(h.let("b"), "u64") as bigint);
    const r0 = rt.shr_i64(v_a, v_b);
    return [encInt(r0)];
  },
  "core.integer.shr/arith_wide": function* (h: H) {
    const v_a = (decInt(h.let("a"), "i8") as number);
    const v_b = (decInt(h.let("b"), "i64") as bigint);
    const r0 = rt.shr_i8(v_a, v_b);
    return [encInt(r0)];
  },
  "core.integer.shr/logical": function* (h: H) {
    const v_a = (decInt(h.let("a"), "u8") as number);
    const v_b = (decInt(h.let("b"), "i64") as bigint);
    const r0 = rt.shr_u8(v_a, v_b);
    return [encInt(r0)];
  },
  "core.integer.shr/logical_wide": function* (h: H) {
    const v_a = (decInt(h.let("a"), "u64") as bigint);
    const v_b = (decInt(h.let("b"), "u64") as bigint);
    const r0 = rt.shr_u64(v_a, v_b);
    return [encInt(r0)];
  },
  "core.integer.shr/negative": function* (h: H) {
    const v_a = (decInt(h.let("a"), "i8") as number);
    const v_b = (decInt(h.let("b"), "i64") as bigint);
    const r0 = rt.shr_i8(v_a, v_b);
    return [encInt(r0)];
  },
  "core.integer.shr/pos_wide": function* (h: H) {
    const v_a = (decInt(h.let("a"), "i32") as number);
    const v_b = (decInt(h.let("b"), "i64") as bigint);
    const r0 = rt.shr_i32(v_a, v_b);
    return [encInt(r0)];
  },
  "core.integer.sub/int16_wrap": function* (h: H) {
    const v_a = (decInt(h.let("a"), "i16") as number);
    const v_b = (decInt(h.let("b"), "i16") as number);
    const r0 = rt.sub_i16(v_a, v_b);
    return [encInt(r0)];
  },
  "core.integer.sub/int_plain": function* (h: H) {
    const v_a = (decInt(h.let("a"), "i64") as bigint);
    const v_b = (decInt(h.let("b"), "i64") as bigint);
    const r0 = rt.sub_i64(v_a, v_b);
    return [encInt(r0)];
  },
  "core.integer.sub/uint8_wrap": function* (h: H) {
    const v_a = (decInt(h.let("a"), "u8") as number);
    const v_b = (decInt(h.let("b"), "u8") as number);
    const r0 = rt.sub_u8(v_a, v_b);
    return [encInt(r0)];
  },
  "core.integer.sub/uint_wrap": function* (h: H) {
    const v_a = (decInt(h.let("a"), "u64") as bigint);
    const v_b = (decInt(h.let("b"), "u64") as bigint);
    const r0 = rt.sub_u64(v_a, v_b);
    return [encInt(r0)];
  },
  "core.integer.xor/i32": function* (h: H) {
    const v_a = (decInt(h.let("a"), "i32") as number);
    const v_b = (decInt(h.let("b"), "i32") as number);
    const r0 = rt.xor_i32(v_a, v_b);
    return [encInt(r0)];
  },
  "core.integer.xor/u64": function* (h: H) {
    const v_a = (decInt(h.let("a"), "u64") as bigint);
    const v_b = (decInt(h.let("b"), "u64") as bigint);
    const r0 = rt.xor_u64(v_a, v_b);
    return [encInt(r0)];
  },
  "core.map.clear/all": function* (h: H) {
    const v_m = decMap(h.let("m"), (r: any) => (decInt(r, "i64") as bigint), (r: any) => (decInt(r, "i64") as bigint));
    rt.mapClear(v_m);
    h.after("m", encMap(v_m, (e: any) => encInt(e), (e: any) => encInt(e)));
    return [];
  },
  "core.map.delete/nil_map": function* (h: H) {
    const v_m = decMap(h.let("m"), (r: any) => (decInt(r, "i64") as bigint), (r: any) => (decInt(r, "i64") as bigint));
    const v_k = (decInt(h.let("k"), "i64") as bigint);
    rt.mapDelete(v_m, v_k, rt.identityKey);
    return [];
  },
  "core.map.delete/reinsert_moves": function* (h: H) {
    const v_m = decMap(h.let("m"), (r: any) => (decInt(r, "i64") as bigint), (r: any) => (decInt(r, "i64") as bigint));
    const v_k = (decInt(h.let("k"), "i64") as bigint);
    rt.mapDelete(v_m, v_k, rt.identityKey);
    h.after("m", encMap(v_m, (e: any) => encInt(e), (e: any) => encInt(e)));
    return [];
  },
  "core.map.iterate/insertion_order": function* (h: H) {
    const v_m = decMap(h.let("m"), (r: any) => (decInt(r, "i64") as bigint), (r: any) => (decInt(r, "i64") as bigint));
    const r0 = rt.mapKeys(v_m);
    return [encSlice(r0, (e: any) => encInt(e))];
  },
  "core.map.len/nil": function* (h: H) {
    const v_m = decMap(h.let("m"), (r: any) => (decInt(r, "i64") as bigint), (r: any) => (decInt(r, "i64") as bigint));
    const r0 = rt.mapLen(v_m);
    return [encInt(r0)];
  },
  "core.map.len/two": function* (h: H) {
    const v_m = decMap(h.let("m"), (r: any) => (decInt(r, "i64") as bigint), (r: any) => (decInt(r, "i64") as bigint));
    const r0 = rt.mapLen(v_m);
    return [encInt(r0)];
  },
  "core.map.lookup/nil_map": function* (h: H) {
    const v_m = decMap(h.let("m"), (r: any) => (decInt(r, "i64") as bigint), (r: any) => decString(r));
    const v_k = (decInt(h.let("k"), "i64") as bigint);
    const [r0, r1] = rt.mapGet(v_m, v_k, rt.identityKey, () => "");
    return [encString(r0), encBool(r1)];
  },
  "core.map.lookup/present": function* (h: H) {
    const v_m = decMap(h.let("m"), (r: any) => decString(r), (r: any) => (decInt(r, "i64") as bigint));
    const v_k = decString(h.let("k"));
    const [r0, r1] = rt.mapGet(v_m, v_k, rt.identityKey, () => 0n);
    return [encInt(r0), encBool(r1)];
  },
  "core.map.make/empty": function* (h: H) {
    const r0 = rt.makeMap(rt.identityKey);
    return [encMap(r0, (e: any) => encString(e), (e: any) => encInt(e))];
  },
  "core.map.store/nil_map": function* (h: H) {
    const v_m = decMap(h.let("m"), (r: any) => (decInt(r, "i64") as bigint), (r: any) => (decInt(r, "i64") as bigint));
    const v_k = (decInt(h.let("k"), "i64") as bigint);
    const v_v = (decInt(h.let("v"), "i64") as bigint);
    rt.mapSet(v_m, v_k, v_v);
    return [];
  },
  "core.map.store/update_keeps_order": function* (h: H) {
    const v_m = decMap(h.let("m"), (r: any) => (decInt(r, "i64") as bigint), (r: any) => (decInt(r, "i64") as bigint));
    const v_k = (decInt(h.let("k"), "i64") as bigint);
    const v_v = (decInt(h.let("v"), "i64") as bigint);
    rt.mapSet(v_m, v_k, v_v);
    h.after("m", encMap(v_m, (e: any) => encInt(e), (e: any) => encInt(e)));
    return [];
  },
  "core.print/bool": function* (h: H) {
    const v_v = decBool(h.let("v"));
    const r0 = rt.printString(v_v);
    return [encString(r0)];
  },
  "core.print/bytes": function* (h: H) {
    const v_v = decString(h.let("v"));
    const r0 = rt.printString(v_v);
    return [encString(r0)];
  },
  "core.print/int": function* (h: H) {
    const v_v = (decInt(h.let("v"), "i64") as bigint);
    const r0 = rt.printString(v_v);
    return [encString(r0)];
  },
  "core.print/u64": function* (h: H) {
    const v_v = (decInt(h.let("v"), "u64") as bigint);
    const r0 = rt.printString(v_v);
    return [encString(r0)];
  },
  "core.select/closed_ready": function* (h: H) {
    const v_a = decChan(h.let("a"), (r: any) => (decInt(r, "i64") as bigint));
    const v_b = decChan(h.let("b"), (r: any) => (decInt(r, "i64") as bigint));
    const v_dflt = decBool(h.let("dflt"));
    const r0 = yield* harnessSelect2(v_a, v_b, v_dflt);
    return [encInt(r0)];
  },
  "core.select/default_when_idle": function* (h: H) {
    const v_a = decChan(h.let("a"), (r: any) => (decInt(r, "i64") as bigint));
    const v_b = decChan(h.let("b"), (r: any) => (decInt(r, "i64") as bigint));
    const v_dflt = decBool(h.let("dflt"));
    const r0 = yield* harnessSelect2(v_a, v_b, v_dflt);
    return [encInt(r0)];
  },
  "core.select/nothing_blocks": function* (h: H) {
    const v_a = decChan(h.let("a"), (r: any) => (decInt(r, "i64") as bigint));
    const v_b = decChan(h.let("b"), (r: any) => (decInt(r, "i64") as bigint));
    const v_dflt = decBool(h.let("dflt"));
    const r0 = yield* harnessSelect2(v_a, v_b, v_dflt);
    return [encInt(r0)];
  },
  "core.select/only_ready": function* (h: H) {
    const v_a = decChan(h.let("a"), (r: any) => (decInt(r, "i64") as bigint));
    const v_b = decChan(h.let("b"), (r: any) => (decInt(r, "i64") as bigint));
    const v_dflt = decBool(h.let("dflt"));
    const r0 = yield* harnessSelect2(v_a, v_b, v_dflt);
    h.after("b", encChan(v_b, (e: any) => encInt(e)));
    return [encInt(r0)];
  },
  "core.slice.append/from_nil": function* (h: H) {
    const v_s = decSlice(h.let("s"), (r: any) => decString(r));
    const v_vs = decSlice(h.let("vs"), (r: any) => decString(r));
    const r0 = rt.appendSlice(v_s, v_vs);
    return [encSlice(r0, (e: any) => encString(e))];
  },
  "core.slice.append/grow_doubles": function* (h: H) {
    const v_s = decSlice(h.let("s"), (r: any) => (decInt(r, "i64") as bigint));
    const v_vs = decSlice(h.let("vs"), (r: any) => (decInt(r, "i64") as bigint));
    const r0 = rt.appendSlice(v_s, v_vs);
    return [encSlice(r0, (e: any) => encInt(e))];
  },
  "core.slice.append/grow_required": function* (h: H) {
    const v_s = decSlice(h.let("s"), (r: any) => (decInt(r, "i64") as bigint));
    const v_vs = decSlice(h.let("vs"), (r: any) => (decInt(r, "i64") as bigint));
    const r0 = rt.appendSlice(v_s, v_vs);
    return [encSlice(r0, (e: any) => encInt(e))];
  },
  "core.slice.append/in_place": function* (h: H) {
    const v_s = decSlice(h.let("s"), (r: any) => (decInt(r, "i64") as bigint));
    const v_t = view(v_s, h.let("t"));
    const v_vs = decSlice(h.let("vs"), (r: any) => (decInt(r, "i64") as bigint));
    const r0 = rt.appendSlice(v_s, v_vs);
    h.after("t", encSlice(v_t, (e: any) => encInt(e)));
    return [encSlice(r0, (e: any) => encInt(e))];
  },
  "core.slice.append/nil_empty": function* (h: H) {
    const v_s = decSlice(h.let("s"), (r: any) => (decInt(r, "i64") as bigint));
    const v_vs = decSlice(h.let("vs"), (r: any) => (decInt(r, "i64") as bigint));
    const r0 = rt.appendSlice(v_s, v_vs);
    return [encSlice(r0, (e: any) => encInt(e))];
  },
  "core.slice.append/overlap": function* (h: H) {
    const v_s = decSlice(h.let("s"), (r: any) => (decInt(r, "i64") as bigint));
    const v_a = view(v_s, h.let("a"));
    const v_vs = view(v_s, h.let("vs"));
    const r0 = rt.appendSlice(v_a, v_vs);
    h.after("s", encSlice(v_s, (e: any) => encInt(e)));
    return [encSlice(r0, (e: any) => encInt(e))];
  },
  "core.slice.clear/shared": function* (h: H) {
    const v_s = decSlice(h.let("s"), (r: any) => (decInt(r, "i64") as bigint));
    const v_t = view(v_s, h.let("t"));
    rt.clearSlice(v_t, () => 0n);
    h.after("s", encSlice(v_s, (e: any) => encInt(e)));
    return [];
  },
  "core.slice.copy/overlap_forward": function* (h: H) {
    const v_s = decSlice(h.let("s"), (r: any) => (decInt(r, "i64") as bigint));
    const v_d = view(v_s, h.let("d"));
    const v_src = view(v_s, h.let("src"));
    const r0 = rt.copy(v_d, v_src);
    h.after("s", encSlice(v_s, (e: any) => encInt(e)));
    return [encInt(r0)];
  },
  "core.slice.copy/short_dst": function* (h: H) {
    const v_d = decSlice(h.let("d"), (r: any) => (decInt(r, "u8") as number));
    const v_src = decSlice(h.let("src"), (r: any) => (decInt(r, "u8") as number));
    const r0 = rt.copy(v_d, v_src);
    h.after("d", encSlice(v_d, (e: any) => encInt(e)));
    return [encInt(r0)];
  },
  "core.slice.index/basic": function* (h: H) {
    const v_s = decSlice(h.let("s"), (r: any) => (decInt(r, "i64") as bigint));
    const v_i = (decInt(h.let("i"), "i64") as bigint);
    const r0 = rt.sget(v_s, v_i);
    return [encInt(r0)];
  },
  "core.slice.index/beyond_len": function* (h: H) {
    const v_s = decSlice(h.let("s"), (r: any) => (decInt(r, "i64") as bigint));
    const v_i = (decInt(h.let("i"), "i64") as bigint);
    const r0 = rt.sget(v_s, v_i);
    return [encInt(r0)];
  },
  "core.slice.index/nil": function* (h: H) {
    const v_s = decSlice(h.let("s"), (r: any) => decString(r));
    const v_i = (decInt(h.let("i"), "i64") as bigint);
    const r0 = rt.sget(v_s, v_i);
    return [encString(r0)];
  },
  "core.slice.make/basic": function* (h: H) {
    const v_len = (decInt(h.let("len"), "i64") as bigint);
    const v_cap = (decInt(h.let("cap"), "i64") as bigint);
    const r0 = rt.makeSlice(v_len, v_cap, () => 0n);
    return [encSlice(r0, (e: any) => encInt(e))];
  },
  "core.slice.make/cap_lt_len": function* (h: H) {
    const v_len = (decInt(h.let("len"), "i64") as bigint);
    const v_cap = (decInt(h.let("cap"), "i64") as bigint);
    const r0 = rt.makeSlice(v_len, v_cap, () => 0);
    return [encSlice(r0, (e: any) => encInt(e))];
  },
  "core.slice.make/neg_len": function* (h: H) {
    const v_len = (decInt(h.let("len"), "i64") as bigint);
    const v_cap = (decInt(h.let("cap"), "i64") as bigint);
    const r0 = rt.makeSlice(v_len, v_cap, () => 0n);
    return [encSlice(r0, (e: any) => encInt(e))];
  },
  "core.slice.slice/hi_gt_max": function* (h: H) {
    const v_s = decSlice(h.let("s"), (r: any) => (decInt(r, "i64") as bigint));
    const v_lo = (decInt(h.let("lo"), "i64") as bigint);
    const v_hi = (decInt(h.let("hi"), "i64") as bigint);
    const v_max = (decInt(h.let("max"), "i64") as bigint);
    const r0 = rt.reslice(v_s, v_lo, v_hi, v_max);
    return [encSlice(r0, (e: any) => encInt(e))];
  },
  "core.slice.slice/lo_gt_hi": function* (h: H) {
    const v_s = decSlice(h.let("s"), (r: any) => (decInt(r, "i64") as bigint));
    const v_lo = (decInt(h.let("lo"), "i64") as bigint);
    const v_hi = (decInt(h.let("hi"), "i64") as bigint);
    const v_max = (decInt(h.let("max"), "i64") as bigint);
    const r0 = rt.reslice(v_s, v_lo, v_hi, v_max);
    return [encSlice(r0, (e: any) => encInt(e))];
  },
  "core.slice.slice/max_oob": function* (h: H) {
    const v_s = decSlice(h.let("s"), (r: any) => (decInt(r, "i64") as bigint));
    const v_lo = (decInt(h.let("lo"), "i64") as bigint);
    const v_hi = (decInt(h.let("hi"), "i64") as bigint);
    const v_max = (decInt(h.let("max"), "i64") as bigint);
    const r0 = rt.reslice(v_s, v_lo, v_hi, v_max);
    return [encSlice(r0, (e: any) => encInt(e))];
  },
  "core.slice.slice/nil_empty": function* (h: H) {
    const v_s = decSlice(h.let("s"), (r: any) => (decInt(r, "i64") as bigint));
    const v_lo = (decInt(h.let("lo"), "i64") as bigint);
    const v_hi = (decInt(h.let("hi"), "i64") as bigint);
    const v_max = (decInt(h.let("max"), "i64") as bigint);
    const r0 = rt.reslice(v_s, v_lo, v_hi, v_max);
    return [encSlice(r0, (e: any) => encInt(e))];
  },
  "core.slice.slice/share": function* (h: H) {
    const v_s = decSlice(h.let("s"), (r: any) => (decInt(r, "i64") as bigint));
    const v_lo = (decInt(h.let("lo"), "i64") as bigint);
    const v_hi = (decInt(h.let("hi"), "i64") as bigint);
    const v_max = (decInt(h.let("max"), "i64") as bigint);
    const r0 = rt.reslice(v_s, v_lo, v_hi, v_max);
    return [encSlice(r0, (e: any) => encInt(e))];
  },
  "core.slice.store/alias_visible": function* (h: H) {
    const v_s = decSlice(h.let("s"), (r: any) => (decInt(r, "i64") as bigint));
    const v_t = view(v_s, h.let("t"));
    const v_i = (decInt(h.let("i"), "i64") as bigint);
    const v_v = (decInt(h.let("v"), "i64") as bigint);
    rt.sset(v_t, v_i, v_v);
    h.after("s", encSlice(v_s, (e: any) => encInt(e)));
    return [];
  },
  "core.slice.store/oob": function* (h: H) {
    const v_s = decSlice(h.let("s"), (r: any) => (decInt(r, "i64") as bigint));
    const v_i = (decInt(h.let("i"), "i64") as bigint);
    const v_v = (decInt(h.let("v"), "i64") as bigint);
    rt.sset(v_s, v_i, v_v);
    return [];
  },
  "core.slice.to_array/prefix": function* (h: H) {
    const v_s = decSlice(h.let("s"), (r: any) => (decInt(r, "i64") as bigint));
    const r0 = rt.sliceToArray(v_s, 2);
    return [encArray(r0, (e: any) => encInt(e))];
  },
  "core.slice.to_array/short": function* (h: H) {
    const v_s = decSlice(h.let("s"), (r: any) => (decInt(r, "i64") as bigint));
    const r0 = rt.sliceToArray(v_s, 2);
    return [encArray(r0, (e: any) => encInt(e))];
  },
  "core.string.compare/equal": function* (h: H) {
    const v_a = decString(h.let("a"));
    const v_b = decString(h.let("b"));
    const r0 = rt.scompare(v_a, v_b);
    return [encInt(r0)];
  },
  "core.string.compare/high_byte": function* (h: H) {
    const v_a = decString(h.let("a"));
    const v_b = decString(h.let("b"));
    const r0 = rt.scompare(v_a, v_b);
    return [encInt(r0)];
  },
  "core.string.compare/less": function* (h: H) {
    const v_a = decString(h.let("a"));
    const v_b = decString(h.let("b"));
    const r0 = rt.scompare(v_a, v_b);
    return [encInt(r0)];
  },
  "core.string.compare/prefix": function* (h: H) {
    const v_a = decString(h.let("a"));
    const v_b = decString(h.let("b"));
    const r0 = rt.scompare(v_a, v_b);
    return [encInt(r0)];
  },
  "core.string.concat/basic": function* (h: H) {
    const v_a = decString(h.let("a"));
    const v_b = decString(h.let("b"));
    const r0 = rt.concat(v_a, v_b);
    return [encString(r0)];
  },
  "core.string.concat/raw_bytes": function* (h: H) {
    const v_a = decString(h.let("a"));
    const v_b = decString(h.let("b"));
    const r0 = rt.concat(v_a, v_b);
    return [encString(r0)];
  },
  "core.string.decode_rune/ascii": function* (h: H) {
    const v_s = decString(h.let("s"));
    const v_i = (decInt(h.let("i"), "i64") as bigint);
    const [r0, r1] = rt.decodeRune(v_s, v_i);
    return [encInt(r0), encInt(r1)];
  },
  "core.string.decode_rune/four": function* (h: H) {
    const v_s = decString(h.let("s"));
    const v_i = (decInt(h.let("i"), "i64") as bigint);
    const [r0, r1] = rt.decodeRune(v_s, v_i);
    return [encInt(r0), encInt(r1)];
  },
  "core.string.decode_rune/invalid": function* (h: H) {
    const v_s = decString(h.let("s"));
    const v_i = (decInt(h.let("i"), "i64") as bigint);
    const [r0, r1] = rt.decodeRune(v_s, v_i);
    return [encInt(r0), encInt(r1)];
  },
  "core.string.decode_rune/overlong": function* (h: H) {
    const v_s = decString(h.let("s"));
    const v_i = (decInt(h.let("i"), "i64") as bigint);
    const [r0, r1] = rt.decodeRune(v_s, v_i);
    return [encInt(r0), encInt(r1)];
  },
  "core.string.decode_rune/surrogate": function* (h: H) {
    const v_s = decString(h.let("s"));
    const v_i = (decInt(h.let("i"), "i64") as bigint);
    const [r0, r1] = rt.decodeRune(v_s, v_i);
    return [encInt(r0), encInt(r1)];
  },
  "core.string.decode_rune/truncated": function* (h: H) {
    const v_s = decString(h.let("s"));
    const v_i = (decInt(h.let("i"), "i64") as bigint);
    const [r0, r1] = rt.decodeRune(v_s, v_i);
    return [encInt(r0), encInt(r1)];
  },
  "core.string.decode_rune/two": function* (h: H) {
    const v_s = decString(h.let("s"));
    const v_i = (decInt(h.let("i"), "i64") as bigint);
    const [r0, r1] = rt.decodeRune(v_s, v_i);
    return [encInt(r0), encInt(r1)];
  },
  "core.string.from_bytes/basic": function* (h: H) {
    const v_b = decSlice(h.let("b"), (r: any) => (decInt(r, "u8") as number));
    const r0 = rt.fromBytes(v_b);
    return [encString(r0)];
  },
  "core.string.from_bytes/nil": function* (h: H) {
    const v_b = decSlice(h.let("b"), (r: any) => (decInt(r, "u8") as number));
    const r0 = rt.fromBytes(v_b);
    return [encString(r0)];
  },
  "core.string.from_rune/ascii": function* (h: H) {
    const v_r = (decInt(h.let("r"), "i32") as number);
    const r0 = rt.fromRune(v_r);
    return [encString(r0)];
  },
  "core.string.from_rune/huge": function* (h: H) {
    const v_r = (decInt(h.let("r"), "i64") as bigint);
    const r0 = rt.fromRune(v_r);
    return [encString(r0)];
  },
  "core.string.from_rune/negative": function* (h: H) {
    const v_r = (decInt(h.let("r"), "i8") as number);
    const r0 = rt.fromRune(v_r);
    return [encString(r0)];
  },
  "core.string.from_rune/surrogate": function* (h: H) {
    const v_r = (decInt(h.let("r"), "i64") as bigint);
    const r0 = rt.fromRune(v_r);
    return [encString(r0)];
  },
  "core.string.from_runes/basic": function* (h: H) {
    const v_r = decSlice(h.let("r"), (r: any) => (decInt(r, "i32") as number));
    const r0 = rt.fromRunes(v_r);
    return [encString(r0)];
  },
  "core.string.from_runes/invalid": function* (h: H) {
    const v_r = decSlice(h.let("r"), (r: any) => (decInt(r, "i32") as number));
    const r0 = rt.fromRunes(v_r);
    return [encString(r0)];
  },
  "core.string.index/first": function* (h: H) {
    const v_s = decString(h.let("s"));
    const v_i = (decInt(h.let("i"), "i64") as bigint);
    const r0 = rt.sindex(v_s, v_i);
    return [encInt(r0)];
  },
  "core.string.index/negative": function* (h: H) {
    const v_s = decString(h.let("s"));
    const v_i = (decInt(h.let("i"), "i64") as bigint);
    const r0 = rt.sindex(v_s, v_i);
    return [encInt(r0)];
  },
  "core.string.index/oob": function* (h: H) {
    const v_s = decString(h.let("s"));
    const v_i = (decInt(h.let("i"), "i64") as bigint);
    const r0 = rt.sindex(v_s, v_i);
    return [encInt(r0)];
  },
  "core.string.index/unsigned_huge": function* (h: H) {
    const v_s = decString(h.let("s"));
    const v_i = (decInt(h.let("i"), "u64") as bigint);
    const r0 = rt.sindex(v_s, v_i);
    return [encInt(r0)];
  },
  "core.string.slice/hi_oob": function* (h: H) {
    const v_s = decString(h.let("s"));
    const v_lo = (decInt(h.let("lo"), "i64") as bigint);
    const v_hi = (decInt(h.let("hi"), "i64") as bigint);
    const r0 = rt.sslice(v_s, v_lo, v_hi);
    return [encString(r0)];
  },
  "core.string.slice/inverted": function* (h: H) {
    const v_s = decString(h.let("s"));
    const v_lo = (decInt(h.let("lo"), "i64") as bigint);
    const v_hi = (decInt(h.let("hi"), "i64") as bigint);
    const r0 = rt.sslice(v_s, v_lo, v_hi);
    return [encString(r0)];
  },
  "core.string.slice/mid": function* (h: H) {
    const v_s = decString(h.let("s"));
    const v_lo = (decInt(h.let("lo"), "i64") as bigint);
    const v_hi = (decInt(h.let("hi"), "i64") as bigint);
    const r0 = rt.sslice(v_s, v_lo, v_hi);
    return [encString(r0)];
  },
  "core.string.slice/split_rune": function* (h: H) {
    const v_s = decString(h.let("s"));
    const v_lo = (decInt(h.let("lo"), "i64") as bigint);
    const v_hi = (decInt(h.let("hi"), "i64") as bigint);
    const r0 = rt.sslice(v_s, v_lo, v_hi);
    return [encString(r0)];
  },
  "core.string.to_bytes/basic": function* (h: H) {
    const v_s = decString(h.let("s"));
    const r0 = rt.toBytes(v_s);
    return [encSlice(r0, (e: any) => encInt(e))];
  },
  "core.string.to_bytes/empty": function* (h: H) {
    const v_s = decString(h.let("s"));
    const r0 = rt.toBytes(v_s);
    return [encSlice(r0, (e: any) => encInt(e))];
  },
  "core.string.to_runes/mixed": function* (h: H) {
    const v_s = decString(h.let("s"));
    const r0 = rt.toRunes(v_s);
    return [encSlice(r0, (e: any) => encInt(e))];
  },
  "core.task.spawn/parent_continues": function* (h: H) {
    const r0 = yield* harnessSpawn();
    return [encBool(r0)];
  },
  "std.context.background/root": function* (h: H) {
    const r0 = rt.stdContextBackground();
    return [encZero(r0)];
  },
  "std.context.canceled/message": function* (h: H) {
    const r0 = rt.stdContextCanceled();
    return [encError(r0)];
  },
  "std.context.deadline_exceeded/message": function* (h: H) {
    const r0 = rt.stdContextDeadlineExceeded();
    return [encError(r0)];
  },
  "std.context.done/background": function* (h: H) {
    const v_ctx = rt.stdContextBackground();
    const r0 = rt.stdContextContextDone(v_ctx);
    return [encChan(r0, (e: any) => encZero(e))];
  },
  "std.context.err/background": function* (h: H) {
    const v_ctx = rt.stdContextBackground();
    const r0 = rt.stdContextContextErr(v_ctx);
    return [encError(r0)];
  },
  "std.context.with_cancel/child": function* (h: H) {
    const v_parent = rt.stdContextBackground();
    const [r0, r1] = rt.stdContextWithCancel(v_parent);
    return [encZero(r0), encZero(r1)];
  },
  "std.context.with_timeout/child": function* (h: H) {
    const v_parent = rt.stdContextBackground();
    const v_d = (decInt(h.let("d"), "i64") as bigint);
    const [r0, r1] = rt.stdContextWithTimeout(v_parent, v_d);
    return [encZero(r0), encZero(r1)];
  },
  "std.errors.is/distinct": function* (h: H) {
    const v_err = decError(h.let("err"));
    const v_target = decError(h.let("target"));
    const r0 = rt.stdErrorsIs(v_err, v_target);
    return [encBool(r0)];
  },
  "std.errors.is/nils": function* (h: H) {
    const v_err = decError(h.let("err"));
    const v_target = decError(h.let("target"));
    const r0 = rt.stdErrorsIs(v_err, v_target);
    return [encBool(r0)];
  },
  "std.errors.is/same": function* (h: H) {
    const v_err = decError(h.let("err"));
    const v_target = v_err;
    const r0 = rt.stdErrorsIs(v_err, v_target);
    return [encBool(r0)];
  },
  "std.errors.new/message": function* (h: H) {
    const v_text = decString(h.let("text"));
    const r0 = rt.stdErrorsNew(v_text);
    return [encError(r0)];
  },
  "std.errors.unwrap/plain": function* (h: H) {
    const v_err = decError(h.let("err"));
    const r0 = rt.stdErrorsUnwrap(v_err);
    return [encError(r0)];
  },
  "std.runtime.gosched/alone": function* (h: H) {
    yield* rt.stdRuntimeGosched();
    return [];
  },
  "std.sync.mutex.lock/unlocked": function* (h: H) {
    const v_m = new rt.Mutex();
    yield* rt.stdSyncMutexLock(v_m);
    return [];
  },
  "std.sync.mutex.unlock/lock_then_unlock": function* (h: H) {
    const v_m = new rt.Mutex();
    yield* harnessLockUnlock(v_m);
    return [];
  },
  "std.sync.waitgroup.add/negative": function* (h: H) {
    const v_wg = new rt.WaitGroup();
    const v_delta = (decInt(h.let("delta"), "i64") as bigint);
    rt.stdSyncWaitgroupAdd(v_wg, v_delta);
    return [];
  },
  "std.sync.waitgroup.add/positive": function* (h: H) {
    const v_wg = new rt.WaitGroup();
    const v_delta = (decInt(h.let("delta"), "i64") as bigint);
    rt.stdSyncWaitgroupAdd(v_wg, v_delta);
    return [];
  },
  "std.sync.waitgroup.done/underflow": function* (h: H) {
    const v_wg = new rt.WaitGroup();
    rt.stdSyncWaitgroupDone(v_wg);
    return [];
  },
  "std.sync.waitgroup.wait/zero_returns": function* (h: H) {
    const v_wg = new rt.WaitGroup();
    yield* rt.stdSyncWaitgroupWait(v_wg);
    return [];
  },
  "std.time.sleep/zero": function* (h: H) {
    const v_d = (decInt(h.let("d"), "i64") as bigint);
    yield* rt.stdTimeSleep(v_d);
    return [];
  },
};
