package strconv

const (
	lowerhex = "0123456789abcdef"
	upperhex = "0123456789ABCDEF"
)

type floatInfo struct {
	mantbits uint
	expbits  uint
	bias     int
}

var float32info = floatInfo{23, 8, -127}
var float64info = floatInfo{52, 11, -1023}

// FormatFloat converts the floating-point number f to a string, according to
// the format fmt and precision prec. It rounds the result assuming that the
// original was obtained from a floating-point value of bitSize bits (32 for
// float32, 64 for float64).
//
// The format fmt is one of 'b' (-ddddp±ddd), 'e' (-d.dddde±dd), 'E'
// (-d.ddddE±dd), 'f' (-ddd.dddd), 'g' ('e' for large exponents, 'f'
// otherwise), 'G' ('E' for large exponents, 'f' otherwise), 'x'
// (-0xd.ddddp±ddd) or 'X' (-0Xd.ddddP±ddd).
//
// The precision prec controls the number of digits (excluding the exponent)
// printed by the 'e', 'E', 'f', 'g', 'G', 'x', and 'X' formats. For 'e',
// 'E', 'f', 'x', and 'X', it is the number of digits after the decimal
// point. For 'g' and 'G' it is the maximum number of significant digits
// (trailing zeros are removed). The special precision -1 uses the smallest
// number of digits necessary such that ParseFloat will return f exactly.
func FormatFloat(f float64, fmt byte, prec, bitSize int) string {
	if bitSize != 32 && bitSize != 64 {
		panic("strconv: illegal FormatFloat bitSize")
	}
	return string(genericFtoa(make([]byte, 0, max(prec+4, 24)), f, fmt, prec, bitSize))
}

// AppendFloat appends the string form of the floating-point number f, as
// generated by FormatFloat, to dst and returns the extended buffer.
func AppendFloat(dst []byte, f float64, fmt byte, prec, bitSize int) []byte {
	if bitSize != 32 && bitSize != 64 {
		panic("strconv: illegal AppendFloat bitSize")
	}
	return genericFtoa(dst, f, fmt, prec, bitSize)
}

// float64bits returns the IEEE 754 binary representation of f. NaN payloads
// are not observable in the subset, so every NaN encodes as Go's math.NaN().
func float64bits(f float64) uint64 {
	if f != f {
		return 0x7FF8000000000001
	}
	var sign uint64
	if f < 0 || f == 0 && 1/f < 0 {
		sign = 1 << 63
		f = -f
	}
	if f == 0 {
		return sign
	}
	if f > 1.7976931348623157e308 {
		return sign | 0x7FF0000000000000
	}
	frac, exp := normalize(f)
	if exp >= -1022 {
		return sign | uint64(exp+1023)<<52 | uint64(frac*(1<<52))&(1<<52-1)
	}
	return sign | uint64(frac*(1<<52))>>uint(-1022-exp)
}

// float32bits returns the IEEE 754 binary representation of a float32 value
// held exactly in f.
func float32bits(f float64) uint32 {
	if f != f {
		return 0x7FC00000
	}
	var sign uint32
	if f < 0 || f == 0 && 1/f < 0 {
		sign = 1 << 31
		f = -f
	}
	if f == 0 {
		return sign
	}
	if f > 3.4028234663852886e38 {
		return sign | 0x7F800000
	}
	frac, exp := normalize(f)
	if exp >= -126 {
		return sign | uint32(exp+127)<<23 | uint32(frac*(1<<23))&(1<<23-1)
	}
	return sign | uint32(uint64(frac*(1<<23))>>uint(-126-exp))
}

// normalize returns frac in [1, 2) and exp with f == frac * 2**exp. Scaling
// by powers of two is exact for positive finite f.
func normalize(f float64) (float64, int) {
	exp := 0
	for f >= 0x1p64 {
		f *= 0x1p-64
		exp += 64
	}
	for f >= 2 {
		f *= 0.5
		exp++
	}
	for f < 0x1p-64 {
		f *= 0x1p64
		exp -= 64
	}
	for f < 1 {
		f *= 2
		exp--
	}
	return f, exp
}

func genericFtoa(dst []byte, val float64, fmt byte, prec, bitSize int) []byte {
	var bits uint64
	var flt *floatInfo
	if bitSize == 32 {
		bits = uint64(float32bits(float64(float32(val))))
		flt = &float32info
	} else {
		bits = float64bits(val)
		flt = &float64info
	}
	neg := bits>>(flt.expbits+flt.mantbits) != 0
	exp := int(bits>>flt.mantbits) & (1<<flt.expbits - 1)
	mant := bits & (uint64(1)<<flt.mantbits - 1)
	switch exp {
	case 1<<flt.expbits - 1:
		var s string
		switch {
		case mant != 0:
			s = "NaN"
		case neg:
			s = "-Inf"
		default:
			s = "+Inf"
		}
		return append(dst, s...)
	case 0:
		exp++
	default:
		mant |= uint64(1) << flt.mantbits
	}
	exp += flt.bias
	if fmt == 'b' {
		return fmtB(dst, neg, mant, exp, flt)
	}
	if fmt == 'x' || fmt == 'X' {
		return fmtX(dst, prec, fmt, neg, mant, exp, flt)
	}
	return bigFtoa(dst, prec, fmt, neg, mant, exp, flt)
}

func bigFtoa(dst []byte, prec int, fmt byte, neg bool, mant uint64, exp int, flt *floatInfo) []byte {
	d := newDecimal()
	d.Assign(mant)
	d.Shift(exp - int(flt.mantbits))
	shortest := prec < 0
	if shortest {
		roundShortest(d, mant, exp, flt)
		switch fmt {
		case 'e', 'E':
			prec = d.nd - 1
		case 'f':
			prec = max(d.nd-d.dp, 0)
		case 'g', 'G':
			prec = d.nd
		}
	} else {
		switch fmt {
		case 'e', 'E':
			d.Round(prec + 1)
		case 'f':
			d.Round(d.dp + prec)
		case 'g', 'G':
			if prec == 0 {
				prec = 1
			}
			d.Round(prec)
		}
	}
	return formatDigits(dst, shortest, neg, d, prec, fmt)
}

func formatDigits(dst []byte, shortest bool, neg bool, d *decimal, prec int, fmt byte) []byte {
	switch fmt {
	case 'e', 'E':
		return fmtE(dst, neg, d, prec, fmt)
	case 'f':
		return fmtF(dst, neg, d, prec)
	case 'g', 'G':
		eprec := prec
		if eprec > d.nd && d.nd >= d.dp {
			eprec = d.nd
		}
		if shortest {
			eprec = 6
		}
		exp := d.dp - 1
		if exp < -4 || exp >= eprec {
			if prec > d.nd {
				prec = d.nd
			}
			return fmtE(dst, neg, d, prec-1, fmt+'e'-'g')
		}
		if prec > d.dp {
			prec = d.nd
		}
		return fmtF(dst, neg, d, max(prec-d.dp, 0))
	}
	return append(dst, '%', fmt)
}

// roundShortest rounds d (= mant * 2^exp) to the shortest number of digits
// that will let the original floating point value be precisely reconstructed.
func roundShortest(d *decimal, mant uint64, exp int, flt *floatInfo) {
	if mant == 0 {
		d.nd = 0
		return
	}
	minexp := flt.bias + 1
	if exp > minexp && 332*(d.dp-d.nd) >= 100*(exp-int(flt.mantbits)) {
		return
	}
	upper := newDecimal()
	upper.Assign(mant*2 + 1)
	upper.Shift(exp - int(flt.mantbits) - 1)
	var mantlo uint64
	var explo int
	if mant > 1<<flt.mantbits || exp == minexp {
		mantlo = mant - 1
		explo = exp
	} else {
		mantlo = mant*2 - 1
		explo = exp - 1
	}
	lower := newDecimal()
	lower.Assign(mantlo*2 + 1)
	lower.Shift(explo - int(flt.mantbits) - 1)
	inclusive := mant%2 == 0
	var upperdelta uint8
	for ui := 0; ; ui++ {
		mi := ui - upper.dp + d.dp
		if mi >= d.nd {
			break
		}
		li := ui - upper.dp + lower.dp
		l := byte('0')
		if li >= 0 && li < lower.nd {
			l = lower.d[li]
		}
		m := byte('0')
		if mi >= 0 {
			m = d.d[mi]
		}
		u := byte('0')
		if ui < upper.nd {
			u = upper.d[ui]
		}
		okdown := l != m || inclusive && li+1 == lower.nd
		switch {
		case upperdelta == 0 && m+1 < u:
			upperdelta = 2
		case upperdelta == 0 && m != u:
			upperdelta = 1
		case upperdelta == 1 && (m != '9' || u != '0'):
			upperdelta = 2
		}
		okup := upperdelta > 0 && (inclusive || upperdelta > 1 || ui+1 < upper.nd)
		switch {
		case okdown && okup:
			d.Round(mi + 1)
			return
		case okdown:
			d.RoundDown(mi + 1)
			return
		case okup:
			d.RoundUp(mi + 1)
			return
		}
	}
}

func fmtE(dst []byte, neg bool, d *decimal, prec int, fmt byte) []byte {
	if neg {
		dst = append(dst, '-')
	}
	ch := byte('0')
	if d.nd != 0 {
		ch = d.d[0]
	}
	dst = append(dst, ch)
	if prec > 0 {
		dst = append(dst, '.')
		i := 1
		m := min(d.nd, prec+1)
		if i < m {
			dst = append(dst, d.d[i:m]...)
			i = m
		}
		for ; i <= prec; i++ {
			dst = append(dst, '0')
		}
	}
	dst = append(dst, fmt)
	exp := d.dp - 1
	if d.nd == 0 {
		exp = 0
	}
	if exp < 0 {
		ch = '-'
		exp = -exp
	} else {
		ch = '+'
	}
	dst = append(dst, ch)
	switch {
	case exp < 10:
		dst = append(dst, '0', byte(exp)+'0')
	case exp < 100:
		dst = append(dst, byte(exp/10)+'0', byte(exp%10)+'0')
	default:
		dst = append(dst, byte(exp/100)+'0', byte(exp/10)%10+'0', byte(exp%10)+'0')
	}
	return dst
}

func fmtF(dst []byte, neg bool, d *decimal, prec int) []byte {
	if neg {
		dst = append(dst, '-')
	}
	if d.dp > 0 {
		m := min(d.nd, d.dp)
		dst = append(dst, d.d[:m]...)
		for ; m < d.dp; m++ {
			dst = append(dst, '0')
		}
	} else {
		dst = append(dst, '0')
	}
	if prec > 0 {
		dst = append(dst, '.')
		for i := 0; i < prec; i++ {
			ch := byte('0')
			if j := d.dp + i; 0 <= j && j < d.nd {
				ch = d.d[j]
			}
			dst = append(dst, ch)
		}
	}
	return dst
}

func fmtB(dst []byte, neg bool, mant uint64, exp int, flt *floatInfo) []byte {
	if neg {
		dst = append(dst, '-')
	}
	dst = AppendUint(dst, mant, 10)
	dst = append(dst, 'p')
	exp -= int(flt.mantbits)
	if exp >= 0 {
		dst = append(dst, '+')
	}
	return AppendInt(dst, int64(exp), 10)
}

func fmtX(dst []byte, prec int, fmt byte, neg bool, mant uint64, exp int, flt *floatInfo) []byte {
	if mant == 0 {
		exp = 0
	}
	mant <<= 60 - flt.mantbits
	for mant != 0 && mant&(1<<60) == 0 {
		mant <<= 1
		exp--
	}
	if prec >= 0 && prec < 15 {
		shift := uint(prec * 4)
		extra := (mant << shift) & (1<<60 - 1)
		mant >>= 60 - shift
		if extra|(mant&1) > 1<<59 {
			mant++
		}
		mant <<= 60 - shift
		if mant&(1<<61) != 0 {
			mant >>= 1
			exp++
		}
	}
	hex := lowerhex
	if fmt == 'X' {
		hex = upperhex
	}
	if neg {
		dst = append(dst, '-')
	}
	dst = append(dst, '0', fmt, '0'+byte((mant>>60)&1))
	mant <<= 4
	if prec < 0 && mant != 0 {
		dst = append(dst, '.')
		for mant != 0 {
			dst = append(dst, hex[(mant>>60)&15])
			mant <<= 4
		}
	} else if prec > 0 {
		dst = append(dst, '.')
		for i := 0; i < prec; i++ {
			dst = append(dst, hex[(mant>>60)&15])
			mant <<= 4
		}
	}
	ch := byte('P')
	if fmt == fmt|('x'-'X') {
		ch = 'p'
	}
	dst = append(dst, ch)
	if exp < 0 {
		ch = '-'
		exp = -exp
	} else {
		ch = '+'
	}
	dst = append(dst, ch)
	switch {
	case exp < 100:
		dst = append(dst, byte(exp/10)+'0', byte(exp%10)+'0')
	case exp < 1000:
		dst = append(dst, byte(exp/100)+'0', byte((exp/10)%10)+'0', byte(exp%10)+'0')
	default:
		dst = append(dst, byte(exp/1000)+'0', byte(exp/100)%10+'0', byte((exp/10)%10)+'0', byte(exp%10)+'0')
	}
	return dst
}
