package c

import (
	"bytes"
	"fmt"
	"go/token"
	"sort"

	"github.com/eugenioenko/goalchemy/internal/emit/artifact"
	"github.com/eugenioenko/goalchemy/internal/ir"
	"github.com/eugenioenko/goalchemy/internal/naming"
)

// Emit writes source-owned definitions directly to separately compiled native
// translation units. The private header shares declarations, never bodies.
func Emit(p *ir.Program, symbols map[string]string) (*Output, error) {
	layout, err := artifact.NewLayout(p)
	if err != nil {
		return nil, err
	}
	e := &emitter{p: p, names: naming.New(p), symbols: symbols, contracts: map[string]bool{}, tds: map[*ir.Type]bool{},
		seenHelp: map[*ir.Type]bool{}, externs: map[string]*ir.Extern{}, layout: layout,
		helpers: map[string]*bytes.Buffer{"": {}}, localProtos: map[string]*bytes.Buffer{"": {}}}
	bodies := map[string]*bytes.Buffer{"": {}}
	for _, pkg := range layout.Packages {
		bodies[pkg.Path] = &bytes.Buffer{}
		e.helpers[pkg.Path] = &bytes.Buffer{}
		e.localProtos[pkg.Path] = &bytes.Buffer{}
	}
	for _, typ := range p.Types.All {
		if typ.Boxed {
			e.tds[typ] = true
		}
	}
	for _, global := range p.Globals {
		name := e.names.Symbol(global.Sym)
		fmt.Fprintf(bodies[global.Pkg], "%sgx_V %s;\n", position(global.Pos), name)
		e.proto("extern gx_V %s", name)
	}
	for _, function := range p.Funcs {
		owner := function.Pkg
		if function == p.Init || function == p.Entry {
			owner = ""
		}
		e.current = owner
		bodies[owner].WriteString(e.function(function))
		bodies[owner].WriteString(e.wrapper(function))
	}
	e.current = ""
	root := bodies[""]
	root.WriteString("static void init_zero_globals(void) {\n")
	for _, global := range p.Globals {
		zero := e.zero(global.Type)
		if global.AddrTaken && !global.Type.IsAggregate() {
			zero = "gx_cellv(" + zero + ")"
		}
		fmt.Fprintf(root, "    %s = %s;\n", e.names.Symbol(global.Sym), zero)
	}
	root.WriteString("}\n\n")
	var descriptors bytes.Buffer
	e.typeDescs(&descriptors)
	var header []byte
	if p.Library {
		header, err = e.library(root)
		if err != nil {
			return nil, err
		}
	} else if p.Cooperative {
		e.use("core.task.spawn")
		root.WriteString("static gx_V entry_frame(void) {\n")
		if p.Entry.MaySuspend {
			fmt.Fprintf(root, "    return f_%s();\n", e.names.Symbol(p.Entry.Sym))
		} else {
			fmt.Fprintf(root, "    return gx_sync_frame(gx_func(-1, w_%s, 0, NULL), 0, NULL, 0);\n", e.names.Symbol(p.Entry.Sym))
		}
		run := "gx_run_main"
		if ir.HostEntry(e.contracts) {
			run = "gx_host_main"
		}
		root.WriteString("}\n\nint goalchemy_run_host(void) {\n    return gx_run_main_host(init_zero_globals, entry_frame);\n}\n\nint main(void) {\n    " + run + "(init_zero_globals, entry_frame);\n}\n")
	} else {
		fmt.Fprintf(root, "static void entry(void) {\n    f_%s();\n", e.names.Symbol(p.Init.Sym))
		if p.Main != nil {
			fmt.Fprintf(root, "    f_%s();\n", e.names.Symbol(p.Main.Sym))
		}
		root.WriteString("}\n\nint main(void) {\n    gx_program_main(init_zero_globals, entry);\n}\n")
	}
	e.externWrappers(root)
	e.flushHelpers()
	const banner = "/* Code generated by goalchemy. DO NOT EDIT. */\n"
	var internal bytes.Buffer
	internal.WriteString(banner + "#ifndef GOALCHEMY_INTERNAL_H\n#define GOALCHEMY_INTERNAL_H\n#include \"gx.h\"\n")
	if p.Library {
		internal.WriteString("#include \"library.h\"\n")
	}
	internal.Write(e.protos.Bytes())
	internal.WriteString("#endif\n")
	files := []artifact.File{{Path: "goalchemy_internal.h", Source: internal.Bytes()}}
	write := func(path, owner string, body []byte) {
		source, lines := e.resolveMarkers(banner + "#include \"goalchemy_internal.h\"\n\n" + string(body))
		files = append(files, artifact.File{Path: path, Owner: owner, Source: []byte(source), Lines: lines})
	}
	var shared bytes.Buffer
	shared.Write(e.helpers[""].Bytes())
	shared.Write(descriptors.Bytes())
	write("shared.c", "", shared.Bytes())
	for _, pkg := range layout.Packages {
		var body bytes.Buffer
		body.Write(e.localProtos[pkg.Path].Bytes())
		body.Write(e.helpers[pkg.Path].Bytes())
		body.Write(bodies[pkg.Path].Bytes())
		write(layout.Stem(pkg.Path)+".c", pkg.Path, body.Bytes())
	}
	var main bytes.Buffer
	main.Write(e.localProtos[""].Bytes())
	main.Write(root.Bytes())
	write("main.c", "", main.Bytes())
	if header != nil {
		files = append(files, artifact.File{Path: "goalchemy.h", Source: header})
	}
	var contracts []string
	for contract := range e.contracts {
		contracts = append(contracts, contract)
	}
	sort.Strings(contracts)
	return &Output{Files: files, Packages: layout.PackageFiles(files), Header: header, Contracts: contracts}, nil
}

func position(pos token.Pos) string {
	if !pos.IsValid() {
		return ""
	}
	return fmt.Sprintf("%s%d\x00", marker, pos)
}

func (e *emitter) localProto(format string, args ...any) {
	fmt.Fprintf(e.localProtos[e.current], format+";\n", args...)
}
