// Code generated by protoc-gen-goalchemy. DO NOT EDIT.
// source: policy/selectors.proto

package policy

import (
	jsonvalue "github.com/eugenioenko/goalchemy/std/encoding/jsonvalue"
	protojson "github.com/eugenioenko/goalchemy/std/encoding/protojson"
)

type PageResponse struct {
	CurrentOffset int32
	NextOffset    int32
	Total         int32
}

func (m *PageResponse) GetCurrentOffset() int32 {
	if m != nil {
		return m.CurrentOffset
	}
	return 0
}

func (m *PageResponse) GetNextOffset() int32 {
	if m != nil {
		return m.NextOffset
	}
	return 0
}

func (m *PageResponse) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *PageResponse) EncodeProtoJSON(e *protojson.Encoder) {
	e.BeginObject()
	if m != nil {
		if m.CurrentOffset != 0 {
			e.Key("currentOffset")
			e.Int32(m.CurrentOffset)
		}
		if m.NextOffset != 0 {
			e.Key("nextOffset")
			e.Int32(m.NextOffset)
		}
		if m.Total != 0 {
			e.Key("total")
			e.Int32(m.Total)
		}
	}
	e.EndObject()
}

func (m *PageResponse) DecodeProtoJSON(d *protojson.Decoder, v jsonvalue.Value) {
	if !d.Object(v, "policy.PageResponse") {
		return
	}
	seenCurrentOffset := false
	seenNextOffset := false
	for _, k := range v.Keys() {
		f := v.Get(k)
		switch k {
		case "currentOffset", "current_offset":
			if seenCurrentOffset {
				d.Duplicate(k)
				return
			}
			seenCurrentOffset = true
			if f.IsNull() {
				break
			}
			m.CurrentOffset = d.Int32(f, "currentOffset")
		case "nextOffset", "next_offset":
			if seenNextOffset {
				d.Duplicate(k)
				return
			}
			seenNextOffset = true
			if f.IsNull() {
				break
			}
			m.NextOffset = d.Int32(f, "nextOffset")
		case "total":
			if f.IsNull() {
				break
			}
			m.Total = d.Int32(f, "total")
		}
		if d.Err() != nil {
			return
		}
	}
}

func (m *PageResponse) MarshalJSON() ([]byte, error) { return protojson.Marshal(m) }

func (m *PageResponse) UnmarshalJSON(b []byte) error { return protojson.Unmarshal(b, m) }

func init() {
	protojson.Register([]string{
		"policy.PageResponse",
	}, func(name string) protojson.Message {
		switch name {
		case "policy.PageResponse":
			return &PageResponse{}
		}
		return nil
	})
}
