package driver

import (
	"fmt"
	"sort"
	"strings"

	"goalchemy/internal/diagnostics"
	"goalchemy/internal/emit/golang"
	"goalchemy/internal/emit/ts"
	"goalchemy/internal/link"
)

func init() {
	Register("go", emitGo)
}

func emitErr(code, msg string) []diagnostics.Diagnostic {
	return []diagnostics.Diagnostic{{Code: code, Severity: diagnostics.Error, Feature: "emission", Message: msg,
		Remedy: "This is a compiler defect; please report it with the source program."}}
}

func emitGo(res *Result, out string) []diagnostics.Diagnostic {
	o, err := golang.Emit(res.IR)
	if err != nil {
		_ = link.WriteFile(out, "main.go", o.Source)
		return emitErr("GCE004", err.Error())
	}
	refs, files, ds := link.Plan(res.Catalog, "go", o.Contracts)
	if len(ds) > 0 {
		return ds
	}
	rtFiles, err := link.CopyRuntime(res.Catalog, "go", files, out, "rt", true)
	if err != nil {
		return emitErr("GCE005", err.Error())
	}
	if err := link.WriteFile(out, "main.go", o.Source); err != nil {
		return emitErr("GCE005", err.Error())
	}
	if err := link.WriteFile(out, "go.mod", []byte("module goalchemyout\n\ngo 1.25\n")); err != nil {
		return emitErr("GCE005", err.Error())
	}
	if err := link.WriteManifest(out, res.Catalog, "go", refs, rtFiles, []string{"main.go", "go.mod"}, res.Program); err != nil {
		return emitErr("GCE005", err.Error())
	}
	return nil
}

func init() {
	Register("typescript", emitTS)
}

func emitTS(res *Result, out string) []diagnostics.Diagnostic {
	o, err := ts.Emit(res.IR)
	if err != nil {
		return emitErr("GCE004", err.Error())
	}
	refs, files, ds := link.Plan(res.Catalog, "typescript", o.Contracts)
	if len(ds) > 0 {
		return ds
	}
	rtFiles, err := link.CopyRuntime(res.Catalog, "typescript", files, out, "rt", false)
	if err != nil {
		return emitErr("GCE005", err.Error())
	}
	var index strings.Builder
	index.WriteString("// Code generated by goalchemy. DO NOT EDIT.\n")
	for _, f := range files {
		fmt.Fprintf(&index, "export * from \"./%s\";\n", f)
	}
	gen := map[string][]byte{
		"main.ts":      o.Source,
		"rt/index.ts":  []byte(index.String()),
		"package.json": []byte("{\n  \"type\": \"module\",\n  \"private\": true,\n  \"engines\": {\"node\": \">=22.6\"}\n}\n"),
	}
	var names []string
	for name, data := range gen {
		if err := link.WriteFile(out, name, data); err != nil {
			return emitErr("GCE005", err.Error())
		}
		names = append(names, name)
	}
	sort.Strings(names)
	if err := link.WriteManifest(out, res.Catalog, "typescript", refs, rtFiles, names, res.Program); err != nil {
		return emitErr("GCE005", err.Error())
	}
	return nil
}
