// Code generated by goalchemy spec generate. DO NOT EDIT.
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import rt.*;

@SuppressWarnings({"unchecked", "unused"})
final class HarnessGen extends Codec {
    static List<Object> case_0(Harness.H h) {
        var v_ch = decChan(h.let("ch"), r -> decInt(r, "i64"), () -> 0L);
        var r0 = ChanCap.chanCap(v_ch);
        return Arrays.asList(new Object[] {encInt(r0, "i64")});
    }

    static List<Object> case_1(Harness.H h) {
        var v_ch = decChan(h.let("ch"), r -> decInt(r, "i64"), () -> 0L);
        ChanClose.chanClose(v_ch);
        return Arrays.asList(new Object[] {});
    }

    static List<Object> case_2(Harness.H h) {
        var v_ch = decChan(h.let("ch"), r -> decInt(r, "i64"), () -> 0L);
        ChanClose.chanClose(v_ch);
        h.after("ch", encChan(v_ch, e -> encInt(e, "i64")));
        return Arrays.asList(new Object[] {});
    }

    static List<Object> case_3(Harness.H h) {
        var v_ch = decChan(h.let("ch"), r -> decInt(r, "i64"), () -> 0L);
        ChanClose.chanClose(v_ch);
        return Arrays.asList(new Object[] {});
    }

    static List<Object> case_4(Harness.H h) {
        var v_ch = decChan(h.let("ch"), r -> decInt(r, "i64"), () -> 0L);
        var r0 = ChanLen.chanLen(v_ch);
        return Arrays.asList(new Object[] {encInt(r0, "i64")});
    }

    static List<Object> case_5(Harness.H h) {
        var v_ch = decChan(h.let("ch"), r -> decInt(r, "i64"), () -> 0L);
        var r0 = ChanLen.chanLen(v_ch);
        return Arrays.asList(new Object[] {encInt(r0, "i64")});
    }

    static List<Object> case_6(Harness.H h) {
        var v_size = decInt(h.let("size"), "i64");
        var r0 = ChanMake.makeChan(v_size, () -> 0L);
        return Arrays.asList(new Object[] {encChan(r0, e -> encInt(e, "i64"))});
    }

    static List<Object> case_7(Harness.H h) {
        var v_size = decInt(h.let("size"), "i64");
        var r0 = ChanMake.makeChan(v_size, () -> 0L);
        return Arrays.asList(new Object[] {encChan(r0, e -> encInt(e, "i64"))});
    }

    static List<Object> case_8(Harness.H h) {
        var v_ch = decChan(h.let("ch"), r -> decInt(r, "i64"), () -> 0L);
        Object[] rv = TaskSpawn.runIsolated(t -> { ChanRecv.chanRecv(t, v_ch); });
        var r0 = rv[0];
        var r1 = rv[1];
        h.after("ch", encChan(v_ch, e -> encInt(e, "i64")));
        return Arrays.asList(new Object[] {encInt(r0, "i64"), encBool(r1)});
    }

    static List<Object> case_9(Harness.H h) {
        var v_ch = decChan(h.let("ch"), r -> decString(r), () -> "");
        Object[] rv = TaskSpawn.runIsolated(t -> { ChanRecv.chanRecv(t, v_ch); });
        var r0 = rv[0];
        var r1 = rv[1];
        return Arrays.asList(new Object[] {encString(r0), encBool(r1)});
    }

    static List<Object> case_10(Harness.H h) {
        var v_ch = decChan(h.let("ch"), r -> decInt(r, "i64"), () -> 0L);
        Object[] rv = TaskSpawn.runIsolated(t -> { ChanRecv.chanRecv(t, v_ch); });
        var r0 = rv[0];
        var r1 = rv[1];
        return Arrays.asList(new Object[] {encInt(r0, "i64"), encBool(r1)});
    }

    static List<Object> case_11(Harness.H h) {
        var v_ch = decChan(h.let("ch"), r -> decInt(r, "i64"), () -> 0L);
        Object[] rv = TaskSpawn.runIsolated(t -> { ChanRecv.chanRecv(t, v_ch); });
        var r0 = rv[0];
        var r1 = rv[1];
        return Arrays.asList(new Object[] {encInt(r0, "i64"), encBool(r1)});
    }

    static List<Object> case_12(Harness.H h) {
        var v_ch = decChan(h.let("ch"), r -> decInt(r, "i64"), () -> 0L);
        Object[] rv = TaskSpawn.runIsolated(t -> { ChanRecv.chanRecv(t, v_ch); });
        var r0 = rv[0];
        var r1 = rv[1];
        return Arrays.asList(new Object[] {encInt(r0, "i64"), encBool(r1)});
    }

    static List<Object> case_13(Harness.H h) {
        var v_ch = decChan(h.let("ch"), r -> decInt(r, "i64"), () -> 0L);
        var v_v = decInt(h.let("v"), "i64");
        Object[] rv = TaskSpawn.runIsolated(t -> { ChanSend.chanSend(t, v_ch, v_v); });
        h.after("ch", encChan(v_ch, e -> encInt(e, "i64")));
        return Arrays.asList(new Object[] {});
    }

    static List<Object> case_14(Harness.H h) {
        var v_ch = decChan(h.let("ch"), r -> decInt(r, "i64"), () -> 0L);
        var v_v = decInt(h.let("v"), "i64");
        Object[] rv = TaskSpawn.runIsolated(t -> { ChanSend.chanSend(t, v_ch, v_v); });
        return Arrays.asList(new Object[] {});
    }

    static List<Object> case_15(Harness.H h) {
        var v_ch = decChan(h.let("ch"), r -> decInt(r, "i64"), () -> 0L);
        var v_v = decInt(h.let("v"), "i64");
        Object[] rv = TaskSpawn.runIsolated(t -> { ChanSend.chanSend(t, v_ch, v_v); });
        return Arrays.asList(new Object[] {});
    }

    static List<Object> case_16(Harness.H h) {
        var v_ch = decChan(h.let("ch"), r -> decInt(r, "i64"), () -> 0L);
        var v_v = decInt(h.let("v"), "i64");
        Object[] rv = TaskSpawn.runIsolated(t -> { ChanSend.chanSend(t, v_ch, v_v); });
        return Arrays.asList(new Object[] {});
    }

    static List<Object> case_17(Harness.H h) {
        var v_ch = decChan(h.let("ch"), r -> decString(r), () -> "");
        var v_v = decString(h.let("v"));
        Object[] rv = TaskSpawn.runIsolated(t -> { ChanSend.chanSend(t, v_ch, v_v); });
        return Arrays.asList(new Object[] {});
    }

    static List<Object> case_18(Harness.H h) {
        var v_a = decInt(h.let("a"), "i32");
        var v_b = decInt(h.let("b"), "i32");
        var r0 = IntegerAdd.add_i32(v_a, v_b);
        return Arrays.asList(new Object[] {encInt(r0, "i32")});
    }

    static List<Object> case_19(Harness.H h) {
        var v_a = decInt(h.let("a"), "i64");
        var v_b = decInt(h.let("b"), "i64");
        var r0 = IntegerAdd.add_i64(v_a, v_b);
        return Arrays.asList(new Object[] {encInt(r0, "i64")});
    }

    static List<Object> case_20(Harness.H h) {
        var v_a = decInt(h.let("a"), "i8");
        var v_b = decInt(h.let("b"), "i8");
        var r0 = IntegerAdd.add_i8(v_a, v_b);
        return Arrays.asList(new Object[] {encInt(r0, "i8")});
    }

    static List<Object> case_21(Harness.H h) {
        var v_a = decInt(h.let("a"), "i64");
        var v_b = decInt(h.let("b"), "i64");
        var r0 = IntegerAdd.add_i64(v_a, v_b);
        return Arrays.asList(new Object[] {encInt(r0, "i64")});
    }

    static List<Object> case_22(Harness.H h) {
        var v_a = decInt(h.let("a"), "u32");
        var v_b = decInt(h.let("b"), "u32");
        var r0 = IntegerAdd.add_u32(v_a, v_b);
        return Arrays.asList(new Object[] {encInt(r0, "u32")});
    }

    static List<Object> case_23(Harness.H h) {
        var v_a = decInt(h.let("a"), "u64");
        var v_b = decInt(h.let("b"), "u64");
        var r0 = IntegerAdd.add_u64(v_a, v_b);
        return Arrays.asList(new Object[] {encInt(r0, "u64")});
    }

    static List<Object> case_24(Harness.H h) {
        var v_a = decInt(h.let("a"), "i64");
        var v_b = decInt(h.let("b"), "i64");
        var r0 = IntegerAnd.and_i64(v_a, v_b);
        return Arrays.asList(new Object[] {encInt(r0, "i64")});
    }

    static List<Object> case_25(Harness.H h) {
        var v_a = decInt(h.let("a"), "u32");
        var v_b = decInt(h.let("b"), "u32");
        var r0 = IntegerAnd.and_u32(v_a, v_b);
        return Arrays.asList(new Object[] {encInt(r0, "u32")});
    }

    static List<Object> case_26(Harness.H h) {
        var v_a = decInt(h.let("a"), "i64");
        var v_b = decInt(h.let("b"), "i64");
        var r0 = IntegerAndnot.andnot_i64(v_a, v_b);
        return Arrays.asList(new Object[] {encInt(r0, "i64")});
    }

    static List<Object> case_27(Harness.H h) {
        var v_a = decInt(h.let("a"), "u16");
        var v_b = decInt(h.let("b"), "u16");
        var r0 = IntegerAndnot.andnot_u16(v_a, v_b);
        return Arrays.asList(new Object[] {encInt(r0, "u16")});
    }

    static List<Object> case_28(Harness.H h) {
        var v_a = decInt(h.let("a"), "u32");
        var v_b = decInt(h.let("b"), "u32");
        var r0 = IntegerCompare.compare_int(v_a, v_b);
        return Arrays.asList(new Object[] {encInt(r0, "i64")});
    }

    static List<Object> case_29(Harness.H h) {
        var v_a = decInt(h.let("a"), "i64");
        var v_b = decInt(h.let("b"), "i64");
        var r0 = IntegerCompare.compare_int(v_a, v_b);
        return Arrays.asList(new Object[] {encInt(r0, "i64")});
    }

    static List<Object> case_30(Harness.H h) {
        var v_a = decInt(h.let("a"), "u32");
        var v_b = decInt(h.let("b"), "u32");
        var r0 = IntegerCompare.compare_int(v_a, v_b);
        return Arrays.asList(new Object[] {encInt(r0, "i64")});
    }

    static List<Object> case_31(Harness.H h) {
        var v_a = decInt(h.let("a"), "u64");
        var v_b = decInt(h.let("b"), "u64");
        var r0 = IntegerCompare.compare_uint(v_a, v_b);
        return Arrays.asList(new Object[] {encInt(r0, "i64")});
    }

    static List<Object> case_32(Harness.H h) {
        var v_a = decInt(h.let("a"), "i32");
        var r0 = IntegerConvert.to_u16(v_a);
        return Arrays.asList(new Object[] {encInt(r0, "u16")});
    }

    static List<Object> case_33(Harness.H h) {
        var v_a = decInt(h.let("a"), "i64");
        var r0 = IntegerConvert.to_i64(v_a);
        return Arrays.asList(new Object[] {encInt(r0, "i64")});
    }

    static List<Object> case_34(Harness.H h) {
        var v_a = decInt(h.let("a"), "i8");
        var r0 = IntegerConvert.to_u64(v_a);
        return Arrays.asList(new Object[] {encInt(r0, "u64")});
    }

    static List<Object> case_35(Harness.H h) {
        var v_a = decInt(h.let("a"), "i64");
        var r0 = IntegerConvert.to_i8(v_a);
        return Arrays.asList(new Object[] {encInt(r0, "i8")});
    }

    static List<Object> case_36(Harness.H h) {
        var v_a = decInt(h.let("a"), "u32");
        var r0 = IntegerConvert.to_i32(v_a);
        return Arrays.asList(new Object[] {encInt(r0, "i32")});
    }

    static List<Object> case_37(Harness.H h) {
        var v_a = decInt(h.let("a"), "u64");
        var r0 = IntegerConvert.to_i64(v_a);
        return Arrays.asList(new Object[] {encInt(r0, "i64")});
    }

    static List<Object> case_38(Harness.H h) {
        var v_a = decInt(h.let("a"), "i32");
        var v_b = decInt(h.let("b"), "i32");
        var r0 = IntegerDiv.div_i32(v_a, v_b);
        return Arrays.asList(new Object[] {encInt(r0, "i32")});
    }

    static List<Object> case_39(Harness.H h) {
        var v_a = decInt(h.let("a"), "i64");
        var v_b = decInt(h.let("b"), "i64");
        var r0 = IntegerDiv.div_i64(v_a, v_b);
        return Arrays.asList(new Object[] {encInt(r0, "i64")});
    }

    static List<Object> case_40(Harness.H h) {
        var v_a = decInt(h.let("a"), "i8");
        var v_b = decInt(h.let("b"), "i8");
        var r0 = IntegerDiv.div_i8(v_a, v_b);
        return Arrays.asList(new Object[] {encInt(r0, "i8")});
    }

    static List<Object> case_41(Harness.H h) {
        var v_a = decInt(h.let("a"), "i64");
        var v_b = decInt(h.let("b"), "i64");
        var r0 = IntegerDiv.div_i64(v_a, v_b);
        return Arrays.asList(new Object[] {encInt(r0, "i64")});
    }

    static List<Object> case_42(Harness.H h) {
        var v_a = decInt(h.let("a"), "i64");
        var v_b = decInt(h.let("b"), "i64");
        var r0 = IntegerDiv.div_i64(v_a, v_b);
        return Arrays.asList(new Object[] {encInt(r0, "i64")});
    }

    static List<Object> case_43(Harness.H h) {
        var v_a = decInt(h.let("a"), "u64");
        var v_b = decInt(h.let("b"), "u64");
        var r0 = IntegerDiv.div_u64(v_a, v_b);
        return Arrays.asList(new Object[] {encInt(r0, "u64")});
    }

    static List<Object> case_44(Harness.H h) {
        var v_a = decInt(h.let("a"), "i32");
        var v_b = decInt(h.let("b"), "i32");
        var r0 = IntegerMul.mul_i32(v_a, v_b);
        return Arrays.asList(new Object[] {encInt(r0, "i32")});
    }

    static List<Object> case_45(Harness.H h) {
        var v_a = decInt(h.let("a"), "i32");
        var v_b = decInt(h.let("b"), "i32");
        var r0 = IntegerMul.mul_i32(v_a, v_b);
        return Arrays.asList(new Object[] {encInt(r0, "i32")});
    }

    static List<Object> case_46(Harness.H h) {
        var v_a = decInt(h.let("a"), "i64");
        var v_b = decInt(h.let("b"), "i64");
        var r0 = IntegerMul.mul_i64(v_a, v_b);
        return Arrays.asList(new Object[] {encInt(r0, "i64")});
    }

    static List<Object> case_47(Harness.H h) {
        var v_a = decInt(h.let("a"), "i8");
        var v_b = decInt(h.let("b"), "i8");
        var r0 = IntegerMul.mul_i8(v_a, v_b);
        return Arrays.asList(new Object[] {encInt(r0, "i8")});
    }

    static List<Object> case_48(Harness.H h) {
        var v_a = decInt(h.let("a"), "u32");
        var v_b = decInt(h.let("b"), "u32");
        var r0 = IntegerMul.mul_u32(v_a, v_b);
        return Arrays.asList(new Object[] {encInt(r0, "u32")});
    }

    static List<Object> case_49(Harness.H h) {
        var v_a = decInt(h.let("a"), "u64");
        var v_b = decInt(h.let("b"), "u64");
        var r0 = IntegerMul.mul_u64(v_a, v_b);
        return Arrays.asList(new Object[] {encInt(r0, "u64")});
    }

    static List<Object> case_50(Harness.H h) {
        var v_a = decInt(h.let("a"), "i32");
        var r0 = IntegerNeg.neg_i32(v_a);
        return Arrays.asList(new Object[] {encInt(r0, "i32")});
    }

    static List<Object> case_51(Harness.H h) {
        var v_a = decInt(h.let("a"), "i64");
        var r0 = IntegerNeg.neg_i64(v_a);
        return Arrays.asList(new Object[] {encInt(r0, "i64")});
    }

    static List<Object> case_52(Harness.H h) {
        var v_a = decInt(h.let("a"), "u64");
        var r0 = IntegerNeg.neg_u64(v_a);
        return Arrays.asList(new Object[] {encInt(r0, "u64")});
    }

    static List<Object> case_53(Harness.H h) {
        var v_a = decInt(h.let("a"), "u8");
        var r0 = IntegerNeg.neg_u8(v_a);
        return Arrays.asList(new Object[] {encInt(r0, "u8")});
    }

    static List<Object> case_54(Harness.H h) {
        var v_a = decInt(h.let("a"), "i64");
        var r0 = IntegerNot.not_i64(v_a);
        return Arrays.asList(new Object[] {encInt(r0, "i64")});
    }

    static List<Object> case_55(Harness.H h) {
        var v_a = decInt(h.let("a"), "u32");
        var r0 = IntegerNot.not_u32(v_a);
        return Arrays.asList(new Object[] {encInt(r0, "u32")});
    }

    static List<Object> case_56(Harness.H h) {
        var v_a = decInt(h.let("a"), "u8");
        var r0 = IntegerNot.not_u8(v_a);
        return Arrays.asList(new Object[] {encInt(r0, "u8")});
    }

    static List<Object> case_57(Harness.H h) {
        var v_a = decInt(h.let("a"), "i8");
        var v_b = decInt(h.let("b"), "i8");
        var r0 = IntegerOr.or_i8(v_a, v_b);
        return Arrays.asList(new Object[] {encInt(r0, "i8")});
    }

    static List<Object> case_58(Harness.H h) {
        var v_a = decInt(h.let("a"), "u32");
        var v_b = decInt(h.let("b"), "u32");
        var r0 = IntegerOr.or_u32(v_a, v_b);
        return Arrays.asList(new Object[] {encInt(r0, "u32")});
    }

    static List<Object> case_59(Harness.H h) {
        var v_a = decInt(h.let("a"), "u8");
        var v_b = decInt(h.let("b"), "u8");
        var r0 = IntegerRem.rem_u8(v_a, v_b);
        return Arrays.asList(new Object[] {encInt(r0, "u8")});
    }

    static List<Object> case_60(Harness.H h) {
        var v_a = decInt(h.let("a"), "i64");
        var v_b = decInt(h.let("b"), "i64");
        var r0 = IntegerRem.rem_i64(v_a, v_b);
        return Arrays.asList(new Object[] {encInt(r0, "i64")});
    }

    static List<Object> case_61(Harness.H h) {
        var v_a = decInt(h.let("a"), "i64");
        var v_b = decInt(h.let("b"), "i64");
        var r0 = IntegerRem.rem_i64(v_a, v_b);
        return Arrays.asList(new Object[] {encInt(r0, "i64")});
    }

    static List<Object> case_62(Harness.H h) {
        var v_a = decInt(h.let("a"), "i64");
        var v_b = decInt(h.let("b"), "i64");
        var r0 = IntegerRem.rem_i64(v_a, v_b);
        return Arrays.asList(new Object[] {encInt(r0, "i64")});
    }

    static List<Object> case_63(Harness.H h) {
        var v_a = decInt(h.let("a"), "u32");
        var v_b = decInt(h.let("b"), "u32");
        var r0 = IntegerRem.rem_u32(v_a, v_b);
        return Arrays.asList(new Object[] {encInt(r0, "u32")});
    }

    static List<Object> case_64(Harness.H h) {
        var v_a = decInt(h.let("a"), "i64");
        var v_b = decInt(h.let("b"), "u64");
        var r0 = IntegerShl.shl_i64(v_a, Ints.countu(v_b));
        return Arrays.asList(new Object[] {encInt(r0, "i64")});
    }

    static List<Object> case_65(Harness.H h) {
        var v_a = decInt(h.let("a"), "u64");
        var v_b = decInt(h.let("b"), "u64");
        var r0 = IntegerShl.shl_u64(v_a, Ints.countu(v_b));
        return Arrays.asList(new Object[] {encInt(r0, "u64")});
    }

    static List<Object> case_66(Harness.H h) {
        var v_a = decInt(h.let("a"), "i64");
        var v_b = decInt(h.let("b"), "i64");
        var r0 = IntegerShl.shl_i64(v_a, Ints.count(v_b));
        return Arrays.asList(new Object[] {encInt(r0, "i64")});
    }

    static List<Object> case_67(Harness.H h) {
        var v_a = decInt(h.let("a"), "i64");
        var v_b = decInt(h.let("b"), "i64");
        var r0 = IntegerShl.shl_i64(v_a, Ints.count(v_b));
        return Arrays.asList(new Object[] {encInt(r0, "i64")});
    }

    static List<Object> case_68(Harness.H h) {
        var v_a = decInt(h.let("a"), "i8");
        var v_b = decInt(h.let("b"), "i64");
        var r0 = IntegerShl.shl_i8(v_a, Ints.count(v_b));
        return Arrays.asList(new Object[] {encInt(r0, "i8")});
    }

    static List<Object> case_69(Harness.H h) {
        var v_a = decInt(h.let("a"), "i32");
        var v_b = decInt(h.let("b"), "u64");
        var r0 = IntegerShl.shl_i32(v_a, Ints.countu(v_b));
        return Arrays.asList(new Object[] {encInt(r0, "i32")});
    }

    static List<Object> case_70(Harness.H h) {
        var v_a = decInt(h.let("a"), "i64");
        var v_b = decInt(h.let("b"), "u64");
        var r0 = IntegerShr.shr_i64(v_a, Ints.countu(v_b));
        return Arrays.asList(new Object[] {encInt(r0, "i64")});
    }

    static List<Object> case_71(Harness.H h) {
        var v_a = decInt(h.let("a"), "i8");
        var v_b = decInt(h.let("b"), "i64");
        var r0 = IntegerShr.shr_i8(v_a, Ints.count(v_b));
        return Arrays.asList(new Object[] {encInt(r0, "i8")});
    }

    static List<Object> case_72(Harness.H h) {
        var v_a = decInt(h.let("a"), "u8");
        var v_b = decInt(h.let("b"), "i64");
        var r0 = IntegerShr.shr_u8(v_a, Ints.count(v_b));
        return Arrays.asList(new Object[] {encInt(r0, "u8")});
    }

    static List<Object> case_73(Harness.H h) {
        var v_a = decInt(h.let("a"), "u64");
        var v_b = decInt(h.let("b"), "u64");
        var r0 = IntegerShr.shr_u64(v_a, Ints.countu(v_b));
        return Arrays.asList(new Object[] {encInt(r0, "u64")});
    }

    static List<Object> case_74(Harness.H h) {
        var v_a = decInt(h.let("a"), "i8");
        var v_b = decInt(h.let("b"), "i64");
        var r0 = IntegerShr.shr_i8(v_a, Ints.count(v_b));
        return Arrays.asList(new Object[] {encInt(r0, "i8")});
    }

    static List<Object> case_75(Harness.H h) {
        var v_a = decInt(h.let("a"), "i32");
        var v_b = decInt(h.let("b"), "i64");
        var r0 = IntegerShr.shr_i32(v_a, Ints.count(v_b));
        return Arrays.asList(new Object[] {encInt(r0, "i32")});
    }

    static List<Object> case_76(Harness.H h) {
        var v_a = decInt(h.let("a"), "i16");
        var v_b = decInt(h.let("b"), "i16");
        var r0 = IntegerSub.sub_i16(v_a, v_b);
        return Arrays.asList(new Object[] {encInt(r0, "i16")});
    }

    static List<Object> case_77(Harness.H h) {
        var v_a = decInt(h.let("a"), "i64");
        var v_b = decInt(h.let("b"), "i64");
        var r0 = IntegerSub.sub_i64(v_a, v_b);
        return Arrays.asList(new Object[] {encInt(r0, "i64")});
    }

    static List<Object> case_78(Harness.H h) {
        var v_a = decInt(h.let("a"), "u8");
        var v_b = decInt(h.let("b"), "u8");
        var r0 = IntegerSub.sub_u8(v_a, v_b);
        return Arrays.asList(new Object[] {encInt(r0, "u8")});
    }

    static List<Object> case_79(Harness.H h) {
        var v_a = decInt(h.let("a"), "u64");
        var v_b = decInt(h.let("b"), "u64");
        var r0 = IntegerSub.sub_u64(v_a, v_b);
        return Arrays.asList(new Object[] {encInt(r0, "u64")});
    }

    static List<Object> case_80(Harness.H h) {
        var v_a = decInt(h.let("a"), "i32");
        var v_b = decInt(h.let("b"), "i32");
        var r0 = IntegerXor.xor_i32(v_a, v_b);
        return Arrays.asList(new Object[] {encInt(r0, "i32")});
    }

    static List<Object> case_81(Harness.H h) {
        var v_a = decInt(h.let("a"), "u64");
        var v_b = decInt(h.let("b"), "u64");
        var r0 = IntegerXor.xor_u64(v_a, v_b);
        return Arrays.asList(new Object[] {encInt(r0, "u64")});
    }

    static List<Object> case_82(Harness.H h) {
        var v_m = decMap(h.let("m"), r -> decInt(r, "i64"), r -> decInt(r, "i64"));
        MapClear.mapClear(v_m);
        h.after("m", encMap(v_m, e -> encInt(e, "i64"), e -> encInt(e, "i64")));
        return Arrays.asList(new Object[] {});
    }

    static List<Object> case_83(Harness.H h) {
        var v_m = decMap(h.let("m"), r -> decInt(r, "i64"), r -> decInt(r, "i64"));
        var v_k = decInt(h.let("k"), "i64");
        MapDelete.mapDelete(v_m, v_k, GoMap::identityKey);
        return Arrays.asList(new Object[] {});
    }

    static List<Object> case_84(Harness.H h) {
        var v_m = decMap(h.let("m"), r -> decInt(r, "i64"), r -> decInt(r, "i64"));
        var v_k = decInt(h.let("k"), "i64");
        MapDelete.mapDelete(v_m, v_k, GoMap::identityKey);
        h.after("m", encMap(v_m, e -> encInt(e, "i64"), e -> encInt(e, "i64")));
        return Arrays.asList(new Object[] {});
    }

    static List<Object> case_85(Harness.H h) {
        var v_m = decMap(h.let("m"), r -> decInt(r, "i64"), r -> decInt(r, "i64"));
        var r0 = MapIterate.mapKeys(v_m);
        return Arrays.asList(new Object[] {encSlice(r0, e -> encInt(e, "i64"))});
    }

    static List<Object> case_86(Harness.H h) {
        var v_m = decMap(h.let("m"), r -> decInt(r, "i64"), r -> decInt(r, "i64"));
        var r0 = MapLen.mapLen(v_m);
        return Arrays.asList(new Object[] {encInt(r0, "i64")});
    }

    static List<Object> case_87(Harness.H h) {
        var v_m = decMap(h.let("m"), r -> decInt(r, "i64"), r -> decInt(r, "i64"));
        var r0 = MapLen.mapLen(v_m);
        return Arrays.asList(new Object[] {encInt(r0, "i64")});
    }

    static List<Object> case_88(Harness.H h) {
        var v_m = decMap(h.let("m"), r -> decInt(r, "i64"), r -> decString(r));
        var v_k = decInt(h.let("k"), "i64");
        Object[] rv = (Object[]) (MapLookup.mapGet(v_m, v_k, GoMap::identityKey, () -> ""));
        var r0 = rv[0];
        var r1 = rv[1];
        return Arrays.asList(new Object[] {encString(r0), encBool(r1)});
    }

    static List<Object> case_89(Harness.H h) {
        var v_m = decMap(h.let("m"), r -> decString(r), r -> decInt(r, "i64"));
        var v_k = decString(h.let("k"));
        Object[] rv = (Object[]) (MapLookup.mapGet(v_m, v_k, GoMap::identityKey, () -> 0L));
        var r0 = rv[0];
        var r1 = rv[1];
        return Arrays.asList(new Object[] {encInt(r0, "i64"), encBool(r1)});
    }

    static List<Object> case_90(Harness.H h) {
        var r0 = MapMake.makeMap(GoMap::identityKey);
        return Arrays.asList(new Object[] {encMap(r0, e -> encString(e), e -> encInt(e, "i64"))});
    }

    static List<Object> case_91(Harness.H h) {
        var v_m = decMap(h.let("m"), r -> decInt(r, "i64"), r -> decInt(r, "i64"));
        var v_k = decInt(h.let("k"), "i64");
        var v_v = decInt(h.let("v"), "i64");
        MapStore.mapSet(v_m, v_k, v_v);
        return Arrays.asList(new Object[] {});
    }

    static List<Object> case_92(Harness.H h) {
        var v_m = decMap(h.let("m"), r -> decInt(r, "i64"), r -> decInt(r, "i64"));
        var v_k = decInt(h.let("k"), "i64");
        var v_v = decInt(h.let("v"), "i64");
        MapStore.mapSet(v_m, v_k, v_v);
        h.after("m", encMap(v_m, e -> encInt(e, "i64"), e -> encInt(e, "i64")));
        return Arrays.asList(new Object[] {});
    }

    static List<Object> case_93(Harness.H h) {
        var v_v = decBool(h.let("v"));
        var r0 = Print.printString(v_v, false);
        return Arrays.asList(new Object[] {encString(r0)});
    }

    static List<Object> case_94(Harness.H h) {
        var v_v = decString(h.let("v"));
        var r0 = Print.printString(v_v, false);
        return Arrays.asList(new Object[] {encString(r0)});
    }

    static List<Object> case_95(Harness.H h) {
        var v_v = decInt(h.let("v"), "i64");
        var r0 = Print.printString(v_v, false);
        return Arrays.asList(new Object[] {encString(r0)});
    }

    static List<Object> case_96(Harness.H h) {
        var v_v = decInt(h.let("v"), "u64");
        var r0 = Print.printString(v_v, true);
        return Arrays.asList(new Object[] {encString(r0)});
    }

    static List<Object> case_97(Harness.H h) {
        var v_a = decChan(h.let("a"), r -> decInt(r, "i64"), () -> 0L);
        var v_b = decChan(h.let("b"), r -> decInt(r, "i64"), () -> 0L);
        var v_dflt = decBool(h.let("dflt"));
        Object[] rv = TaskSpawn.runIsolated(t -> { harnessSelect2(t, v_a, v_b, v_dflt); });
        var r0 = rv[0];
        return Arrays.asList(new Object[] {encInt(r0, "i64")});
    }

    static List<Object> case_98(Harness.H h) {
        var v_a = decChan(h.let("a"), r -> decInt(r, "i64"), () -> 0L);
        var v_b = decChan(h.let("b"), r -> decInt(r, "i64"), () -> 0L);
        var v_dflt = decBool(h.let("dflt"));
        Object[] rv = TaskSpawn.runIsolated(t -> { harnessSelect2(t, v_a, v_b, v_dflt); });
        var r0 = rv[0];
        return Arrays.asList(new Object[] {encInt(r0, "i64")});
    }

    static List<Object> case_99(Harness.H h) {
        var v_a = decChan(h.let("a"), r -> decInt(r, "i64"), () -> 0L);
        var v_b = decChan(h.let("b"), r -> decInt(r, "i64"), () -> 0L);
        var v_dflt = decBool(h.let("dflt"));
        Object[] rv = TaskSpawn.runIsolated(t -> { harnessSelect2(t, v_a, v_b, v_dflt); });
        var r0 = rv[0];
        return Arrays.asList(new Object[] {encInt(r0, "i64")});
    }

    static List<Object> case_100(Harness.H h) {
        var v_a = decChan(h.let("a"), r -> decInt(r, "i64"), () -> 0L);
        var v_b = decChan(h.let("b"), r -> decInt(r, "i64"), () -> 0L);
        var v_dflt = decBool(h.let("dflt"));
        Object[] rv = TaskSpawn.runIsolated(t -> { harnessSelect2(t, v_a, v_b, v_dflt); });
        var r0 = rv[0];
        h.after("b", encChan(v_b, e -> encInt(e, "i64")));
        return Arrays.asList(new Object[] {encInt(r0, "i64")});
    }

    static List<Object> case_101(Harness.H h) {
        var v_s = decSlice(h.let("s"), r -> decString(r), () -> "");
        var v_vs = decSlice(h.let("vs"), r -> decString(r), () -> "");
        var r0 = Slice.zeroAppendGrowth(SliceAppend.appendSlice(v_s, v_vs, null), v_s, () -> "");
        return Arrays.asList(new Object[] {encSlice(r0, e -> encString(e))});
    }

    static List<Object> case_102(Harness.H h) {
        var v_s = decSlice(h.let("s"), r -> decInt(r, "i64"), () -> 0L);
        var v_vs = decSlice(h.let("vs"), r -> decInt(r, "i64"), () -> 0L);
        var r0 = Slice.zeroAppendGrowth(SliceAppend.appendSlice(v_s, v_vs, null), v_s, () -> 0L);
        return Arrays.asList(new Object[] {encSlice(r0, e -> encInt(e, "i64"))});
    }

    static List<Object> case_103(Harness.H h) {
        var v_s = decSlice(h.let("s"), r -> decInt(r, "i64"), () -> 0L);
        var v_vs = decSlice(h.let("vs"), r -> decInt(r, "i64"), () -> 0L);
        var r0 = Slice.zeroAppendGrowth(SliceAppend.appendSlice(v_s, v_vs, null), v_s, () -> 0L);
        return Arrays.asList(new Object[] {encSlice(r0, e -> encInt(e, "i64"))});
    }

    static List<Object> case_104(Harness.H h) {
        var v_s = decSlice(h.let("s"), r -> decInt(r, "i64"), () -> 0L);
        var v_t = view(v_s, h.let("t"));
        var v_vs = decSlice(h.let("vs"), r -> decInt(r, "i64"), () -> 0L);
        var r0 = Slice.zeroAppendGrowth(SliceAppend.appendSlice(v_s, v_vs, null), v_s, () -> 0L);
        h.after("t", encSlice(v_t, e -> encInt(e, "i64")));
        return Arrays.asList(new Object[] {encSlice(r0, e -> encInt(e, "i64"))});
    }

    static List<Object> case_105(Harness.H h) {
        var v_s = decSlice(h.let("s"), r -> decInt(r, "i64"), () -> 0L);
        var v_vs = decSlice(h.let("vs"), r -> decInt(r, "i64"), () -> 0L);
        var r0 = Slice.zeroAppendGrowth(SliceAppend.appendSlice(v_s, v_vs, null), v_s, () -> 0L);
        return Arrays.asList(new Object[] {encSlice(r0, e -> encInt(e, "i64"))});
    }

    static List<Object> case_106(Harness.H h) {
        var v_s = decSlice(h.let("s"), r -> decInt(r, "i64"), () -> 0L);
        var v_a = view(v_s, h.let("a"));
        var v_vs = view(v_s, h.let("vs"));
        var r0 = Slice.zeroAppendGrowth(SliceAppend.appendSlice(v_a, v_vs, null), v_a, () -> 0L);
        h.after("s", encSlice(v_s, e -> encInt(e, "i64")));
        return Arrays.asList(new Object[] {encSlice(r0, e -> encInt(e, "i64"))});
    }

    static List<Object> case_107(Harness.H h) {
        var v_s = decSlice(h.let("s"), r -> decInt(r, "i64"), () -> 0L);
        var v_t = view(v_s, h.let("t"));
        SliceClear.clearSlice(v_t, () -> 0L);
        h.after("s", encSlice(v_s, e -> encInt(e, "i64")));
        return Arrays.asList(new Object[] {});
    }

    static List<Object> case_108(Harness.H h) {
        var v_s = decSlice(h.let("s"), r -> decInt(r, "i64"), () -> 0L);
        var v_d = view(v_s, h.let("d"));
        var v_src = view(v_s, h.let("src"));
        var r0 = SliceCopy.copy(v_d, v_src, null);
        h.after("s", encSlice(v_s, e -> encInt(e, "i64")));
        return Arrays.asList(new Object[] {encInt(r0, "i64")});
    }

    static List<Object> case_109(Harness.H h) {
        var v_d = decBytes(h.let("d"));
        var v_src = decBytes(h.let("src"));
        var r0 = SliceCopy.copy(v_d, v_src, null);
        h.after("d", encSlice(v_d, e -> encInt(e, "u8")));
        return Arrays.asList(new Object[] {encInt(r0, "i64")});
    }

    static List<Object> case_110(Harness.H h) {
        var v_s = decSlice(h.let("s"), r -> decInt(r, "i64"), () -> 0L);
        var v_i = decInt(h.let("i"), "i64");
        var r0 = SliceIndex.sget(v_s, v_i);
        return Arrays.asList(new Object[] {encInt(r0, "i64")});
    }

    static List<Object> case_111(Harness.H h) {
        var v_s = decSlice(h.let("s"), r -> decInt(r, "i64"), () -> 0L);
        var v_i = decInt(h.let("i"), "i64");
        var r0 = SliceIndex.sget(v_s, v_i);
        return Arrays.asList(new Object[] {encInt(r0, "i64")});
    }

    static List<Object> case_112(Harness.H h) {
        var v_s = decSlice(h.let("s"), r -> decString(r), () -> "");
        var v_i = decInt(h.let("i"), "i64");
        var r0 = SliceIndex.sget(v_s, v_i);
        return Arrays.asList(new Object[] {encString(r0)});
    }

    static List<Object> case_113(Harness.H h) {
        var v_len = decInt(h.let("len"), "i64");
        var v_cap = decInt(h.let("cap"), "i64");
        var r0 = SliceMake.makeSlice(v_len, v_cap, () -> 0L, false);
        return Arrays.asList(new Object[] {encSlice(r0, e -> encInt(e, "i64"))});
    }

    static List<Object> case_114(Harness.H h) {
        var v_len = decInt(h.let("len"), "i64");
        var v_cap = decInt(h.let("cap"), "i64");
        var r0 = SliceMake.makeSlice(v_len, v_cap, () -> 0L, true);
        return Arrays.asList(new Object[] {encSlice(r0, e -> encInt(e, "u8"))});
    }

    static List<Object> case_115(Harness.H h) {
        var v_len = decInt(h.let("len"), "i64");
        var v_cap = decInt(h.let("cap"), "i64");
        var r0 = SliceMake.makeSlice(v_len, v_cap, () -> 0L, false);
        return Arrays.asList(new Object[] {encSlice(r0, e -> encInt(e, "i64"))});
    }

    static List<Object> case_116(Harness.H h) {
        var v_s = decSlice(h.let("s"), r -> decInt(r, "i64"), () -> 0L);
        var v_lo = decInt(h.let("lo"), "i64");
        var v_hi = decInt(h.let("hi"), "i64");
        var v_max = decInt(h.let("max"), "i64");
        var r0 = SliceSlice.reslice(v_s, v_lo, v_hi, v_max, false);
        return Arrays.asList(new Object[] {encSlice(r0, e -> encInt(e, "i64"))});
    }

    static List<Object> case_117(Harness.H h) {
        var v_s = decSlice(h.let("s"), r -> decInt(r, "i64"), () -> 0L);
        var v_lo = decInt(h.let("lo"), "i64");
        var v_hi = decInt(h.let("hi"), "i64");
        var v_max = decInt(h.let("max"), "i64");
        var r0 = SliceSlice.reslice(v_s, v_lo, v_hi, v_max, false);
        return Arrays.asList(new Object[] {encSlice(r0, e -> encInt(e, "i64"))});
    }

    static List<Object> case_118(Harness.H h) {
        var v_s = decSlice(h.let("s"), r -> decInt(r, "i64"), () -> 0L);
        var v_lo = decInt(h.let("lo"), "i64");
        var v_hi = decInt(h.let("hi"), "i64");
        var v_max = decInt(h.let("max"), "i64");
        var r0 = SliceSlice.reslice(v_s, v_lo, v_hi, v_max, false);
        return Arrays.asList(new Object[] {encSlice(r0, e -> encInt(e, "i64"))});
    }

    static List<Object> case_119(Harness.H h) {
        var v_s = decSlice(h.let("s"), r -> decInt(r, "i64"), () -> 0L);
        var v_lo = decInt(h.let("lo"), "i64");
        var v_hi = decInt(h.let("hi"), "i64");
        var v_max = decInt(h.let("max"), "i64");
        var r0 = SliceSlice.reslice(v_s, v_lo, v_hi, v_max, false);
        return Arrays.asList(new Object[] {encSlice(r0, e -> encInt(e, "i64"))});
    }

    static List<Object> case_120(Harness.H h) {
        var v_s = decSlice(h.let("s"), r -> decInt(r, "i64"), () -> 0L);
        var v_lo = decInt(h.let("lo"), "i64");
        var v_hi = decInt(h.let("hi"), "i64");
        var v_max = decInt(h.let("max"), "i64");
        var r0 = SliceSlice.reslice(v_s, v_lo, v_hi, v_max, false);
        return Arrays.asList(new Object[] {encSlice(r0, e -> encInt(e, "i64"))});
    }

    static List<Object> case_121(Harness.H h) {
        var v_s = decSlice(h.let("s"), r -> decInt(r, "i64"), () -> 0L);
        var v_t = view(v_s, h.let("t"));
        var v_i = decInt(h.let("i"), "i64");
        var v_v = decInt(h.let("v"), "i64");
        SliceStore.sset(v_t, v_i, v_v);
        h.after("s", encSlice(v_s, e -> encInt(e, "i64")));
        return Arrays.asList(new Object[] {});
    }

    static List<Object> case_122(Harness.H h) {
        var v_s = decSlice(h.let("s"), r -> decInt(r, "i64"), () -> 0L);
        var v_i = decInt(h.let("i"), "i64");
        var v_v = decInt(h.let("v"), "i64");
        SliceStore.sset(v_s, v_i, v_v);
        return Arrays.asList(new Object[] {});
    }

    static List<Object> case_123(Harness.H h) {
        var v_s = decSlice(h.let("s"), r -> decInt(r, "i64"), () -> 0L);
        var r0 = SliceToArray.sliceToArray(v_s, 2, null);
        return Arrays.asList(new Object[] {encArray(r0, e -> encInt(e, "i64"))});
    }

    static List<Object> case_124(Harness.H h) {
        var v_s = decSlice(h.let("s"), r -> decInt(r, "i64"), () -> 0L);
        var r0 = SliceToArray.sliceToArray(v_s, 2, null);
        return Arrays.asList(new Object[] {encArray(r0, e -> encInt(e, "i64"))});
    }

    static List<Object> case_125(Harness.H h) {
        var v_a = decString(h.let("a"));
        var v_b = decString(h.let("b"));
        var r0 = StringCompare.scompare(v_a, v_b);
        return Arrays.asList(new Object[] {encInt(r0, "i64")});
    }

    static List<Object> case_126(Harness.H h) {
        var v_a = decString(h.let("a"));
        var v_b = decString(h.let("b"));
        var r0 = StringCompare.scompare(v_a, v_b);
        return Arrays.asList(new Object[] {encInt(r0, "i64")});
    }

    static List<Object> case_127(Harness.H h) {
        var v_a = decString(h.let("a"));
        var v_b = decString(h.let("b"));
        var r0 = StringCompare.scompare(v_a, v_b);
        return Arrays.asList(new Object[] {encInt(r0, "i64")});
    }

    static List<Object> case_128(Harness.H h) {
        var v_a = decString(h.let("a"));
        var v_b = decString(h.let("b"));
        var r0 = StringCompare.scompare(v_a, v_b);
        return Arrays.asList(new Object[] {encInt(r0, "i64")});
    }

    static List<Object> case_129(Harness.H h) {
        var v_a = decString(h.let("a"));
        var v_b = decString(h.let("b"));
        var r0 = StringConcat.concat(v_a, v_b);
        return Arrays.asList(new Object[] {encString(r0)});
    }

    static List<Object> case_130(Harness.H h) {
        var v_a = decString(h.let("a"));
        var v_b = decString(h.let("b"));
        var r0 = StringConcat.concat(v_a, v_b);
        return Arrays.asList(new Object[] {encString(r0)});
    }

    static List<Object> case_131(Harness.H h) {
        var v_s = decString(h.let("s"));
        var v_i = decInt(h.let("i"), "i64");
        Object[] rv = (Object[]) (StringDecodeRune.decodeRune(v_s, v_i));
        var r0 = rv[0];
        var r1 = rv[1];
        return Arrays.asList(new Object[] {encInt(r0, "i32"), encInt(r1, "i64")});
    }

    static List<Object> case_132(Harness.H h) {
        var v_s = decString(h.let("s"));
        var v_i = decInt(h.let("i"), "i64");
        Object[] rv = (Object[]) (StringDecodeRune.decodeRune(v_s, v_i));
        var r0 = rv[0];
        var r1 = rv[1];
        return Arrays.asList(new Object[] {encInt(r0, "i32"), encInt(r1, "i64")});
    }

    static List<Object> case_133(Harness.H h) {
        var v_s = decString(h.let("s"));
        var v_i = decInt(h.let("i"), "i64");
        Object[] rv = (Object[]) (StringDecodeRune.decodeRune(v_s, v_i));
        var r0 = rv[0];
        var r1 = rv[1];
        return Arrays.asList(new Object[] {encInt(r0, "i32"), encInt(r1, "i64")});
    }

    static List<Object> case_134(Harness.H h) {
        var v_s = decString(h.let("s"));
        var v_i = decInt(h.let("i"), "i64");
        Object[] rv = (Object[]) (StringDecodeRune.decodeRune(v_s, v_i));
        var r0 = rv[0];
        var r1 = rv[1];
        return Arrays.asList(new Object[] {encInt(r0, "i32"), encInt(r1, "i64")});
    }

    static List<Object> case_135(Harness.H h) {
        var v_s = decString(h.let("s"));
        var v_i = decInt(h.let("i"), "i64");
        Object[] rv = (Object[]) (StringDecodeRune.decodeRune(v_s, v_i));
        var r0 = rv[0];
        var r1 = rv[1];
        return Arrays.asList(new Object[] {encInt(r0, "i32"), encInt(r1, "i64")});
    }

    static List<Object> case_136(Harness.H h) {
        var v_s = decString(h.let("s"));
        var v_i = decInt(h.let("i"), "i64");
        Object[] rv = (Object[]) (StringDecodeRune.decodeRune(v_s, v_i));
        var r0 = rv[0];
        var r1 = rv[1];
        return Arrays.asList(new Object[] {encInt(r0, "i32"), encInt(r1, "i64")});
    }

    static List<Object> case_137(Harness.H h) {
        var v_s = decString(h.let("s"));
        var v_i = decInt(h.let("i"), "i64");
        Object[] rv = (Object[]) (StringDecodeRune.decodeRune(v_s, v_i));
        var r0 = rv[0];
        var r1 = rv[1];
        return Arrays.asList(new Object[] {encInt(r0, "i32"), encInt(r1, "i64")});
    }

    static List<Object> case_138(Harness.H h) {
        var v_b = decBytes(h.let("b"));
        var r0 = StringFromBytes.fromBytes(v_b);
        return Arrays.asList(new Object[] {encString(r0)});
    }

    static List<Object> case_139(Harness.H h) {
        var v_b = decBytes(h.let("b"));
        var r0 = StringFromBytes.fromBytes(v_b);
        return Arrays.asList(new Object[] {encString(r0)});
    }

    static List<Object> case_140(Harness.H h) {
        var v_r = decInt(h.let("r"), "i32");
        var r0 = StringFromRune.fromRune(v_r);
        return Arrays.asList(new Object[] {encString(r0)});
    }

    static List<Object> case_141(Harness.H h) {
        var v_r = decInt(h.let("r"), "i64");
        var r0 = StringFromRune.fromRune(v_r);
        return Arrays.asList(new Object[] {encString(r0)});
    }

    static List<Object> case_142(Harness.H h) {
        var v_r = decInt(h.let("r"), "i8");
        var r0 = StringFromRune.fromRune(v_r);
        return Arrays.asList(new Object[] {encString(r0)});
    }

    static List<Object> case_143(Harness.H h) {
        var v_r = decInt(h.let("r"), "i64");
        var r0 = StringFromRune.fromRune(v_r);
        return Arrays.asList(new Object[] {encString(r0)});
    }

    static List<Object> case_144(Harness.H h) {
        var v_r = decSlice(h.let("r"), r -> decInt(r, "i32"), () -> 0L);
        var r0 = StringFromRunes.fromRunes(v_r);
        return Arrays.asList(new Object[] {encString(r0)});
    }

    static List<Object> case_145(Harness.H h) {
        var v_r = decSlice(h.let("r"), r -> decInt(r, "i32"), () -> 0L);
        var r0 = StringFromRunes.fromRunes(v_r);
        return Arrays.asList(new Object[] {encString(r0)});
    }

    static List<Object> case_146(Harness.H h) {
        var v_s = decString(h.let("s"));
        var v_i = decInt(h.let("i"), "i64");
        var r0 = StringIndex.sindex(v_s, v_i);
        return Arrays.asList(new Object[] {encInt(r0, "u8")});
    }

    static List<Object> case_147(Harness.H h) {
        var v_s = decString(h.let("s"));
        var v_i = decInt(h.let("i"), "i64");
        var r0 = StringIndex.sindex(v_s, v_i);
        return Arrays.asList(new Object[] {encInt(r0, "u8")});
    }

    static List<Object> case_148(Harness.H h) {
        var v_s = decString(h.let("s"));
        var v_i = decInt(h.let("i"), "i64");
        var r0 = StringIndex.sindex(v_s, v_i);
        return Arrays.asList(new Object[] {encInt(r0, "u8")});
    }

    static List<Object> case_149(Harness.H h) {
        var v_s = decString(h.let("s"));
        var v_i = decInt(h.let("i"), "u64");
        var r0 = StringIndex.sindexu(v_s, v_i);
        return Arrays.asList(new Object[] {encInt(r0, "u8")});
    }

    static List<Object> case_150(Harness.H h) {
        var v_s = decString(h.let("s"));
        var v_lo = decInt(h.let("lo"), "i64");
        var v_hi = decInt(h.let("hi"), "i64");
        var r0 = StringSlice.sslice(v_s, v_lo, v_hi, false);
        return Arrays.asList(new Object[] {encString(r0)});
    }

    static List<Object> case_151(Harness.H h) {
        var v_s = decString(h.let("s"));
        var v_lo = decInt(h.let("lo"), "i64");
        var v_hi = decInt(h.let("hi"), "i64");
        var r0 = StringSlice.sslice(v_s, v_lo, v_hi, false);
        return Arrays.asList(new Object[] {encString(r0)});
    }

    static List<Object> case_152(Harness.H h) {
        var v_s = decString(h.let("s"));
        var v_lo = decInt(h.let("lo"), "i64");
        var v_hi = decInt(h.let("hi"), "i64");
        var r0 = StringSlice.sslice(v_s, v_lo, v_hi, false);
        return Arrays.asList(new Object[] {encString(r0)});
    }

    static List<Object> case_153(Harness.H h) {
        var v_s = decString(h.let("s"));
        var v_lo = decInt(h.let("lo"), "i64");
        var v_hi = decInt(h.let("hi"), "i64");
        var r0 = StringSlice.sslice(v_s, v_lo, v_hi, false);
        return Arrays.asList(new Object[] {encString(r0)});
    }

    static List<Object> case_154(Harness.H h) {
        var v_s = decString(h.let("s"));
        var r0 = StringToBytes.toBytes(v_s);
        return Arrays.asList(new Object[] {encSlice(r0, e -> encInt(e, "u8"))});
    }

    static List<Object> case_155(Harness.H h) {
        var v_s = decString(h.let("s"));
        var r0 = StringToBytes.toBytes(v_s);
        return Arrays.asList(new Object[] {encSlice(r0, e -> encInt(e, "u8"))});
    }

    static List<Object> case_156(Harness.H h) {
        var v_s = decString(h.let("s"));
        var r0 = StringToRunes.toRunes(v_s);
        return Arrays.asList(new Object[] {encSlice(r0, e -> encInt(e, "i32"))});
    }

    static List<Object> case_157(Harness.H h) {
        Object[] rv = TaskSpawn.runIsolated(t -> { TaskSpawn.call(t, newSpawnCheck()); });
        var r0 = rv[0];
        return Arrays.asList(new Object[] {encBool(r0)});
    }

    static List<Object> case_158(Harness.H h) {
        var v_data = decBytes(h.let("data"));
        var r0 = LibChecksumCRC32IEEE.libChecksumCRC32IEEE(v_data);
        return Arrays.asList(new Object[] {encInt(r0, "u32")});
    }

    static List<Object> case_159(Harness.H h) {
        var v_data = decBytes(h.let("data"));
        var r0 = LibChecksumCRC32IEEE.libChecksumCRC32IEEE(v_data);
        return Arrays.asList(new Object[] {encInt(r0, "u32")});
    }

    static List<Object> case_160(Harness.H h) {
        var v_data = decBytes(h.let("data"));
        var r0 = LibChecksumCRC32IEEE.libChecksumCRC32IEEE(v_data);
        return Arrays.asList(new Object[] {encInt(r0, "u32")});
    }

    static List<Object> case_161(Harness.H h) {
        var v_data = decBytes(h.let("data"));
        var r0 = LibChecksumCRC32IEEE.libChecksumCRC32IEEE(v_data);
        return Arrays.asList(new Object[] {encInt(r0, "u32")});
    }

    static List<Object> case_162(Harness.H h) {
        var v_data = decBytes(h.let("data"));
        var r0 = LibChecksumCRC32IEEE.libChecksumCRC32IEEE(v_data);
        return Arrays.asList(new Object[] {encInt(r0, "u32")});
    }

    static List<Object> case_163(Harness.H h) {
        var v_key = decBytes(h.let("key"));
        var v_nonce = decBytes(h.let("nonce"));
        var v_data = decBytes(h.let("data"));
        var v_aad = decBytes(h.let("aad"));
        Object[] rv = host(t -> { LibCryptoAes256GcmDecrypt.libCryptoAes256GcmDecrypt(t, v_key, v_nonce, v_data, v_aad); });
        var r0 = rv[0];
        var r1 = rv[1];
        return Arrays.asList(new Object[] {encSlice(r0, e -> encInt(e, "u8")), encError(r1)});
    }

    static List<Object> case_164(Harness.H h) {
        var v_key = decBytes(h.let("key"));
        var v_nonce = decBytes(h.let("nonce"));
        var v_data = decBytes(h.let("data"));
        var v_aad = decBytes(h.let("aad"));
        Object[] rv = host(t -> { LibCryptoAes256GcmEncrypt.libCryptoAes256GcmEncrypt(t, v_key, v_nonce, v_data, v_aad); });
        var r0 = rv[0];
        var r1 = rv[1];
        return Arrays.asList(new Object[] {encSlice(r0, e -> encInt(e, "u8")), encError(r1)});
    }

    static List<Object> case_165(Harness.H h) {
        var v_key = (Native.Key)null;
        Object[] rv = host(t -> { LibCryptoClose.libCryptoClose(t,v_key); });
        return Arrays.asList(new Object[] {});
    }

    static List<Object> case_166(Harness.H h) {
        var v_private_key = (Native.Key)null;
        var v_public_key = (Native.Key)null;
        Object[] rv = host(t -> { LibCryptoEcdh.libCryptoEcdh(t, v_private_key, v_public_key); });
        var r0 = rv[0];
        var r1 = rv[1];
        return Arrays.asList(new Object[] {encSlice(r0, e -> encInt(e, "u8")), encError(r1)});
    }

    static List<Object> case_167(Harness.H h) {
        var v_key = (Native.Key)null;
        var v_data = decBytes(h.let("data"));
        Object[] rv = host(t -> { LibCryptoEs256Sign.libCryptoEs256Sign(t, v_key, v_data); });
        var r0 = rv[0];
        var r1 = rv[1];
        return Arrays.asList(new Object[] {encSlice(r0, e -> encInt(e, "u8")), encError(r1)});
    }

    static List<Object> case_168(Harness.H h) {
        var v_key = (Native.Key)null;
        var v_data = decBytes(h.let("data"));
        var v_signature = decBytes(h.let("signature"));
        Object[] rv = host(t -> { LibCryptoEs256Verify.libCryptoEs256Verify(t, v_key, v_data, v_signature); });
        var r0 = rv[0];
        var r1 = rv[1];
        return Arrays.asList(new Object[] {encBool(r0), encError(r1)});
    }

    static List<Object> case_169(Harness.H h) {
        var v_key = (Native.Key)null;
        var v_data = decBytes(h.let("data"));
        Object[] rv = host(t -> { LibCryptoEs384Sign.libCryptoEs384Sign(t, v_key, v_data); });
        var r0 = rv[0];
        var r1 = rv[1];
        return Arrays.asList(new Object[] {encSlice(r0, e -> encInt(e, "u8")), encError(r1)});
    }

    static List<Object> case_170(Harness.H h) {
        var v_key = (Native.Key)null;
        var v_data = decBytes(h.let("data"));
        var v_signature = decBytes(h.let("signature"));
        Object[] rv = host(t -> { LibCryptoEs384Verify.libCryptoEs384Verify(t, v_key, v_data, v_signature); });
        var r0 = rv[0];
        var r1 = rv[1];
        return Arrays.asList(new Object[] {encBool(r0), encError(r1)});
    }

    static List<Object> case_171(Harness.H h) {
        var v_key = (Native.Key)null;
        var v_data = decBytes(h.let("data"));
        Object[] rv = host(t -> { LibCryptoEs512Sign.libCryptoEs512Sign(t, v_key, v_data); });
        var r0 = rv[0];
        var r1 = rv[1];
        return Arrays.asList(new Object[] {encSlice(r0, e -> encInt(e, "u8")), encError(r1)});
    }

    static List<Object> case_172(Harness.H h) {
        var v_key = (Native.Key)null;
        var v_data = decBytes(h.let("data"));
        var v_signature = decBytes(h.let("signature"));
        Object[] rv = host(t -> { LibCryptoEs512Verify.libCryptoEs512Verify(t, v_key, v_data, v_signature); });
        var r0 = rv[0];
        var r1 = rv[1];
        return Arrays.asList(new Object[] {encBool(r0), encError(r1)});
    }

    static List<Object> case_173(Harness.H h) {
        var v_secret = decBytes(h.let("secret"));
        var v_salt = decBytes(h.let("salt"));
        var v_info = decBytes(h.let("info"));
        var v_n = decInt(h.let("n"), "i64");
        Object[] rv = host(t -> { LibCryptoHkdfSha256.libCryptoHkdfSha256(t, v_secret, v_salt, v_info, v_n); });
        var r0 = rv[0];
        var r1 = rv[1];
        return Arrays.asList(new Object[] {encSlice(r0, e -> encInt(e, "u8")), encError(r1)});
    }

    static List<Object> case_174(Harness.H h) {
        var v_key = decBytes(h.let("key"));
        var v_data = decBytes(h.let("data"));
        Object[] rv = host(t -> { LibCryptoHmacSha256.libCryptoHmacSha256(t, v_key, v_data); });
        var r0 = rv[0];
        var r1 = rv[1];
        return Arrays.asList(new Object[] {encSlice(r0, e -> encInt(e, "u8")), encError(r1)});
    }

    static List<Object> case_175(Harness.H h) {
        var v_key = decBytes(h.let("key"));
        var v_data = decBytes(h.let("data"));
        var v_mac = decBytes(h.let("mac"));
        Object[] rv = host(t -> { LibCryptoHmacSha256Verify.libCryptoHmacSha256Verify(t, v_key, v_data, v_mac); });
        var r0 = rv[0];
        var r1 = rv[1];
        return Arrays.asList(new Object[] {encBool(r0), encError(r1)});
    }

    static List<Object> case_176(Harness.H h) {
        var v_data = decString(h.let("data"));
        Object[] rv = host(t -> { LibCryptoImportPem.libCryptoImportPem(t, v_data); });
        var r0 = rv[0];
        var r1 = rv[1];
        return Arrays.asList(new Object[] {encKey(r0), encError(r1)});
    }

    static List<Object> case_177(Harness.H h) {
        var v_key = (Native.Key)null;
        Object[] rv = host(t -> { LibCryptoPrivatePem.libCryptoPrivatePem(t, v_key); });
        var r0 = rv[0];
        var r1 = rv[1];
        return Arrays.asList(new Object[] {encString(r0), encError(r1)});
    }

    static List<Object> case_178(Harness.H h) {
        var v_key = (Native.Key)null;
        Object[] rv = host(t -> { LibCryptoPublicJwk.libCryptoPublicJwk(t, v_key); });
        var r0 = rv[0];
        var r1 = rv[1];
        return Arrays.asList(new Object[] {encSlice(r0, e -> encString(e)), encError(r1)});
    }

    static List<Object> case_179(Harness.H h) {
        var v_key = (Native.Key)null;
        Object[] rv = host(t -> { LibCryptoPublicPem.libCryptoPublicPem(t, v_key); });
        var r0 = rv[0];
        var r1 = rv[1];
        return Arrays.asList(new Object[] {encString(r0), encError(r1)});
    }

    static List<Object> case_180(Harness.H h) {
        var v_n = decInt(h.let("n"), "i64");
        Object[] rv = host(t -> { LibCryptoRandom.libCryptoRandom(t, v_n); });
        var r0 = rv[0];
        var r1 = rv[1];
        return Arrays.asList(new Object[] {encSlice(r0, e -> encInt(e, "u8")), encError(r1)});
    }

    static List<Object> case_181(Harness.H h) {
        var v_key = (Native.Key)null;
        var v_data = decBytes(h.let("data"));
        Object[] rv = host(t -> { LibCryptoRs256Sign.libCryptoRs256Sign(t, v_key, v_data); });
        var r0 = rv[0];
        var r1 = rv[1];
        return Arrays.asList(new Object[] {encSlice(r0, e -> encInt(e, "u8")), encError(r1)});
    }

    static List<Object> case_182(Harness.H h) {
        var v_key = (Native.Key)null;
        var v_data = decBytes(h.let("data"));
        var v_signature = decBytes(h.let("signature"));
        Object[] rv = host(t -> { LibCryptoRs256Verify.libCryptoRs256Verify(t, v_key, v_data, v_signature); });
        var r0 = rv[0];
        var r1 = rv[1];
        return Arrays.asList(new Object[] {encBool(r0), encError(r1)});
    }

    static List<Object> case_183(Harness.H h) {
        var v_key = (Native.Key)null;
        var v_data = decBytes(h.let("data"));
        Object[] rv = host(t -> { LibCryptoRs384Sign.libCryptoRs384Sign(t, v_key, v_data); });
        var r0 = rv[0];
        var r1 = rv[1];
        return Arrays.asList(new Object[] {encSlice(r0, e -> encInt(e, "u8")), encError(r1)});
    }

    static List<Object> case_184(Harness.H h) {
        var v_key = (Native.Key)null;
        var v_data = decBytes(h.let("data"));
        var v_signature = decBytes(h.let("signature"));
        Object[] rv = host(t -> { LibCryptoRs384Verify.libCryptoRs384Verify(t, v_key, v_data, v_signature); });
        var r0 = rv[0];
        var r1 = rv[1];
        return Arrays.asList(new Object[] {encBool(r0), encError(r1)});
    }

    static List<Object> case_185(Harness.H h) {
        var v_key = (Native.Key)null;
        var v_data = decBytes(h.let("data"));
        Object[] rv = host(t -> { LibCryptoRs512Sign.libCryptoRs512Sign(t, v_key, v_data); });
        var r0 = rv[0];
        var r1 = rv[1];
        return Arrays.asList(new Object[] {encSlice(r0, e -> encInt(e, "u8")), encError(r1)});
    }

    static List<Object> case_186(Harness.H h) {
        var v_key = (Native.Key)null;
        var v_data = decBytes(h.let("data"));
        var v_signature = decBytes(h.let("signature"));
        Object[] rv = host(t -> { LibCryptoRs512Verify.libCryptoRs512Verify(t, v_key, v_data, v_signature); });
        var r0 = rv[0];
        var r1 = rv[1];
        return Arrays.asList(new Object[] {encBool(r0), encError(r1)});
    }

    static List<Object> case_187(Harness.H h) {
        var v_key = (Native.Key)null;
        var v_data = decBytes(h.let("data"));
        Object[] rv = host(t -> { LibCryptoRsaOaepDecrypt.libCryptoRsaOaepDecrypt(t, v_key, v_data); });
        var r0 = rv[0];
        var r1 = rv[1];
        return Arrays.asList(new Object[] {encSlice(r0, e -> encInt(e, "u8")), encError(r1)});
    }

    static List<Object> case_188(Harness.H h) {
        var v_key = (Native.Key)null;
        var v_data = decBytes(h.let("data"));
        Object[] rv = host(t -> { LibCryptoRsaOaepEncrypt.libCryptoRsaOaepEncrypt(t, v_key, v_data); });
        var r0 = rv[0];
        var r1 = rv[1];
        return Arrays.asList(new Object[] {encSlice(r0, e -> encInt(e, "u8")), encError(r1)});
    }

    static List<Object> case_189(Harness.H h) {
        var v_data = decBytes(h.let("data"));
        Object[] rv = host(t -> { LibCryptoSha256.libCryptoSha256(t, v_data); });
        var r0 = rv[0];
        var r1 = rv[1];
        return Arrays.asList(new Object[] {encSlice(r0, e -> encInt(e, "u8")), encError(r1)});
    }

    static List<Object> case_190(Harness.H h) {
        var v_data = decString(h.let("data"));
        Object[] rv = (Object[]) (LibEncodingBase64Decode.libEncodingBase64Decode(v_data));
        var r0 = rv[0];
        var r1 = rv[1];
        return Arrays.asList(new Object[] {encSlice(r0, e -> encInt(e, "u8")), encError(r1)});
    }

    static List<Object> case_191(Harness.H h) {
        var v_data = decBytes(h.let("data"));
        Object[] rv = (Object[]) (LibEncodingBase64Encode.libEncodingBase64Encode(v_data));
        var r0 = rv[0];
        var r1 = rv[1];
        return Arrays.asList(new Object[] {encString(r0), encError(r1)});
    }

    static List<Object> case_192(Harness.H h) {
        var v_data = decString(h.let("data"));
        Object[] rv = (Object[]) (LibEncodingBase64UrlDecode.libEncodingBase64UrlDecode(v_data));
        var r0 = rv[0];
        var r1 = rv[1];
        return Arrays.asList(new Object[] {encSlice(r0, e -> encInt(e, "u8")), encError(r1)});
    }

    static List<Object> case_193(Harness.H h) {
        var v_data = decBytes(h.let("data"));
        Object[] rv = (Object[]) (LibEncodingBase64UrlEncode.libEncodingBase64UrlEncode(v_data));
        var r0 = rv[0];
        var r1 = rv[1];
        return Arrays.asList(new Object[] {encString(r0), encError(r1)});
    }

    static List<Object> case_194(Harness.H h) {
        var v_ctx = StdContextBackground.stdContextBackground();
        var v_method = decString(h.let("method"));
        var v_url = decString(h.let("url"));
        var v_headers = decSlice(h.let("headers"), r -> decString(r), () -> "");
        var v_body = decBytes(h.let("body"));
        var v_max_response_bytes = decInt(h.let("max_response_bytes"), "i64");
        var v_timeout_millis = decInt(h.let("timeout_millis"), "i64");
        Object[] rv = host(t -> { LibHttpDo.libHttpDo(t,v_ctx,v_method,v_url,v_headers,v_body,v_max_response_bytes,v_timeout_millis); });
        var r0 = rv[0];
        var r1 = rv[1];
        var r2 = rv[2];
        var r3 = rv[3];
        return Arrays.asList(new Object[] {encInt(r0, "i64"), encSlice(r1, e -> encString(e)), encSlice(r2, e -> encInt(e, "u8")), encError(r3)});
    }

    static List<Object> case_195(Harness.H h) {
        var v_level = decInt(h.let("level"), "i64");
        var r0 = LibLogEnabled.libLogEnabled(v_level);
        return Arrays.asList(new Object[] {encBool(r0)});
    }

    static List<Object> case_196(Harness.H h) {
        var v_level = decInt(h.let("level"), "i64");
        var r0 = LibLogEnabled.libLogEnabled(v_level);
        return Arrays.asList(new Object[] {encBool(r0)});
    }

    static List<Object> case_197(Harness.H h) {
        var v_level = decInt(h.let("level"), "i64");
        var r0 = LibLogEnabled.libLogEnabled(v_level);
        return Arrays.asList(new Object[] {encBool(r0)});
    }

    static List<Object> case_198(Harness.H h) {
        var v_level = decInt(h.let("level"), "i64");
        var r0 = LibLogEnabled.libLogEnabled(v_level);
        return Arrays.asList(new Object[] {encBool(r0)});
    }

    static List<Object> case_199(Harness.H h) {
        var v_fns = decSlice(h.let("fns"), r -> (Fn) null, () -> null);
        Object[] rv = TaskSpawn.runIsolated(t -> { LibTaskAll.libTaskAll(t, v_fns); });
        return Arrays.asList(new Object[] {});
    }

    static List<Object> case_200(Harness.H h) {
        var r0 = StdContextBackground.stdContextBackground();
        return Arrays.asList(new Object[] {encZero(r0)});
    }

    static List<Object> case_201(Harness.H h) {
        var r0 = StdContextCanceled.stdContextCanceled();
        return Arrays.asList(new Object[] {encError(r0)});
    }

    static List<Object> case_202(Harness.H h) {
        var r0 = StdContextDeadlineExceeded.stdContextDeadlineExceeded();
        return Arrays.asList(new Object[] {encError(r0)});
    }

    static List<Object> case_203(Harness.H h) {
        var v_ctx = StdContextBackground.stdContextBackground();
        var r0 = StdContextDone.stdContextContextDone(v_ctx);
        return Arrays.asList(new Object[] {encChan(r0, e -> encZero(e))});
    }

    static List<Object> case_204(Harness.H h) {
        var v_ctx = StdContextBackground.stdContextBackground();
        var r0 = StdContextErr.stdContextContextErr(v_ctx);
        return Arrays.asList(new Object[] {encError(r0)});
    }

    static List<Object> case_205(Harness.H h) {
        var v_parent = StdContextBackground.stdContextBackground();
        Object[] rv = (Object[]) (StdContextWithCancel.stdContextWithCancel(v_parent));
        var r0 = rv[0];
        var r1 = rv[1];
        return Arrays.asList(new Object[] {encZero(r0), encZero(r1)});
    }

    static List<Object> case_206(Harness.H h) {
        var v_parent = StdContextBackground.stdContextBackground();
        var v_d = decInt(h.let("d"), "i64");
        Object[] rv = (Object[]) (StdContextWithTimeout.stdContextWithTimeout(v_parent, v_d));
        var r0 = rv[0];
        var r1 = rv[1];
        return Arrays.asList(new Object[] {encZero(r0), encZero(r1)});
    }

    static List<Object> case_207(Harness.H h) {
        var v_err = decError(h.let("err"));
        var v_target = decError(h.let("target"));
        var r0 = StdErrorsIs.stdErrorsIs(v_err, v_target);
        return Arrays.asList(new Object[] {encBool(r0)});
    }

    static List<Object> case_208(Harness.H h) {
        var v_err = decError(h.let("err"));
        var v_target = decError(h.let("target"));
        var r0 = StdErrorsIs.stdErrorsIs(v_err, v_target);
        return Arrays.asList(new Object[] {encBool(r0)});
    }

    static List<Object> case_209(Harness.H h) {
        var v_err = decError(h.let("err"));
        var v_target = v_err;
        var r0 = StdErrorsIs.stdErrorsIs(v_err, v_target);
        return Arrays.asList(new Object[] {encBool(r0)});
    }

    static List<Object> case_210(Harness.H h) {
        var v_text = decString(h.let("text"));
        var r0 = StdErrorsNew.stdErrorsNew(v_text);
        return Arrays.asList(new Object[] {encError(r0)});
    }

    static List<Object> case_211(Harness.H h) {
        var v_err = decError(h.let("err"));
        var r0 = StdErrorsUnwrap.stdErrorsUnwrap(v_err);
        return Arrays.asList(new Object[] {encError(r0)});
    }

    static List<Object> case_212(Harness.H h) {
        Object[] rv = TaskSpawn.runIsolated(t -> { StdRuntimeGosched.stdRuntimeGosched(t); });
        return Arrays.asList(new Object[] {});
    }

    static List<Object> case_213(Harness.H h) {
        var v_m = new StdSyncMutexLock.Mutex();
        Object[] rv = TaskSpawn.runIsolated(t -> { StdSyncMutexLock.stdSyncMutexLock(t, v_m); });
        return Arrays.asList(new Object[] {});
    }

    static List<Object> case_214(Harness.H h) {
        var v_m = new StdSyncMutexLock.Mutex();
        Object[] rv = TaskSpawn.runIsolated(t -> { StdSyncMutexLock.stdSyncMutexLock(t, v_m); StdSyncMutexUnlock.stdSyncMutexUnlock(v_m); });
        return Arrays.asList(new Object[] {});
    }

    static List<Object> case_215(Harness.H h) {
        var v_wg = new StdSyncWaitgroupAdd.WaitGroup();
        var v_delta = decInt(h.let("delta"), "i64");
        StdSyncWaitgroupAdd.stdSyncWaitgroupAdd(v_wg, v_delta);
        return Arrays.asList(new Object[] {});
    }

    static List<Object> case_216(Harness.H h) {
        var v_wg = new StdSyncWaitgroupAdd.WaitGroup();
        var v_delta = decInt(h.let("delta"), "i64");
        StdSyncWaitgroupAdd.stdSyncWaitgroupAdd(v_wg, v_delta);
        return Arrays.asList(new Object[] {});
    }

    static List<Object> case_217(Harness.H h) {
        var v_wg = new StdSyncWaitgroupAdd.WaitGroup();
        StdSyncWaitgroupDone.stdSyncWaitgroupDone(v_wg);
        return Arrays.asList(new Object[] {});
    }

    static List<Object> case_218(Harness.H h) {
        var v_wg = new StdSyncWaitgroupAdd.WaitGroup();
        Object[] rv = TaskSpawn.runIsolated(t -> { StdSyncWaitgroupWait.stdSyncWaitgroupWait(t, v_wg); });
        return Arrays.asList(new Object[] {});
    }

    static List<Object> case_219(Harness.H h) {
        var v_d = decInt(h.let("d"), "i64");
        Object[] rv = TaskSpawn.runIsolated(t -> { StdTimeSleep.stdTimeSleep(t, v_d); });
        return Arrays.asList(new Object[] {});
    }

    static final Map<String, Harness.Case> CASES = new HashMap<>();

    static {
        CASES.put("core.chan.cap/three", HarnessGen::case_0);
        CASES.put("core.chan.close/nil", HarnessGen::case_1);
        CASES.put("core.chan.close/open", HarnessGen::case_2);
        CASES.put("core.chan.close/twice", HarnessGen::case_3);
        CASES.put("core.chan.len/nil", HarnessGen::case_4);
        CASES.put("core.chan.len/two", HarnessGen::case_5);
        CASES.put("core.chan.make/buffered", HarnessGen::case_6);
        CASES.put("core.chan.make/negative", HarnessGen::case_7);
        CASES.put("core.chan.recv/buffered", HarnessGen::case_8);
        CASES.put("core.chan.recv/closed", HarnessGen::case_9);
        CASES.put("core.chan.recv/drains_before_close", HarnessGen::case_10);
        CASES.put("core.chan.recv/empty_blocks", HarnessGen::case_11);
        CASES.put("core.chan.recv/nil_blocks", HarnessGen::case_12);
        CASES.put("core.chan.send/buffered", HarnessGen::case_13);
        CASES.put("core.chan.send/closed", HarnessGen::case_14);
        CASES.put("core.chan.send/full_blocks", HarnessGen::case_15);
        CASES.put("core.chan.send/nil_blocks", HarnessGen::case_16);
        CASES.put("core.chan.send/unbuffered_blocks", HarnessGen::case_17);
        CASES.put("core.integer.add/int32_plain", HarnessGen::case_18);
        CASES.put("core.integer.add/int64_min", HarnessGen::case_19);
        CASES.put("core.integer.add/int8_wrap", HarnessGen::case_20);
        CASES.put("core.integer.add/int_big", HarnessGen::case_21);
        CASES.put("core.integer.add/uint32_wrap", HarnessGen::case_22);
        CASES.put("core.integer.add/uint64_wrap", HarnessGen::case_23);
        CASES.put("core.integer.and/neg", HarnessGen::case_24);
        CASES.put("core.integer.and/u32", HarnessGen::case_25);
        CASES.put("core.integer.andnot/i64", HarnessGen::case_26);
        CASES.put("core.integer.andnot/u16", HarnessGen::case_27);
        CASES.put("core.integer.compare/equal", HarnessGen::case_28);
        CASES.put("core.integer.compare/signed", HarnessGen::case_29);
        CASES.put("core.integer.compare/u32_high", HarnessGen::case_30);
        CASES.put("core.integer.compare/unsigned_high", HarnessGen::case_31);
        CASES.put("core.integer.convert/narrow_unsigned", HarnessGen::case_32);
        CASES.put("core.integer.convert/same", HarnessGen::case_33);
        CASES.put("core.integer.convert/sign_extend", HarnessGen::case_34);
        CASES.put("core.integer.convert/truncate", HarnessGen::case_35);
        CASES.put("core.integer.convert/u32_to_i32", HarnessGen::case_36);
        CASES.put("core.integer.convert/unsigned_wrap", HarnessGen::case_37);
        CASES.put("core.integer.div/by_zero", HarnessGen::case_38);
        CASES.put("core.integer.div/int64_min_neg1", HarnessGen::case_39);
        CASES.put("core.integer.div/int8_min_neg1", HarnessGen::case_40);
        CASES.put("core.integer.div/trunc_neg", HarnessGen::case_41);
        CASES.put("core.integer.div/trunc_pos", HarnessGen::case_42);
        CASES.put("core.integer.div/uint64_big", HarnessGen::case_43);
        CASES.put("core.integer.mul/int32_neg", HarnessGen::case_44);
        CASES.put("core.integer.mul/int32_wrap", HarnessGen::case_45);
        CASES.put("core.integer.mul/int64_wrap", HarnessGen::case_46);
        CASES.put("core.integer.mul/int8_wrap", HarnessGen::case_47);
        CASES.put("core.integer.mul/uint32_exact", HarnessGen::case_48);
        CASES.put("core.integer.mul/uint64_big", HarnessGen::case_49);
        CASES.put("core.integer.neg/min", HarnessGen::case_50);
        CASES.put("core.integer.neg/plain", HarnessGen::case_51);
        CASES.put("core.integer.neg/u64", HarnessGen::case_52);
        CASES.put("core.integer.neg/unsigned", HarnessGen::case_53);
        CASES.put("core.integer.not/signed", HarnessGen::case_54);
        CASES.put("core.integer.not/u32", HarnessGen::case_55);
        CASES.put("core.integer.not/u8", HarnessGen::case_56);
        CASES.put("core.integer.or/i8", HarnessGen::case_57);
        CASES.put("core.integer.or/u32", HarnessGen::case_58);
        CASES.put("core.integer.rem/by_zero", HarnessGen::case_59);
        CASES.put("core.integer.rem/min_neg1", HarnessGen::case_60);
        CASES.put("core.integer.rem/neg_dividend", HarnessGen::case_61);
        CASES.put("core.integer.rem/neg_divisor", HarnessGen::case_62);
        CASES.put("core.integer.rem/uint", HarnessGen::case_63);
        CASES.put("core.integer.shl/basic", HarnessGen::case_64);
        CASES.put("core.integer.shl/huge", HarnessGen::case_65);
        CASES.put("core.integer.shl/int64_63", HarnessGen::case_66);
        CASES.put("core.integer.shl/negative", HarnessGen::case_67);
        CASES.put("core.integer.shl/overflow_int8", HarnessGen::case_68);
        CASES.put("core.integer.shl/wide", HarnessGen::case_69);
        CASES.put("core.integer.shr/arith", HarnessGen::case_70);
        CASES.put("core.integer.shr/arith_wide", HarnessGen::case_71);
        CASES.put("core.integer.shr/logical", HarnessGen::case_72);
        CASES.put("core.integer.shr/logical_wide", HarnessGen::case_73);
        CASES.put("core.integer.shr/negative", HarnessGen::case_74);
        CASES.put("core.integer.shr/pos_wide", HarnessGen::case_75);
        CASES.put("core.integer.sub/int16_wrap", HarnessGen::case_76);
        CASES.put("core.integer.sub/int_plain", HarnessGen::case_77);
        CASES.put("core.integer.sub/uint8_wrap", HarnessGen::case_78);
        CASES.put("core.integer.sub/uint_wrap", HarnessGen::case_79);
        CASES.put("core.integer.xor/i32", HarnessGen::case_80);
        CASES.put("core.integer.xor/u64", HarnessGen::case_81);
        CASES.put("core.map.clear/all", HarnessGen::case_82);
        CASES.put("core.map.delete/nil_map", HarnessGen::case_83);
        CASES.put("core.map.delete/reinsert_moves", HarnessGen::case_84);
        CASES.put("core.map.iterate/insertion_order", HarnessGen::case_85);
        CASES.put("core.map.len/nil", HarnessGen::case_86);
        CASES.put("core.map.len/two", HarnessGen::case_87);
        CASES.put("core.map.lookup/nil_map", HarnessGen::case_88);
        CASES.put("core.map.lookup/present", HarnessGen::case_89);
        CASES.put("core.map.make/empty", HarnessGen::case_90);
        CASES.put("core.map.store/nil_map", HarnessGen::case_91);
        CASES.put("core.map.store/update_keeps_order", HarnessGen::case_92);
        CASES.put("core.print/bool", HarnessGen::case_93);
        CASES.put("core.print/bytes", HarnessGen::case_94);
        CASES.put("core.print/int", HarnessGen::case_95);
        CASES.put("core.print/u64", HarnessGen::case_96);
        CASES.put("core.select/closed_ready", HarnessGen::case_97);
        CASES.put("core.select/default_when_idle", HarnessGen::case_98);
        CASES.put("core.select/nothing_blocks", HarnessGen::case_99);
        CASES.put("core.select/only_ready", HarnessGen::case_100);
        CASES.put("core.slice.append/from_nil", HarnessGen::case_101);
        CASES.put("core.slice.append/grow_doubles", HarnessGen::case_102);
        CASES.put("core.slice.append/grow_required", HarnessGen::case_103);
        CASES.put("core.slice.append/in_place", HarnessGen::case_104);
        CASES.put("core.slice.append/nil_empty", HarnessGen::case_105);
        CASES.put("core.slice.append/overlap", HarnessGen::case_106);
        CASES.put("core.slice.clear/shared", HarnessGen::case_107);
        CASES.put("core.slice.copy/overlap_forward", HarnessGen::case_108);
        CASES.put("core.slice.copy/short_dst", HarnessGen::case_109);
        CASES.put("core.slice.index/basic", HarnessGen::case_110);
        CASES.put("core.slice.index/beyond_len", HarnessGen::case_111);
        CASES.put("core.slice.index/nil", HarnessGen::case_112);
        CASES.put("core.slice.make/basic", HarnessGen::case_113);
        CASES.put("core.slice.make/cap_lt_len", HarnessGen::case_114);
        CASES.put("core.slice.make/neg_len", HarnessGen::case_115);
        CASES.put("core.slice.slice/hi_gt_max", HarnessGen::case_116);
        CASES.put("core.slice.slice/lo_gt_hi", HarnessGen::case_117);
        CASES.put("core.slice.slice/max_oob", HarnessGen::case_118);
        CASES.put("core.slice.slice/nil_empty", HarnessGen::case_119);
        CASES.put("core.slice.slice/share", HarnessGen::case_120);
        CASES.put("core.slice.store/alias_visible", HarnessGen::case_121);
        CASES.put("core.slice.store/oob", HarnessGen::case_122);
        CASES.put("core.slice.to_array/prefix", HarnessGen::case_123);
        CASES.put("core.slice.to_array/short", HarnessGen::case_124);
        CASES.put("core.string.compare/equal", HarnessGen::case_125);
        CASES.put("core.string.compare/high_byte", HarnessGen::case_126);
        CASES.put("core.string.compare/less", HarnessGen::case_127);
        CASES.put("core.string.compare/prefix", HarnessGen::case_128);
        CASES.put("core.string.concat/basic", HarnessGen::case_129);
        CASES.put("core.string.concat/raw_bytes", HarnessGen::case_130);
        CASES.put("core.string.decode_rune/ascii", HarnessGen::case_131);
        CASES.put("core.string.decode_rune/four", HarnessGen::case_132);
        CASES.put("core.string.decode_rune/invalid", HarnessGen::case_133);
        CASES.put("core.string.decode_rune/overlong", HarnessGen::case_134);
        CASES.put("core.string.decode_rune/surrogate", HarnessGen::case_135);
        CASES.put("core.string.decode_rune/truncated", HarnessGen::case_136);
        CASES.put("core.string.decode_rune/two", HarnessGen::case_137);
        CASES.put("core.string.from_bytes/basic", HarnessGen::case_138);
        CASES.put("core.string.from_bytes/nil", HarnessGen::case_139);
        CASES.put("core.string.from_rune/ascii", HarnessGen::case_140);
        CASES.put("core.string.from_rune/huge", HarnessGen::case_141);
        CASES.put("core.string.from_rune/negative", HarnessGen::case_142);
        CASES.put("core.string.from_rune/surrogate", HarnessGen::case_143);
        CASES.put("core.string.from_runes/basic", HarnessGen::case_144);
        CASES.put("core.string.from_runes/invalid", HarnessGen::case_145);
        CASES.put("core.string.index/first", HarnessGen::case_146);
        CASES.put("core.string.index/negative", HarnessGen::case_147);
        CASES.put("core.string.index/oob", HarnessGen::case_148);
        CASES.put("core.string.index/unsigned_huge", HarnessGen::case_149);
        CASES.put("core.string.slice/hi_oob", HarnessGen::case_150);
        CASES.put("core.string.slice/inverted", HarnessGen::case_151);
        CASES.put("core.string.slice/mid", HarnessGen::case_152);
        CASES.put("core.string.slice/split_rune", HarnessGen::case_153);
        CASES.put("core.string.to_bytes/basic", HarnessGen::case_154);
        CASES.put("core.string.to_bytes/empty", HarnessGen::case_155);
        CASES.put("core.string.to_runes/mixed", HarnessGen::case_156);
        CASES.put("core.task.spawn/parent_continues", HarnessGen::case_157);
        CASES.put("lib.checksum.crc32_ieee/all_bytes", HarnessGen::case_158);
        CASES.put("lib.checksum.crc32_ieee/binary", HarnessGen::case_159);
        CASES.put("lib.checksum.crc32_ieee/check", HarnessGen::case_160);
        CASES.put("lib.checksum.crc32_ieee/empty", HarnessGen::case_161);
        CASES.put("lib.checksum.crc32_ieee/nil", HarnessGen::case_162);
        CASES.put("lib.crypto.aes256_gcm_decrypt/boundary_example", HarnessGen::case_163);
        CASES.put("lib.crypto.aes256_gcm_encrypt/boundary_example", HarnessGen::case_164);
        CASES.put("lib.crypto.close/boundary_example", HarnessGen::case_165);
        CASES.put("lib.crypto.ecdh/boundary_example", HarnessGen::case_166);
        CASES.put("lib.crypto.es256_sign/boundary_example", HarnessGen::case_167);
        CASES.put("lib.crypto.es256_verify/boundary_example", HarnessGen::case_168);
        CASES.put("lib.crypto.es384_sign/boundary_example", HarnessGen::case_169);
        CASES.put("lib.crypto.es384_verify/boundary_example", HarnessGen::case_170);
        CASES.put("lib.crypto.es512_sign/boundary_example", HarnessGen::case_171);
        CASES.put("lib.crypto.es512_verify/boundary_example", HarnessGen::case_172);
        CASES.put("lib.crypto.hkdf_sha256/boundary_example", HarnessGen::case_173);
        CASES.put("lib.crypto.hmac_sha256/boundary_example", HarnessGen::case_174);
        CASES.put("lib.crypto.hmac_sha256_verify/boundary_example", HarnessGen::case_175);
        CASES.put("lib.crypto.import_pem/boundary_example", HarnessGen::case_176);
        CASES.put("lib.crypto.private_pem/boundary_example", HarnessGen::case_177);
        CASES.put("lib.crypto.public_jwk/boundary_example", HarnessGen::case_178);
        CASES.put("lib.crypto.public_pem/boundary_example", HarnessGen::case_179);
        CASES.put("lib.crypto.random/boundary_example", HarnessGen::case_180);
        CASES.put("lib.crypto.rs256_sign/boundary_example", HarnessGen::case_181);
        CASES.put("lib.crypto.rs256_verify/boundary_example", HarnessGen::case_182);
        CASES.put("lib.crypto.rs384_sign/boundary_example", HarnessGen::case_183);
        CASES.put("lib.crypto.rs384_verify/boundary_example", HarnessGen::case_184);
        CASES.put("lib.crypto.rs512_sign/boundary_example", HarnessGen::case_185);
        CASES.put("lib.crypto.rs512_verify/boundary_example", HarnessGen::case_186);
        CASES.put("lib.crypto.rsa_oaep_decrypt/boundary_example", HarnessGen::case_187);
        CASES.put("lib.crypto.rsa_oaep_encrypt/boundary_example", HarnessGen::case_188);
        CASES.put("lib.crypto.sha256/boundary_example", HarnessGen::case_189);
        CASES.put("lib.encoding.base64_decode/boundary_example", HarnessGen::case_190);
        CASES.put("lib.encoding.base64_encode/boundary_example", HarnessGen::case_191);
        CASES.put("lib.encoding.base64_url_decode/boundary_example", HarnessGen::case_192);
        CASES.put("lib.encoding.base64_url_encode/boundary_example", HarnessGen::case_193);
        CASES.put("lib.http.do/boundary_example", HarnessGen::case_194);
        CASES.put("lib.log.enabled/debug_disabled_by_default", HarnessGen::case_195);
        CASES.put("lib.log.enabled/error_enabled_by_default", HarnessGen::case_196);
        CASES.put("lib.log.enabled/info_disabled_by_default", HarnessGen::case_197);
        CASES.put("lib.log.enabled/warn_enabled_by_default", HarnessGen::case_198);
        CASES.put("lib.task.all/empty", HarnessGen::case_199);
        CASES.put("std.context.background/root", HarnessGen::case_200);
        CASES.put("std.context.canceled/message", HarnessGen::case_201);
        CASES.put("std.context.deadline_exceeded/message", HarnessGen::case_202);
        CASES.put("std.context.done/background", HarnessGen::case_203);
        CASES.put("std.context.err/background", HarnessGen::case_204);
        CASES.put("std.context.with_cancel/child", HarnessGen::case_205);
        CASES.put("std.context.with_timeout/child", HarnessGen::case_206);
        CASES.put("std.errors.is/distinct", HarnessGen::case_207);
        CASES.put("std.errors.is/nils", HarnessGen::case_208);
        CASES.put("std.errors.is/same", HarnessGen::case_209);
        CASES.put("std.errors.new/message", HarnessGen::case_210);
        CASES.put("std.errors.unwrap/plain", HarnessGen::case_211);
        CASES.put("std.runtime.gosched/alone", HarnessGen::case_212);
        CASES.put("std.sync.mutex.lock/unlocked", HarnessGen::case_213);
        CASES.put("std.sync.mutex.unlock/lock_then_unlock", HarnessGen::case_214);
        CASES.put("std.sync.waitgroup.add/negative", HarnessGen::case_215);
        CASES.put("std.sync.waitgroup.add/positive", HarnessGen::case_216);
        CASES.put("std.sync.waitgroup.done/underflow", HarnessGen::case_217);
        CASES.put("std.sync.waitgroup.wait/zero_returns", HarnessGen::case_218);
        CASES.put("std.time.sleep/zero", HarnessGen::case_219);
    }
}
