import {generateKeyPairSync,sign}from'node:crypto';
import{mkdtempSync,writeFileSync,rmSync}from'node:fs';
function certificateFor(pem){const dir=mkdtempSync('out/typescript-tdf-library/cert-browser-');try{const file=dir+'/key.pem';writeFileSync(file,pem,{mode:0o600});return execFileSync('openssl',['req','-new','-x509','-key',file,'-subj','/CN=Goalchemy-browser-test','-days','1'],{encoding:'utf8'});}finally{rmSync(dir,{recursive:true});}}
import {createServer}from'node:http';import{readFile,writeFile,mkdir}from'node:fs/promises';import{execFileSync}from'node:child_process';
import{build}from'../../../out/typescript-host-operations/tooling/node_modules/esbuild/lib/main.js';import{chromium}from'../../../out/typescript-host-operations/tooling/node_modules/playwright/index.mjs';
const certificates=['RSA','EC'].map(family=>{const {privateKey}=generateKeyPairSync(family==='RSA'?'rsa':'ec',family==='RSA'?{modulusLength:2048}:{namedCurve:'prime256v1'});const pem=privateKey.export({format:'pem',type:'pkcs8'});return {pem:certificateFor(pem),signature:Array.from(sign('sha256',Uint8Array.from([0,255,128,7]),{key:privateKey,dsaEncoding:'ieee-p1363'}))};});
const emitted=await build({entryPoints:['targets/typescript/tests/crypto_suite.ts'],bundle:true,platform:'browser',format:'esm',write:false,metafile:true});for(const file of Object.keys(emitted.metafile.inputs)){const text=await readFile(file,'utf8');if(/node:|\bBuffer\b|\bprocess\b/.test(text))throw new Error('Node dependency '+file);}await mkdir('out/typescript-tdf-library',{recursive:true});await writeFile('out/typescript-tdf-library/crypto-browser-graph.json',JSON.stringify(emitted.metafile,null,2));
const server=createServer((req,res)=>{res.setHeader('Content-Type',req.url==='/suite.js'?'text/javascript':'text/html');res.end(req.url==='/suite.js'?emitted.outputFiles[0].text:'<script type="module">import{runCryptoSuite}from"/suite.js";window.result=runCryptoSuite('+JSON.stringify(certificates)+');</script>');});await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;
try{let executablePath=process.env.GOALCHEMY_CHROME;for(const name of ['google-chrome','chromium','chromium-browser']){if(executablePath)break;try{executablePath=execFileSync('which',[name],{encoding:'utf8',stdio:['ignore','pipe','ignore']}).trim();}catch{}}
 browser=await chromium.launch({...(executablePath?{executablePath}:{}),headless:true,args:['--no-sandbox']});console.log('Browser',await browser.version());const page=await browser.newPage();await page.goto('http://127.0.0.1:'+server.address().port);for(const name of await page.evaluate(()=>window.result))console.log('PASS browser',name);console.log('PASS portable graph',Object.keys(emitted.metafile.inputs).length,'inputs');}finally{await browser?.close();await new Promise(r=>server.close(r));}
