// Code generated by goalchemy spec generate. DO NOT EDIT.

package main

import (
	"encoding/json"

	rt "github.com/eugenioenko/goalchemy/targets/go/runtime"
)

var _ json.RawMessage

var cases = map[string]func(h *H) []any{
	"core.chan.cap/three": func(h *H) []any {
		v_ch := DecChan(h.Let("ch"), func(r json.RawMessage) int { return DecInt[int](r) })
		_ = v_ch
		r0 := v_ch.Cap()
		return []any{EncInt(r0)}
	},
	"core.chan.close/nil": func(h *H) []any {
		v_ch := DecChan(h.Let("ch"), func(r json.RawMessage) int { return DecInt[int](r) })
		_ = v_ch
		v_ch.Close()
		return []any{}
	},
	"core.chan.close/open": func(h *H) []any {
		v_ch := DecChan(h.Let("ch"), func(r json.RawMessage) int { return DecInt[int](r) })
		_ = v_ch
		v_ch.Close()
		h.After("ch", EncChan(v_ch, func(e int) any { return EncInt(e) }))
		return []any{}
	},
	"core.chan.close/twice": func(h *H) []any {
		v_ch := DecChan(h.Let("ch"), func(r json.RawMessage) int { return DecInt[int](r) })
		_ = v_ch
		v_ch.Close()
		return []any{}
	},
	"core.chan.len/nil": func(h *H) []any {
		v_ch := DecChan(h.Let("ch"), func(r json.RawMessage) int { return DecInt[int](r) })
		_ = v_ch
		r0 := v_ch.Len()
		return []any{EncInt(r0)}
	},
	"core.chan.len/two": func(h *H) []any {
		v_ch := DecChan(h.Let("ch"), func(r json.RawMessage) int { return DecInt[int](r) })
		_ = v_ch
		r0 := v_ch.Len()
		return []any{EncInt(r0)}
	},
	"core.chan.make/buffered": func(h *H) []any {
		v_size := DecInt[int](h.Let("size"))
		_ = v_size
		r0 := rt.MakeChan[int](v_size)
		return []any{EncChan(r0, func(e int) any { return EncInt(e) })}
	},
	"core.chan.make/negative": func(h *H) []any {
		v_size := DecInt[int](h.Let("size"))
		_ = v_size
		r0 := rt.MakeChan[int](v_size)
		return []any{EncChan(r0, func(e int) any { return EncInt(e) })}
	},
	"core.chan.recv/buffered": func(h *H) []any {
		v_ch := DecChan(h.Let("ch"), func(r json.RawMessage) int { return DecInt[int](r) })
		_ = v_ch
		rv := Await(func(t *rt.Task) { v_ch.Recv(t) })
		_ = rv
		r0 := rt.As[int](rv[0])
		r1 := rt.As[bool](rv[1])
		h.After("ch", EncChan(v_ch, func(e int) any { return EncInt(e) }))
		return []any{EncInt(r0), EncBool(r1)}
	},
	"core.chan.recv/closed": func(h *H) []any {
		v_ch := DecChan(h.Let("ch"), func(r json.RawMessage) string { return DecString(r) })
		_ = v_ch
		rv := Await(func(t *rt.Task) { v_ch.Recv(t) })
		_ = rv
		r0 := rt.As[string](rv[0])
		r1 := rt.As[bool](rv[1])
		return []any{EncString(r0), EncBool(r1)}
	},
	"core.chan.recv/drains_before_close": func(h *H) []any {
		v_ch := DecChan(h.Let("ch"), func(r json.RawMessage) int { return DecInt[int](r) })
		_ = v_ch
		rv := Await(func(t *rt.Task) { v_ch.Recv(t) })
		_ = rv
		r0 := rt.As[int](rv[0])
		r1 := rt.As[bool](rv[1])
		return []any{EncInt(r0), EncBool(r1)}
	},
	"core.chan.recv/empty_blocks": func(h *H) []any {
		v_ch := DecChan(h.Let("ch"), func(r json.RawMessage) int { return DecInt[int](r) })
		_ = v_ch
		rv := Await(func(t *rt.Task) { v_ch.Recv(t) })
		_ = rv
		r0 := rt.As[int](rv[0])
		r1 := rt.As[bool](rv[1])
		return []any{EncInt(r0), EncBool(r1)}
	},
	"core.chan.recv/nil_blocks": func(h *H) []any {
		v_ch := DecChan(h.Let("ch"), func(r json.RawMessage) int { return DecInt[int](r) })
		_ = v_ch
		rv := Await(func(t *rt.Task) { v_ch.Recv(t) })
		_ = rv
		r0 := rt.As[int](rv[0])
		r1 := rt.As[bool](rv[1])
		return []any{EncInt(r0), EncBool(r1)}
	},
	"core.chan.send/buffered": func(h *H) []any {
		v_ch := DecChan(h.Let("ch"), func(r json.RawMessage) int { return DecInt[int](r) })
		_ = v_ch
		v_v := DecInt[int](h.Let("v"))
		_ = v_v
		rv := Await(func(t *rt.Task) { v_ch.Send(t, v_v) })
		_ = rv
		h.After("ch", EncChan(v_ch, func(e int) any { return EncInt(e) }))
		return []any{}
	},
	"core.chan.send/closed": func(h *H) []any {
		v_ch := DecChan(h.Let("ch"), func(r json.RawMessage) int { return DecInt[int](r) })
		_ = v_ch
		v_v := DecInt[int](h.Let("v"))
		_ = v_v
		rv := Await(func(t *rt.Task) { v_ch.Send(t, v_v) })
		_ = rv
		return []any{}
	},
	"core.chan.send/full_blocks": func(h *H) []any {
		v_ch := DecChan(h.Let("ch"), func(r json.RawMessage) int { return DecInt[int](r) })
		_ = v_ch
		v_v := DecInt[int](h.Let("v"))
		_ = v_v
		rv := Await(func(t *rt.Task) { v_ch.Send(t, v_v) })
		_ = rv
		return []any{}
	},
	"core.chan.send/nil_blocks": func(h *H) []any {
		v_ch := DecChan(h.Let("ch"), func(r json.RawMessage) int { return DecInt[int](r) })
		_ = v_ch
		v_v := DecInt[int](h.Let("v"))
		_ = v_v
		rv := Await(func(t *rt.Task) { v_ch.Send(t, v_v) })
		_ = rv
		return []any{}
	},
	"core.chan.send/unbuffered_blocks": func(h *H) []any {
		v_ch := DecChan(h.Let("ch"), func(r json.RawMessage) string { return DecString(r) })
		_ = v_ch
		v_v := DecString(h.Let("v"))
		_ = v_v
		rv := Await(func(t *rt.Task) { v_ch.Send(t, v_v) })
		_ = rv
		return []any{}
	},
	"core.integer.add/int32_plain": func(h *H) []any {
		v_a := DecInt[int32](h.Let("a"))
		_ = v_a
		v_b := DecInt[int32](h.Let("b"))
		_ = v_b
		r0 := rt.IntAdd(v_a, v_b)
		return []any{EncInt(r0)}
	},
	"core.integer.add/int64_min": func(h *H) []any {
		v_a := DecInt[int64](h.Let("a"))
		_ = v_a
		v_b := DecInt[int64](h.Let("b"))
		_ = v_b
		r0 := rt.IntAdd(v_a, v_b)
		return []any{EncInt(r0)}
	},
	"core.integer.add/int8_wrap": func(h *H) []any {
		v_a := DecInt[int8](h.Let("a"))
		_ = v_a
		v_b := DecInt[int8](h.Let("b"))
		_ = v_b
		r0 := rt.IntAdd(v_a, v_b)
		return []any{EncInt(r0)}
	},
	"core.integer.add/int_big": func(h *H) []any {
		v_a := DecInt[int](h.Let("a"))
		_ = v_a
		v_b := DecInt[int](h.Let("b"))
		_ = v_b
		r0 := rt.IntAdd(v_a, v_b)
		return []any{EncInt(r0)}
	},
	"core.integer.add/uint32_wrap": func(h *H) []any {
		v_a := DecInt[uint32](h.Let("a"))
		_ = v_a
		v_b := DecInt[uint32](h.Let("b"))
		_ = v_b
		r0 := rt.IntAdd(v_a, v_b)
		return []any{EncInt(r0)}
	},
	"core.integer.add/uint64_wrap": func(h *H) []any {
		v_a := DecInt[uint64](h.Let("a"))
		_ = v_a
		v_b := DecInt[uint64](h.Let("b"))
		_ = v_b
		r0 := rt.IntAdd(v_a, v_b)
		return []any{EncInt(r0)}
	},
	"core.integer.and/neg": func(h *H) []any {
		v_a := DecInt[int](h.Let("a"))
		_ = v_a
		v_b := DecInt[int](h.Let("b"))
		_ = v_b
		r0 := rt.IntAnd(v_a, v_b)
		return []any{EncInt(r0)}
	},
	"core.integer.and/u32": func(h *H) []any {
		v_a := DecInt[uint32](h.Let("a"))
		_ = v_a
		v_b := DecInt[uint32](h.Let("b"))
		_ = v_b
		r0 := rt.IntAnd(v_a, v_b)
		return []any{EncInt(r0)}
	},
	"core.integer.andnot/i64": func(h *H) []any {
		v_a := DecInt[int64](h.Let("a"))
		_ = v_a
		v_b := DecInt[int64](h.Let("b"))
		_ = v_b
		r0 := rt.IntAndNot(v_a, v_b)
		return []any{EncInt(r0)}
	},
	"core.integer.andnot/u16": func(h *H) []any {
		v_a := DecInt[uint16](h.Let("a"))
		_ = v_a
		v_b := DecInt[uint16](h.Let("b"))
		_ = v_b
		r0 := rt.IntAndNot(v_a, v_b)
		return []any{EncInt(r0)}
	},
	"core.integer.compare/equal": func(h *H) []any {
		v_a := DecInt[uint32](h.Let("a"))
		_ = v_a
		v_b := DecInt[uint32](h.Let("b"))
		_ = v_b
		r0 := rt.IntCompare(v_a, v_b)
		return []any{EncInt(r0)}
	},
	"core.integer.compare/signed": func(h *H) []any {
		v_a := DecInt[int64](h.Let("a"))
		_ = v_a
		v_b := DecInt[int64](h.Let("b"))
		_ = v_b
		r0 := rt.IntCompare(v_a, v_b)
		return []any{EncInt(r0)}
	},
	"core.integer.compare/u32_high": func(h *H) []any {
		v_a := DecInt[uint32](h.Let("a"))
		_ = v_a
		v_b := DecInt[uint32](h.Let("b"))
		_ = v_b
		r0 := rt.IntCompare(v_a, v_b)
		return []any{EncInt(r0)}
	},
	"core.integer.compare/unsigned_high": func(h *H) []any {
		v_a := DecInt[uint64](h.Let("a"))
		_ = v_a
		v_b := DecInt[uint64](h.Let("b"))
		_ = v_b
		r0 := rt.IntCompare(v_a, v_b)
		return []any{EncInt(r0)}
	},
	"core.integer.convert/narrow_unsigned": func(h *H) []any {
		v_a := DecInt[int32](h.Let("a"))
		_ = v_a
		r0 := rt.IntConvert[uint16](v_a)
		return []any{EncInt(r0)}
	},
	"core.integer.convert/same": func(h *H) []any {
		v_a := DecInt[int](h.Let("a"))
		_ = v_a
		r0 := rt.IntConvert[int](v_a)
		return []any{EncInt(r0)}
	},
	"core.integer.convert/sign_extend": func(h *H) []any {
		v_a := DecInt[int8](h.Let("a"))
		_ = v_a
		r0 := rt.IntConvert[uint64](v_a)
		return []any{EncInt(r0)}
	},
	"core.integer.convert/truncate": func(h *H) []any {
		v_a := DecInt[int](h.Let("a"))
		_ = v_a
		r0 := rt.IntConvert[int8](v_a)
		return []any{EncInt(r0)}
	},
	"core.integer.convert/u32_to_i32": func(h *H) []any {
		v_a := DecInt[uint32](h.Let("a"))
		_ = v_a
		r0 := rt.IntConvert[int32](v_a)
		return []any{EncInt(r0)}
	},
	"core.integer.convert/unsigned_wrap": func(h *H) []any {
		v_a := DecInt[uint64](h.Let("a"))
		_ = v_a
		r0 := rt.IntConvert[int64](v_a)
		return []any{EncInt(r0)}
	},
	"core.integer.div/by_zero": func(h *H) []any {
		v_a := DecInt[int32](h.Let("a"))
		_ = v_a
		v_b := DecInt[int32](h.Let("b"))
		_ = v_b
		r0 := rt.IntDiv(v_a, v_b)
		return []any{EncInt(r0)}
	},
	"core.integer.div/int64_min_neg1": func(h *H) []any {
		v_a := DecInt[int64](h.Let("a"))
		_ = v_a
		v_b := DecInt[int64](h.Let("b"))
		_ = v_b
		r0 := rt.IntDiv(v_a, v_b)
		return []any{EncInt(r0)}
	},
	"core.integer.div/int8_min_neg1": func(h *H) []any {
		v_a := DecInt[int8](h.Let("a"))
		_ = v_a
		v_b := DecInt[int8](h.Let("b"))
		_ = v_b
		r0 := rt.IntDiv(v_a, v_b)
		return []any{EncInt(r0)}
	},
	"core.integer.div/trunc_neg": func(h *H) []any {
		v_a := DecInt[int](h.Let("a"))
		_ = v_a
		v_b := DecInt[int](h.Let("b"))
		_ = v_b
		r0 := rt.IntDiv(v_a, v_b)
		return []any{EncInt(r0)}
	},
	"core.integer.div/trunc_pos": func(h *H) []any {
		v_a := DecInt[int](h.Let("a"))
		_ = v_a
		v_b := DecInt[int](h.Let("b"))
		_ = v_b
		r0 := rt.IntDiv(v_a, v_b)
		return []any{EncInt(r0)}
	},
	"core.integer.div/uint64_big": func(h *H) []any {
		v_a := DecInt[uint64](h.Let("a"))
		_ = v_a
		v_b := DecInt[uint64](h.Let("b"))
		_ = v_b
		r0 := rt.IntDiv(v_a, v_b)
		return []any{EncInt(r0)}
	},
	"core.integer.mul/int32_neg": func(h *H) []any {
		v_a := DecInt[int32](h.Let("a"))
		_ = v_a
		v_b := DecInt[int32](h.Let("b"))
		_ = v_b
		r0 := rt.IntMul(v_a, v_b)
		return []any{EncInt(r0)}
	},
	"core.integer.mul/int32_wrap": func(h *H) []any {
		v_a := DecInt[int32](h.Let("a"))
		_ = v_a
		v_b := DecInt[int32](h.Let("b"))
		_ = v_b
		r0 := rt.IntMul(v_a, v_b)
		return []any{EncInt(r0)}
	},
	"core.integer.mul/int64_wrap": func(h *H) []any {
		v_a := DecInt[int64](h.Let("a"))
		_ = v_a
		v_b := DecInt[int64](h.Let("b"))
		_ = v_b
		r0 := rt.IntMul(v_a, v_b)
		return []any{EncInt(r0)}
	},
	"core.integer.mul/int8_wrap": func(h *H) []any {
		v_a := DecInt[int8](h.Let("a"))
		_ = v_a
		v_b := DecInt[int8](h.Let("b"))
		_ = v_b
		r0 := rt.IntMul(v_a, v_b)
		return []any{EncInt(r0)}
	},
	"core.integer.mul/uint32_exact": func(h *H) []any {
		v_a := DecInt[uint32](h.Let("a"))
		_ = v_a
		v_b := DecInt[uint32](h.Let("b"))
		_ = v_b
		r0 := rt.IntMul(v_a, v_b)
		return []any{EncInt(r0)}
	},
	"core.integer.mul/uint64_big": func(h *H) []any {
		v_a := DecInt[uint64](h.Let("a"))
		_ = v_a
		v_b := DecInt[uint64](h.Let("b"))
		_ = v_b
		r0 := rt.IntMul(v_a, v_b)
		return []any{EncInt(r0)}
	},
	"core.integer.neg/min": func(h *H) []any {
		v_a := DecInt[int32](h.Let("a"))
		_ = v_a
		r0 := rt.IntNeg(v_a)
		return []any{EncInt(r0)}
	},
	"core.integer.neg/plain": func(h *H) []any {
		v_a := DecInt[int](h.Let("a"))
		_ = v_a
		r0 := rt.IntNeg(v_a)
		return []any{EncInt(r0)}
	},
	"core.integer.neg/u64": func(h *H) []any {
		v_a := DecInt[uint64](h.Let("a"))
		_ = v_a
		r0 := rt.IntNeg(v_a)
		return []any{EncInt(r0)}
	},
	"core.integer.neg/unsigned": func(h *H) []any {
		v_a := DecInt[uint8](h.Let("a"))
		_ = v_a
		r0 := rt.IntNeg(v_a)
		return []any{EncInt(r0)}
	},
	"core.integer.not/signed": func(h *H) []any {
		v_a := DecInt[int](h.Let("a"))
		_ = v_a
		r0 := rt.IntNot(v_a)
		return []any{EncInt(r0)}
	},
	"core.integer.not/u32": func(h *H) []any {
		v_a := DecInt[uint32](h.Let("a"))
		_ = v_a
		r0 := rt.IntNot(v_a)
		return []any{EncInt(r0)}
	},
	"core.integer.not/u8": func(h *H) []any {
		v_a := DecInt[uint8](h.Let("a"))
		_ = v_a
		r0 := rt.IntNot(v_a)
		return []any{EncInt(r0)}
	},
	"core.integer.or/i8": func(h *H) []any {
		v_a := DecInt[int8](h.Let("a"))
		_ = v_a
		v_b := DecInt[int8](h.Let("b"))
		_ = v_b
		r0 := rt.IntOr(v_a, v_b)
		return []any{EncInt(r0)}
	},
	"core.integer.or/u32": func(h *H) []any {
		v_a := DecInt[uint32](h.Let("a"))
		_ = v_a
		v_b := DecInt[uint32](h.Let("b"))
		_ = v_b
		r0 := rt.IntOr(v_a, v_b)
		return []any{EncInt(r0)}
	},
	"core.integer.rem/by_zero": func(h *H) []any {
		v_a := DecInt[uint8](h.Let("a"))
		_ = v_a
		v_b := DecInt[uint8](h.Let("b"))
		_ = v_b
		r0 := rt.IntRem(v_a, v_b)
		return []any{EncInt(r0)}
	},
	"core.integer.rem/min_neg1": func(h *H) []any {
		v_a := DecInt[int64](h.Let("a"))
		_ = v_a
		v_b := DecInt[int64](h.Let("b"))
		_ = v_b
		r0 := rt.IntRem(v_a, v_b)
		return []any{EncInt(r0)}
	},
	"core.integer.rem/neg_dividend": func(h *H) []any {
		v_a := DecInt[int](h.Let("a"))
		_ = v_a
		v_b := DecInt[int](h.Let("b"))
		_ = v_b
		r0 := rt.IntRem(v_a, v_b)
		return []any{EncInt(r0)}
	},
	"core.integer.rem/neg_divisor": func(h *H) []any {
		v_a := DecInt[int](h.Let("a"))
		_ = v_a
		v_b := DecInt[int](h.Let("b"))
		_ = v_b
		r0 := rt.IntRem(v_a, v_b)
		return []any{EncInt(r0)}
	},
	"core.integer.rem/uint": func(h *H) []any {
		v_a := DecInt[uint32](h.Let("a"))
		_ = v_a
		v_b := DecInt[uint32](h.Let("b"))
		_ = v_b
		r0 := rt.IntRem(v_a, v_b)
		return []any{EncInt(r0)}
	},
	"core.integer.shl/basic": func(h *H) []any {
		v_a := DecInt[int](h.Let("a"))
		_ = v_a
		v_b := DecInt[uint](h.Let("b"))
		_ = v_b
		r0 := rt.IntShl(v_a, v_b)
		return []any{EncInt(r0)}
	},
	"core.integer.shl/huge": func(h *H) []any {
		v_a := DecInt[uint64](h.Let("a"))
		_ = v_a
		v_b := DecInt[uint64](h.Let("b"))
		_ = v_b
		r0 := rt.IntShl(v_a, v_b)
		return []any{EncInt(r0)}
	},
	"core.integer.shl/int64_63": func(h *H) []any {
		v_a := DecInt[int64](h.Let("a"))
		_ = v_a
		v_b := DecInt[int](h.Let("b"))
		_ = v_b
		r0 := rt.IntShl(v_a, v_b)
		return []any{EncInt(r0)}
	},
	"core.integer.shl/negative": func(h *H) []any {
		v_a := DecInt[int](h.Let("a"))
		_ = v_a
		v_b := DecInt[int](h.Let("b"))
		_ = v_b
		r0 := rt.IntShl(v_a, v_b)
		return []any{EncInt(r0)}
	},
	"core.integer.shl/overflow_int8": func(h *H) []any {
		v_a := DecInt[int8](h.Let("a"))
		_ = v_a
		v_b := DecInt[int](h.Let("b"))
		_ = v_b
		r0 := rt.IntShl(v_a, v_b)
		return []any{EncInt(r0)}
	},
	"core.integer.shl/wide": func(h *H) []any {
		v_a := DecInt[int32](h.Let("a"))
		_ = v_a
		v_b := DecInt[uint64](h.Let("b"))
		_ = v_b
		r0 := rt.IntShl(v_a, v_b)
		return []any{EncInt(r0)}
	},
	"core.integer.shr/arith": func(h *H) []any {
		v_a := DecInt[int](h.Let("a"))
		_ = v_a
		v_b := DecInt[uint](h.Let("b"))
		_ = v_b
		r0 := rt.IntShr(v_a, v_b)
		return []any{EncInt(r0)}
	},
	"core.integer.shr/arith_wide": func(h *H) []any {
		v_a := DecInt[int8](h.Let("a"))
		_ = v_a
		v_b := DecInt[int](h.Let("b"))
		_ = v_b
		r0 := rt.IntShr(v_a, v_b)
		return []any{EncInt(r0)}
	},
	"core.integer.shr/logical": func(h *H) []any {
		v_a := DecInt[uint8](h.Let("a"))
		_ = v_a
		v_b := DecInt[int](h.Let("b"))
		_ = v_b
		r0 := rt.IntShr(v_a, v_b)
		return []any{EncInt(r0)}
	},
	"core.integer.shr/logical_wide": func(h *H) []any {
		v_a := DecInt[uint64](h.Let("a"))
		_ = v_a
		v_b := DecInt[uint](h.Let("b"))
		_ = v_b
		r0 := rt.IntShr(v_a, v_b)
		return []any{EncInt(r0)}
	},
	"core.integer.shr/negative": func(h *H) []any {
		v_a := DecInt[int8](h.Let("a"))
		_ = v_a
		v_b := DecInt[int64](h.Let("b"))
		_ = v_b
		r0 := rt.IntShr(v_a, v_b)
		return []any{EncInt(r0)}
	},
	"core.integer.shr/pos_wide": func(h *H) []any {
		v_a := DecInt[int32](h.Let("a"))
		_ = v_a
		v_b := DecInt[int](h.Let("b"))
		_ = v_b
		r0 := rt.IntShr(v_a, v_b)
		return []any{EncInt(r0)}
	},
	"core.integer.sub/int16_wrap": func(h *H) []any {
		v_a := DecInt[int16](h.Let("a"))
		_ = v_a
		v_b := DecInt[int16](h.Let("b"))
		_ = v_b
		r0 := rt.IntSub(v_a, v_b)
		return []any{EncInt(r0)}
	},
	"core.integer.sub/int_plain": func(h *H) []any {
		v_a := DecInt[int](h.Let("a"))
		_ = v_a
		v_b := DecInt[int](h.Let("b"))
		_ = v_b
		r0 := rt.IntSub(v_a, v_b)
		return []any{EncInt(r0)}
	},
	"core.integer.sub/uint8_wrap": func(h *H) []any {
		v_a := DecInt[uint8](h.Let("a"))
		_ = v_a
		v_b := DecInt[uint8](h.Let("b"))
		_ = v_b
		r0 := rt.IntSub(v_a, v_b)
		return []any{EncInt(r0)}
	},
	"core.integer.sub/uint_wrap": func(h *H) []any {
		v_a := DecInt[uint](h.Let("a"))
		_ = v_a
		v_b := DecInt[uint](h.Let("b"))
		_ = v_b
		r0 := rt.IntSub(v_a, v_b)
		return []any{EncInt(r0)}
	},
	"core.integer.xor/i32": func(h *H) []any {
		v_a := DecInt[int32](h.Let("a"))
		_ = v_a
		v_b := DecInt[int32](h.Let("b"))
		_ = v_b
		r0 := rt.IntXor(v_a, v_b)
		return []any{EncInt(r0)}
	},
	"core.integer.xor/u64": func(h *H) []any {
		v_a := DecInt[uint64](h.Let("a"))
		_ = v_a
		v_b := DecInt[uint64](h.Let("b"))
		_ = v_b
		r0 := rt.IntXor(v_a, v_b)
		return []any{EncInt(r0)}
	},
	"core.map.clear/all": func(h *H) []any {
		v_m := DecMap(h.Let("m"), func(r json.RawMessage) int { return DecInt[int](r) }, func(r json.RawMessage) int { return DecInt[int](r) })
		_ = v_m
		v_m.Clear()
		h.After("m", EncMap(v_m, func(e int) any { return EncInt(e) }, func(e int) any { return EncInt(e) }))
		return []any{}
	},
	"core.map.delete/nil_map": func(h *H) []any {
		v_m := DecMap(h.Let("m"), func(r json.RawMessage) int { return DecInt[int](r) }, func(r json.RawMessage) int { return DecInt[int](r) })
		_ = v_m
		v_k := DecInt[int](h.Let("k"))
		_ = v_k
		v_m.Delete(v_k)
		return []any{}
	},
	"core.map.delete/reinsert_moves": func(h *H) []any {
		v_m := DecMap(h.Let("m"), func(r json.RawMessage) int { return DecInt[int](r) }, func(r json.RawMessage) int { return DecInt[int](r) })
		_ = v_m
		v_k := DecInt[int](h.Let("k"))
		_ = v_k
		v_m.Delete(v_k)
		h.After("m", EncMap(v_m, func(e int) any { return EncInt(e) }, func(e int) any { return EncInt(e) }))
		return []any{}
	},
	"core.map.iterate/insertion_order": func(h *H) []any {
		v_m := DecMap(h.Let("m"), func(r json.RawMessage) int { return DecInt[int](r) }, func(r json.RawMessage) int { return DecInt[int](r) })
		_ = v_m
		r0 := rt.MapKeys(v_m)
		return []any{EncSlice(r0, func(e int) any { return EncInt(e) })}
	},
	"core.map.len/nil": func(h *H) []any {
		v_m := DecMap(h.Let("m"), func(r json.RawMessage) int { return DecInt[int](r) }, func(r json.RawMessage) int { return DecInt[int](r) })
		_ = v_m
		r0 := v_m.Len()
		return []any{EncInt(r0)}
	},
	"core.map.len/two": func(h *H) []any {
		v_m := DecMap(h.Let("m"), func(r json.RawMessage) int { return DecInt[int](r) }, func(r json.RawMessage) int { return DecInt[int](r) })
		_ = v_m
		r0 := v_m.Len()
		return []any{EncInt(r0)}
	},
	"core.map.lookup/nil_map": func(h *H) []any {
		v_m := DecMap(h.Let("m"), func(r json.RawMessage) int { return DecInt[int](r) }, func(r json.RawMessage) string { return DecString(r) })
		_ = v_m
		v_k := DecInt[int](h.Let("k"))
		_ = v_k
		r0, r1 := v_m.Get(v_k)
		return []any{EncString(r0), EncBool(r1)}
	},
	"core.map.lookup/present": func(h *H) []any {
		v_m := DecMap(h.Let("m"), func(r json.RawMessage) string { return DecString(r) }, func(r json.RawMessage) int { return DecInt[int](r) })
		_ = v_m
		v_k := DecString(h.Let("k"))
		_ = v_k
		r0, r1 := v_m.Get(v_k)
		return []any{EncInt(r0), EncBool(r1)}
	},
	"core.map.make/empty": func(h *H) []any {
		r0 := rt.NewMap[string, int]()
		return []any{EncMap(r0, func(e string) any { return EncString(e) }, func(e int) any { return EncInt(e) })}
	},
	"core.map.store/nil_map": func(h *H) []any {
		v_m := DecMap(h.Let("m"), func(r json.RawMessage) int { return DecInt[int](r) }, func(r json.RawMessage) int { return DecInt[int](r) })
		_ = v_m
		v_k := DecInt[int](h.Let("k"))
		_ = v_k
		v_v := DecInt[int](h.Let("v"))
		_ = v_v
		v_m.Set(v_k, v_v)
		return []any{}
	},
	"core.map.store/update_keeps_order": func(h *H) []any {
		v_m := DecMap(h.Let("m"), func(r json.RawMessage) int { return DecInt[int](r) }, func(r json.RawMessage) int { return DecInt[int](r) })
		_ = v_m
		v_k := DecInt[int](h.Let("k"))
		_ = v_k
		v_v := DecInt[int](h.Let("v"))
		_ = v_v
		v_m.Set(v_k, v_v)
		h.After("m", EncMap(v_m, func(e int) any { return EncInt(e) }, func(e int) any { return EncInt(e) }))
		return []any{}
	},
	"core.print/bool": func(h *H) []any {
		v_v := DecBool(h.Let("v"))
		_ = v_v
		r0 := rt.PrintString(v_v)
		return []any{EncString(r0)}
	},
	"core.print/bytes": func(h *H) []any {
		v_v := DecString(h.Let("v"))
		_ = v_v
		r0 := rt.PrintString(v_v)
		return []any{EncString(r0)}
	},
	"core.print/int": func(h *H) []any {
		v_v := DecInt[int](h.Let("v"))
		_ = v_v
		r0 := rt.PrintString(v_v)
		return []any{EncString(r0)}
	},
	"core.print/u64": func(h *H) []any {
		v_v := DecInt[uint64](h.Let("v"))
		_ = v_v
		r0 := rt.PrintString(v_v)
		return []any{EncString(r0)}
	},
	"core.select/closed_ready": func(h *H) []any {
		v_a := DecChan(h.Let("a"), func(r json.RawMessage) int { return DecInt[int](r) })
		_ = v_a
		v_b := DecChan(h.Let("b"), func(r json.RawMessage) int { return DecInt[int](r) })
		_ = v_b
		v_dflt := DecBool(h.Let("dflt"))
		_ = v_dflt
		rv := Await(func(t *rt.Task) { HarnessSelect2(t, v_a, v_b, v_dflt) })
		_ = rv
		r0 := rt.As[int](rv[0])
		return []any{EncInt(r0)}
	},
	"core.select/default_when_idle": func(h *H) []any {
		v_a := DecChan(h.Let("a"), func(r json.RawMessage) int { return DecInt[int](r) })
		_ = v_a
		v_b := DecChan(h.Let("b"), func(r json.RawMessage) int { return DecInt[int](r) })
		_ = v_b
		v_dflt := DecBool(h.Let("dflt"))
		_ = v_dflt
		rv := Await(func(t *rt.Task) { HarnessSelect2(t, v_a, v_b, v_dflt) })
		_ = rv
		r0 := rt.As[int](rv[0])
		return []any{EncInt(r0)}
	},
	"core.select/nothing_blocks": func(h *H) []any {
		v_a := DecChan(h.Let("a"), func(r json.RawMessage) int { return DecInt[int](r) })
		_ = v_a
		v_b := DecChan(h.Let("b"), func(r json.RawMessage) int { return DecInt[int](r) })
		_ = v_b
		v_dflt := DecBool(h.Let("dflt"))
		_ = v_dflt
		rv := Await(func(t *rt.Task) { HarnessSelect2(t, v_a, v_b, v_dflt) })
		_ = rv
		r0 := rt.As[int](rv[0])
		return []any{EncInt(r0)}
	},
	"core.select/only_ready": func(h *H) []any {
		v_a := DecChan(h.Let("a"), func(r json.RawMessage) int { return DecInt[int](r) })
		_ = v_a
		v_b := DecChan(h.Let("b"), func(r json.RawMessage) int { return DecInt[int](r) })
		_ = v_b
		v_dflt := DecBool(h.Let("dflt"))
		_ = v_dflt
		rv := Await(func(t *rt.Task) { HarnessSelect2(t, v_a, v_b, v_dflt) })
		_ = rv
		r0 := rt.As[int](rv[0])
		h.After("b", EncChan(v_b, func(e int) any { return EncInt(e) }))
		return []any{EncInt(r0)}
	},
	"core.slice.append/from_nil": func(h *H) []any {
		v_s := DecSlice(h.Let("s"), func(r json.RawMessage) string { return DecString(r) })
		_ = v_s
		v_vs := DecSlice(h.Let("vs"), func(r json.RawMessage) string { return DecString(r) })
		_ = v_vs
		r0 := rt.Append(v_s, v_vs...)
		return []any{EncSlice(r0, func(e string) any { return EncString(e) })}
	},
	"core.slice.append/grow_doubles": func(h *H) []any {
		v_s := DecSlice(h.Let("s"), func(r json.RawMessage) int { return DecInt[int](r) })
		_ = v_s
		v_vs := DecSlice(h.Let("vs"), func(r json.RawMessage) int { return DecInt[int](r) })
		_ = v_vs
		r0 := rt.Append(v_s, v_vs...)
		return []any{EncSlice(r0, func(e int) any { return EncInt(e) })}
	},
	"core.slice.append/grow_required": func(h *H) []any {
		v_s := DecSlice(h.Let("s"), func(r json.RawMessage) int { return DecInt[int](r) })
		_ = v_s
		v_vs := DecSlice(h.Let("vs"), func(r json.RawMessage) int { return DecInt[int](r) })
		_ = v_vs
		r0 := rt.Append(v_s, v_vs...)
		return []any{EncSlice(r0, func(e int) any { return EncInt(e) })}
	},
	"core.slice.append/in_place": func(h *H) []any {
		v_s := DecSlice(h.Let("s"), func(r json.RawMessage) int { return DecInt[int](r) })
		_ = v_s
		v_t := View(v_s, h.Let("t"))
		_ = v_t
		v_vs := DecSlice(h.Let("vs"), func(r json.RawMessage) int { return DecInt[int](r) })
		_ = v_vs
		r0 := rt.Append(v_s, v_vs...)
		h.After("t", EncSlice(v_t, func(e int) any { return EncInt(e) }))
		return []any{EncSlice(r0, func(e int) any { return EncInt(e) })}
	},
	"core.slice.append/nil_empty": func(h *H) []any {
		v_s := DecSlice(h.Let("s"), func(r json.RawMessage) int { return DecInt[int](r) })
		_ = v_s
		v_vs := DecSlice(h.Let("vs"), func(r json.RawMessage) int { return DecInt[int](r) })
		_ = v_vs
		r0 := rt.Append(v_s, v_vs...)
		return []any{EncSlice(r0, func(e int) any { return EncInt(e) })}
	},
	"core.slice.append/overlap": func(h *H) []any {
		v_s := DecSlice(h.Let("s"), func(r json.RawMessage) int { return DecInt[int](r) })
		_ = v_s
		v_a := View(v_s, h.Let("a"))
		_ = v_a
		v_vs := View(v_s, h.Let("vs"))
		_ = v_vs
		r0 := rt.Append(v_a, v_vs...)
		h.After("s", EncSlice(v_s, func(e int) any { return EncInt(e) }))
		return []any{EncSlice(r0, func(e int) any { return EncInt(e) })}
	},
	"core.slice.clear/shared": func(h *H) []any {
		v_s := DecSlice(h.Let("s"), func(r json.RawMessage) int { return DecInt[int](r) })
		_ = v_s
		v_t := View(v_s, h.Let("t"))
		_ = v_t
		rt.SliceClear(v_t)
		h.After("s", EncSlice(v_s, func(e int) any { return EncInt(e) }))
		return []any{}
	},
	"core.slice.copy/overlap_forward": func(h *H) []any {
		v_s := DecSlice(h.Let("s"), func(r json.RawMessage) int { return DecInt[int](r) })
		_ = v_s
		v_d := View(v_s, h.Let("d"))
		_ = v_d
		v_src := View(v_s, h.Let("src"))
		_ = v_src
		r0 := rt.SliceCopy(v_d, v_src)
		h.After("s", EncSlice(v_s, func(e int) any { return EncInt(e) }))
		return []any{EncInt(r0)}
	},
	"core.slice.copy/short_dst": func(h *H) []any {
		v_d := DecSlice(h.Let("d"), func(r json.RawMessage) uint8 { return DecInt[uint8](r) })
		_ = v_d
		v_src := DecSlice(h.Let("src"), func(r json.RawMessage) uint8 { return DecInt[uint8](r) })
		_ = v_src
		r0 := rt.SliceCopy(v_d, v_src)
		h.After("d", EncSlice(v_d, func(e uint8) any { return EncInt(e) }))
		return []any{EncInt(r0)}
	},
	"core.slice.index/basic": func(h *H) []any {
		v_s := DecSlice(h.Let("s"), func(r json.RawMessage) int { return DecInt[int](r) })
		_ = v_s
		v_i := DecInt[int](h.Let("i"))
		_ = v_i
		r0 := rt.SliceIndex(v_s, v_i)
		return []any{EncInt(r0)}
	},
	"core.slice.index/beyond_len": func(h *H) []any {
		v_s := DecSlice(h.Let("s"), func(r json.RawMessage) int { return DecInt[int](r) })
		_ = v_s
		v_i := DecInt[int](h.Let("i"))
		_ = v_i
		r0 := rt.SliceIndex(v_s, v_i)
		return []any{EncInt(r0)}
	},
	"core.slice.index/nil": func(h *H) []any {
		v_s := DecSlice(h.Let("s"), func(r json.RawMessage) string { return DecString(r) })
		_ = v_s
		v_i := DecInt[int](h.Let("i"))
		_ = v_i
		r0 := rt.SliceIndex(v_s, v_i)
		return []any{EncString(r0)}
	},
	"core.slice.make/basic": func(h *H) []any {
		v_len := DecInt[int](h.Let("len"))
		_ = v_len
		v_cap := DecInt[int](h.Let("cap"))
		_ = v_cap
		r0 := rt.SliceMake[int](v_len, v_cap)
		return []any{EncSlice(r0, func(e int) any { return EncInt(e) })}
	},
	"core.slice.make/cap_lt_len": func(h *H) []any {
		v_len := DecInt[int](h.Let("len"))
		_ = v_len
		v_cap := DecInt[int](h.Let("cap"))
		_ = v_cap
		r0 := rt.SliceMake[uint8](v_len, v_cap)
		return []any{EncSlice(r0, func(e uint8) any { return EncInt(e) })}
	},
	"core.slice.make/neg_len": func(h *H) []any {
		v_len := DecInt[int](h.Let("len"))
		_ = v_len
		v_cap := DecInt[int](h.Let("cap"))
		_ = v_cap
		r0 := rt.SliceMake[int](v_len, v_cap)
		return []any{EncSlice(r0, func(e int) any { return EncInt(e) })}
	},
	"core.slice.slice/hi_gt_max": func(h *H) []any {
		v_s := DecSlice(h.Let("s"), func(r json.RawMessage) int { return DecInt[int](r) })
		_ = v_s
		v_lo := DecInt[int](h.Let("lo"))
		_ = v_lo
		v_hi := DecInt[int](h.Let("hi"))
		_ = v_hi
		v_max := DecInt[int](h.Let("max"))
		_ = v_max
		r0 := rt.SliceSlice(v_s, v_lo, v_hi, v_max)
		return []any{EncSlice(r0, func(e int) any { return EncInt(e) })}
	},
	"core.slice.slice/lo_gt_hi": func(h *H) []any {
		v_s := DecSlice(h.Let("s"), func(r json.RawMessage) int { return DecInt[int](r) })
		_ = v_s
		v_lo := DecInt[int](h.Let("lo"))
		_ = v_lo
		v_hi := DecInt[int](h.Let("hi"))
		_ = v_hi
		v_max := DecInt[int](h.Let("max"))
		_ = v_max
		r0 := rt.SliceSlice(v_s, v_lo, v_hi, v_max)
		return []any{EncSlice(r0, func(e int) any { return EncInt(e) })}
	},
	"core.slice.slice/max_oob": func(h *H) []any {
		v_s := DecSlice(h.Let("s"), func(r json.RawMessage) int { return DecInt[int](r) })
		_ = v_s
		v_lo := DecInt[int](h.Let("lo"))
		_ = v_lo
		v_hi := DecInt[int](h.Let("hi"))
		_ = v_hi
		v_max := DecInt[int](h.Let("max"))
		_ = v_max
		r0 := rt.SliceSlice(v_s, v_lo, v_hi, v_max)
		return []any{EncSlice(r0, func(e int) any { return EncInt(e) })}
	},
	"core.slice.slice/nil_empty": func(h *H) []any {
		v_s := DecSlice(h.Let("s"), func(r json.RawMessage) int { return DecInt[int](r) })
		_ = v_s
		v_lo := DecInt[int](h.Let("lo"))
		_ = v_lo
		v_hi := DecInt[int](h.Let("hi"))
		_ = v_hi
		v_max := DecInt[int](h.Let("max"))
		_ = v_max
		r0 := rt.SliceSlice(v_s, v_lo, v_hi, v_max)
		return []any{EncSlice(r0, func(e int) any { return EncInt(e) })}
	},
	"core.slice.slice/share": func(h *H) []any {
		v_s := DecSlice(h.Let("s"), func(r json.RawMessage) int { return DecInt[int](r) })
		_ = v_s
		v_lo := DecInt[int](h.Let("lo"))
		_ = v_lo
		v_hi := DecInt[int](h.Let("hi"))
		_ = v_hi
		v_max := DecInt[int](h.Let("max"))
		_ = v_max
		r0 := rt.SliceSlice(v_s, v_lo, v_hi, v_max)
		return []any{EncSlice(r0, func(e int) any { return EncInt(e) })}
	},
	"core.slice.store/alias_visible": func(h *H) []any {
		v_s := DecSlice(h.Let("s"), func(r json.RawMessage) int { return DecInt[int](r) })
		_ = v_s
		v_t := View(v_s, h.Let("t"))
		_ = v_t
		v_i := DecInt[int](h.Let("i"))
		_ = v_i
		v_v := DecInt[int](h.Let("v"))
		_ = v_v
		rt.SliceStore(v_t, v_i, v_v)
		h.After("s", EncSlice(v_s, func(e int) any { return EncInt(e) }))
		return []any{}
	},
	"core.slice.store/oob": func(h *H) []any {
		v_s := DecSlice(h.Let("s"), func(r json.RawMessage) int { return DecInt[int](r) })
		_ = v_s
		v_i := DecInt[int](h.Let("i"))
		_ = v_i
		v_v := DecInt[int](h.Let("v"))
		_ = v_v
		rt.SliceStore(v_s, v_i, v_v)
		return []any{}
	},
	"core.slice.to_array/prefix": func(h *H) []any {
		v_s := DecSlice(h.Let("s"), func(r json.RawMessage) int { return DecInt[int](r) })
		_ = v_s
		r0 := rt.SliceToArray2(v_s)
		return []any{EncArray(r0[:], func(e int) any { return EncInt(e) })}
	},
	"core.slice.to_array/short": func(h *H) []any {
		v_s := DecSlice(h.Let("s"), func(r json.RawMessage) int { return DecInt[int](r) })
		_ = v_s
		r0 := rt.SliceToArray2(v_s)
		return []any{EncArray(r0[:], func(e int) any { return EncInt(e) })}
	},
	"core.string.compare/equal": func(h *H) []any {
		v_a := DecString(h.Let("a"))
		_ = v_a
		v_b := DecString(h.Let("b"))
		_ = v_b
		r0 := rt.StringCompare(v_a, v_b)
		return []any{EncInt(r0)}
	},
	"core.string.compare/high_byte": func(h *H) []any {
		v_a := DecString(h.Let("a"))
		_ = v_a
		v_b := DecString(h.Let("b"))
		_ = v_b
		r0 := rt.StringCompare(v_a, v_b)
		return []any{EncInt(r0)}
	},
	"core.string.compare/less": func(h *H) []any {
		v_a := DecString(h.Let("a"))
		_ = v_a
		v_b := DecString(h.Let("b"))
		_ = v_b
		r0 := rt.StringCompare(v_a, v_b)
		return []any{EncInt(r0)}
	},
	"core.string.compare/prefix": func(h *H) []any {
		v_a := DecString(h.Let("a"))
		_ = v_a
		v_b := DecString(h.Let("b"))
		_ = v_b
		r0 := rt.StringCompare(v_a, v_b)
		return []any{EncInt(r0)}
	},
	"core.string.concat/basic": func(h *H) []any {
		v_a := DecString(h.Let("a"))
		_ = v_a
		v_b := DecString(h.Let("b"))
		_ = v_b
		r0 := rt.StringConcat(v_a, v_b)
		return []any{EncString(r0)}
	},
	"core.string.concat/raw_bytes": func(h *H) []any {
		v_a := DecString(h.Let("a"))
		_ = v_a
		v_b := DecString(h.Let("b"))
		_ = v_b
		r0 := rt.StringConcat(v_a, v_b)
		return []any{EncString(r0)}
	},
	"core.string.decode_rune/ascii": func(h *H) []any {
		v_s := DecString(h.Let("s"))
		_ = v_s
		v_i := DecInt[int](h.Let("i"))
		_ = v_i
		r0, r1 := rt.DecodeRune(v_s, v_i)
		return []any{EncInt(r0), EncInt(r1)}
	},
	"core.string.decode_rune/four": func(h *H) []any {
		v_s := DecString(h.Let("s"))
		_ = v_s
		v_i := DecInt[int](h.Let("i"))
		_ = v_i
		r0, r1 := rt.DecodeRune(v_s, v_i)
		return []any{EncInt(r0), EncInt(r1)}
	},
	"core.string.decode_rune/invalid": func(h *H) []any {
		v_s := DecString(h.Let("s"))
		_ = v_s
		v_i := DecInt[int](h.Let("i"))
		_ = v_i
		r0, r1 := rt.DecodeRune(v_s, v_i)
		return []any{EncInt(r0), EncInt(r1)}
	},
	"core.string.decode_rune/overlong": func(h *H) []any {
		v_s := DecString(h.Let("s"))
		_ = v_s
		v_i := DecInt[int](h.Let("i"))
		_ = v_i
		r0, r1 := rt.DecodeRune(v_s, v_i)
		return []any{EncInt(r0), EncInt(r1)}
	},
	"core.string.decode_rune/surrogate": func(h *H) []any {
		v_s := DecString(h.Let("s"))
		_ = v_s
		v_i := DecInt[int](h.Let("i"))
		_ = v_i
		r0, r1 := rt.DecodeRune(v_s, v_i)
		return []any{EncInt(r0), EncInt(r1)}
	},
	"core.string.decode_rune/truncated": func(h *H) []any {
		v_s := DecString(h.Let("s"))
		_ = v_s
		v_i := DecInt[int](h.Let("i"))
		_ = v_i
		r0, r1 := rt.DecodeRune(v_s, v_i)
		return []any{EncInt(r0), EncInt(r1)}
	},
	"core.string.decode_rune/two": func(h *H) []any {
		v_s := DecString(h.Let("s"))
		_ = v_s
		v_i := DecInt[int](h.Let("i"))
		_ = v_i
		r0, r1 := rt.DecodeRune(v_s, v_i)
		return []any{EncInt(r0), EncInt(r1)}
	},
	"core.string.from_bytes/basic": func(h *H) []any {
		v_b := DecSlice(h.Let("b"), func(r json.RawMessage) uint8 { return DecInt[uint8](r) })
		_ = v_b
		r0 := rt.StringFromBytes(v_b)
		return []any{EncString(r0)}
	},
	"core.string.from_bytes/nil": func(h *H) []any {
		v_b := DecSlice(h.Let("b"), func(r json.RawMessage) uint8 { return DecInt[uint8](r) })
		_ = v_b
		r0 := rt.StringFromBytes(v_b)
		return []any{EncString(r0)}
	},
	"core.string.from_rune/ascii": func(h *H) []any {
		v_r := DecInt[int32](h.Let("r"))
		_ = v_r
		r0 := rt.StringFromRune(v_r)
		return []any{EncString(r0)}
	},
	"core.string.from_rune/huge": func(h *H) []any {
		v_r := DecInt[int64](h.Let("r"))
		_ = v_r
		r0 := rt.StringFromRune(v_r)
		return []any{EncString(r0)}
	},
	"core.string.from_rune/negative": func(h *H) []any {
		v_r := DecInt[int8](h.Let("r"))
		_ = v_r
		r0 := rt.StringFromRune(v_r)
		return []any{EncString(r0)}
	},
	"core.string.from_rune/surrogate": func(h *H) []any {
		v_r := DecInt[int](h.Let("r"))
		_ = v_r
		r0 := rt.StringFromRune(v_r)
		return []any{EncString(r0)}
	},
	"core.string.from_runes/basic": func(h *H) []any {
		v_r := DecSlice(h.Let("r"), func(r json.RawMessage) int32 { return DecInt[int32](r) })
		_ = v_r
		r0 := rt.StringFromRunes(v_r)
		return []any{EncString(r0)}
	},
	"core.string.from_runes/invalid": func(h *H) []any {
		v_r := DecSlice(h.Let("r"), func(r json.RawMessage) int32 { return DecInt[int32](r) })
		_ = v_r
		r0 := rt.StringFromRunes(v_r)
		return []any{EncString(r0)}
	},
	"core.string.index/first": func(h *H) []any {
		v_s := DecString(h.Let("s"))
		_ = v_s
		v_i := DecInt[int](h.Let("i"))
		_ = v_i
		r0 := rt.StringIndex(v_s, v_i)
		return []any{EncInt(r0)}
	},
	"core.string.index/negative": func(h *H) []any {
		v_s := DecString(h.Let("s"))
		_ = v_s
		v_i := DecInt[int](h.Let("i"))
		_ = v_i
		r0 := rt.StringIndex(v_s, v_i)
		return []any{EncInt(r0)}
	},
	"core.string.index/oob": func(h *H) []any {
		v_s := DecString(h.Let("s"))
		_ = v_s
		v_i := DecInt[int](h.Let("i"))
		_ = v_i
		r0 := rt.StringIndex(v_s, v_i)
		return []any{EncInt(r0)}
	},
	"core.string.index/unsigned_huge": func(h *H) []any {
		v_s := DecString(h.Let("s"))
		_ = v_s
		v_i := DecInt[uint64](h.Let("i"))
		_ = v_i
		r0 := rt.StringIndex(v_s, v_i)
		return []any{EncInt(r0)}
	},
	"core.string.slice/hi_oob": func(h *H) []any {
		v_s := DecString(h.Let("s"))
		_ = v_s
		v_lo := DecInt[int](h.Let("lo"))
		_ = v_lo
		v_hi := DecInt[int](h.Let("hi"))
		_ = v_hi
		r0 := rt.StringSlice(v_s, v_lo, v_hi)
		return []any{EncString(r0)}
	},
	"core.string.slice/inverted": func(h *H) []any {
		v_s := DecString(h.Let("s"))
		_ = v_s
		v_lo := DecInt[int](h.Let("lo"))
		_ = v_lo
		v_hi := DecInt[int](h.Let("hi"))
		_ = v_hi
		r0 := rt.StringSlice(v_s, v_lo, v_hi)
		return []any{EncString(r0)}
	},
	"core.string.slice/mid": func(h *H) []any {
		v_s := DecString(h.Let("s"))
		_ = v_s
		v_lo := DecInt[int](h.Let("lo"))
		_ = v_lo
		v_hi := DecInt[int](h.Let("hi"))
		_ = v_hi
		r0 := rt.StringSlice(v_s, v_lo, v_hi)
		return []any{EncString(r0)}
	},
	"core.string.slice/split_rune": func(h *H) []any {
		v_s := DecString(h.Let("s"))
		_ = v_s
		v_lo := DecInt[int](h.Let("lo"))
		_ = v_lo
		v_hi := DecInt[int](h.Let("hi"))
		_ = v_hi
		r0 := rt.StringSlice(v_s, v_lo, v_hi)
		return []any{EncString(r0)}
	},
	"core.string.to_bytes/basic": func(h *H) []any {
		v_s := DecString(h.Let("s"))
		_ = v_s
		r0 := rt.StringToBytes(v_s)
		return []any{EncSlice(r0, func(e uint8) any { return EncInt(e) })}
	},
	"core.string.to_bytes/empty": func(h *H) []any {
		v_s := DecString(h.Let("s"))
		_ = v_s
		r0 := rt.StringToBytes(v_s)
		return []any{EncSlice(r0, func(e uint8) any { return EncInt(e) })}
	},
	"core.string.to_runes/mixed": func(h *H) []any {
		v_s := DecString(h.Let("s"))
		_ = v_s
		r0 := rt.StringToRunes(v_s)
		return []any{EncSlice(r0, func(e int32) any { return EncInt(e) })}
	},
	"core.task.spawn/parent_continues": func(h *H) []any {
		rv := Await(func(t *rt.Task) { rt.Call(t, NewSpawnCheck()) })
		_ = rv
		r0 := rt.As[bool](rv[0])
		return []any{EncBool(r0)}
	},
	"lib.task.all/empty": func(h *H) []any {
		v_fns := DecSlice(h.Let("fns"), func(r json.RawMessage) func() { return nil })
		_ = v_fns
		rv := Await(func(t *rt.Task) { rt.LibTaskAll(t, v_fns) })
		_ = rv
		return []any{}
	},
	"std.context.background/root": func(h *H) []any {
		r0 := rt.StdContextBackground()
		return []any{EncZero(r0)}
	},
	"std.context.canceled/message": func(h *H) []any {
		r0 := rt.StdContextCanceled()
		return []any{EncError(r0)}
	},
	"std.context.deadline_exceeded/message": func(h *H) []any {
		r0 := rt.StdContextDeadlineExceeded()
		return []any{EncError(r0)}
	},
	"std.context.done/background": func(h *H) []any {
		v_ctx := rt.StdContextBackground()
		_ = v_ctx
		r0 := rt.StdContextContextDone(v_ctx)
		return []any{EncChan(r0, func(e struct{}) any { return EncZero(e) })}
	},
	"std.context.err/background": func(h *H) []any {
		v_ctx := rt.StdContextBackground()
		_ = v_ctx
		r0 := rt.StdContextContextErr(v_ctx)
		return []any{EncError(r0)}
	},
	"std.context.with_cancel/child": func(h *H) []any {
		v_parent := rt.StdContextBackground()
		_ = v_parent
		r0, r1 := rt.StdContextWithCancel(v_parent)
		return []any{EncZero(r0), EncZero(r1)}
	},
	"std.context.with_timeout/child": func(h *H) []any {
		v_parent := rt.StdContextBackground()
		_ = v_parent
		v_d := DecInt[int64](h.Let("d"))
		_ = v_d
		r0, r1 := rt.StdContextWithTimeout(v_parent, v_d)
		return []any{EncZero(r0), EncZero(r1)}
	},
	"std.errors.is/distinct": func(h *H) []any {
		v_err := DecError(h.Let("err"))
		_ = v_err
		v_target := DecError(h.Let("target"))
		_ = v_target
		r0 := rt.StdErrorsIs(v_err, v_target)
		return []any{EncBool(r0)}
	},
	"std.errors.is/nils": func(h *H) []any {
		v_err := DecError(h.Let("err"))
		_ = v_err
		v_target := DecError(h.Let("target"))
		_ = v_target
		r0 := rt.StdErrorsIs(v_err, v_target)
		return []any{EncBool(r0)}
	},
	"std.errors.is/same": func(h *H) []any {
		v_err := DecError(h.Let("err"))
		_ = v_err
		v_target := v_err
		_ = v_target
		r0 := rt.StdErrorsIs(v_err, v_target)
		return []any{EncBool(r0)}
	},
	"std.errors.new/message": func(h *H) []any {
		v_text := DecString(h.Let("text"))
		_ = v_text
		r0 := rt.StdErrorsNew(v_text)
		return []any{EncError(r0)}
	},
	"std.errors.unwrap/plain": func(h *H) []any {
		v_err := DecError(h.Let("err"))
		_ = v_err
		r0 := rt.StdErrorsUnwrap(v_err)
		return []any{EncError(r0)}
	},
	"std.runtime.gosched/alone": func(h *H) []any {
		rv := Await(func(t *rt.Task) { rt.StdRuntimeGosched(t) })
		_ = rv
		return []any{}
	},
	"std.sync.mutex.lock/unlocked": func(h *H) []any {
		v_m := new(rt.Mutex)
		_ = v_m
		rv := Await(func(t *rt.Task) { rt.StdSyncMutexLock(t, v_m) })
		_ = rv
		return []any{}
	},
	"std.sync.mutex.unlock/lock_then_unlock": func(h *H) []any {
		v_m := new(rt.Mutex)
		_ = v_m
		rv := Await(func(t *rt.Task) { rt.StdSyncMutexLock(t, v_m); rt.StdSyncMutexUnlock(v_m) })
		_ = rv
		return []any{}
	},
	"std.sync.waitgroup.add/negative": func(h *H) []any {
		v_wg := new(rt.WaitGroup)
		_ = v_wg
		v_delta := DecInt[int](h.Let("delta"))
		_ = v_delta
		rt.StdSyncWaitgroupAdd(v_wg, v_delta)
		return []any{}
	},
	"std.sync.waitgroup.add/positive": func(h *H) []any {
		v_wg := new(rt.WaitGroup)
		_ = v_wg
		v_delta := DecInt[int](h.Let("delta"))
		_ = v_delta
		rt.StdSyncWaitgroupAdd(v_wg, v_delta)
		return []any{}
	},
	"std.sync.waitgroup.done/underflow": func(h *H) []any {
		v_wg := new(rt.WaitGroup)
		_ = v_wg
		rt.StdSyncWaitgroupDone(v_wg)
		return []any{}
	},
	"std.sync.waitgroup.wait/zero_returns": func(h *H) []any {
		v_wg := new(rt.WaitGroup)
		_ = v_wg
		rv := Await(func(t *rt.Task) { rt.StdSyncWaitgroupWait(t, v_wg) })
		_ = rv
		return []any{}
	},
	"std.time.sleep/zero": func(h *H) []any {
		v_d := DecInt[int64](h.Let("d"))
		_ = v_d
		rv := Await(func(t *rt.Task) { rt.StdTimeSleep(t, v_d) })
		_ = rv
		return []any{}
	},
}
