// Code generated by goalchemy spec generate. DO NOT EDIT.
use crate::codec::*;
use crate::json::J;
use crate::rt::*;
use crate::H;

fn case_0(h: &H) -> Vec<J> {
    let v_ch = dec_chan(h.let_("ch"), &|r: &J| dec_int(r, "i64"), zero_int);
    let _roots = temp_root(&[v_ch.clone()]);
    let a0 = v_ch.clone();
    let r0 = chan_cap(a0.clone());
    vec![enc_int(&r0, "i64")]
}

fn case_1(h: &H) -> Vec<J> {
    let v_ch = dec_chan(h.let_("ch"), &|r: &J| dec_int(r, "i64"), zero_int);
    let _roots = temp_root(&[v_ch.clone()]);
    let a0 = v_ch.clone();
    chan_close(a0.clone());
    vec![]
}

fn case_2(h: &H) -> Vec<J> {
    let v_ch = dec_chan(h.let_("ch"), &|r: &J| dec_int(r, "i64"), zero_int);
    let _roots = temp_root(&[v_ch.clone()]);
    let a0 = v_ch.clone();
    chan_close(a0.clone());
    h.after("ch", enc_chan(&v_ch, &|e: &V| enc_int(e, "i64")));
    vec![]
}

fn case_3(h: &H) -> Vec<J> {
    let v_ch = dec_chan(h.let_("ch"), &|r: &J| dec_int(r, "i64"), zero_int);
    let _roots = temp_root(&[v_ch.clone()]);
    let a0 = v_ch.clone();
    chan_close(a0.clone());
    vec![]
}

fn case_4(h: &H) -> Vec<J> {
    let v_ch = dec_chan(h.let_("ch"), &|r: &J| dec_int(r, "i64"), zero_int);
    let _roots = temp_root(&[v_ch.clone()]);
    let a0 = v_ch.clone();
    let r0 = chan_len(a0.clone());
    vec![enc_int(&r0, "i64")]
}

fn case_5(h: &H) -> Vec<J> {
    let v_ch = dec_chan(h.let_("ch"), &|r: &J| dec_int(r, "i64"), zero_int);
    let _roots = temp_root(&[v_ch.clone()]);
    let a0 = v_ch.clone();
    let r0 = chan_len(a0.clone());
    vec![enc_int(&r0, "i64")]
}

fn case_6(h: &H) -> Vec<J> {
    let v_size = dec_int(h.let_("size"), "i64");
    let _roots = temp_root(&[v_size.clone()]);
    let a0 = v_size.clone();
    let r0 = make_chan(a0.clone(), zero_int);
    vec![enc_chan(&r0, &|e: &V| enc_int(e, "i64"))]
}

fn case_7(h: &H) -> Vec<J> {
    let v_size = dec_int(h.let_("size"), "i64");
    let _roots = temp_root(&[v_size.clone()]);
    let a0 = v_size.clone();
    let r0 = make_chan(a0.clone(), zero_int);
    vec![enc_chan(&r0, &|e: &V| enc_int(e, "i64"))]
}

fn case_8(h: &H) -> Vec<J> {
    let v_ch = dec_chan(h.let_("ch"), &|r: &J| dec_int(r, "i64"), zero_int);
    let _roots = temp_root(&[v_ch.clone()]);
    let a0 = v_ch.clone();
    let rv = run_isolated(move |t: &Rc<Task>| { chan_recv(t, a0.clone()); });
    let r0 = rv[0].clone();
    let r1 = rv[1].clone();
    h.after("ch", enc_chan(&v_ch, &|e: &V| enc_int(e, "i64")));
    vec![enc_int(&r0, "i64"), enc_bool(&r1)]
}

fn case_9(h: &H) -> Vec<J> {
    let v_ch = dec_chan(h.let_("ch"), &|r: &J| dec_string(r), zero_string);
    let _roots = temp_root(&[v_ch.clone()]);
    let a0 = v_ch.clone();
    let rv = run_isolated(move |t: &Rc<Task>| { chan_recv(t, a0.clone()); });
    let r0 = rv[0].clone();
    let r1 = rv[1].clone();
    vec![enc_string(&r0), enc_bool(&r1)]
}

fn case_10(h: &H) -> Vec<J> {
    let v_ch = dec_chan(h.let_("ch"), &|r: &J| dec_int(r, "i64"), zero_int);
    let _roots = temp_root(&[v_ch.clone()]);
    let a0 = v_ch.clone();
    let rv = run_isolated(move |t: &Rc<Task>| { chan_recv(t, a0.clone()); });
    let r0 = rv[0].clone();
    let r1 = rv[1].clone();
    vec![enc_int(&r0, "i64"), enc_bool(&r1)]
}

fn case_11(h: &H) -> Vec<J> {
    let v_ch = dec_chan(h.let_("ch"), &|r: &J| dec_int(r, "i64"), zero_int);
    let _roots = temp_root(&[v_ch.clone()]);
    let a0 = v_ch.clone();
    let rv = run_isolated(move |t: &Rc<Task>| { chan_recv(t, a0.clone()); });
    let r0 = rv[0].clone();
    let r1 = rv[1].clone();
    vec![enc_int(&r0, "i64"), enc_bool(&r1)]
}

fn case_12(h: &H) -> Vec<J> {
    let v_ch = dec_chan(h.let_("ch"), &|r: &J| dec_int(r, "i64"), zero_int);
    let _roots = temp_root(&[v_ch.clone()]);
    let a0 = v_ch.clone();
    let rv = run_isolated(move |t: &Rc<Task>| { chan_recv(t, a0.clone()); });
    let r0 = rv[0].clone();
    let r1 = rv[1].clone();
    vec![enc_int(&r0, "i64"), enc_bool(&r1)]
}

fn case_13(h: &H) -> Vec<J> {
    let v_ch = dec_chan(h.let_("ch"), &|r: &J| dec_int(r, "i64"), zero_int);
    let v_v = dec_int(h.let_("v"), "i64");
    let _roots = temp_root(&[v_ch.clone(), v_v.clone()]);
    let a0 = v_ch.clone();
    let a1 = v_v.clone();
    let rv = run_isolated(move |t: &Rc<Task>| { chan_send(t, a0.clone(), a1.clone()); });
    h.after("ch", enc_chan(&v_ch, &|e: &V| enc_int(e, "i64")));
    vec![]
}

fn case_14(h: &H) -> Vec<J> {
    let v_ch = dec_chan(h.let_("ch"), &|r: &J| dec_int(r, "i64"), zero_int);
    let v_v = dec_int(h.let_("v"), "i64");
    let _roots = temp_root(&[v_ch.clone(), v_v.clone()]);
    let a0 = v_ch.clone();
    let a1 = v_v.clone();
    let rv = run_isolated(move |t: &Rc<Task>| { chan_send(t, a0.clone(), a1.clone()); });
    vec![]
}

fn case_15(h: &H) -> Vec<J> {
    let v_ch = dec_chan(h.let_("ch"), &|r: &J| dec_int(r, "i64"), zero_int);
    let v_v = dec_int(h.let_("v"), "i64");
    let _roots = temp_root(&[v_ch.clone(), v_v.clone()]);
    let a0 = v_ch.clone();
    let a1 = v_v.clone();
    let rv = run_isolated(move |t: &Rc<Task>| { chan_send(t, a0.clone(), a1.clone()); });
    vec![]
}

fn case_16(h: &H) -> Vec<J> {
    let v_ch = dec_chan(h.let_("ch"), &|r: &J| dec_int(r, "i64"), zero_int);
    let v_v = dec_int(h.let_("v"), "i64");
    let _roots = temp_root(&[v_ch.clone(), v_v.clone()]);
    let a0 = v_ch.clone();
    let a1 = v_v.clone();
    let rv = run_isolated(move |t: &Rc<Task>| { chan_send(t, a0.clone(), a1.clone()); });
    vec![]
}

fn case_17(h: &H) -> Vec<J> {
    let v_ch = dec_chan(h.let_("ch"), &|r: &J| dec_string(r), zero_string);
    let v_v = dec_string(h.let_("v"));
    let _roots = temp_root(&[v_ch.clone(), v_v.clone()]);
    let a0 = v_ch.clone();
    let a1 = v_v.clone();
    let rv = run_isolated(move |t: &Rc<Task>| { chan_send(t, a0.clone(), a1.clone()); });
    vec![]
}

fn case_18(h: &H) -> Vec<J> {
    let v_a = dec_int(h.let_("a"), "i32");
    let v_b = dec_int(h.let_("b"), "i32");
    let _roots = temp_root(&[v_a.clone(), v_b.clone()]);
    let a0 = v_a.clone();
    let a1 = v_b.clone();
    let r0 = add_i32(a0.clone(), a1.clone());
    vec![enc_int(&r0, "i32")]
}

fn case_19(h: &H) -> Vec<J> {
    let v_a = dec_int(h.let_("a"), "i64");
    let v_b = dec_int(h.let_("b"), "i64");
    let _roots = temp_root(&[v_a.clone(), v_b.clone()]);
    let a0 = v_a.clone();
    let a1 = v_b.clone();
    let r0 = add_i64(a0.clone(), a1.clone());
    vec![enc_int(&r0, "i64")]
}

fn case_20(h: &H) -> Vec<J> {
    let v_a = dec_int(h.let_("a"), "i8");
    let v_b = dec_int(h.let_("b"), "i8");
    let _roots = temp_root(&[v_a.clone(), v_b.clone()]);
    let a0 = v_a.clone();
    let a1 = v_b.clone();
    let r0 = add_i8(a0.clone(), a1.clone());
    vec![enc_int(&r0, "i8")]
}

fn case_21(h: &H) -> Vec<J> {
    let v_a = dec_int(h.let_("a"), "i64");
    let v_b = dec_int(h.let_("b"), "i64");
    let _roots = temp_root(&[v_a.clone(), v_b.clone()]);
    let a0 = v_a.clone();
    let a1 = v_b.clone();
    let r0 = add_i64(a0.clone(), a1.clone());
    vec![enc_int(&r0, "i64")]
}

fn case_22(h: &H) -> Vec<J> {
    let v_a = dec_int(h.let_("a"), "u32");
    let v_b = dec_int(h.let_("b"), "u32");
    let _roots = temp_root(&[v_a.clone(), v_b.clone()]);
    let a0 = v_a.clone();
    let a1 = v_b.clone();
    let r0 = add_u32(a0.clone(), a1.clone());
    vec![enc_int(&r0, "u32")]
}

fn case_23(h: &H) -> Vec<J> {
    let v_a = dec_int(h.let_("a"), "u64");
    let v_b = dec_int(h.let_("b"), "u64");
    let _roots = temp_root(&[v_a.clone(), v_b.clone()]);
    let a0 = v_a.clone();
    let a1 = v_b.clone();
    let r0 = add_u64(a0.clone(), a1.clone());
    vec![enc_int(&r0, "u64")]
}

fn case_24(h: &H) -> Vec<J> {
    let v_a = dec_int(h.let_("a"), "i64");
    let v_b = dec_int(h.let_("b"), "i64");
    let _roots = temp_root(&[v_a.clone(), v_b.clone()]);
    let a0 = v_a.clone();
    let a1 = v_b.clone();
    let r0 = and_i64(a0.clone(), a1.clone());
    vec![enc_int(&r0, "i64")]
}

fn case_25(h: &H) -> Vec<J> {
    let v_a = dec_int(h.let_("a"), "u32");
    let v_b = dec_int(h.let_("b"), "u32");
    let _roots = temp_root(&[v_a.clone(), v_b.clone()]);
    let a0 = v_a.clone();
    let a1 = v_b.clone();
    let r0 = and_u32(a0.clone(), a1.clone());
    vec![enc_int(&r0, "u32")]
}

fn case_26(h: &H) -> Vec<J> {
    let v_a = dec_int(h.let_("a"), "i64");
    let v_b = dec_int(h.let_("b"), "i64");
    let _roots = temp_root(&[v_a.clone(), v_b.clone()]);
    let a0 = v_a.clone();
    let a1 = v_b.clone();
    let r0 = andnot_i64(a0.clone(), a1.clone());
    vec![enc_int(&r0, "i64")]
}

fn case_27(h: &H) -> Vec<J> {
    let v_a = dec_int(h.let_("a"), "u16");
    let v_b = dec_int(h.let_("b"), "u16");
    let _roots = temp_root(&[v_a.clone(), v_b.clone()]);
    let a0 = v_a.clone();
    let a1 = v_b.clone();
    let r0 = andnot_u16(a0.clone(), a1.clone());
    vec![enc_int(&r0, "u16")]
}

fn case_28(h: &H) -> Vec<J> {
    let v_a = dec_int(h.let_("a"), "u32");
    let v_b = dec_int(h.let_("b"), "u32");
    let _roots = temp_root(&[v_a.clone(), v_b.clone()]);
    let a0 = v_a.clone();
    let a1 = v_b.clone();
    let r0 = compare_int(a0.clone(), a1.clone());
    vec![enc_int(&r0, "i64")]
}

fn case_29(h: &H) -> Vec<J> {
    let v_a = dec_int(h.let_("a"), "i64");
    let v_b = dec_int(h.let_("b"), "i64");
    let _roots = temp_root(&[v_a.clone(), v_b.clone()]);
    let a0 = v_a.clone();
    let a1 = v_b.clone();
    let r0 = compare_int(a0.clone(), a1.clone());
    vec![enc_int(&r0, "i64")]
}

fn case_30(h: &H) -> Vec<J> {
    let v_a = dec_int(h.let_("a"), "u32");
    let v_b = dec_int(h.let_("b"), "u32");
    let _roots = temp_root(&[v_a.clone(), v_b.clone()]);
    let a0 = v_a.clone();
    let a1 = v_b.clone();
    let r0 = compare_int(a0.clone(), a1.clone());
    vec![enc_int(&r0, "i64")]
}

fn case_31(h: &H) -> Vec<J> {
    let v_a = dec_int(h.let_("a"), "u64");
    let v_b = dec_int(h.let_("b"), "u64");
    let _roots = temp_root(&[v_a.clone(), v_b.clone()]);
    let a0 = v_a.clone();
    let a1 = v_b.clone();
    let r0 = compare_uint(a0.clone(), a1.clone());
    vec![enc_int(&r0, "i64")]
}

fn case_32(h: &H) -> Vec<J> {
    let v_a = dec_int(h.let_("a"), "i32");
    let _roots = temp_root(&[v_a.clone()]);
    let a0 = v_a.clone();
    let r0 = to_u16(a0.clone());
    vec![enc_int(&r0, "u16")]
}

fn case_33(h: &H) -> Vec<J> {
    let v_a = dec_int(h.let_("a"), "i64");
    let _roots = temp_root(&[v_a.clone()]);
    let a0 = v_a.clone();
    let r0 = to_i64(a0.clone());
    vec![enc_int(&r0, "i64")]
}

fn case_34(h: &H) -> Vec<J> {
    let v_a = dec_int(h.let_("a"), "i8");
    let _roots = temp_root(&[v_a.clone()]);
    let a0 = v_a.clone();
    let r0 = to_u64(a0.clone());
    vec![enc_int(&r0, "u64")]
}

fn case_35(h: &H) -> Vec<J> {
    let v_a = dec_int(h.let_("a"), "i64");
    let _roots = temp_root(&[v_a.clone()]);
    let a0 = v_a.clone();
    let r0 = to_i8(a0.clone());
    vec![enc_int(&r0, "i8")]
}

fn case_36(h: &H) -> Vec<J> {
    let v_a = dec_int(h.let_("a"), "u32");
    let _roots = temp_root(&[v_a.clone()]);
    let a0 = v_a.clone();
    let r0 = to_i32(a0.clone());
    vec![enc_int(&r0, "i32")]
}

fn case_37(h: &H) -> Vec<J> {
    let v_a = dec_int(h.let_("a"), "u64");
    let _roots = temp_root(&[v_a.clone()]);
    let a0 = v_a.clone();
    let r0 = to_i64(a0.clone());
    vec![enc_int(&r0, "i64")]
}

fn case_38(h: &H) -> Vec<J> {
    let v_a = dec_int(h.let_("a"), "i32");
    let v_b = dec_int(h.let_("b"), "i32");
    let _roots = temp_root(&[v_a.clone(), v_b.clone()]);
    let a0 = v_a.clone();
    let a1 = v_b.clone();
    let r0 = div_i32(a0.clone(), a1.clone());
    vec![enc_int(&r0, "i32")]
}

fn case_39(h: &H) -> Vec<J> {
    let v_a = dec_int(h.let_("a"), "i64");
    let v_b = dec_int(h.let_("b"), "i64");
    let _roots = temp_root(&[v_a.clone(), v_b.clone()]);
    let a0 = v_a.clone();
    let a1 = v_b.clone();
    let r0 = div_i64(a0.clone(), a1.clone());
    vec![enc_int(&r0, "i64")]
}

fn case_40(h: &H) -> Vec<J> {
    let v_a = dec_int(h.let_("a"), "i8");
    let v_b = dec_int(h.let_("b"), "i8");
    let _roots = temp_root(&[v_a.clone(), v_b.clone()]);
    let a0 = v_a.clone();
    let a1 = v_b.clone();
    let r0 = div_i8(a0.clone(), a1.clone());
    vec![enc_int(&r0, "i8")]
}

fn case_41(h: &H) -> Vec<J> {
    let v_a = dec_int(h.let_("a"), "i64");
    let v_b = dec_int(h.let_("b"), "i64");
    let _roots = temp_root(&[v_a.clone(), v_b.clone()]);
    let a0 = v_a.clone();
    let a1 = v_b.clone();
    let r0 = div_i64(a0.clone(), a1.clone());
    vec![enc_int(&r0, "i64")]
}

fn case_42(h: &H) -> Vec<J> {
    let v_a = dec_int(h.let_("a"), "i64");
    let v_b = dec_int(h.let_("b"), "i64");
    let _roots = temp_root(&[v_a.clone(), v_b.clone()]);
    let a0 = v_a.clone();
    let a1 = v_b.clone();
    let r0 = div_i64(a0.clone(), a1.clone());
    vec![enc_int(&r0, "i64")]
}

fn case_43(h: &H) -> Vec<J> {
    let v_a = dec_int(h.let_("a"), "u64");
    let v_b = dec_int(h.let_("b"), "u64");
    let _roots = temp_root(&[v_a.clone(), v_b.clone()]);
    let a0 = v_a.clone();
    let a1 = v_b.clone();
    let r0 = div_u64(a0.clone(), a1.clone());
    vec![enc_int(&r0, "u64")]
}

fn case_44(h: &H) -> Vec<J> {
    let v_a = dec_int(h.let_("a"), "i32");
    let v_b = dec_int(h.let_("b"), "i32");
    let _roots = temp_root(&[v_a.clone(), v_b.clone()]);
    let a0 = v_a.clone();
    let a1 = v_b.clone();
    let r0 = mul_i32(a0.clone(), a1.clone());
    vec![enc_int(&r0, "i32")]
}

fn case_45(h: &H) -> Vec<J> {
    let v_a = dec_int(h.let_("a"), "i32");
    let v_b = dec_int(h.let_("b"), "i32");
    let _roots = temp_root(&[v_a.clone(), v_b.clone()]);
    let a0 = v_a.clone();
    let a1 = v_b.clone();
    let r0 = mul_i32(a0.clone(), a1.clone());
    vec![enc_int(&r0, "i32")]
}

fn case_46(h: &H) -> Vec<J> {
    let v_a = dec_int(h.let_("a"), "i64");
    let v_b = dec_int(h.let_("b"), "i64");
    let _roots = temp_root(&[v_a.clone(), v_b.clone()]);
    let a0 = v_a.clone();
    let a1 = v_b.clone();
    let r0 = mul_i64(a0.clone(), a1.clone());
    vec![enc_int(&r0, "i64")]
}

fn case_47(h: &H) -> Vec<J> {
    let v_a = dec_int(h.let_("a"), "i8");
    let v_b = dec_int(h.let_("b"), "i8");
    let _roots = temp_root(&[v_a.clone(), v_b.clone()]);
    let a0 = v_a.clone();
    let a1 = v_b.clone();
    let r0 = mul_i8(a0.clone(), a1.clone());
    vec![enc_int(&r0, "i8")]
}

fn case_48(h: &H) -> Vec<J> {
    let v_a = dec_int(h.let_("a"), "u32");
    let v_b = dec_int(h.let_("b"), "u32");
    let _roots = temp_root(&[v_a.clone(), v_b.clone()]);
    let a0 = v_a.clone();
    let a1 = v_b.clone();
    let r0 = mul_u32(a0.clone(), a1.clone());
    vec![enc_int(&r0, "u32")]
}

fn case_49(h: &H) -> Vec<J> {
    let v_a = dec_int(h.let_("a"), "u64");
    let v_b = dec_int(h.let_("b"), "u64");
    let _roots = temp_root(&[v_a.clone(), v_b.clone()]);
    let a0 = v_a.clone();
    let a1 = v_b.clone();
    let r0 = mul_u64(a0.clone(), a1.clone());
    vec![enc_int(&r0, "u64")]
}

fn case_50(h: &H) -> Vec<J> {
    let v_a = dec_int(h.let_("a"), "i32");
    let _roots = temp_root(&[v_a.clone()]);
    let a0 = v_a.clone();
    let r0 = neg_i32(a0.clone());
    vec![enc_int(&r0, "i32")]
}

fn case_51(h: &H) -> Vec<J> {
    let v_a = dec_int(h.let_("a"), "i64");
    let _roots = temp_root(&[v_a.clone()]);
    let a0 = v_a.clone();
    let r0 = neg_i64(a0.clone());
    vec![enc_int(&r0, "i64")]
}

fn case_52(h: &H) -> Vec<J> {
    let v_a = dec_int(h.let_("a"), "u64");
    let _roots = temp_root(&[v_a.clone()]);
    let a0 = v_a.clone();
    let r0 = neg_u64(a0.clone());
    vec![enc_int(&r0, "u64")]
}

fn case_53(h: &H) -> Vec<J> {
    let v_a = dec_int(h.let_("a"), "u8");
    let _roots = temp_root(&[v_a.clone()]);
    let a0 = v_a.clone();
    let r0 = neg_u8(a0.clone());
    vec![enc_int(&r0, "u8")]
}

fn case_54(h: &H) -> Vec<J> {
    let v_a = dec_int(h.let_("a"), "i64");
    let _roots = temp_root(&[v_a.clone()]);
    let a0 = v_a.clone();
    let r0 = not_i64(a0.clone());
    vec![enc_int(&r0, "i64")]
}

fn case_55(h: &H) -> Vec<J> {
    let v_a = dec_int(h.let_("a"), "u32");
    let _roots = temp_root(&[v_a.clone()]);
    let a0 = v_a.clone();
    let r0 = not_u32(a0.clone());
    vec![enc_int(&r0, "u32")]
}

fn case_56(h: &H) -> Vec<J> {
    let v_a = dec_int(h.let_("a"), "u8");
    let _roots = temp_root(&[v_a.clone()]);
    let a0 = v_a.clone();
    let r0 = not_u8(a0.clone());
    vec![enc_int(&r0, "u8")]
}

fn case_57(h: &H) -> Vec<J> {
    let v_a = dec_int(h.let_("a"), "i8");
    let v_b = dec_int(h.let_("b"), "i8");
    let _roots = temp_root(&[v_a.clone(), v_b.clone()]);
    let a0 = v_a.clone();
    let a1 = v_b.clone();
    let r0 = or_i8(a0.clone(), a1.clone());
    vec![enc_int(&r0, "i8")]
}

fn case_58(h: &H) -> Vec<J> {
    let v_a = dec_int(h.let_("a"), "u32");
    let v_b = dec_int(h.let_("b"), "u32");
    let _roots = temp_root(&[v_a.clone(), v_b.clone()]);
    let a0 = v_a.clone();
    let a1 = v_b.clone();
    let r0 = or_u32(a0.clone(), a1.clone());
    vec![enc_int(&r0, "u32")]
}

fn case_59(h: &H) -> Vec<J> {
    let v_a = dec_int(h.let_("a"), "u8");
    let v_b = dec_int(h.let_("b"), "u8");
    let _roots = temp_root(&[v_a.clone(), v_b.clone()]);
    let a0 = v_a.clone();
    let a1 = v_b.clone();
    let r0 = rem_u8(a0.clone(), a1.clone());
    vec![enc_int(&r0, "u8")]
}

fn case_60(h: &H) -> Vec<J> {
    let v_a = dec_int(h.let_("a"), "i64");
    let v_b = dec_int(h.let_("b"), "i64");
    let _roots = temp_root(&[v_a.clone(), v_b.clone()]);
    let a0 = v_a.clone();
    let a1 = v_b.clone();
    let r0 = rem_i64(a0.clone(), a1.clone());
    vec![enc_int(&r0, "i64")]
}

fn case_61(h: &H) -> Vec<J> {
    let v_a = dec_int(h.let_("a"), "i64");
    let v_b = dec_int(h.let_("b"), "i64");
    let _roots = temp_root(&[v_a.clone(), v_b.clone()]);
    let a0 = v_a.clone();
    let a1 = v_b.clone();
    let r0 = rem_i64(a0.clone(), a1.clone());
    vec![enc_int(&r0, "i64")]
}

fn case_62(h: &H) -> Vec<J> {
    let v_a = dec_int(h.let_("a"), "i64");
    let v_b = dec_int(h.let_("b"), "i64");
    let _roots = temp_root(&[v_a.clone(), v_b.clone()]);
    let a0 = v_a.clone();
    let a1 = v_b.clone();
    let r0 = rem_i64(a0.clone(), a1.clone());
    vec![enc_int(&r0, "i64")]
}

fn case_63(h: &H) -> Vec<J> {
    let v_a = dec_int(h.let_("a"), "u32");
    let v_b = dec_int(h.let_("b"), "u32");
    let _roots = temp_root(&[v_a.clone(), v_b.clone()]);
    let a0 = v_a.clone();
    let a1 = v_b.clone();
    let r0 = rem_u32(a0.clone(), a1.clone());
    vec![enc_int(&r0, "u32")]
}

fn case_64(h: &H) -> Vec<J> {
    let v_a = dec_int(h.let_("a"), "i64");
    let v_b = dec_int(h.let_("b"), "u64");
    let _roots = temp_root(&[v_a.clone(), v_b.clone()]);
    let a0 = v_a.clone();
    let a1 = v_b.clone();
    let r0 = shl_i64(a0.clone(), countu(&a1.clone()));
    vec![enc_int(&r0, "i64")]
}

fn case_65(h: &H) -> Vec<J> {
    let v_a = dec_int(h.let_("a"), "u64");
    let v_b = dec_int(h.let_("b"), "u64");
    let _roots = temp_root(&[v_a.clone(), v_b.clone()]);
    let a0 = v_a.clone();
    let a1 = v_b.clone();
    let r0 = shl_u64(a0.clone(), countu(&a1.clone()));
    vec![enc_int(&r0, "u64")]
}

fn case_66(h: &H) -> Vec<J> {
    let v_a = dec_int(h.let_("a"), "i64");
    let v_b = dec_int(h.let_("b"), "i64");
    let _roots = temp_root(&[v_a.clone(), v_b.clone()]);
    let a0 = v_a.clone();
    let a1 = v_b.clone();
    let r0 = shl_i64(a0.clone(), count(&a1.clone()));
    vec![enc_int(&r0, "i64")]
}

fn case_67(h: &H) -> Vec<J> {
    let v_a = dec_int(h.let_("a"), "i64");
    let v_b = dec_int(h.let_("b"), "i64");
    let _roots = temp_root(&[v_a.clone(), v_b.clone()]);
    let a0 = v_a.clone();
    let a1 = v_b.clone();
    let r0 = shl_i64(a0.clone(), count(&a1.clone()));
    vec![enc_int(&r0, "i64")]
}

fn case_68(h: &H) -> Vec<J> {
    let v_a = dec_int(h.let_("a"), "i8");
    let v_b = dec_int(h.let_("b"), "i64");
    let _roots = temp_root(&[v_a.clone(), v_b.clone()]);
    let a0 = v_a.clone();
    let a1 = v_b.clone();
    let r0 = shl_i8(a0.clone(), count(&a1.clone()));
    vec![enc_int(&r0, "i8")]
}

fn case_69(h: &H) -> Vec<J> {
    let v_a = dec_int(h.let_("a"), "i32");
    let v_b = dec_int(h.let_("b"), "u64");
    let _roots = temp_root(&[v_a.clone(), v_b.clone()]);
    let a0 = v_a.clone();
    let a1 = v_b.clone();
    let r0 = shl_i32(a0.clone(), countu(&a1.clone()));
    vec![enc_int(&r0, "i32")]
}

fn case_70(h: &H) -> Vec<J> {
    let v_a = dec_int(h.let_("a"), "i64");
    let v_b = dec_int(h.let_("b"), "u64");
    let _roots = temp_root(&[v_a.clone(), v_b.clone()]);
    let a0 = v_a.clone();
    let a1 = v_b.clone();
    let r0 = shr_i64(a0.clone(), countu(&a1.clone()));
    vec![enc_int(&r0, "i64")]
}

fn case_71(h: &H) -> Vec<J> {
    let v_a = dec_int(h.let_("a"), "i8");
    let v_b = dec_int(h.let_("b"), "i64");
    let _roots = temp_root(&[v_a.clone(), v_b.clone()]);
    let a0 = v_a.clone();
    let a1 = v_b.clone();
    let r0 = shr_i8(a0.clone(), count(&a1.clone()));
    vec![enc_int(&r0, "i8")]
}

fn case_72(h: &H) -> Vec<J> {
    let v_a = dec_int(h.let_("a"), "u8");
    let v_b = dec_int(h.let_("b"), "i64");
    let _roots = temp_root(&[v_a.clone(), v_b.clone()]);
    let a0 = v_a.clone();
    let a1 = v_b.clone();
    let r0 = shr_u8(a0.clone(), count(&a1.clone()));
    vec![enc_int(&r0, "u8")]
}

fn case_73(h: &H) -> Vec<J> {
    let v_a = dec_int(h.let_("a"), "u64");
    let v_b = dec_int(h.let_("b"), "u64");
    let _roots = temp_root(&[v_a.clone(), v_b.clone()]);
    let a0 = v_a.clone();
    let a1 = v_b.clone();
    let r0 = shr_u64(a0.clone(), countu(&a1.clone()));
    vec![enc_int(&r0, "u64")]
}

fn case_74(h: &H) -> Vec<J> {
    let v_a = dec_int(h.let_("a"), "i8");
    let v_b = dec_int(h.let_("b"), "i64");
    let _roots = temp_root(&[v_a.clone(), v_b.clone()]);
    let a0 = v_a.clone();
    let a1 = v_b.clone();
    let r0 = shr_i8(a0.clone(), count(&a1.clone()));
    vec![enc_int(&r0, "i8")]
}

fn case_75(h: &H) -> Vec<J> {
    let v_a = dec_int(h.let_("a"), "i32");
    let v_b = dec_int(h.let_("b"), "i64");
    let _roots = temp_root(&[v_a.clone(), v_b.clone()]);
    let a0 = v_a.clone();
    let a1 = v_b.clone();
    let r0 = shr_i32(a0.clone(), count(&a1.clone()));
    vec![enc_int(&r0, "i32")]
}

fn case_76(h: &H) -> Vec<J> {
    let v_a = dec_int(h.let_("a"), "i16");
    let v_b = dec_int(h.let_("b"), "i16");
    let _roots = temp_root(&[v_a.clone(), v_b.clone()]);
    let a0 = v_a.clone();
    let a1 = v_b.clone();
    let r0 = sub_i16(a0.clone(), a1.clone());
    vec![enc_int(&r0, "i16")]
}

fn case_77(h: &H) -> Vec<J> {
    let v_a = dec_int(h.let_("a"), "i64");
    let v_b = dec_int(h.let_("b"), "i64");
    let _roots = temp_root(&[v_a.clone(), v_b.clone()]);
    let a0 = v_a.clone();
    let a1 = v_b.clone();
    let r0 = sub_i64(a0.clone(), a1.clone());
    vec![enc_int(&r0, "i64")]
}

fn case_78(h: &H) -> Vec<J> {
    let v_a = dec_int(h.let_("a"), "u8");
    let v_b = dec_int(h.let_("b"), "u8");
    let _roots = temp_root(&[v_a.clone(), v_b.clone()]);
    let a0 = v_a.clone();
    let a1 = v_b.clone();
    let r0 = sub_u8(a0.clone(), a1.clone());
    vec![enc_int(&r0, "u8")]
}

fn case_79(h: &H) -> Vec<J> {
    let v_a = dec_int(h.let_("a"), "u64");
    let v_b = dec_int(h.let_("b"), "u64");
    let _roots = temp_root(&[v_a.clone(), v_b.clone()]);
    let a0 = v_a.clone();
    let a1 = v_b.clone();
    let r0 = sub_u64(a0.clone(), a1.clone());
    vec![enc_int(&r0, "u64")]
}

fn case_80(h: &H) -> Vec<J> {
    let v_a = dec_int(h.let_("a"), "i32");
    let v_b = dec_int(h.let_("b"), "i32");
    let _roots = temp_root(&[v_a.clone(), v_b.clone()]);
    let a0 = v_a.clone();
    let a1 = v_b.clone();
    let r0 = xor_i32(a0.clone(), a1.clone());
    vec![enc_int(&r0, "i32")]
}

fn case_81(h: &H) -> Vec<J> {
    let v_a = dec_int(h.let_("a"), "u64");
    let v_b = dec_int(h.let_("b"), "u64");
    let _roots = temp_root(&[v_a.clone(), v_b.clone()]);
    let a0 = v_a.clone();
    let a1 = v_b.clone();
    let r0 = xor_u64(a0.clone(), a1.clone());
    vec![enc_int(&r0, "u64")]
}

fn case_82(h: &H) -> Vec<J> {
    let v_m = dec_map(h.let_("m"), &|r: &J| dec_int(r, "i64"), &|r: &J| dec_int(r, "i64"));
    let _roots = temp_root(&[v_m.clone()]);
    let a0 = v_m.clone();
    map_clear(a0.clone());
    h.after("m", enc_map(&v_m, &|e: &V| enc_int(e, "i64"), &|e: &V| enc_int(e, "i64")));
    vec![]
}

fn case_83(h: &H) -> Vec<J> {
    let v_m = dec_map(h.let_("m"), &|r: &J| dec_int(r, "i64"), &|r: &J| dec_int(r, "i64"));
    let v_k = dec_int(h.let_("k"), "i64");
    let _roots = temp_root(&[v_m.clone(), v_k.clone()]);
    let a0 = v_m.clone();
    let a1 = v_k.clone();
    map_delete(a0.clone(), a1.clone(), vkey);
    vec![]
}

fn case_84(h: &H) -> Vec<J> {
    let v_m = dec_map(h.let_("m"), &|r: &J| dec_int(r, "i64"), &|r: &J| dec_int(r, "i64"));
    let v_k = dec_int(h.let_("k"), "i64");
    let _roots = temp_root(&[v_m.clone(), v_k.clone()]);
    let a0 = v_m.clone();
    let a1 = v_k.clone();
    map_delete(a0.clone(), a1.clone(), vkey);
    h.after("m", enc_map(&v_m, &|e: &V| enc_int(e, "i64"), &|e: &V| enc_int(e, "i64")));
    vec![]
}

fn case_85(h: &H) -> Vec<J> {
    let v_m = dec_map(h.let_("m"), &|r: &J| dec_int(r, "i64"), &|r: &J| dec_int(r, "i64"));
    let _roots = temp_root(&[v_m.clone()]);
    let a0 = v_m.clone();
    let r0 = map_keys(a0.clone());
    vec![enc_slice(&r0, &|e: &V| enc_int(e, "i64"))]
}

fn case_86(h: &H) -> Vec<J> {
    let v_m = dec_map(h.let_("m"), &|r: &J| dec_int(r, "i64"), &|r: &J| dec_int(r, "i64"));
    let _roots = temp_root(&[v_m.clone()]);
    let a0 = v_m.clone();
    let r0 = map_len(a0.clone());
    vec![enc_int(&r0, "i64")]
}

fn case_87(h: &H) -> Vec<J> {
    let v_m = dec_map(h.let_("m"), &|r: &J| dec_int(r, "i64"), &|r: &J| dec_int(r, "i64"));
    let _roots = temp_root(&[v_m.clone()]);
    let a0 = v_m.clone();
    let r0 = map_len(a0.clone());
    vec![enc_int(&r0, "i64")]
}

fn case_88(h: &H) -> Vec<J> {
    let v_m = dec_map(h.let_("m"), &|r: &J| dec_int(r, "i64"), &|r: &J| dec_string(r));
    let v_k = dec_int(h.let_("k"), "i64");
    let _roots = temp_root(&[v_m.clone(), v_k.clone()]);
    let a0 = v_m.clone();
    let a1 = v_k.clone();
    let rv = map_get(a0.clone(), a1.clone(), vkey, zero_string);
    let r0 = rv.at(0);
    let r1 = rv.at(1);
    vec![enc_string(&r0), enc_bool(&r1)]
}

fn case_89(h: &H) -> Vec<J> {
    let v_m = dec_map(h.let_("m"), &|r: &J| dec_string(r), &|r: &J| dec_int(r, "i64"));
    let v_k = dec_string(h.let_("k"));
    let _roots = temp_root(&[v_m.clone(), v_k.clone()]);
    let a0 = v_m.clone();
    let a1 = v_k.clone();
    let rv = map_get(a0.clone(), a1.clone(), vkey, zero_int);
    let r0 = rv.at(0);
    let r1 = rv.at(1);
    vec![enc_int(&r0, "i64"), enc_bool(&r1)]
}

fn case_90(h: &H) -> Vec<J> {
    let _roots = temp_root(&[]);
    let r0 = make_map(vkey);
    vec![enc_map(&r0, &|e: &V| enc_string(e), &|e: &V| enc_int(e, "i64"))]
}

fn case_91(h: &H) -> Vec<J> {
    let v_m = dec_map(h.let_("m"), &|r: &J| dec_int(r, "i64"), &|r: &J| dec_int(r, "i64"));
    let v_k = dec_int(h.let_("k"), "i64");
    let v_v = dec_int(h.let_("v"), "i64");
    let _roots = temp_root(&[v_m.clone(), v_k.clone(), v_v.clone()]);
    let a0 = v_m.clone();
    let a1 = v_k.clone();
    let a2 = v_v.clone();
    map_set(a0.clone(), a1.clone(), a2.clone());
    vec![]
}

fn case_92(h: &H) -> Vec<J> {
    let v_m = dec_map(h.let_("m"), &|r: &J| dec_int(r, "i64"), &|r: &J| dec_int(r, "i64"));
    let v_k = dec_int(h.let_("k"), "i64");
    let v_v = dec_int(h.let_("v"), "i64");
    let _roots = temp_root(&[v_m.clone(), v_k.clone(), v_v.clone()]);
    let a0 = v_m.clone();
    let a1 = v_k.clone();
    let a2 = v_v.clone();
    map_set(a0.clone(), a1.clone(), a2.clone());
    h.after("m", enc_map(&v_m, &|e: &V| enc_int(e, "i64"), &|e: &V| enc_int(e, "i64")));
    vec![]
}

fn case_93(h: &H) -> Vec<J> {
    let v_v = dec_bool(h.let_("v"));
    let _roots = temp_root(&[v_v.clone()]);
    let a0 = v_v.clone();
    let r0 = print_string(a0.clone(), false);
    vec![enc_string(&r0)]
}

fn case_94(h: &H) -> Vec<J> {
    let v_v = dec_string(h.let_("v"));
    let _roots = temp_root(&[v_v.clone()]);
    let a0 = v_v.clone();
    let r0 = print_string(a0.clone(), false);
    vec![enc_string(&r0)]
}

fn case_95(h: &H) -> Vec<J> {
    let v_v = dec_int(h.let_("v"), "i64");
    let _roots = temp_root(&[v_v.clone()]);
    let a0 = v_v.clone();
    let r0 = print_string(a0.clone(), false);
    vec![enc_string(&r0)]
}

fn case_96(h: &H) -> Vec<J> {
    let v_v = dec_int(h.let_("v"), "u64");
    let _roots = temp_root(&[v_v.clone()]);
    let a0 = v_v.clone();
    let r0 = print_string(a0.clone(), true);
    vec![enc_string(&r0)]
}

fn case_97(h: &H) -> Vec<J> {
    let v_a = dec_chan(h.let_("a"), &|r: &J| dec_int(r, "i64"), zero_int);
    let v_b = dec_chan(h.let_("b"), &|r: &J| dec_int(r, "i64"), zero_int);
    let v_dflt = dec_bool(h.let_("dflt"));
    let _roots = temp_root(&[v_a.clone(), v_b.clone(), v_dflt.clone()]);
    let a0 = v_a.clone();
    let a1 = v_b.clone();
    let a2 = v_dflt.clone();
    let rv = run_isolated(move |t: &Rc<Task>| { harness_select2(t, a0.clone(), a1.clone(), a2.clone()); });
    let r0 = rv[0].clone();
    vec![enc_int(&r0, "i64")]
}

fn case_98(h: &H) -> Vec<J> {
    let v_a = dec_chan(h.let_("a"), &|r: &J| dec_int(r, "i64"), zero_int);
    let v_b = dec_chan(h.let_("b"), &|r: &J| dec_int(r, "i64"), zero_int);
    let v_dflt = dec_bool(h.let_("dflt"));
    let _roots = temp_root(&[v_a.clone(), v_b.clone(), v_dflt.clone()]);
    let a0 = v_a.clone();
    let a1 = v_b.clone();
    let a2 = v_dflt.clone();
    let rv = run_isolated(move |t: &Rc<Task>| { harness_select2(t, a0.clone(), a1.clone(), a2.clone()); });
    let r0 = rv[0].clone();
    vec![enc_int(&r0, "i64")]
}

fn case_99(h: &H) -> Vec<J> {
    let v_a = dec_chan(h.let_("a"), &|r: &J| dec_int(r, "i64"), zero_int);
    let v_b = dec_chan(h.let_("b"), &|r: &J| dec_int(r, "i64"), zero_int);
    let v_dflt = dec_bool(h.let_("dflt"));
    let _roots = temp_root(&[v_a.clone(), v_b.clone(), v_dflt.clone()]);
    let a0 = v_a.clone();
    let a1 = v_b.clone();
    let a2 = v_dflt.clone();
    let rv = run_isolated(move |t: &Rc<Task>| { harness_select2(t, a0.clone(), a1.clone(), a2.clone()); });
    let r0 = rv[0].clone();
    vec![enc_int(&r0, "i64")]
}

fn case_100(h: &H) -> Vec<J> {
    let v_a = dec_chan(h.let_("a"), &|r: &J| dec_int(r, "i64"), zero_int);
    let v_b = dec_chan(h.let_("b"), &|r: &J| dec_int(r, "i64"), zero_int);
    let v_dflt = dec_bool(h.let_("dflt"));
    let _roots = temp_root(&[v_a.clone(), v_b.clone(), v_dflt.clone()]);
    let a0 = v_a.clone();
    let a1 = v_b.clone();
    let a2 = v_dflt.clone();
    let rv = run_isolated(move |t: &Rc<Task>| { harness_select2(t, a0.clone(), a1.clone(), a2.clone()); });
    let r0 = rv[0].clone();
    h.after("b", enc_chan(&v_b, &|e: &V| enc_int(e, "i64")));
    vec![enc_int(&r0, "i64")]
}

fn case_101(h: &H) -> Vec<J> {
    let v_s = dec_slice(h.let_("s"), &|r: &J| dec_string(r), zero_string);
    let v_vs = dec_slice(h.let_("vs"), &|r: &J| dec_string(r), zero_string);
    let _roots = temp_root(&[v_s.clone(), v_vs.clone()]);
    let a0 = v_s.clone();
    let a1 = v_vs.clone();
    let r0 = append_slice(a0.clone(), a1.clone(), None);
    vec![enc_slice(&r0, &|e: &V| enc_string(e))]
}

fn case_102(h: &H) -> Vec<J> {
    let v_s = dec_slice(h.let_("s"), &|r: &J| dec_int(r, "i64"), zero_int);
    let v_vs = dec_slice(h.let_("vs"), &|r: &J| dec_int(r, "i64"), zero_int);
    let _roots = temp_root(&[v_s.clone(), v_vs.clone()]);
    let a0 = v_s.clone();
    let a1 = v_vs.clone();
    let r0 = append_slice(a0.clone(), a1.clone(), None);
    vec![enc_slice(&r0, &|e: &V| enc_int(e, "i64"))]
}

fn case_103(h: &H) -> Vec<J> {
    let v_s = dec_slice(h.let_("s"), &|r: &J| dec_int(r, "i64"), zero_int);
    let v_vs = dec_slice(h.let_("vs"), &|r: &J| dec_int(r, "i64"), zero_int);
    let _roots = temp_root(&[v_s.clone(), v_vs.clone()]);
    let a0 = v_s.clone();
    let a1 = v_vs.clone();
    let r0 = append_slice(a0.clone(), a1.clone(), None);
    vec![enc_slice(&r0, &|e: &V| enc_int(e, "i64"))]
}

fn case_104(h: &H) -> Vec<J> {
    let v_s = dec_slice(h.let_("s"), &|r: &J| dec_int(r, "i64"), zero_int);
    let v_t = view(&v_s, h.let_("t"));
    let v_vs = dec_slice(h.let_("vs"), &|r: &J| dec_int(r, "i64"), zero_int);
    let _roots = temp_root(&[v_s.clone(), v_t.clone(), v_vs.clone()]);
    let a0 = v_s.clone();
    let a1 = v_vs.clone();
    let r0 = append_slice(a0.clone(), a1.clone(), None);
    h.after("t", enc_slice(&v_t, &|e: &V| enc_int(e, "i64")));
    vec![enc_slice(&r0, &|e: &V| enc_int(e, "i64"))]
}

fn case_105(h: &H) -> Vec<J> {
    let v_s = dec_slice(h.let_("s"), &|r: &J| dec_int(r, "i64"), zero_int);
    let v_vs = dec_slice(h.let_("vs"), &|r: &J| dec_int(r, "i64"), zero_int);
    let _roots = temp_root(&[v_s.clone(), v_vs.clone()]);
    let a0 = v_s.clone();
    let a1 = v_vs.clone();
    let r0 = append_slice(a0.clone(), a1.clone(), None);
    vec![enc_slice(&r0, &|e: &V| enc_int(e, "i64"))]
}

fn case_106(h: &H) -> Vec<J> {
    let v_s = dec_slice(h.let_("s"), &|r: &J| dec_int(r, "i64"), zero_int);
    let v_a = view(&v_s, h.let_("a"));
    let v_vs = view(&v_s, h.let_("vs"));
    let _roots = temp_root(&[v_s.clone(), v_a.clone(), v_vs.clone()]);
    let a0 = v_a.clone();
    let a1 = v_vs.clone();
    let r0 = append_slice(a0.clone(), a1.clone(), None);
    h.after("s", enc_slice(&v_s, &|e: &V| enc_int(e, "i64")));
    vec![enc_slice(&r0, &|e: &V| enc_int(e, "i64"))]
}

fn case_107(h: &H) -> Vec<J> {
    let v_s = dec_slice(h.let_("s"), &|r: &J| dec_int(r, "i64"), zero_int);
    let v_t = view(&v_s, h.let_("t"));
    let _roots = temp_root(&[v_s.clone(), v_t.clone()]);
    let a0 = v_t.clone();
    clear_slice(a0.clone(), zero_int);
    h.after("s", enc_slice(&v_s, &|e: &V| enc_int(e, "i64")));
    vec![]
}

fn case_108(h: &H) -> Vec<J> {
    let v_s = dec_slice(h.let_("s"), &|r: &J| dec_int(r, "i64"), zero_int);
    let v_d = view(&v_s, h.let_("d"));
    let v_src = view(&v_s, h.let_("src"));
    let _roots = temp_root(&[v_s.clone(), v_d.clone(), v_src.clone()]);
    let a0 = v_d.clone();
    let a1 = v_src.clone();
    let r0 = copy(a0.clone(), a1.clone(), None);
    h.after("s", enc_slice(&v_s, &|e: &V| enc_int(e, "i64")));
    vec![enc_int(&r0, "i64")]
}

fn case_109(h: &H) -> Vec<J> {
    let v_d = dec_byte_slice(h.let_("d"));
    let v_src = dec_byte_slice(h.let_("src"));
    let _roots = temp_root(&[v_d.clone(), v_src.clone()]);
    let a0 = v_d.clone();
    let a1 = v_src.clone();
    let r0 = copy(a0.clone(), a1.clone(), None);
    h.after("d", enc_slice(&v_d, &|e: &V| enc_int(e, "u8")));
    vec![enc_int(&r0, "i64")]
}

fn case_110(h: &H) -> Vec<J> {
    let v_s = dec_slice(h.let_("s"), &|r: &J| dec_int(r, "i64"), zero_int);
    let v_i = dec_int(h.let_("i"), "i64");
    let _roots = temp_root(&[v_s.clone(), v_i.clone()]);
    let a0 = v_s.clone();
    let a1 = v_i.clone();
    let r0 = sget(a0.clone(), a1.clone());
    vec![enc_int(&r0, "i64")]
}

fn case_111(h: &H) -> Vec<J> {
    let v_s = dec_slice(h.let_("s"), &|r: &J| dec_int(r, "i64"), zero_int);
    let v_i = dec_int(h.let_("i"), "i64");
    let _roots = temp_root(&[v_s.clone(), v_i.clone()]);
    let a0 = v_s.clone();
    let a1 = v_i.clone();
    let r0 = sget(a0.clone(), a1.clone());
    vec![enc_int(&r0, "i64")]
}

fn case_112(h: &H) -> Vec<J> {
    let v_s = dec_slice(h.let_("s"), &|r: &J| dec_string(r), zero_string);
    let v_i = dec_int(h.let_("i"), "i64");
    let _roots = temp_root(&[v_s.clone(), v_i.clone()]);
    let a0 = v_s.clone();
    let a1 = v_i.clone();
    let r0 = sget(a0.clone(), a1.clone());
    vec![enc_string(&r0)]
}

fn case_113(h: &H) -> Vec<J> {
    let v_len = dec_int(h.let_("len"), "i64");
    let v_cap = dec_int(h.let_("cap"), "i64");
    let _roots = temp_root(&[v_len.clone(), v_cap.clone()]);
    let a0 = v_len.clone();
    let a1 = v_cap.clone();
    let r0 = make_slice(a0.clone(), a1.clone(), zero_int, false);
    vec![enc_slice(&r0, &|e: &V| enc_int(e, "i64"))]
}

fn case_114(h: &H) -> Vec<J> {
    let v_len = dec_int(h.let_("len"), "i64");
    let v_cap = dec_int(h.let_("cap"), "i64");
    let _roots = temp_root(&[v_len.clone(), v_cap.clone()]);
    let a0 = v_len.clone();
    let a1 = v_cap.clone();
    let r0 = make_slice(a0.clone(), a1.clone(), zero_int, true);
    vec![enc_slice(&r0, &|e: &V| enc_int(e, "u8"))]
}

fn case_115(h: &H) -> Vec<J> {
    let v_len = dec_int(h.let_("len"), "i64");
    let v_cap = dec_int(h.let_("cap"), "i64");
    let _roots = temp_root(&[v_len.clone(), v_cap.clone()]);
    let a0 = v_len.clone();
    let a1 = v_cap.clone();
    let r0 = make_slice(a0.clone(), a1.clone(), zero_int, false);
    vec![enc_slice(&r0, &|e: &V| enc_int(e, "i64"))]
}

fn case_116(h: &H) -> Vec<J> {
    let v_s = dec_slice(h.let_("s"), &|r: &J| dec_int(r, "i64"), zero_int);
    let v_lo = dec_int(h.let_("lo"), "i64");
    let v_hi = dec_int(h.let_("hi"), "i64");
    let v_max = dec_int(h.let_("max"), "i64");
    let _roots = temp_root(&[v_s.clone(), v_lo.clone(), v_hi.clone(), v_max.clone()]);
    let a0 = v_s.clone();
    let a1 = v_lo.clone();
    let a2 = v_hi.clone();
    let a3 = v_max.clone();
    let r0 = reslice(a0.clone(), a1.clone(), a2.clone(), a3.clone(), false);
    vec![enc_slice(&r0, &|e: &V| enc_int(e, "i64"))]
}

fn case_117(h: &H) -> Vec<J> {
    let v_s = dec_slice(h.let_("s"), &|r: &J| dec_int(r, "i64"), zero_int);
    let v_lo = dec_int(h.let_("lo"), "i64");
    let v_hi = dec_int(h.let_("hi"), "i64");
    let v_max = dec_int(h.let_("max"), "i64");
    let _roots = temp_root(&[v_s.clone(), v_lo.clone(), v_hi.clone(), v_max.clone()]);
    let a0 = v_s.clone();
    let a1 = v_lo.clone();
    let a2 = v_hi.clone();
    let a3 = v_max.clone();
    let r0 = reslice(a0.clone(), a1.clone(), a2.clone(), a3.clone(), false);
    vec![enc_slice(&r0, &|e: &V| enc_int(e, "i64"))]
}

fn case_118(h: &H) -> Vec<J> {
    let v_s = dec_slice(h.let_("s"), &|r: &J| dec_int(r, "i64"), zero_int);
    let v_lo = dec_int(h.let_("lo"), "i64");
    let v_hi = dec_int(h.let_("hi"), "i64");
    let v_max = dec_int(h.let_("max"), "i64");
    let _roots = temp_root(&[v_s.clone(), v_lo.clone(), v_hi.clone(), v_max.clone()]);
    let a0 = v_s.clone();
    let a1 = v_lo.clone();
    let a2 = v_hi.clone();
    let a3 = v_max.clone();
    let r0 = reslice(a0.clone(), a1.clone(), a2.clone(), a3.clone(), false);
    vec![enc_slice(&r0, &|e: &V| enc_int(e, "i64"))]
}

fn case_119(h: &H) -> Vec<J> {
    let v_s = dec_slice(h.let_("s"), &|r: &J| dec_int(r, "i64"), zero_int);
    let v_lo = dec_int(h.let_("lo"), "i64");
    let v_hi = dec_int(h.let_("hi"), "i64");
    let v_max = dec_int(h.let_("max"), "i64");
    let _roots = temp_root(&[v_s.clone(), v_lo.clone(), v_hi.clone(), v_max.clone()]);
    let a0 = v_s.clone();
    let a1 = v_lo.clone();
    let a2 = v_hi.clone();
    let a3 = v_max.clone();
    let r0 = reslice(a0.clone(), a1.clone(), a2.clone(), a3.clone(), false);
    vec![enc_slice(&r0, &|e: &V| enc_int(e, "i64"))]
}

fn case_120(h: &H) -> Vec<J> {
    let v_s = dec_slice(h.let_("s"), &|r: &J| dec_int(r, "i64"), zero_int);
    let v_lo = dec_int(h.let_("lo"), "i64");
    let v_hi = dec_int(h.let_("hi"), "i64");
    let v_max = dec_int(h.let_("max"), "i64");
    let _roots = temp_root(&[v_s.clone(), v_lo.clone(), v_hi.clone(), v_max.clone()]);
    let a0 = v_s.clone();
    let a1 = v_lo.clone();
    let a2 = v_hi.clone();
    let a3 = v_max.clone();
    let r0 = reslice(a0.clone(), a1.clone(), a2.clone(), a3.clone(), false);
    vec![enc_slice(&r0, &|e: &V| enc_int(e, "i64"))]
}

fn case_121(h: &H) -> Vec<J> {
    let v_s = dec_slice(h.let_("s"), &|r: &J| dec_int(r, "i64"), zero_int);
    let v_t = view(&v_s, h.let_("t"));
    let v_i = dec_int(h.let_("i"), "i64");
    let v_v = dec_int(h.let_("v"), "i64");
    let _roots = temp_root(&[v_s.clone(), v_t.clone(), v_i.clone(), v_v.clone()]);
    let a0 = v_t.clone();
    let a1 = v_i.clone();
    let a2 = v_v.clone();
    sset(a0.clone(), a1.clone(), a2.clone());
    h.after("s", enc_slice(&v_s, &|e: &V| enc_int(e, "i64")));
    vec![]
}

fn case_122(h: &H) -> Vec<J> {
    let v_s = dec_slice(h.let_("s"), &|r: &J| dec_int(r, "i64"), zero_int);
    let v_i = dec_int(h.let_("i"), "i64");
    let v_v = dec_int(h.let_("v"), "i64");
    let _roots = temp_root(&[v_s.clone(), v_i.clone(), v_v.clone()]);
    let a0 = v_s.clone();
    let a1 = v_i.clone();
    let a2 = v_v.clone();
    sset(a0.clone(), a1.clone(), a2.clone());
    vec![]
}

fn case_123(h: &H) -> Vec<J> {
    let v_s = dec_slice(h.let_("s"), &|r: &J| dec_int(r, "i64"), zero_int);
    let _roots = temp_root(&[v_s.clone()]);
    let a0 = v_s.clone();
    let r0 = slice_to_array(a0.clone(), 2, None);
    vec![enc_array(&r0, &|e: &V| enc_int(e, "i64"))]
}

fn case_124(h: &H) -> Vec<J> {
    let v_s = dec_slice(h.let_("s"), &|r: &J| dec_int(r, "i64"), zero_int);
    let _roots = temp_root(&[v_s.clone()]);
    let a0 = v_s.clone();
    let r0 = slice_to_array(a0.clone(), 2, None);
    vec![enc_array(&r0, &|e: &V| enc_int(e, "i64"))]
}

fn case_125(h: &H) -> Vec<J> {
    let v_a = dec_string(h.let_("a"));
    let v_b = dec_string(h.let_("b"));
    let _roots = temp_root(&[v_a.clone(), v_b.clone()]);
    let a0 = v_a.clone();
    let a1 = v_b.clone();
    let r0 = scompare(a0.clone(), a1.clone());
    vec![enc_int(&r0, "i64")]
}

fn case_126(h: &H) -> Vec<J> {
    let v_a = dec_string(h.let_("a"));
    let v_b = dec_string(h.let_("b"));
    let _roots = temp_root(&[v_a.clone(), v_b.clone()]);
    let a0 = v_a.clone();
    let a1 = v_b.clone();
    let r0 = scompare(a0.clone(), a1.clone());
    vec![enc_int(&r0, "i64")]
}

fn case_127(h: &H) -> Vec<J> {
    let v_a = dec_string(h.let_("a"));
    let v_b = dec_string(h.let_("b"));
    let _roots = temp_root(&[v_a.clone(), v_b.clone()]);
    let a0 = v_a.clone();
    let a1 = v_b.clone();
    let r0 = scompare(a0.clone(), a1.clone());
    vec![enc_int(&r0, "i64")]
}

fn case_128(h: &H) -> Vec<J> {
    let v_a = dec_string(h.let_("a"));
    let v_b = dec_string(h.let_("b"));
    let _roots = temp_root(&[v_a.clone(), v_b.clone()]);
    let a0 = v_a.clone();
    let a1 = v_b.clone();
    let r0 = scompare(a0.clone(), a1.clone());
    vec![enc_int(&r0, "i64")]
}

fn case_129(h: &H) -> Vec<J> {
    let v_a = dec_string(h.let_("a"));
    let v_b = dec_string(h.let_("b"));
    let _roots = temp_root(&[v_a.clone(), v_b.clone()]);
    let a0 = v_a.clone();
    let a1 = v_b.clone();
    let r0 = concat(a0.clone(), a1.clone());
    vec![enc_string(&r0)]
}

fn case_130(h: &H) -> Vec<J> {
    let v_a = dec_string(h.let_("a"));
    let v_b = dec_string(h.let_("b"));
    let _roots = temp_root(&[v_a.clone(), v_b.clone()]);
    let a0 = v_a.clone();
    let a1 = v_b.clone();
    let r0 = concat(a0.clone(), a1.clone());
    vec![enc_string(&r0)]
}

fn case_131(h: &H) -> Vec<J> {
    let v_s = dec_string(h.let_("s"));
    let v_i = dec_int(h.let_("i"), "i64");
    let _roots = temp_root(&[v_s.clone(), v_i.clone()]);
    let a0 = v_s.clone();
    let a1 = v_i.clone();
    let rv = decode_rune(a0.clone(), a1.clone());
    let r0 = rv.at(0);
    let r1 = rv.at(1);
    vec![enc_int(&r0, "i32"), enc_int(&r1, "i64")]
}

fn case_132(h: &H) -> Vec<J> {
    let v_s = dec_string(h.let_("s"));
    let v_i = dec_int(h.let_("i"), "i64");
    let _roots = temp_root(&[v_s.clone(), v_i.clone()]);
    let a0 = v_s.clone();
    let a1 = v_i.clone();
    let rv = decode_rune(a0.clone(), a1.clone());
    let r0 = rv.at(0);
    let r1 = rv.at(1);
    vec![enc_int(&r0, "i32"), enc_int(&r1, "i64")]
}

fn case_133(h: &H) -> Vec<J> {
    let v_s = dec_string(h.let_("s"));
    let v_i = dec_int(h.let_("i"), "i64");
    let _roots = temp_root(&[v_s.clone(), v_i.clone()]);
    let a0 = v_s.clone();
    let a1 = v_i.clone();
    let rv = decode_rune(a0.clone(), a1.clone());
    let r0 = rv.at(0);
    let r1 = rv.at(1);
    vec![enc_int(&r0, "i32"), enc_int(&r1, "i64")]
}

fn case_134(h: &H) -> Vec<J> {
    let v_s = dec_string(h.let_("s"));
    let v_i = dec_int(h.let_("i"), "i64");
    let _roots = temp_root(&[v_s.clone(), v_i.clone()]);
    let a0 = v_s.clone();
    let a1 = v_i.clone();
    let rv = decode_rune(a0.clone(), a1.clone());
    let r0 = rv.at(0);
    let r1 = rv.at(1);
    vec![enc_int(&r0, "i32"), enc_int(&r1, "i64")]
}

fn case_135(h: &H) -> Vec<J> {
    let v_s = dec_string(h.let_("s"));
    let v_i = dec_int(h.let_("i"), "i64");
    let _roots = temp_root(&[v_s.clone(), v_i.clone()]);
    let a0 = v_s.clone();
    let a1 = v_i.clone();
    let rv = decode_rune(a0.clone(), a1.clone());
    let r0 = rv.at(0);
    let r1 = rv.at(1);
    vec![enc_int(&r0, "i32"), enc_int(&r1, "i64")]
}

fn case_136(h: &H) -> Vec<J> {
    let v_s = dec_string(h.let_("s"));
    let v_i = dec_int(h.let_("i"), "i64");
    let _roots = temp_root(&[v_s.clone(), v_i.clone()]);
    let a0 = v_s.clone();
    let a1 = v_i.clone();
    let rv = decode_rune(a0.clone(), a1.clone());
    let r0 = rv.at(0);
    let r1 = rv.at(1);
    vec![enc_int(&r0, "i32"), enc_int(&r1, "i64")]
}

fn case_137(h: &H) -> Vec<J> {
    let v_s = dec_string(h.let_("s"));
    let v_i = dec_int(h.let_("i"), "i64");
    let _roots = temp_root(&[v_s.clone(), v_i.clone()]);
    let a0 = v_s.clone();
    let a1 = v_i.clone();
    let rv = decode_rune(a0.clone(), a1.clone());
    let r0 = rv.at(0);
    let r1 = rv.at(1);
    vec![enc_int(&r0, "i32"), enc_int(&r1, "i64")]
}

fn case_138(h: &H) -> Vec<J> {
    let v_b = dec_byte_slice(h.let_("b"));
    let _roots = temp_root(&[v_b.clone()]);
    let a0 = v_b.clone();
    let r0 = from_bytes(a0.clone());
    vec![enc_string(&r0)]
}

fn case_139(h: &H) -> Vec<J> {
    let v_b = dec_byte_slice(h.let_("b"));
    let _roots = temp_root(&[v_b.clone()]);
    let a0 = v_b.clone();
    let r0 = from_bytes(a0.clone());
    vec![enc_string(&r0)]
}

fn case_140(h: &H) -> Vec<J> {
    let v_r = dec_int(h.let_("r"), "i32");
    let _roots = temp_root(&[v_r.clone()]);
    let a0 = v_r.clone();
    let r0 = from_rune(a0.clone());
    vec![enc_string(&r0)]
}

fn case_141(h: &H) -> Vec<J> {
    let v_r = dec_int(h.let_("r"), "i64");
    let _roots = temp_root(&[v_r.clone()]);
    let a0 = v_r.clone();
    let r0 = from_rune(a0.clone());
    vec![enc_string(&r0)]
}

fn case_142(h: &H) -> Vec<J> {
    let v_r = dec_int(h.let_("r"), "i8");
    let _roots = temp_root(&[v_r.clone()]);
    let a0 = v_r.clone();
    let r0 = from_rune(a0.clone());
    vec![enc_string(&r0)]
}

fn case_143(h: &H) -> Vec<J> {
    let v_r = dec_int(h.let_("r"), "i64");
    let _roots = temp_root(&[v_r.clone()]);
    let a0 = v_r.clone();
    let r0 = from_rune(a0.clone());
    vec![enc_string(&r0)]
}

fn case_144(h: &H) -> Vec<J> {
    let v_r = dec_slice(h.let_("r"), &|r: &J| dec_int(r, "i32"), zero_int);
    let _roots = temp_root(&[v_r.clone()]);
    let a0 = v_r.clone();
    let r0 = from_runes(a0.clone());
    vec![enc_string(&r0)]
}

fn case_145(h: &H) -> Vec<J> {
    let v_r = dec_slice(h.let_("r"), &|r: &J| dec_int(r, "i32"), zero_int);
    let _roots = temp_root(&[v_r.clone()]);
    let a0 = v_r.clone();
    let r0 = from_runes(a0.clone());
    vec![enc_string(&r0)]
}

fn case_146(h: &H) -> Vec<J> {
    let v_s = dec_string(h.let_("s"));
    let v_i = dec_int(h.let_("i"), "i64");
    let _roots = temp_root(&[v_s.clone(), v_i.clone()]);
    let a0 = v_s.clone();
    let a1 = v_i.clone();
    let r0 = sindex(a0.clone(), a1.clone());
    vec![enc_int(&r0, "u8")]
}

fn case_147(h: &H) -> Vec<J> {
    let v_s = dec_string(h.let_("s"));
    let v_i = dec_int(h.let_("i"), "i64");
    let _roots = temp_root(&[v_s.clone(), v_i.clone()]);
    let a0 = v_s.clone();
    let a1 = v_i.clone();
    let r0 = sindex(a0.clone(), a1.clone());
    vec![enc_int(&r0, "u8")]
}

fn case_148(h: &H) -> Vec<J> {
    let v_s = dec_string(h.let_("s"));
    let v_i = dec_int(h.let_("i"), "i64");
    let _roots = temp_root(&[v_s.clone(), v_i.clone()]);
    let a0 = v_s.clone();
    let a1 = v_i.clone();
    let r0 = sindex(a0.clone(), a1.clone());
    vec![enc_int(&r0, "u8")]
}

fn case_149(h: &H) -> Vec<J> {
    let v_s = dec_string(h.let_("s"));
    let v_i = dec_int(h.let_("i"), "u64");
    let _roots = temp_root(&[v_s.clone(), v_i.clone()]);
    let a0 = v_s.clone();
    let a1 = v_i.clone();
    let r0 = sindexu(a0.clone(), a1.clone());
    vec![enc_int(&r0, "u8")]
}

fn case_150(h: &H) -> Vec<J> {
    let v_s = dec_string(h.let_("s"));
    let v_lo = dec_int(h.let_("lo"), "i64");
    let v_hi = dec_int(h.let_("hi"), "i64");
    let _roots = temp_root(&[v_s.clone(), v_lo.clone(), v_hi.clone()]);
    let a0 = v_s.clone();
    let a1 = v_lo.clone();
    let a2 = v_hi.clone();
    let r0 = sslice(a0.clone(), a1.clone(), a2.clone(), false);
    vec![enc_string(&r0)]
}

fn case_151(h: &H) -> Vec<J> {
    let v_s = dec_string(h.let_("s"));
    let v_lo = dec_int(h.let_("lo"), "i64");
    let v_hi = dec_int(h.let_("hi"), "i64");
    let _roots = temp_root(&[v_s.clone(), v_lo.clone(), v_hi.clone()]);
    let a0 = v_s.clone();
    let a1 = v_lo.clone();
    let a2 = v_hi.clone();
    let r0 = sslice(a0.clone(), a1.clone(), a2.clone(), false);
    vec![enc_string(&r0)]
}

fn case_152(h: &H) -> Vec<J> {
    let v_s = dec_string(h.let_("s"));
    let v_lo = dec_int(h.let_("lo"), "i64");
    let v_hi = dec_int(h.let_("hi"), "i64");
    let _roots = temp_root(&[v_s.clone(), v_lo.clone(), v_hi.clone()]);
    let a0 = v_s.clone();
    let a1 = v_lo.clone();
    let a2 = v_hi.clone();
    let r0 = sslice(a0.clone(), a1.clone(), a2.clone(), false);
    vec![enc_string(&r0)]
}

fn case_153(h: &H) -> Vec<J> {
    let v_s = dec_string(h.let_("s"));
    let v_lo = dec_int(h.let_("lo"), "i64");
    let v_hi = dec_int(h.let_("hi"), "i64");
    let _roots = temp_root(&[v_s.clone(), v_lo.clone(), v_hi.clone()]);
    let a0 = v_s.clone();
    let a1 = v_lo.clone();
    let a2 = v_hi.clone();
    let r0 = sslice(a0.clone(), a1.clone(), a2.clone(), false);
    vec![enc_string(&r0)]
}

fn case_154(h: &H) -> Vec<J> {
    let v_s = dec_string(h.let_("s"));
    let _roots = temp_root(&[v_s.clone()]);
    let a0 = v_s.clone();
    let r0 = to_bytes(a0.clone());
    vec![enc_slice(&r0, &|e: &V| enc_int(e, "u8"))]
}

fn case_155(h: &H) -> Vec<J> {
    let v_s = dec_string(h.let_("s"));
    let _roots = temp_root(&[v_s.clone()]);
    let a0 = v_s.clone();
    let r0 = to_bytes(a0.clone());
    vec![enc_slice(&r0, &|e: &V| enc_int(e, "u8"))]
}

fn case_156(h: &H) -> Vec<J> {
    let v_s = dec_string(h.let_("s"));
    let _roots = temp_root(&[v_s.clone()]);
    let a0 = v_s.clone();
    let r0 = to_runes(a0.clone());
    vec![enc_slice(&r0, &|e: &V| enc_int(e, "i32"))]
}

fn case_157(h: &H) -> Vec<J> {
    let _roots = temp_root(&[]);
    let rv = run_isolated(move |t: &Rc<Task>| { call(t, new_spawn_check()); });
    let r0 = rv[0].clone();
    vec![enc_bool(&r0)]
}

fn case_158(h: &H) -> Vec<J> {
    let v_fns = dec_slice(h.let_("fns"), &|r: &J| V::Nil, zero_nil);
    let _roots = temp_root(&[v_fns.clone()]);
    let a0 = v_fns.clone();
    let rv = run_isolated(move |t: &Rc<Task>| { lib_task_all(t, a0.clone()); });
    vec![]
}

fn case_159(h: &H) -> Vec<J> {
    let _roots = temp_root(&[]);
    let r0 = std_context_background();
    vec![enc_zero(&r0)]
}

fn case_160(h: &H) -> Vec<J> {
    let _roots = temp_root(&[]);
    let r0 = std_context_canceled();
    vec![enc_error(&r0)]
}

fn case_161(h: &H) -> Vec<J> {
    let _roots = temp_root(&[]);
    let r0 = std_context_deadline_exceeded();
    vec![enc_error(&r0)]
}

fn case_162(h: &H) -> Vec<J> {
    let v_ctx = std_context_background();
    let _roots = temp_root(&[v_ctx.clone()]);
    let a0 = v_ctx.clone();
    let r0 = std_context_context_done(a0.clone());
    vec![enc_chan(&r0, &|e: &V| enc_zero(e))]
}

fn case_163(h: &H) -> Vec<J> {
    let v_ctx = std_context_background();
    let _roots = temp_root(&[v_ctx.clone()]);
    let a0 = v_ctx.clone();
    let r0 = std_context_context_err(a0.clone());
    vec![enc_error(&r0)]
}

fn case_164(h: &H) -> Vec<J> {
    let v_parent = std_context_background();
    let _roots = temp_root(&[v_parent.clone()]);
    let a0 = v_parent.clone();
    let rv = std_context_with_cancel(a0.clone());
    let r0 = rv.at(0);
    let r1 = rv.at(1);
    vec![enc_zero(&r0), enc_zero(&r1)]
}

fn case_165(h: &H) -> Vec<J> {
    let v_parent = std_context_background();
    let v_d = dec_int(h.let_("d"), "i64");
    let _roots = temp_root(&[v_parent.clone(), v_d.clone()]);
    let a0 = v_parent.clone();
    let a1 = v_d.clone();
    let rv = std_context_with_timeout(a0.clone(), a1.clone());
    let r0 = rv.at(0);
    let r1 = rv.at(1);
    vec![enc_zero(&r0), enc_zero(&r1)]
}

fn case_166(h: &H) -> Vec<J> {
    let v_err = dec_error(h.let_("err"));
    let v_target = dec_error(h.let_("target"));
    let _roots = temp_root(&[v_err.clone(), v_target.clone()]);
    let a0 = v_err.clone();
    let a1 = v_target.clone();
    let r0 = std_errors_is(a0.clone(), a1.clone());
    vec![enc_bool(&r0)]
}

fn case_167(h: &H) -> Vec<J> {
    let v_err = dec_error(h.let_("err"));
    let v_target = dec_error(h.let_("target"));
    let _roots = temp_root(&[v_err.clone(), v_target.clone()]);
    let a0 = v_err.clone();
    let a1 = v_target.clone();
    let r0 = std_errors_is(a0.clone(), a1.clone());
    vec![enc_bool(&r0)]
}

fn case_168(h: &H) -> Vec<J> {
    let v_err = dec_error(h.let_("err"));
    let v_target = v_err.clone();
    let _roots = temp_root(&[v_err.clone(), v_target.clone()]);
    let a0 = v_err.clone();
    let a1 = v_target.clone();
    let r0 = std_errors_is(a0.clone(), a1.clone());
    vec![enc_bool(&r0)]
}

fn case_169(h: &H) -> Vec<J> {
    let v_text = dec_string(h.let_("text"));
    let _roots = temp_root(&[v_text.clone()]);
    let a0 = v_text.clone();
    let r0 = std_errors_new(a0.clone());
    vec![enc_error(&r0)]
}

fn case_170(h: &H) -> Vec<J> {
    let v_err = dec_error(h.let_("err"));
    let _roots = temp_root(&[v_err.clone()]);
    let a0 = v_err.clone();
    let r0 = std_errors_unwrap(a0.clone());
    vec![enc_error(&r0)]
}

fn case_171(h: &H) -> Vec<J> {
    let _roots = temp_root(&[]);
    let rv = run_isolated(move |t: &Rc<Task>| { std_runtime_gosched(t); });
    vec![]
}

fn case_172(h: &H) -> Vec<J> {
    let v_m = new_mutex();
    let _roots = temp_root(&[v_m.clone()]);
    let a0 = v_m.clone();
    let rv = run_isolated(move |t: &Rc<Task>| { std_sync_mutex_lock(t, a0.clone()); });
    vec![]
}

fn case_173(h: &H) -> Vec<J> {
    let v_m = new_mutex();
    let _roots = temp_root(&[v_m.clone()]);
    let a0 = v_m.clone();
    let rv = run_isolated(move |t: &Rc<Task>| { std_sync_mutex_lock(t, a0.clone().clone()); std_sync_mutex_unlock(a0.clone()); });
    vec![]
}

fn case_174(h: &H) -> Vec<J> {
    let v_wg = new_waitgroup();
    let v_delta = dec_int(h.let_("delta"), "i64");
    let _roots = temp_root(&[v_wg.clone(), v_delta.clone()]);
    let a0 = v_wg.clone();
    let a1 = v_delta.clone();
    std_sync_waitgroup_add(a0.clone(), a1.clone());
    vec![]
}

fn case_175(h: &H) -> Vec<J> {
    let v_wg = new_waitgroup();
    let v_delta = dec_int(h.let_("delta"), "i64");
    let _roots = temp_root(&[v_wg.clone(), v_delta.clone()]);
    let a0 = v_wg.clone();
    let a1 = v_delta.clone();
    std_sync_waitgroup_add(a0.clone(), a1.clone());
    vec![]
}

fn case_176(h: &H) -> Vec<J> {
    let v_wg = new_waitgroup();
    let _roots = temp_root(&[v_wg.clone()]);
    let a0 = v_wg.clone();
    std_sync_waitgroup_done(a0.clone());
    vec![]
}

fn case_177(h: &H) -> Vec<J> {
    let v_wg = new_waitgroup();
    let _roots = temp_root(&[v_wg.clone()]);
    let a0 = v_wg.clone();
    let rv = run_isolated(move |t: &Rc<Task>| { std_sync_waitgroup_wait(t, a0.clone()); });
    vec![]
}

fn case_178(h: &H) -> Vec<J> {
    let v_d = dec_int(h.let_("d"), "i64");
    let _roots = temp_root(&[v_d.clone()]);
    let a0 = v_d.clone();
    let rv = run_isolated(move |t: &Rc<Task>| { std_time_sleep(t, a0.clone()); });
    vec![]
}

pub static CASES: &[(&str, fn(&H) -> Vec<J>)] = &[
    ("core.chan.cap/three", case_0),
    ("core.chan.close/nil", case_1),
    ("core.chan.close/open", case_2),
    ("core.chan.close/twice", case_3),
    ("core.chan.len/nil", case_4),
    ("core.chan.len/two", case_5),
    ("core.chan.make/buffered", case_6),
    ("core.chan.make/negative", case_7),
    ("core.chan.recv/buffered", case_8),
    ("core.chan.recv/closed", case_9),
    ("core.chan.recv/drains_before_close", case_10),
    ("core.chan.recv/empty_blocks", case_11),
    ("core.chan.recv/nil_blocks", case_12),
    ("core.chan.send/buffered", case_13),
    ("core.chan.send/closed", case_14),
    ("core.chan.send/full_blocks", case_15),
    ("core.chan.send/nil_blocks", case_16),
    ("core.chan.send/unbuffered_blocks", case_17),
    ("core.integer.add/int32_plain", case_18),
    ("core.integer.add/int64_min", case_19),
    ("core.integer.add/int8_wrap", case_20),
    ("core.integer.add/int_big", case_21),
    ("core.integer.add/uint32_wrap", case_22),
    ("core.integer.add/uint64_wrap", case_23),
    ("core.integer.and/neg", case_24),
    ("core.integer.and/u32", case_25),
    ("core.integer.andnot/i64", case_26),
    ("core.integer.andnot/u16", case_27),
    ("core.integer.compare/equal", case_28),
    ("core.integer.compare/signed", case_29),
    ("core.integer.compare/u32_high", case_30),
    ("core.integer.compare/unsigned_high", case_31),
    ("core.integer.convert/narrow_unsigned", case_32),
    ("core.integer.convert/same", case_33),
    ("core.integer.convert/sign_extend", case_34),
    ("core.integer.convert/truncate", case_35),
    ("core.integer.convert/u32_to_i32", case_36),
    ("core.integer.convert/unsigned_wrap", case_37),
    ("core.integer.div/by_zero", case_38),
    ("core.integer.div/int64_min_neg1", case_39),
    ("core.integer.div/int8_min_neg1", case_40),
    ("core.integer.div/trunc_neg", case_41),
    ("core.integer.div/trunc_pos", case_42),
    ("core.integer.div/uint64_big", case_43),
    ("core.integer.mul/int32_neg", case_44),
    ("core.integer.mul/int32_wrap", case_45),
    ("core.integer.mul/int64_wrap", case_46),
    ("core.integer.mul/int8_wrap", case_47),
    ("core.integer.mul/uint32_exact", case_48),
    ("core.integer.mul/uint64_big", case_49),
    ("core.integer.neg/min", case_50),
    ("core.integer.neg/plain", case_51),
    ("core.integer.neg/u64", case_52),
    ("core.integer.neg/unsigned", case_53),
    ("core.integer.not/signed", case_54),
    ("core.integer.not/u32", case_55),
    ("core.integer.not/u8", case_56),
    ("core.integer.or/i8", case_57),
    ("core.integer.or/u32", case_58),
    ("core.integer.rem/by_zero", case_59),
    ("core.integer.rem/min_neg1", case_60),
    ("core.integer.rem/neg_dividend", case_61),
    ("core.integer.rem/neg_divisor", case_62),
    ("core.integer.rem/uint", case_63),
    ("core.integer.shl/basic", case_64),
    ("core.integer.shl/huge", case_65),
    ("core.integer.shl/int64_63", case_66),
    ("core.integer.shl/negative", case_67),
    ("core.integer.shl/overflow_int8", case_68),
    ("core.integer.shl/wide", case_69),
    ("core.integer.shr/arith", case_70),
    ("core.integer.shr/arith_wide", case_71),
    ("core.integer.shr/logical", case_72),
    ("core.integer.shr/logical_wide", case_73),
    ("core.integer.shr/negative", case_74),
    ("core.integer.shr/pos_wide", case_75),
    ("core.integer.sub/int16_wrap", case_76),
    ("core.integer.sub/int_plain", case_77),
    ("core.integer.sub/uint8_wrap", case_78),
    ("core.integer.sub/uint_wrap", case_79),
    ("core.integer.xor/i32", case_80),
    ("core.integer.xor/u64", case_81),
    ("core.map.clear/all", case_82),
    ("core.map.delete/nil_map", case_83),
    ("core.map.delete/reinsert_moves", case_84),
    ("core.map.iterate/insertion_order", case_85),
    ("core.map.len/nil", case_86),
    ("core.map.len/two", case_87),
    ("core.map.lookup/nil_map", case_88),
    ("core.map.lookup/present", case_89),
    ("core.map.make/empty", case_90),
    ("core.map.store/nil_map", case_91),
    ("core.map.store/update_keeps_order", case_92),
    ("core.print/bool", case_93),
    ("core.print/bytes", case_94),
    ("core.print/int", case_95),
    ("core.print/u64", case_96),
    ("core.select/closed_ready", case_97),
    ("core.select/default_when_idle", case_98),
    ("core.select/nothing_blocks", case_99),
    ("core.select/only_ready", case_100),
    ("core.slice.append/from_nil", case_101),
    ("core.slice.append/grow_doubles", case_102),
    ("core.slice.append/grow_required", case_103),
    ("core.slice.append/in_place", case_104),
    ("core.slice.append/nil_empty", case_105),
    ("core.slice.append/overlap", case_106),
    ("core.slice.clear/shared", case_107),
    ("core.slice.copy/overlap_forward", case_108),
    ("core.slice.copy/short_dst", case_109),
    ("core.slice.index/basic", case_110),
    ("core.slice.index/beyond_len", case_111),
    ("core.slice.index/nil", case_112),
    ("core.slice.make/basic", case_113),
    ("core.slice.make/cap_lt_len", case_114),
    ("core.slice.make/neg_len", case_115),
    ("core.slice.slice/hi_gt_max", case_116),
    ("core.slice.slice/lo_gt_hi", case_117),
    ("core.slice.slice/max_oob", case_118),
    ("core.slice.slice/nil_empty", case_119),
    ("core.slice.slice/share", case_120),
    ("core.slice.store/alias_visible", case_121),
    ("core.slice.store/oob", case_122),
    ("core.slice.to_array/prefix", case_123),
    ("core.slice.to_array/short", case_124),
    ("core.string.compare/equal", case_125),
    ("core.string.compare/high_byte", case_126),
    ("core.string.compare/less", case_127),
    ("core.string.compare/prefix", case_128),
    ("core.string.concat/basic", case_129),
    ("core.string.concat/raw_bytes", case_130),
    ("core.string.decode_rune/ascii", case_131),
    ("core.string.decode_rune/four", case_132),
    ("core.string.decode_rune/invalid", case_133),
    ("core.string.decode_rune/overlong", case_134),
    ("core.string.decode_rune/surrogate", case_135),
    ("core.string.decode_rune/truncated", case_136),
    ("core.string.decode_rune/two", case_137),
    ("core.string.from_bytes/basic", case_138),
    ("core.string.from_bytes/nil", case_139),
    ("core.string.from_rune/ascii", case_140),
    ("core.string.from_rune/huge", case_141),
    ("core.string.from_rune/negative", case_142),
    ("core.string.from_rune/surrogate", case_143),
    ("core.string.from_runes/basic", case_144),
    ("core.string.from_runes/invalid", case_145),
    ("core.string.index/first", case_146),
    ("core.string.index/negative", case_147),
    ("core.string.index/oob", case_148),
    ("core.string.index/unsigned_huge", case_149),
    ("core.string.slice/hi_oob", case_150),
    ("core.string.slice/inverted", case_151),
    ("core.string.slice/mid", case_152),
    ("core.string.slice/split_rune", case_153),
    ("core.string.to_bytes/basic", case_154),
    ("core.string.to_bytes/empty", case_155),
    ("core.string.to_runes/mixed", case_156),
    ("core.task.spawn/parent_continues", case_157),
    ("lib.task.all/empty", case_158),
    ("std.context.background/root", case_159),
    ("std.context.canceled/message", case_160),
    ("std.context.deadline_exceeded/message", case_161),
    ("std.context.done/background", case_162),
    ("std.context.err/background", case_163),
    ("std.context.with_cancel/child", case_164),
    ("std.context.with_timeout/child", case_165),
    ("std.errors.is/distinct", case_166),
    ("std.errors.is/nils", case_167),
    ("std.errors.is/same", case_168),
    ("std.errors.new/message", case_169),
    ("std.errors.unwrap/plain", case_170),
    ("std.runtime.gosched/alone", case_171),
    ("std.sync.mutex.lock/unlocked", case_172),
    ("std.sync.mutex.unlock/lock_then_unlock", case_173),
    ("std.sync.waitgroup.add/negative", case_174),
    ("std.sync.waitgroup.add/positive", case_175),
    ("std.sync.waitgroup.done/underflow", case_176),
    ("std.sync.waitgroup.wait/zero_returns", case_177),
    ("std.time.sleep/zero", case_178),
];
